== Chapter I.

Edward Burrough was born in the year 1634, in or near Underbarrow,
a village in the barony of Kendal, in Westmoreland.
His parents were respected for their virtue and honesty;
and as they were possessed of a sufficient estate,
they gave their son the best education that could be obtained
for him in the neighbourhood where they resided.
He displayed much manliness of character at an early age,
abstaining in great measure from the ordinary amusements of youth,
and evincing a relish for the company and conversation
of pious persons of enlarged and mature minds.
He was fond of reading the Holy Scriptures, and having a retentive memory,
he became well versed in them.
His parents were members of the Episcopal church,
and brought him up in the practice of the ceremonies which its ritual prescribed.
He describes his religion, at this time,
as consisting in "`going one day in seven to hear a man preach--to read and sing,
and rubble over a prayer; whilst I was wanton and light,
and lived in pleasure without the fear of God;
not knowing God but by hearsay and tradition.`"

He was early favoured with the visitation of divine grace,
making him uneasy with his sensual enjoyments and sinful condition,
and inciting him to seek after better things.
He says, "`When I grew up towards twelve years of age, something stirred in me,
and showed me that there was a higher religion than that I was exercised in.`"
He visited various places of worship,
for the purpose of finding some purer way than that in which he then was;
and thought the Presbyterians had more that seemed like truth amongst them,
than those with whom he had been educated.

[quote]
____
So I got to be a Presbyterian, says he,
and followed the highest of the priests and professors of that form,
and grew in favour with them.
Then I left some little of my vanity and lightness, and pride grew up in me.
Some of my former acquaintance began to scorn me, and by labouring here,
I gathered knowledge of things without, but yet was ignorant of the living truth.

When I was about seventeen years of age, it pleased God to show himself a little to me,
and something struck me with terror.
When I had been praying, I heard the voice often,
"`Thou art ignorant of God--thou knowest not where he is;
to what purpose is thy prayer?`"
So, much fear came upon me, and broke me off from praying many times;
trouble came thick into my mind, and fearfulness fell upon me.
I was struck off from my delights, which I formerly loved, and what I had gathered in,
as of God, died.
I left off reading in the Scriptures, for something showed me that I was very ignorant,
and knew not the true God; and the beauty of all things vanished.
I went to some, asking what that God was, which was professed?
for I said, "`I know him not;`" but I got no satisfaction from any.

At this time, +++[+++he continues,]
I was much separated from the vain ways of the world, and from worldly people;
and was made to reprove many for wickedness in words and actions; and was derided,
and looked upon scornfully by many.
The preaching of those whom I had formerly much delighted in, was withered and decayed.
Yet it pleased the Lord to show himself in love to me, and I had sweet refreshment,
coming in from him to my soul, and had joy and peace in abundance;
and openings of the living truth in me,
which the world knew not of The mystery of the Scriptures was something opened,
which before I knew nothing of; and I saw many glorious things in it,
which lie hid under the letter.
I was in much rejoicing many times, and sang praises,
for I was brought out of the land of darkness, and could say, I was in the light.

But not knowing the cross of Christ, I ran forth,
in my wisdom comprehending the mysteries of God.
Having a light shining in me, I grew up into notions, to talk of high things,
for it was my delight to comprehend in my busy mind.
Thus, being ignorant of the cross, to keep low in it,
I ran before my guide up into comprehension,
and then was I above many of the priests and professors,
and followed only to hear the highest notionists, that preached high things.
But the fleshly man was at liberty, and so I became one of them in their discoursings,
and was looked upon by them to know much.
The former terror was gone,
and I had got up from under the judgment;--pride grew more than ever, self-conceit,
presumption, and fleshly liberty to the carnal mind;
and my delight was much in discoursing; where I gave holy things unto dogs,
and cast pearls before swine.
Wisdom was hid from me; I lived pleasantly, for I had the true God,
and the true truth in my comprehension,
which by my wisdom in the light I had comprehended, and I had the world in my heart.
Pride, covetousness, and the earthly spirit ruled, and my delight was grown up to that,
which once I had no delight in,
and the beauty of things grew which seemed to have been vanished.
Here I was run from my husband after other lovers,
and had left the Lord my Maker who had so graciously made himself manifest unto me.
I became darkened, lost that which I once had,
and had in memory that which before I had enjoyed.
I could tell of experiences, but they were dead to me;
and something within began to question how it was with me?
for I saw myself to be ignorant more than formerly, and I saw that I knew nothing.
____

At this period he felt earnest desires to regain the state from which he had fallen;
yet was not humbled enough to seek restoration in that abasedness of self,
which would have prepared him for knowing the gracious promise fulfilled, "`Seek,
and ye shall find.`"
He endeavoured to comfort himself in the recollection of the seasons
of inward communion with the Lord which he had formerly enjoyed,
saying, "`Whom God loves once, he loves forever.`"
This doctrine, which was very prevalent among the Calvinistic Puritans,
is eminently evil in its tendency, by soothing the anguish for sin,
which the Lord in mercy, as well as in judgment, brings upon his backsliding children,
in order to induce them to seek reconciliation with Him through Christ,
by repentance and amendment of life.

Edward Burrough could not however, long rest satisfied to trust in former experiences,
knowing from the convictions of the Holy Spirit, in himself,
that his heart was not right in the sight of God.
What would it have availed him, if called into another state of existence,
that he had once been favoured with divine approbation, when, to use his own language,
"`that was head and ruled in me, which God never loved?`"
The witness for Truth in his heart did not suffer him to settle down at rest.
He grew weary of the preaching of the priests,
even of those who made the highest profession,
and through the discoveries of that divine Light which still shone in his heart,
he perceived the spiritual ignorance and emptiness
of the professors of the Christian name.

Whilst in this unsettled state, he informs us,
that "`It pleased the Lord to send into the parts where he lived,
his faithful servant and messenger, George Fox.
He spoke the language which I knew not, notwithstanding all my high talking.`"
It was about the first of the fourth month, 1652, that George Fox came to Underbarrow,
where Edward Burrough met with him.
He had previously been at Kendal,
and had preached at a meeting there with such prevailing power,
that a number of persons received his doctrine;
and several of these came with him to Underbarrow.

The doctrine of the light of Christ Jesus, made manifest in the heart,
reproving for evil, giving a right understanding of the Holy Scriptures,
and leading the humble and obedient ones to the saving
knowledge of Him who died for them,
was calculated to produce a strong impression on the minds of those,
who had long been fruitlessly seeking after truth and religious stability,
among empty forms and ceremonies.
Yet the truth thus declared to them, being in the cross to man`'s natural wisdom,
was not received without opposition and argument;
and amongst the contenders against it were Edward Burrough.
His ability in argument, and his desire to save himself from the acknowledgment of error,
were however, of no avail;
for through the power of the Holy Spirit accompanying the word preached,
which gave an awakening force to the language of Truth in the mouth of George Fox,
this strong-minded young man was brought to confess
to the soundness of the doctrine which he then heard,
and its consistency with the testimony of the Holy Scriptures.
But what was more important to him than all this, his heart was touched and softened,
whilst his mind became enlightened,
and he was brought to a sense of his wretched and sinful condition.

He tells us, that the Lord was pleased to show him that he was in the prodigal state,
above the cross of Christ, out of the pure fear of the Lord,
and full of corruption and of the old nature.
He felt himself to be a child of wrath, and "`no more worthy to be called a son.`"
"`A day of weeping, mourning and misery, says he,
and a day of vengeance and recompense came upon me, such as I had never known.
One vial of wrath after another +++[+++was poured out]
and then I separated from all the glory of the world,
and from all my acquaintance and kindred,
and betook myself to the company of a poor despised and condemned people, called Quakers.
Now am I one of that generation which is ever hated of the world;
and have chosen rather to suffer affliction with them,
than to enjoy the pleasures of sin with the great multitude,
though worldly pleasures were not wanting to me.
I do bear witness against all formality in religion, and false hirelings,
and chief priests, who walk in the steps of the Scribes and Pharisees,
and of the false prophets of Israel, that were never sent of God to declare his word.
I am despised of my neighbours and carnal acquaintance, and am not greater than my Lord,
who was called a blasphemer and a deceiver, as now I am.
But praised, praised be the Lord forevermore,
who hath separated me from the world and worldly glories,
and hath made me a partaker of his love, in whom my soul hath full satisfaction,
joy and content.`"

Whilst he was thus made to endure the baptism of
the Holy Spirit to prepare him for the Lord`'s service,
he had also a large share of outward trouble and conflict.
His parents having been educated in the belief,
that religion very much consisted in the observance of the church ritual,
were not prepared to tolerate in their son a profession
which struck at all mere external rites and ceremonies,
as being contrary to the spirituality of the Christian religion.
They no doubt regarded the Quakers as heretics,
in denying the saving efficacy of those rites,
which many deemed to be part of Christianity itself, and obligatory on all.
Other dissenters, however they might differ on certain points of doctrine or discipline,
clung to what were termed the ordinances.
They considered the administration of outward water as the Christian baptism,
and the partaking of bread and wine,
after it was supposed to have been consecrated by the priest, as the Lord`'s supper.
The Quakers, therefore, were condemned by all other professors of the Christian name;
and Edward Burrough`'s parents were so incensed against
him for joining with such a people,
that they refused to permit him to remain in their family.
When they had rejected him as a son,
he offered to remain and work for them in the capacity of a servant,
but in this he was also denied.
Having now literally given up father and mother for the Lord`'s sake and the gospel`'s,
he endeavoured to walk in faithful obedience to Him who had called him,
and whom he found to he a rich "`rewarder of them that diligently seek Him.`"
He that declared, "`whosoever shall do the will of God,
the same is my brother and sister and mother,`" was
with him in this separation from his kindred,
sustaining him under the sacrifice he had made of family endearments.

Having thus given up all for Christ`'s sake,
and passed through various exercises and baptisms to prepare him for the
service and station which he was designed to fill in the church,
he received a divine call to the solemn work of the ministry of the Gospel;
and engaged therein about two months after his convincement.
In a preface which he subsequently wrote to one of George Fox`'s works,
he thus speaks of this period, viz.:

[quote]
____
It is now about seven years, since the Lord raised us up in the north of England,
and opened our mouths +++[+++to preach the gospel]
in His Spirit.
What we were before, in our religious profession and practice,
is well known to that part of the country;
how generally we were men of the strictest sect,
and of the greatest zeal in the performance of outward righteousness.
We went through and tried all sorts of teachers, and ran from mountain to mountain,
and from man to man, and from one form to another, as many do at this day,
and remain not gathered to the Lord.
Such we were that sought the Lord,
and desired the knowledge of his ways more than any thing beside.
For one, I may speak, who from a child, even a few years old,
set his face to seek and find the Saviour, and more than life, treasure or any crown,
sought after with all his heart the one thing that is needful, to wit,
the knowledge of God.

After our long seeking, the Lord appeared to us, and revealed his glory in us,
and gave us of his spirit, and of his wisdom to guide us, whereby we saw all the world,
the true state of things, and the true condition of the church.
First,
the Lord brought us to see that God had given every one of us a light from himself,
shining in our hearts and consciences, with which light, Christ,
the Saviour of the world, had lighted every man.
This light we found sufficient to reprove and convince us of every evil deed,
word and thought.
By it we came to know good from evil, and whatsoever is of God from what is of the devil.
This light gave us to discern between truth and error,
and between every false and right way.
We thereby came to know what man was before transgression,
how he was deceived and overcome by the devil;
how he is driven from the presence of the Lord,
and the sorrow and anguish which he is to undergo.
By this light we came to know the way and means of restoration,
and the state of man come out of the transgression and restored.
These things were revealed in us by the light which Christ had given us,
and enlightened us with.

We found this light to be a sufficient teacher to lead us to Christ, from whom it came;
and it gave us to receive Christ, and to witness him to dwell in us.
Through it we came to enter into the new Covenant, to be made heirs of life and salvation.
In all things we found the Light, which is Christ,
which we and all mankind were enlightened with,
to be sufficient to bring to life and eternal salvation;
and that all who owned this light in them, needed no man to teach them,
but the Lord was their teacher, by his light in their consciences,
and they received the holy anointing.
So we ceased from all the teachings of men, their worships, temples and baptisms,
and from our own words, professions, and practices of religion,
in times before zealously performed by us, and became fools for Christ`'s sake,
that we might become truly wise.

By this light of Christ in us we were led out of all false ways,
false preachings and false ministry,
and met together often and waited upon the Lord in pure silence.
We hearkened to the voice of the Lord,
and felt his word in our hearts to burn up and to beat down all that was contrary to God,
and we obeyed the light of Christ,
and followed the motions of the Lord`'s pure Spirit--took
up the cross to all earthly glories,
crowns and ways, and denied ourselves, our relations,
and all that stood in the way between us and the Lord.
We chose to suffer with and for the name of Christ,
rather than enjoy all the pleasures upon earth,
or all our former professions and practices in religion,
without the power and Spirit of God.

Whilst waiting upon the Lord in silence, as we often did for many hours together,
with our hearts towards him,
being stayed in the light of Christ from all fleshly motions and desires,
we often received the pouring down of his Spirit upon us, and our hearts were made glad,
and our tongues loosened, and our mouths opened, and we spake with new tongues,
as the Lord gave us utterance, and his Spirit led us,
which was poured upon sons and daughters.
Thereby things unutterable were made manifest, and the glory of the Father was revealed.
Then we began to sing praises to the Lord God Almighty, and to the Lamb,
who had redeemed us to God, and brought us out of the bondage of the world,
and put an end to sin and death.

All this was by and through the light of Christ within us;
and much more might be declared hereof, which could not be believed,
of the manifestation of the everlasting spirit that was given us.
But this is the sum, life and immortality where brought to light, power from on high,
and wisdom were made manifest, and the day everlasting appeared unto us.
The joyful Sun of righteousness arose and shone forth unto us and in us,
and the holy anointing, the everlasting Comforter we received.
The heir of the promise was brought forth to reign over the earth,
and over hell and death, whereby we entered into everlasting union, and fellowship,
and covenant with the Lord God, whose mercies are sure and his promise never fails.
We were raised from death to life, and are changed from Satan`'s power to God,
and gathered from all the dumb shepherds, and off all the barren mountains,
into the fold of eternal peace and rest;
and mighty and wonderful things hath the Lord wrought for us, and by us,
by his own outstretched arm.

Being prepared of the Lord, and having received power from on high,
we went forth as commanded of the Lord, leaving all relations,
and all things of the world behind us, that we might fulfill the work of the Lord,
unto which he called us.
With flesh and blood, or any creature we consulted not, nor took counsel of men,
but of the Lord alone,
who lifted up our heads above the world and all fears and doubtings,
and was with us in power and dominion over all that opposed us,
which was great and mighty.
We sounded the word of the Lord, and did not spare; and caused the deaf to hear,
the blind to see, and the heart that was hardened to be awakened;
and the dread of the Lord went before us and behind us, and took hold of our enemies.

We first journeyed out of Westmoreland through Cumberland,
Northumberland and into some parts of Scotland and Durham, Yorkshire, Lancashire,
Cheshire, etc., and in all these counties we had much opposition,
sufferings and cruel dealings from men of all sorts.
Every jail may witness,
how seldom any of them were without some of us imprisoned these six years;
and scarcely one steeple-house or market but may witness what beatings, bruises,
hailings and perils we have sustained.
Let the witness of God in all men`'s consciences,
give testimony what cruelty we suffered,
and also our patience and innocency under all that they have done to us.
____

Others beside Edward Burrough had been convinced
of the Truth in the Northern counties of England,
through the ministry of George Fox;
and these frequently met together to worship the Lord.
Being redeemed from all dependence on man,
and convinced that the solemn act of divine worship must be performed
immediately between the soul and its Almighty Creator,
through the help of the Spirit of Christ Jesus, the one great Mediator,
through whom alone we have access unto the Father,
they were often engaged to sit down together in silence and wait on Him.
Thus reverently seeking after the divine presence and power to
be manifested among them for the renewal of their spiritual strength,
the Lord was pleased at seasons marvellously to break in
upon them and crown their assemblies with his living,
heart tendering virtue, even when no words were spoken.

Francis Howgill tell us, that in joy of heart at this favour,
they often said to one another, "`What! is the kingdom of God come to be with men?
Will he take up his abode among the sons of men, as he did of old?
And shall we, that were reckoned as the outcasts of Israel,
have the honour communicated amongst us, who were but men of small parts,
and of little ability in respect of many others as amongst men?`"

Many were the afflictions which these honest-hearted people were called to partake of,
but having turned their backs upon the world with all its friendships, honours, ways,
religions and worships, they nobly persevered amid all their sufferings,
taking up the cross and following Christ Jesus, the Lamb of God,
whithersoever he led them.
In this patient waiting state, seeking to know and to do the will of God,
they grew in religious understanding,
and divine knowledge of the things pertaining to the kingdom of heaven,
and many of them were deeply instructed in the mysteries of salvation.
Abiding under the teachings of the Spirit of Christ,
they knew him to sanctify and prepare them for the ministry of the gospel,
and in his time felt themselves called of Him,
to declare unto others that which they had seen and felt,
and tasted and handled of the good word of life.
Thus they were made living and able ministers of the New Testament, not of the letter,
but of the Spirit,
and in its power and authority were sent forth to gather souls unto Christ.

We have already seen that Edward Burrough had been driven from his father`'s house,
in consequence of his religious profession;
and having thus early begun to taste of that cup of persecution,
which in those intolerant times,
was poured out in such large measure for the people called Quakers,
he shrunk not from the bitter draught, but with Christian meekness and patience,
continued to bear the allotted portion of suffering,
until at length he sealed his testimony with his life.

At an early period the storm of persecution broke forth in the north,
and Edward Burrough in common with his brethren felt its effects,
but this did not deter him from endeavouring faithfully
to occupy the gift committed to his trust.
He soon began to travel through his native county, and also went into Cumberland,
Northumberland and some parts of Scotland, holding meetings and preaching to the people,
many of whom were awakened by his ministry,
and brought to join in religious fellowship with the Society of Friends.

In the sixth month 1652, Miles Halhead was committed to prison in Kendal,
near Edward Burrough`'s native place, for reproving a priest.
He informs us that the first night he lay in prison,
the word of the Lord came to him saying, "`Fear not,
for I will be with thee according to my promise,
and will make thee a burdensome stone unto the town of Kendal, and to thy persecutors.
And I will send my servants, my sons and my daughters, from the east and from the west,
from the north and from the south,
to bear witness to the same truth that thou suffers for: yea,
against the justice that committed thee.
Therefore be thou faithful,
for I have chosen thee to be the first that shall
suffer for my name`'s sake in the town of Kendal.`"
This promise Miles informs us, was made good.
He was confined three months, during which period,
the same justice committed Francis Howgill, Thomas Holme and thirty others,
"`brethren and sisters,`" for bearing testimony to the Truth.
At the expiration of the three months, the justice set him at liberty.
Soon after, for riding through this town of Kendal,
and exhorting the inhabitants to repentance, he was committed to prison by the mayor.
He tells us that this officer "`had little peace from the Lord in what he had done,
till he had released me.
Then I returned to my house again, and had great peace with the Lord.`"
About the ninth month of this same year, Miles went to the house of justice Fell,
at Swarthmore; he says,
"`I found the Lord`'s people gathered together to wait upon his name.
The Lord was very good to that family, in feeding them with the dew of heaven,
and with the sweet incomes of his love, according to his promise.
Glory and honour, and living eternal praises, be given to the Lord God forevermore.`"

An anecdote will illustrate the unreasonable enmity against Friends,
which at that time prevailed in the north of England.
As Miles was going towards Swarthmore,
a woman whom he passed without uncovering his head to her,
ordered her servant to follow and beat him.
This unreasonable abuse, Miles patiently submitted to.
Towards the close of the year, feeling a concern to visit the woman, he went to her house.
She came to the door, and knowing him,
and being desirous to avoid hearing what he had to say,
feigned herself to be some one else.
Miles, though unacquainted with her person, from a secret impression upon his mind,
was convinced that she was the one, whom he had come to see.
After reproving her falsehood on the present occasion,
he delivered a solemn warning to her, ending with this exhortation,
"`fear the Lord God of heaven and earth, that thou mayest end thy days in peace.`"
Three years afterwards, the servant, who at the command of his mistress had beaten Miles,
came to him, and requested forgiveness, desiring he would pray to the Lord for him,
that he might obtain peace of mind.
To these requests he made this Christian answer, "`Truly friend,
from that time to this day,
I never had anything in my heart against thee or thy mistress, but love.
The Lord forgive you both.
I desire it may never be laid to your charge, for ye knew not what ye did.`"
Miles adds to his account of the occurrence, "`So I parted with him;
my heart being exceedingly broken with the true love of God,
who had pleaded my cause in the hearts of my persecutors.`"

In the latter part of the year 1652, or in the beginning of 1653,
Edward Burrough accompanied his fellow-labourer in the gospel, John Audland,
in one of his earliest, if not in his very first, journey on a religious account.

Of the success of their gospel labours John Audland thus writes:

[quote]
____
Praises and honour to our God forever, who is worthy, for all is falling before Him.
My dear Friends, the harvest here is great; even all the fields are white,
and all the dumb dogs and idle shepherds, drones and loiterers run, quake,
tremble and fly before us.
The sword of the Lord is in the hands of the saints, and this sword divides,
hews and cuts down, and so way is made for the pure seed to arise and reign above all,
which conquers all.
Praises be to the Lord forevermore.

Dear Friends the work of the Lord is great, and many are convinced of the living truth,
and I really see the Lord will raise up to himself a pure and large people,
to serve and worship him in spirit and in truth.
My dear brother and fellow-labourer, Edward Burrough, salutes you in the Lord.
____

Edward Burrough at this time, could scarcely have been older than in his nineteenth year,
yet he was accounted an able minister of the gospel,
being zealous in his Master`'s cause and wise in spiritual things,
understanding the way of life and salvation; and was withal earnest in his manner,
and fluent in the delivery of those important doctrines
which he was commissioned to preach.

How long he continued travelling with John Audland we have no means for ascertaining.
He appears however to have been much engaged at this
early period in labouring in his own county,
and elsewhere, in the markets, the streets, in places of public worship,
and wherever his Master sent him with the message of life and authority to proclaim it.
He had a remarkable gift in discerning the states
and conditions of those amongst whom he was sent;
and the exercise of the wisdom bestowed on him, no less than his zeal,
was often called for.

About the close of the year 1653, or in the beginning of 1654,
Edward Burrough was imprisoned for writing a letter of Christian
reproof to one who was living in gross wickedness.
During this confinement he prepared for publication a manuscript,
bearing the title of _A Warning from the Lord to the Inhabitants of Underbarrow,
and so to all the inhabitants of England._
In this he first addresses the people of Underbarrow,
opening to them the spiritual nature of the gospel of Jesus Christ.
He tells them, that he had, at four different times,
entered their place of public worship, under a sense of religious duty,
in order to declare the Truth among them,
but that as he could not have liberty to speak there,
he now cleared his conscience by writing to them.
He appeals to the Searcher of hearts, to witness, that it was not in his own will,
but in the cross to it, that he had gone to their meetings.
His object was to show them that they were in bondage to a ceremonial, formal worship,
and to a dependance upon a man-made and deceitful ministry,
which tended to keep their souls in death.
That his concern was to direct them to wait, in spirit and in truth on the Lord,
in order to attain the true knowledge of Him, and of that one thing needful,
the eternal welfare of their souls.
He desires that they may be led out of the will-worships of the world,
to worship God in spirit and in truth.
He had had several arguments with their minister,
who had denied the doctrine that Christ, by his light or Spirit in the soul,
enlightens every man that comes into the world.
This he continues, is to make Christ a liar, and proves the assertor of it,
to be ignorant of the first principles of religion,
not knowing the light of the Holy Spirit which leads to God.
This light, which the servants of God in all generations were witnesses of,
Edward Burrough declares,
he and his fellow professors experienced to shine in their hearts,
showing them the deceit of all such ministers, as the priest of Underbarrow.

He then declares that he and his brethren own the one saving baptism,
that of the Holy Ghost and fire;
and witness a being baptised by the One Spirit into the One body,
of which Christ Jesus is Head, though they do not use water baptism.
That they reject the administration of bread and wine as a Christian rite,
whilst acknowledging the communion of saints,
the partaking of the body and blood of Christ,
by which they were nourished up to eternal life.
Singing in the spirit, and making melody in the heart to the Lord,
the singing of that song which none but the redeemed ones can learn, they acknowledge,
believing it to be well pleasing to God; but the singing in the will of man,
without the Spirit, as generally practised in their places of worship,
they reject "`as carnal and traditional.`"
"`True preaching of Jesus Christ crucified we own, and do witness;
for this preaching is not of the will of man, or form and custom, +++[+++but it]
is foolishness to the wisdom of the world now, as it ever was.
This is not with the enticing words of man`'s wisdom,
but in the demonstration of the Spirit and of power.
The preaching of the word of faith, which is nigh thee, in thy mouth and in thy heart,
we do own; for faith comes by hearing of this word preached.
Prayer with the Spirit of Truth we do own, for that is not in word +++[+++merely]
to be seen of men; not by custom, form and tradition, but by the Spirit,
which hath free access to God, and which he heareth, and doth accept.`"

After bearing testimony against the too general depravity of the professors of religion,
and warning them to repentance, he adds;

[quote]
____
Now is the day of your visitation,
wherein the Saviour of the world stands at the door and knocketh.
If any open unto him he will come in: therefore prize your time,
and hear the word of the Lord, and lay aside the works of darkness, lying, swearing,
mocking and scorning, and beating your fellow servants.

Repent and turn to the Lord with mourning and lamentation,
and cease from all your former ways and doings.
Cease from covetousness and oppression, ye aged people; cease from lightness,
vanity and pride, ye young people; and from all priests and steeple-houses,
for there your lightness, pride, and vain minds are fed and nourished,
and the enemies of the Lord are strengthened.
Dear people, there I once had fellowship with you in your pride, lightness and vanity;
and there was once my joy and delight.
But now I am chosen by the Lord out of all these things; praises be to Him forever,
to serve the Lord in declaring against all these abominations.

All ye people, mind the light; for the light hath enlightened every one of you,
which is the Saviour and redeemer of him that loveth it, and bringeth his deeds to it:
but it is the condemnation of him that hateth it, and walks not in it.
Therefore all people, mind this light which is of God; this will lead you up to God.
This is the way to the Father, and no man cometh to the Father but by me, said He,
who was, and is the Light.
If you love this Light, and walk in this Light,
it will bring you to be witnesses of the Scriptures, and of the saints`' condition,
which you are but talkers of This is the Light from which they spoke,
who spoke the truth of God; and from this Light did Isaiah,
who lived in the obedience of it, cry against the greedy dumb dogs,
that sought their gain from their quarter.
So did Jeremiah, Ezekiel, Micah and Malachi cry against hirelings,
and against them that said, "`The Lord saith it,`" and he never spoke to them;
and against them that preached for hire and divined for money;
and taught for the fleece,`" and yet leaned upon the Lord, saying,
"`Is not the Lord among us?`"

Love the Light and obey it.
It will separate you from all filthiness, and corruption,
and lead you into purity and holiness, without which none shall see God.
There is your teacher, always present with you, which teaches to deny ungodliness,
and the wicked ways of the world.
____

At the close of this address,
Edward Burrough felt his heart drawn to salute his brethren, commonly called Quakers,
who had been brought, through the obedience of faith,
into religious fellowship with one another in the Lord.

[quote]
____
By faith, +++[+++says he,]
with Abraham, are ye come out of your native country, from your kindred,
and out of your father`'s house: with Moses,
have ye forsaken the glory of Pharaoh`'s house,
and chosen rather to suffer affliction among the poor despised people,
than to enjoy the pleasures of sin.
Great shall be your reward, ye contemned ones: glory,
honour and everlasting happiness is prepared for you, if you stand faithful to the end.
The Lord is with you as a mighty terrible one;
and therefore shall all your persecutors be ashamed and confounded.

Walk in the fear of the living God, and despise not the cross of Christ,
but let the cross be your rejoicing,
for through the cross is the power of the Lord made manifest.
Rejoice, and be exceeding glad, that you are counted worthy to suffer shame and reproach,
and some of you imprisonment for the Truth`'s sake.
Thus it ever was; he that is born of the flesh, persecutes him that is born of the Spirit.
Be glad and rejoice in the Lord, for you hath he chosen to shine as lights in the world,
and to be a burdensome stone to the nations.
Your fame has gone abroad,
and because of the manchild that is born are the nations troubled,
and the chief priests and rulers combined together.
But that the Lord may be glorified,
for your sakes will he scatter the proud in their imaginations,
and will break in pieces the snares which the chief priests have laid for your feet,
and they shall be taken in their own craftiness,
and fall in the pit which they have digged for you.
The Lord, who hath called you, will set you upon a rock,
and will preserve you out of the mouths of the wolves,
who devour souls for dishonest gain.
____

The encouragement held out to his faithful fellow believers,
that they should experience preservation,
even amid the cruel persecution of their enemies, was fully realized.

All the machinations of their opponents, aided by the strong arm of the government,
and the relentless power of persecuting priests and magistrates,
failed to crush the Society of Friends.
The doctrines they promulgated were responded to
by the witness for Truth in the hearts of multitudes,
who weary of a lifeless profession of religion,
cordially embraced what they found to be no cunningly devised fable,
but the living substance.
Almost every day, some were added to their number, by the power of heartfelt conviction,
and in a few years, they grew to be a considerable people.

Their patient consistency and steadfastness in the performance of their religious duties,
undaunted by personal abuse and cruel imprisonment, finally wore out persecution;
while the meekness and blamelessness of their lives and conversation,
won for them the esteem of the moderate,
and even extorted commendation from their enemies.

The scriptural soundness and excellence of their Christian testimonies,
though at first derided, misunderstood and misrepresented,
at length attracted the serious attention of many in different religious denominations,
and exercised a salutary influence in opposition to the
deadening effects of empty forms and stated rituals.
Many of the spiritual views, which, for many years, the Society maintained single handed,
have since been taken up and advocated by those who
have not been gathered into the same outward fold,
and have had no inconsiderable influence in modifying
the opinions of other Christian professors.
