== Chapter III.

John Camm and John Audland were the first preachers amongst Friends,
who visited the south-west of England.
In the fifth month 1654, they were in Bristol, at which place they appointed meetings,
which were largely attended; many of their hearers were seriously awakened,
and not a few were convinced of the truth.^
footnote:[Josiah Cole, Charles Marshall and many besides,
who afterwards proved valiant men and women in supporting the doctrines of Friends,
were convinced at these meetings.]
Their first visit to the city was brief, but they returned in the seventh month,
after they left London.
They held many meetings in Bristol and its vicinity,
and the same overshadowing influence of the divine presence was with them,
as attended their first labour there.
The newly convinced were confirmed, and the opposing spirit in some was shaken.
They left Bristol again about the 22nd of the seventh month, and travelling north,
were at a meeting at Hereford on the 25th, from whence they proceeded to Bramyard.

In the eighth month, Edward Burrough and Francis Howgill left London,
under a concern to visit Bristol.
They reached that place about the middle of the eighth month, and on the next first-day,
the 21st, they had a meeting in the Castle,
which was attended by many hundreds of people.
When the meeting was over,
in order to obtain a little quiet retirement from
the company of interested and inquiring persons,
who constantly thronged about them, they retired into the country,
to the residence of a captain in the army, about one mile from the city.
Their plan to obtain seclusion did not succeed,
for many followed them and filled the house.
Every day of the succeeding week they had meetings either within or without the city,
largely attended by the citizens,
and crowned with the sensible evidence of divine regard.
On the morning of the following first-day (28th), they were in the city,
at the house of George Bishop, then a military captain,
but afterward a soldier of Christ Jesus the Prince of peace.
His house was large, but it proved altogether inadequate to accommodate those who came.
In the afternoon they went out to the fort, and at the meeting held there,
it is supposed two thousand persons were present,
amongst whom were many of the great men and women of the city.
This large assembly was very quiet, but the multitude was so great,
that the preachers could scarcely extend their voices,
so that those in the outskirts could hear.
When the services of the meeting had closed,
Edward and Francis found it difficult to get away from the awakened crowd;
and they say in a letter to Margaret Fell that they
were obliged to retire into a private chamber.

The priests and magistrates were incensed at the effects
produced by the gospel labours of these ministers of Christ,
and determined if possible to find some cause of complaint against them.
On second-day they came into the city, and going to the house of a merchant,
information was soon spread.
The mayor, aldermen, justices of the peace, with some of the priests assembled,
and a sergeant was sent to bring the strangers before them.
Edward and Francis, conscious of having violated no law, readily obeyed the summons,
and were accompanied by many of the military officers, and great men of the city,
who had been in a measure reached through their ministry.
These were not, however, allowed to be present at the examination that took place.
After Edward and Francis had informed those before whom they were taken,
that they had come according to their desire,
the magistrates manifested great wrath because they did not take off their hats.
Being informed that it was not out of contempt of authority,
but for conscience sake that Friends did not uncover the head to their fellow men;
they were asked their names and country.
We will give the rest in Francis Howgill`'s words,
contained in a letter to Margaret Fell, which was signed by Edward Burrough.

[.embedded-content-document.letter]
--

They asked us how we came to the city, and we answered them;
and told them the command and motion of the Lord;
that we had to bear witness to his name and to declare the gospel committed unto us.
It was asked whether our call was mediate or immediate; we answered immediate;
we denied all mediate calls, for they were carnal.
They said if we had the same immediate call declare it.
Then I declared what I had been and what I was.
We declared where we had habitations, and that at the command of God we left them:
we spoke about a quarter of an hour, and they gave audience.
They asked if we accused all ministers in England?
We said no; there were many ministers of Christ in England, and we had unity with them;
but all hirelings, and such as sought for their gain from their quarter, we denied.
They pleaded for hire; and said the light was natural, and that every one had it not,
and the like.
They also said, we dishonoured the gospel.
After much striving and contending, when they could not ensnare us,
they all cast their ears together, and said, we had tumultuous meetings,
to which one of their own +++[+++number]
answered, there were many godly honest people +++[+++collected]
without tumult.
So they could get nought against us, and they commanded us to depart out of the town;
but we were bold, and said, we were free-born men,
and we knew no law we had transgressed,
and therefore we should not be at any man`'s will; but when He moved us that called us,
we should +++[+++depart]; and come in again as he moved.
So we passed away, and all the people were silent,
and the priest and magistrates were enraged.
We stayed till night, and then went out of the city.
This day +++[+++ninth month]
we were moved to come in again, and walk the streets.

Here is a pretty people, and a great harvest; it is like that bonds will attend us;
but all is one; in the will of God we stand free, out of all.
John Audland and John Camm, we see not yet, but expect their coming.
Here is a thirsty land; and truly, the sound of the gospel committed to us,
is gone through all the regions round about.
The living God of life preserve us in his eternal power and wisdom;
in the will of the Lord we stand, and none can take away our joy.

Salute us dearly to George Fox; one hour with him would be great joy to us.
We +++[+++have]
want of nothing without; the Lord reward thee (and thou hast thy reward),
for the care and love over all the church of Christ.

--

The account of this interview,
given in the "`sufferings of Friends,`" relates rather more of their reply to the magistrates;
it closes thus, "`We are free-born Englishmen,
and have served the commonwealth in faithfulness,
being free in the presence of God from the transgression of any law.
To your command we cannot be obedient, but if by violence you put us out of the city,
and have power to do it, we cannot resist.`"

They continued in and about Bristol,
labouring to fulfill the requiring of their divine Master, during the ninth month,
and it would appear without molestation.
The magistrates astonished at their innocent boldness, knew not what to do with them,
and the priests had not yet matured their plan for
stirring up a persecuting spirit in the mob,
by whose hands in a few weeks afterward, John Camm and John Audland suffered much abuse.
In the mean time,
the faith of those who had been convinced of the truth in that neighbourhood,
was strengthened by the labours of these faithful Friends, and they grew in grace,
so that they were enabled in a remarkable manner
by their constancy in sufferings and imprisonments,
to hold up a light to the world.

Rumors of the great meetings held by Friends in Bristol,
spread far and wide through the country; and twelve Baptists came out of Wiltshire,
to have a public dispute with Edward and Francis.
A meeting was accordingly held, and their confident challengers being unable,
either to defend their own views,
or controvert the doctrine of those they had come to overthrow--fled from the contest.

On returning home in order to cover their defeat,
they reported that the Quakers cursed and swore, and denied Christ and the scriptures.
These reports reached the ears of Edward and Francis,
who were about leaving Bristol to return to London;
the care of Friends there still resting upon them.
Edward had also some controversial tracts about passing through the press in that city.
It was early in the tenth month, that they took leave of their friends at Bristol,
and passing into Wilts,
came to the town where the discomfited champions had spread those false reports.
The people of the place were very fierce towards them,
but they obtained liberty for a meeting in the market place to clear themselves.
As they went to it, they felt a sense of great inward weakness and insufficiency,
which led them to look to the alone source of strength and true wisdom for assistance.
A large company gathered, amongst whom was the mayor of the town,
and a justice of the peace.
They soon felt the power of the Lord strengthening them;
so that for two hours they spoke with irresistible authority, in defence of the truth.
They then had a dispute with two of the Baptists for four hours,
at the conclusion of which their opponents laid aside all boasting.
The justice of the peace thus expressed his satisfaction,
and said he had never heard any, who spake like them, and invited them to his house,
where on the following day they went.
In the evening, the mayor of the town called on them,
confessed that they had spoken the truth, and said if he did not witness to it,
his conscience would witness against him.

This dispute opened their way in Wiltshire, and they had many meetings.
They stayed two days at the house of justice Stooker, who with his wife,
was convinced of the truth, as were many others.
When they departed for London,
the justice sent his man and horses to take them fifteen miles on their way.
From this circumstance, it is evident that their travels were much on foot.
It would appear from a passage in George Fox`'s journal,
that almost immediately after they reached London,
Francis Howgill must have returned to Bristol.
Edward Burrough remained a short time in London,
but towards the close of the tenth month, he met with his friend and former companion,
at a general meeting held at Swanington, in Leicestershire.

By whose agency this meeting was called, no information appears to have been preserved.
George Fox says of it, "`many Ranters, Baptists, and other professors came.`"
The Ranters were as usual wild and rude, but the power of truth,
was present to confound them.
On the second day of the meeting, Jacob Bottomly, a great Ranter, came from Leicester;
but he too was restrained by the Lord`'s power, as was also a priest,
who attempted to oppose.
George Fox says, "`the priests, Baptists, Ranters, and other professors were very rude,
and stirred up rude people against us.
We sent to the Ranters to come forth, and try their god.
Abundance of them came, who sung, whistled and danced;
but the Lord`'s power so prevailed over them, that many of them were convinced.`"

From Swanington, Edward and Francis returned to London.
Among the changes which had taken place in that city,
several of the newly convinced had been called and anointed
to preach the gospel of life and salvation.

Let us now examine what Edward Burrough had been doing with his pen this year,
in which as we have seen, he had been so abundantly occupied in ministerial labours.
Soon after Friends began to hold meetings in London, many Anabaptists,
being convinced of the truth of the gospel, joined them.
This stirred up the zeal of some of their late companions,
who still considered Quakerism to be a dangerous heresy,
and occasioned the publication of a book entitled, [.book-title]#The Quaker Principles,
Dashed in Pieces by Enoch Hewitt, an Anabaptist.#
Edward Burrough, was prompt in answering this, and in the strong and quaint language,
generally adopted for the titles of books in that day, called his tract,
_The Walls of Jericho Razed Down to the Ground, or An Answer to a Lying Book,
Called the Quakery, etc._
One of the charges which Hewitt in his tract, makes against Friends,
is "`They oppose the word of Christ, to the written word;
and will have a word that is a discovery spiritual, to be the word; but whatsoever it is,
they call the word, it is perfectly false, and not the truth.`"

Edward reproves him for allowing his misstatements,
to be carried up and down the streets of London as ballads, and says,
"`We do not oppose Christ to the scriptures; for Christ is the word,
and this the scriptures doth not oppose, but bears witness to him who is the word;
and his name is called the word of God.
And this Word became flesh and dwelt among us; as the scriptures witness;
and the word of the Lord endureth forever.
Thou that wouldst set up the latter in the place of God, to try all things,
and to search all hearts,--thou makest an idol of it, and so opposes God with it,
and would bring that to contend against the Lord, which they witnessed through suffering.
I tell thee and all the world, the word is but one, and all who know God, hear that word.
It is a light and a lantern to their paths; but that is invisible and eternal,
and what the saints witnessed of his word, they declared, and the scripture is true,
and bears a true record and testimony of the word,
and they were witnesses of the word of life that wrote it.
It is a true declaration of these things that are certainly believed,
of the which they saw, and heard and tasted.`"
"`Let all that have heard us in the city of London, or elsewhere, speak,
if they heard us say the scriptures were useless, or did disesteem them;
but on the contrary we exhorted them to search if the scriptures
did not bear witness to these things we declared;
and so let shame cover thy face, thou false accuser.`"

To the charge of denying the Lord Jesus, that was crucified for them;
Edward Burrough says, "`We deny not the Lord that bought us,
for by Him can we say we have received the end of his coming,
and of his death and ascension; even he hath purchased us,
and set us free from the power and kingdom of the devil.`"

Edward Burrough bears a clear testimony to the belief of Friends,
in the resurrection and ascension of Christ,
and in replying to the charge of denying the ordinances of God,
and the Lord who bought them, he says, "`The way unto God and unto everlasting life,
which is Christ Jesus, we do not deny, but are true witnesses,
that the same Christ alone, which was crucified at Jerusalem,
and which God had raised from the dead, and which is ascended, in him alone is salvation,
and by him also alone are all justified that believe on him.
This we declare freely unto all people, that Christ is the ordinance of God,
ordained by him for the salvation of all that believe,
and for the condemnation of all that believe not in him.
And that the way unto this Christ, is not any outward visible thing,
but even that which is manifested from him, and leads up unto him; even the light,
by which he hath enlightened every one that cometh into the world,
which is spiritual as Christ is spiritual.`"

"`The one baptism, which is by one spirit into one body, into the death of Christ,
we are witnesses of; and the bread which we break,
is the communion of the body of Christ; and we being many are one bread;
but the beggarly elements of the world we testify against,
being witnesses of the substance.`"
After declaring once more Friends willingness to be judged by the scriptures,
he concludes thus: "`If thou find any that disown the scriptures, we also disown such,
and do say, they are not spiritual men, but have the spirit of antichrist.`"

E+++.+++ Burrough`'s next work,
was an answer to certain questions put forth by a priest called Philip Bennet,
and a ranting deceiver named John Reeve.
This was followed by a review of a work entitled _Choice Experiences,
Written by J. Turner, a Female._
In this review he shows wherein the doctrine contained in the _Choice Experiences,_
is contrary to the truth.

The success attending the ministry of Friends, and the rapid increase of their converts,
created at this time great alarm among many of the ministers of other societies.
They were stirred up to oppose and vilify the principles and practices of those,
who seemed taking away their congregations.
Many pamphlets were put forth,
the evident design of which was to make Friends appear ridiculous,
heretical and dangerous in the eyes of the community.
None of these pamphlets appear to have been suffered to go unanswered.
One of them written by a John Griffith, entitled _A Voice From the Word of the Lord,
to Those Grand Impostors called Quakers,_
called forth a prompt and spirited reply from Edward Burrough, In this essay,
Edward Burrough makes frequent declarations of the full belief in,
and regard for the Holy Scriptures, which he and his brethren in religious profession,
entertained, as well as many other points of Christian doctrine,
some of which we shall quote:

"`That we reject and despise the scriptures and the words which Christ spake,
which thou accusest us of, is another false slander:
for the scriptures we own in their place, and by the Spirit of God set to our seals,
that they are true.`"
"`I charge thee with a lie in thy mouth, who sayest,
'`We would not have men read the scriptures.`' "`They who have heard us,
shall witness that, that we do direct to search the scriptures,
whether our doctrine be true, and by the scriptures shall our doctrine be tried.`"

John Griffith says, "`they talk of high enjoyments and great revelations, without, above,
and beyond the scriptures, and of a light, which is besides the scriptures,
but it is deep and thick darkness.
And what hath such lights led men into?
even contempt of God, and of all righteousness.`"
He also adds.
"`they call the scriptures a dead letter.`"

Edward Burrough replies; "`Here thou art an accuser of the brethren;
for what we do declare, the scriptures witness to the same.
We speak of nothing, but what is declared of in the scriptures, by the holy men of God;
and neither without it, nor above, nor beyond it, do we speak.
I challenge thee to prove what thou hast asserted, and all the city of London,
whether we have spoken or declared any thing but what the scriptures bear witness to.
And the light which we declare of, is the light of Christ; which the scriptures saith,
hath enlightened every one that comes into the world.
It is not besides the scriptures, so as +++[+++to be]
contrary to it, but the scriptures bear witness of the light;
and here I charge thee with blasphemy, who says, the light of Christ,
which is the light that we declare of, hath led them or leads any to contemn God,
or his ordinances, or righteousness.`"
"`If you know any who cry against the scriptures,
and against the doctrine therein contained, we cry and declare against such;
for the scriptures we own in its place, to be a true declaration of God, of Christ,
and of the saints conditions; but they are not the light, but Christ is the light,
as themselves bear witness.
Nor are they the saints`' guide, but the spirit that gave them forth +++[+++is],
as they themselves bear testimony.
Neither were the scriptures given forth,
to give your own imaginations and suppositions upon,--but
they themselves are doctrine,--and are as they speak;
he that hath the same spirit which spake them forth, reads them, and understands them,
and none else.`"
