== Chapter VI.

Early in the year of 1656, Edward Burrough was arrested at Kingston in Surry,
and taken with nine of his friends, before the magistrates of that place.
Under what pretence they were arrested the account left of the transaction does not show,
but the magistrates tendered them the oath of abjuration,
and because they refused to take it, committed them to prison.
The persecutors knew that Friends conscientiously
believed it to be unlawful for a Christian to swear,
and the plan they frequently adopted of offering them the oath,
was therefore an easy and sure means of furnishing
a legal reason for casting them into prison.
Edward was not very long in confinement.
He appears this year whilst in prison, and out of prison,
to have been diligently employed with his pen in
defence of the doctrines and testimonies of truth.

Many of the clergy of the different denominations,
were engaged in writing and printing against Friends;
some of them out of fondness for religious disputation;
some because they deemed their craft in danger,
and others no doubt prompted by the persuasion that Quakerism was adverse to Christianity.
Being in great measure outward in their views,
and regarding religion as a system of forms and ceremonies,
rather than the dedication of the heart to the Lord,
and submission to the cleansing operations of his Holy Spirit,
they could not understand the spiritual doctrines
so earnestly advocated by our early Friends.
They had no desire to find those to be true Christians,
who denied the lawfulness of compelling any to pay for preaching,
and who considered the receiving hire for such service as contrary to
the commands of the Head of the church,--the giver of all spiritual gifts,
and the alone paymaster of his ministers.

Friends`' steadfastness in refusing to uncover the head in token of honour to men,
which mark of worship they believed due only to God, their Creator,
was construed into a disregard of authority,
and a perverse infraction of the proper courtesies of life.
Their plea for the immediate counsel and direction of the "`Holy Spirit,`"
the "`light of Christ,`" the "`light within,`" was believed by some,
and declared by many, to be from a disbelief in the scriptures of truth,
notwithstanding their constant denial of such an unjust inference,
and their offers in all controversies with their adversaries,
that their faith and practice should be tested by scripture authority,
and that all which could not be thus sustained should
be reckoned and accounted a delusion of the devil.
Some deemed them socinians,
because they did not so frequently hold forth in their ministry and writings,
the benefits derived from the outward offering of our Lord Jesus Christ,
as their opponents deemed needful.
In reply to this charge.
Friends said they were no socinians, that they steadfastly believed in the divinity,
offices, birth, labours of love,
propitiatory sufferings and death of the blessed Saviour Jesus Christ;
and if they did not treat so much on these subjects, as some others did,
it was because they were almost universally preached, and professed in Christendom,
while the gift of the Holy Spirit, purchased for us by the death of Christ,
and universally bestowed upon all mankind as their rule and guide,
was scarcely upheld or preached by any;
and therefore there was more need to direct the minds of the people,
to this divine and saving light in themselves, that through obedience to its discoveries,
they might be led out of sin, and brought into holiness of life and conversation.

Amongst those who took up the pen against the Quakers, was John Bunyan,
who misunderstanding or misrepresenting his antagonists,
zealously beat the air in his attack on a fancied unsoundness.
Edward Burrough was not slow in replying to him,
and having a better opportunity of knowing the truth,
he was able to refute Bunyan`'s unfounded accusations.

Bunyan asserted that "`Friends undervalued the Lord Jesus, God-man;
and though they spoke much of Christ,
did not savingly and rightly lay him for their foundation.`"
On this charge Edward remarks; "`We prize the Lord Jesus Christ, God-man,
to be precious unto us, and unto all that do believe,
and have owned Him alone to be the foundation,
whom God hath laid for salvation to the ends of the earth.
In his light are we saved, and therein do walk; and because hereof are we hated by thee.`"

Bunyan charged Friends with saying,
that "`salvation was not fully and completely wrought out for sinners, by that man,
Christ Jesus.`"
To which Edward Burrough replies,
"`this accusation is clearly false and wickedly cast upon us;
for there is not salvation in any other, nor is it wrought by any other,
but by Jesus Christ.
It is fully and completely brought forth by Him unto every one
who believes and receives the testimony of it in themselves.`"

Bunyan said "`Friends bade persons follow the light,
that they brought into the world with them;
telling them that the light would lead them into the kingdom, etc.`"
Edward Burrough replies, "`this is falsely laid down, +++[+++to say]
the light that they brought into the world with them:
But this is the truth of God and no lie, that to follow the light of Christ Jesus,
wherewith he hath lighted every man that cometh into the world,
will lead into the kingdom of peace and righteousness; for Christ saith,
'`I am the light of the world, he that followeth me shall not walk in darkness,
but shall have the light of life.`'`"

"`Thou goeth on proving,`" says Edward Burrough, "`that He is the Saviour,
that was born of Mary; which thing we never denied,
and therefore I need the less to answer thee.`"

[.discourse-part]
_Bunyan:_ How horribly are those deceived,
who look on Jesus to be but a shadow or type!

[.discourse-part]
_Edward Burrough:_ I know not any who do it, and yet thou sayest,
of something that was afterwards to be revealed, etc.
This hath some truth in it, which is this; the same Christ who was born of Mary,
who wrought righteousness in his person, by doing and suffering,
who was and is the substance, was afterwards revealed in the saints;
and this is no horrible deceit, to witness Christ revealed,
or to wait for him to be revealed within.

[.discourse-part]
_Bunyan:_ How are they deceived,
who think to obtain salvation by following the convictions of the law,
which they call Christ, etc.

[.discourse-part]
_Edward Burrough:_ It is no deceit to mind that which doth convince of sin,
to lead to Christ, to take away sin.
Thou art in the deceived state, who healest up falsely,
and daubest with untempered mortar,
and wouldst teach people to apply the promises unto salvation,
while they are in a condition condemned in the sight of God,
by the light in their own consciences, and will not own that-which discovers sin;
how then can they own Him, who takes it away, and purges from it by his blood.

[.discourse-part]
_Bunyan:_ It is not of works, lest any man should boast, as those fond hypocrites,
called Quakers would do.

[.discourse-part]
_Edward Burrough:_ When did thou hear any of the Quakers boast,
or see them live in hypocrisy?
Will that faith which is without works justify?
Must not every one receive according to their deeds, he that doeth good, life?
he that doeth evil, condemnation?
But such is thy feigned fancy of faith, who seeketh to be justified by it,
whilst thou bringest forth the fruits of unbelief.
Thou speakest of living by faith, which thou sayest is to apply the Lord Jesus Christ,
his benefits, birth, etc.
I say, if to talk of him, was faith in him and to live by faith, then few would want him.
For many have got the words, who are without the life of righteousness through faith.

[.discourse-part]
_Bunyan:_ How are they deceived, who own Christ no otherwise,
than as he was before the world began.

[.discourse-part]
_Edward Burrough:_ Did not the saints own Christ Jesus, the same yesterday, today,
and forever, for salvation?
Is there any other Christ, than he who was before Abraham was?
And is he not now glorified with the same glory, mind the same glory,
which he had with the.
Father before the world was?
Is this deceit, to own him as he was before the world was, for salvation?
That was the very Christ, the Son of God, who was equal with the Father,
which was in the beginning, and in time was made manifest in Bethlehem,
and calls himself the Light of the world, that spiritual rock,
which the fathers did eat and drink of, which followed them,
that rock was Christ the salvation.

Thou speakest of some who told thee to thy face,
that thou usedst conjurations and witchcraft,
because what thou preachedst was according to scripture.
To which I say, let the guilty be reproved;
for we deny thy accusation to be true upon any of the Quakers,
which some may think thou speakest of: so thy accusation rests between thee and them,
and we are clear.
For every truth which the scriptures bear witness of, we do own,
and do not condemn any for preaching according to the scriptures.

[.discourse-part]
_Bunyan:_ If every man hath a measure of the spirit of Christ within him,
why say the scriptures that some are sensual, having not the spirit, and Christ saith,
the wicked cannot receive it?

[.discourse-part]
_Edward Burrough:_ Some men are sensual and have not the spirit,
because they receive it not.
Some cannot receive it, because they believe not in him from whom it comes;
yet is the measure of the spirit given unto every man to profit withal,
as the scriptures saith.
It is given within him to reprove him of sin, but few receive it.
It is one thing in God to give the spirit,
and another thing in the creature to receive it.
He gives it to many that receive it not, to follow it, and to be guided by it.

[.discourse-part]
_Bunyan:_ What is the church of God redeemed by from under the law?
Is it something that is done within them, or something done without them?
If it be redeemed by something that worketh in them,
then why did the man Christ Jesus hang upon the cross on mount Calvary,
without the gates of Jerusalem, for the sin of his people; and why do the scriptures say,
that through this man is preached unto us forgiveness of sins?

[.discourse-part]
_Edward._
Burrough: The church of God is redeemed by Christ Jesus,
who is revealed within all that believe.
Christ Jesus wrought in them mightily, to will and to do;
this is plain according to scripture.
And the man Christ Jesus was hanged upon the cross on mount Calvary,
because they wickedly judged him to be a blasphemer,
and through their envy they persecuted him to death,
because he bore witness against them;
and as in their account he died upon the cross for an evil doer,
this is one ground at least why he hanged upon the cross.
And the scriptures say; that through this man is preached the forgiveness of sins,
because there is no other that can forgive sin,
nor the blood of any other thing that can take away sin, but the blood of God,
as it is written.

[.discourse-part]
_Bunyan:_ Is that very man that was crucified on mount Calvary, between two thieves,
whose name is Jesus, the son of Mary; is he the very Christ of God, yea or nay?

[.discourse-part]
_Edward Burrough:_ Yea, he is the very Christ of God, who was before the world was,
by whom the world was made, who was made manifest from Mary`'s womb,
and was persecuted to death by the Scribes and Pharisees,
in whose steps thou treadest in asking subtle questions to ensnare the innocent,
as they did.

[.small-break]
'''

On the 23rd of seventh month 1656, the Parliament published a proclamation,
calling upon the inhabitants of Great Britain and Ireland,
to observe a day of fasting and humiliation, and seeking the face of God,
through the mediation of Christ.

When Edward Burrough read this proclamation,
he was led to consider the oppressive acts of the government towards tender consciences,
and the iniquities which abounded among the people.
The recollection of these stirred him up to take his pen in hand,
and through the medium of the press,
spread amongst the people his thoughts on the subject.
He enumerates various causes of the divine judgment coming upon them, and then adds:

[quote]
____
Many more abominations cry for vengeance against some of you,
who have had your hands deeply dipped in such oppression;
and therefore this is a warning to you to break off
these sins by righteousness and true repentance,
lest your fasts prove only for strife, and to smite with the fist of wickedness.
Clear yourselves and wash your hands from these abominations,
lest the fruit of them be given to you to eat for food.
Let this, O ye rulers! be acceptable counsel unto you,
that the day of happiness may appear,
and the long expected day of liberty may yet dawn through this dark night of bondage,
which overshadows your heads that you cannot behold the glory of the sun.
And herein shall you be established, and we shall have cause to bless the Lord for you,
and with you; otherwise you shall fail, and evil shall be upon you,
and upon the nation for your sakes.

You that fear God, give audience, and keep yourselves pure from the iniquities,
which the rest love to drink in; and though your power be shorter,
and your voice lower than the uprightness of your hearts desire,
be faithful unto God in bearing your testimony for him,
and against all that which with the light of Jesus, you see to be contrary to him.
Be awakened unto righteousness, judgment and mercy.
The light is springing over your heads,
and the day of the Lord is dawning out of darkness;
a seed is sown in your dominions which cannot be rooted out,
till it has overspread the earth with the precious fruit thereof;
and though it be striven against to be plucked up,
yet shall the branch and root thereof be everlastingly renowned, for it is the true Jew,
and he that falls before it shall never rise up again.
____

Edward Burrough, in the midst of his numerous other engagements,
found time to superintend the printing of various
writings from the prolific pen of his friend,
and father in the truth, George Fox.
To some of these he prefixed or added a few lines.
A preface written by him to one of these publications,
entitled A Testimony of the True Light of the World,
bears date the 1st of the eleventh month, 1656.
In this preface he says;
"`This is truth from the Lord God,--there is no other name given for salvation,
but the name of Jesus; there is no other Christ Jesus,
but he who lighteth every man that cometh into the world.
Except this Christ Jesus be revealed by the Spirit of the Father within,
salvation is not received by him.
Therefore all Friends who have received the testimony
of the light of the Son of God within you,
and have believed the report of the Father, and of the Son,
hold fast the word of that testimony and dwell in it, and walk in it.
This is the power of God, which will keep you from all unrighteousness,
and so from condemnation.
If any turn from the light, they run into evil, and backslide from the Truth.
Such shall bear their own shame and condemnation, in the sight of God,
and all his children; for this is the message which was, and is, '`God is light,
and in him is no darkness at all.`'`"

John Bunyan was still unable to understand Quakerism,
and being stirred up by the reply of Edward Burrough,
he came out in print with a "`Vindication`" of his
former charges against the Society of Friends.
Edward was not long in following him through the press with an answer,
in a quarto of 64 pages, entitled, Truth the Strongest of All.
This reply set forth the doctrines of the Christian religion in words,
which to one who was prepared to understand the language employed,
and to give credit to the author for sincerity,
would have been sufficient to establish the Scriptural
soundness of Edward Burrough and his friends.
But John Bunyan was not in a condition to perceive it,
and it is probable that the closeness of the reproofs administered to him,
had a tendency to blunt his appreciation of the force of the argument.

Soon after this publication, which was issued from the press,
in the twelfth month of this year,
Edward Burrough left London to visit the brethren in Essex,
Francis Howgill being at this time in Kent.
Edward soon returned to the city,
where the difficulties connected with James Nayler
and his ranting companions had not subsided.
Appreciating the trials to which some of the newly convinced were subjected,
because of James Nayler`'s fall, Edward wrote two epistles of encouragement to them.
These he sent from London the 2nd of the third month 1657.

The first addressed "`to all the called and chosen to faithfulness in Christ Jesus,
and to such as are found worthy to suffer,`" contains the following; viz.

[.embedded-content-document.epistle]
--

To all the children of light everywhere, who fear and love the Lord,
who are begotten of God, and unto whom he is known in the spirit and in the truth,
this is a testimony of the Father`'s love unto you.
Grace, mercy, and peace, from him that lives forever, the God of light and life,
be multiplied in you all, that you may daily be renewed in strength,
and girded with truth, and armed with the whole armour of God,
and may be kept by his power until the day of salvation,
to walk in subjection to Jesus Christ, witnessing the power and presence of God in you,
and amongst you, giving you power to fulfill his will in all things.
Thus into all righteousness, and out of all evil you may be led,
and preserved unto the end;, and in the end to show forth the praises of God,
in this generation, as a people called of him,
and redeemed by him for his great glory`'s sake; even so Amen, and Amen.

Dearly beloved, this is the message which came unto you, which is true,
that God is light, and in him is no darkness at all;
the message of peace and reconciliation,
and of glad tidings unto all that have sought the Lord, which we received of him,
and you have heard.
All that have received it are gathered to God, and are in covenant with him,
and one with another,
and are in that which reconcileth and joineth unto Christ Jesus the second Adam.
He is the Lord from Heaven, the prince of peace, the Saviour and the deliverer,
who is made manifest in power, and condemneth the transgressor, and slayeth the enmity,
and raiseth the life out of death.
This is he who kills and makes alive, even God who is light, who brings down one,
and sets up another; who makes war against the mighty, and gives peace to the poor;
and besides him there is none.
He searcheth man`'s heart, and trieth the reins, and knows the thoughts,
and every creature is manifest in his sight,
who gives to every one according to his doing.
This is he who standeth in the congregation of the righteous, even in the midst of us,
and siteth Judge amongst the gods.
Unto him must all the gods of the earth bow,
and the inhabitants of the earth must tremble before him;
and unto him every tongue shall confess, and the light in every man shall answer,
when he ariseth to judgment, who is a swift witness,
to condemn or justify all the children of men on the face of the earth.

This is the God of truth whom we worship, and who will be worshipped in spirit,
and in truth, who is the God of Abraham, and his seed forever;
and with him there is no change, nor shadow of turning.
He hath made known his name, and his power, and his wonderful works in this his day,
and hath caused his voice to be heard in the earth, and the dead have heard,
and now live.

And his name is exalted on high amongst all that fear him, and obey his voice;
and he hath given his Son a covenant of light,
who lighteth every man that cometh into the world with the true light of life,
or condemnation, that all who receive him may come to the knowledge of the Father,
whom to know is life eternal.

And this is the Christ, the Saviour, in whom we have believed, and whom we preach,
who is the way, the truth, and the life, the foundation of God, which cannot be moved;
the Word of God is his name, and there is no other name given for salvation.
This is he who was dead, and is alive, and lives forevermore,
and there is no other to be looked for.
If any preach any other, let them be accursed; and if any bring any other message,
let them not be received.

All you who have believed in Christ Jesus, who is the light of the world,
and have received the knowledge of God, who is light himself and searcheth your hearts,
I exhort you, and warn you all in his presence, to wait upon him, and to fear before him,
and to walk with him forever in uprightness of heart,
which is of great price in his sight.
Forget not his righteous judgments, which he hath made known,
lest you wax fat through mercies, and rebel against him,
and become disobedient and gainsaying, and so be destroyed from being a people;
but be stayed upon the Lord, and let your hearts be established with grace.
Be not tossed, nor shaken with any wind of doctrines of men,
which is not from the life of God, nor reacheth to the life in you,
but begets into idolatry, to worship other gods than he who is light.

Be not troubled at temptations, nor at sufferings, nor at reproaches,
nor any other thing; but stand in the counsel of God, and in his long-suffering,
and wait patiently upon him, in your measure of the grace of God received,
which is sufficient for you, to preserve you, that you may receive victory over death,
and over him that hath the power of it,
to trample upon all that which is contrary to the life of God within you,
and without you.
Neither be you troubled nor offended in Christ.
If any among you deny the Lord, and backslide from his pure way,
through an evil heart of unbelief, and so become disobedient children,
and vex the righteous soul, such shall bear their own burden,
and condemnation in the day of the Lord; and shall know, that truth changes not,
but is the same forever, though the deceitful-hearted through unbelief depart from it,
and choose their own ways, and despise the counsel of the Lord, to their own destruction.

But be ye more watchful, and faithful, and valiant for the truth upon earth,
unto the end; that you may be found faithful witnesses unto the name of Lord,
in this crooked generation; and may receive the fulfilling of the promise of God,
and may witness God within you, the Emanuel, the Saviour, God with us.
This is the whole salvation, and there is no other to be expected, or witnessed,
than this, that God dwells in us, and walks in us, according to his promise;
and all that know this, need not go forth to the right hand, or to the left,
but salvation is come unto us.

He takes away sin, and saves from it, and from condemnation;
and who witness this are begotten by the word of God, and born of the immortal seed,
and are new creatures.
Now there is no condemnation, but the reward of righteousness and peace to us,
who are not in the flesh, but in the spirit.
Here we witness the Lord is our God, and we are his people,
and he seeth no sin in us who are born of him, nor remembers iniquity;
but his covenant is with us,
and the kingdom is become the Lord`'s and his dominion is set up.
Here God is all in all, where the prince of darkness is cast out;
and this is the end and substance of all ministrations, which we bear witness of.

I exhort all you that are called of God everywhere,
patiently to wait in the way of the Lord, and in his judgments, to receive this,
and to possess it within you, that you may be worshippers of God, and doers of his will,
and may have the witness, that you are accepted of him,
and may know your calling and election sure, where nothing that defileth can enter,
but that may be taken away and removed.
And him you may feel and witness, whom Satan hath nothing in, who is the second Adam,
and cannot be overcome, but is greater than the first Adam,
who was overcome (though innocent), and is lost from the presence of God.
But he in whom there is no sin, and who cannot transgress,
comes to seek and to save that which was lost in sin,
and to bring back that which was driven away by sin.
He is greater than innocency, and overcometh the devil, and is called the Son of God;
and to him that overcometh, who is the light of the world,
is all power given of the Father.
And know him in you all to be greatest, who is not of the world,
nor can bow to the devil, to give you dominion and authority over all the world,
and the powers of hell and death, even he who sealeth up the old dragon in perdition,
never more to deceive.
He who witnesseth this, knoweth the election which it is not possible to deceive,
or be deceived.

As every one of you have received him who is the Lord from Heaven,
so let your faith stand in him, and walk in him;
and let all your conversation be ordered by him,
in all pure and blameless walking in the sight of your enemies,
that it may be manifest that you are branches in him,
and that you have received power to become the sons of God,
and that you are heirs of the inheritance which shall not fade away.

And all you that witness this, your eye is open to see God,
and you are cleansed from sin by the Word of God, and you have received peace with God,
and glad tidings from him in your own souls; and this is salvation by the second Adam.
Herein be established and settled, and look not for another;
for there is not any besides this Saviour, and this salvation; but if any preach another,
believe him not; and if any cry, lo here, and lo there is Christ, without you,
go not after them, nor follow them, but know him within you, who is greater than all.
Yea, if we ourselves, or an angel from Heaven, preach any other Jesus,
than he that lighteth every man that cometh into the world; or any other salvation,
than God with us, let us be accursed.
For this is the gospel of our salvation, Christ Jesus within us the hope of glory,
the power and wisdom of God to rule and reign in us,
by which we are changed from death to life,
and translated from the power of darkness into the kingdom of his dear Son.

And now all Friends and elect of God, who are called and faithful,
you that have received this testimony which God hath given of the Son,
and which the Son hath given of the Father,
which in faithfulness hath been testified in this generation;
I exhort you all in the fear and counsel of the Lord,
take heed to that which you have believed, and heard, and learned of the Father,
which is the truth as it is in Jesus, and shall abide forever.
Be not removed from your hope, nor given to change, but mind the life of God in you all,
which is immortal, and is but one,
and it answereth to the Lord in judgments and in mercies,
and one to another in that which is righteous and just,
and witnesseth against all the works of the world, which are evil,
and not wrought in God.

Ye that know this which is of the Father in you, dwell in it, and walk in it,
and be not shaken out of it, nor removed from it,
for it is the way of peace unto everlasting rest, where there is no sorrow,
but righteousness, peace and joy in the Holy Ghost.
Every one in particular, have salt in yourselves to savour withal,
that you may resist the wicked one in all his temptations,
and may not join to anything which is out of union, and contrary to the life of God,
and to the truth which you have received; that you may never be betrayed of your hope,
nor of the simplicity which is in Christ Jesus, in which the Father is well pleased.
Let the light of the world guide you in all things,
that your works may be wrought in God, never to be condemned, nor you to suffer loss;
knowing this first, that none are justified by him,
but them that are led and guided by him; and to whom he is a Saviour,
he is also a teacher, and he is given to teach in all the ways of truth.

Let your fellowship be in the life and power of God,
and know not one another in words only, and in outward appearance,
but witness one another in the spirit and in the truth, and have communion there,
in breaking the bread of life, that Christ Jesus may be seen to be head in you,
and you members to serve him, and one another, all receiving wisdom from the head,
and virtue from the vine, Christ Jesus, that you may abound in love, mercy and peace,
and all the fruits of righteousness unto the Father.
Dwell in the fear and counsel of God, and be subject to his will,
not despising the cross, which is the power of God,
which slayeth the birth that is born of the flesh, which is not heir of the promise;
but walk in the cross daily, that your understandings may be kept open,
to try and discern all spirits, whether they be of God.

Believe not every spirit, for lying spirits may arise among yourselves,
and go forth from the light, who are not in the truth,
but in the feignedness and hypocrisy, with false visions, and lying imaginations,
handling the word of God deceitfully, and corrupting and perverting the pure way of God;
having the form, but not the power, having left the power and gone from the light.
Such utter the words of truth without the life, and are but as the chaff to the wheat,
and they are to be denied and resisted, and not joined to,
lest innocency and simplicity be betrayed, and your faith made void,
and so you be destroyed from the life of God, and death surprise you,
and darkness enter your dwellings, and so unbelief, and doubting and murmuring,
and lustings after evil arise in you,
and you be perverted from the worship of the true God,
and grieve his righteous spirit by bowing to idols, and following of other lovers;
and so the true God, who hath brought you out of Egypt,
and made manifest his power in you, be forgotten,
and the faith of his Son made shipwreck of,
and your latter end be worse than the beginning,
and the name of the Lord be dishonoured by you; and then woe unto you,
his wrath shall suddenly break out against you.

Wherefore hear and fear, and hearken unto the word of the Lord.
He hath caused his light to shine forth, and his voice to be heard;
he hath proclaimed his name amongst you,
and hath caused his marvellous light to approach when you sat in darkness,
in the land of the shadow of death.
When you were lost, he sought you, and when you were driven away and scattered,
he found you, and brought you home.
When you were in your blood and no eye pitied you, he had mercy upon you,
and bound you up, and healed you.
When you were dead, he said unto you, live; and it was so.
When you were led captive by the devil under the power of death,
he broke the chains and set you free; and when there was none to help or save,
his own arm brought deliverance and salvation,
and the way of life and peace he set before you.

And now all this hath his own arm accomplished,
that you should be a praise unto him forevermore.
If you walk in the way which he hath set before you,
and keep his covenant which he hath made with you, and fulfill his will,
and walk in righteousness, in love, and unity, in meekness, lowliness, humbleness,
and in soberness, and watchfulness, and in fear of his name;
then shall his presence never forsake you,
nor his outstretched arm cease to defend and preserve you.
He shall go before you, and be your reward; and he shall be your God,
and you shall be his people; and shall dwell in him; and he shall be your hiding-place,
and he will be to you a father, and you shall be his children,
and his blessing and peace shall remain in your habitations forever and ever.

But if any of you turn aside for a thing of naught, after vanity,
and deny the way of righteousness, and forget the Lord and kick against him,
and follow the way and counsel of your own hearts, and worship other gods,
and join yourselves to strangers, and make the cross of Christ of none effect,
and turn from the light of Christ within you, and fulfill your own wills,
and the desire of your own minds,
and go out of the fear of the Lord into the liberty of the flesh,
(which is not the liberty in Christ Jesus) and so seek yourselves,
and strive for mastery, to be one above another, and surmise evil one against another,
and the bond of peace be broken, and vain contention and strife appear;
then shall the rod of God smite you, and his wrath be suddenly kindled against you,
and you shall not prosper, but his countenance shall be hid,
and the terrors of the Lord and lamentations shall possess you,
and peace shall flee far from you.
Such shall be cast out of the camp of the Lord,
and shall have no part in the inheritance, but the blessing shall depart,
and the curse shall enter, till utter destruction.
If any of you deny the Lord, unto whom his way is made manifest, he will deny you,
and you shall have no part in him,
but vengeance in flames of fire will he render upon the disobedient,
manifold more than if his love and way of peace had not been made manifest to you,
and the light of the world is your condemnation forevermore, if you turn from it.

And in the presence of the living God, I warn you all, believe not that spirit,
neither follow it,
which brings any other message than what hath been declared from the beginning.
Believe not him which crieth, lo here, or lo there is Christ without you,
or that draweth from the measure of Christ within you, to hearken to,
or to be taught by any other thing.
For that spirit is not of the Father which preacheth any
other Christ than he that is the light of the world,
and lighteth every man that cometh into the world; or bringeth any other message,
than that God is light in himself, and hath given his Son a light into the world.
This is the true testimony of the Father, and of the Son;
and he that testifieth any other message, is to be judged and denied.
He is not a worshipper of the true God, but out of the truth, and in the error,
and a deceiver, being deceived.

Believe not that spirit, neither follow it,
which ministereth to others that which it hath not learned of the Father,
but hath the words without the power,
and liveth not in the power of what it ministereth forth in words,
nor is in what it declareth, but is in outward show, in the hypocrisy and feignedness,
and reacheth not the life of God, but vaileth and covereth it;
that spirit is not of the Father, but is to be denied, and not received.

Believe not that spirit, neither follow it, which is at liberty in the flesh,
and maketh the offence of the cross to cease,
which is exalted out of the fear of the Lord, in the liberty of the earthly,
which crucifieth the life, and darkeneth the eye.
That spirit will boast of joy and peace, and experience, and knowledge,
and speak high words in the airy mind, and would lead you to glory above the cross,
till you be past feeling the life; and that spirit begetteth into the love of the world,
which passeth away.
Beware of that spirit, for it is not of the Father, but to be condemned.

Believe not that spirit, neither follow it, which is hasty, and forward, and rash;
for that goeth out of God`'s counsel and betrayeth the just, and striveth to be greatest,
and to be above the weak, and despiseth him, and would be master, and not a servant,
and would rule, and not be ruled in the meek and lowly government of Christ.
That spirit will judge rashly and unsavourily,
and condemn another in secret in what itself is guilty of.
Beware of that spirit, for it is not of God, but to be judged with the life of God.

Believe not that spirit, neither follow it, which seeks to have praise of men,
and would beget divisions and make parties,
which respects persons and glories in gifts and knowledge, and parts,
more than in the giver, and admires men more than Him that gives the increase,
and feeds of the knowledge in that nature which is to be famished,
and glories in what hath been done by it,
as though it had not received power from the Lord,
and is exalted as though it bore the root, not knowing that it is borne of the root.
That spirit spends its treasures amongst harlots, and despises the poor,
and seeks occasion to glory over the weak, that it may be renowned;
beware of that spirit, I charge you all, for it is not of the Father, nor to be followed,
but to be condemned, and resisted unto death.

Believe not that spirit, neither follow it,
which preacheth not from the measure of God received, and to be manifest to it in you,
and approved by it only; but speaks above the measure,
and reaches not to the measure of the grace of God; which leads after words,
and cries peace to the rich, and judgment to the poor,
and the word of God is not divided aright, but heals up falsely,
and daubs with untempered mortar, and cries war where God speaks peace.
That spirit is a deceiver and a betrayer, and feeds but the ear, and not the life,
and darkens the counsel of God by words without knowledge, and is not of the Father,
but of the world, and to be denied and condemned.

Believe not that spirit, neither follow it, which is not subject to rule and order,
and is not meek, and diligent, and long-suffering, but heady, and high, and untoward,
seeking occasions against the just, and watcheth for evil.
That spirit will not bear reproof, but is slothful and careless, surmising evil,
and backbiting, and conforms in appearance, making a fair shew, but is not unto God,
as it appears to man.
It would go, and is not called; and will not go when it is called;
and seeks for the praise of men more than God, and that is fruitless ground,
and brings forth briars and thorns in secret, which chokes the seed of God.
Beware of that spirit, it is a lover of this world; have no fellowship with it,
for it is a deceiver, and is to be denied.

Believe not that spirit, neither follow it, which is tossed and unsettled,
and is given to change, and is not established with grace,
but hunts for the precious life, and seeks by flattery to beguile the innocent.
This spirit is zealous for a moment, but is soon overcome,
and brings not forth fruit to perfection, but withers,
and its latter end is worse than the beginning.
That spirit is exalted into presumption in peace, and cast into desperation in trouble,
and the double mind lodgeth in it, and it is unstable in all its ways,
and is a ground for the seed of Satan, and to it there is no peace from God;
and beware of that spirit, for it is not of the Father, but to be condemned.

Believe not that spirit, neither follow it, which is more zealous than knowing,
whose zeal is without true knowledge, and stands in that which is corrupted,
that flourisheth for a moment, but cannot endure forever.
It hath no root in itself, but is furious and passionate, and not long-suffering.
That spirit knows not itself, but would devour its adversaries with bitterness,
and not gain by long-suffering; that is not the spirit of the Father,
but must be denied in all.

Believe not that spirit which draws back into the world, into its lusts and liberty,
and fashions which pass away.
That spirit forgets God and draws back, for his soul hath no pleasure in it,
but is vexed with it, where the cross is made of none effect,
and the false liberty is walked in, which murders the life.
That spirit is of the devil, and is to be condemned.

And now all friends of God everywhere, who know him, and are known of him,
whom he hath gathered out of this untoward generation, be diligent in your callings,
and keep your meetings in faithfulness, waiting upon the Lord,
that you all may receive of his fullness, and may be nourished up unto himself,
as trees of righteousness, the planting of his own right hand,
to spread forth his name and glory, as a people saved by him.
And this know and understand, that spirit is not of the Father,
which confesseth not the Son to be come in the flesh,
who destroys the works of the devil, and takes away sin.
That spirit believe and follow which condemns sin, and destroys it, and takes it away,
and so gives peace with God in your consciences, and leads you into all truth,
and keeps you from all evil.
You that witness this, the Son you know, and the Father you know, to dwell with you,
and in you; and this is the first, and the last.
Believe in him, and follow him, and look not for any other;
and in this the Father of life and glory, whose dominion is without beginning and end,
establish you, and preserve you: amen and amen.

--

The second Epistle addressed "`to all that suffer for the testimony of Jesus,
and for his name`'s sake,`" is as follows; viz.

[.embedded-content-document.epistle]
--

The glorious God of truth hath appeared,
and made known his way and truth perfectly in this our day,
and hath chosen unto himself faithful witnesses, to testify of his name,
and of his truth before rulers and people;
and hath brought forth a seed which is not of this world, which cannot bow to the devil,
but is heir of God`'s inheritance,
though a sufferer in this world under the powers thereof.
Many in this generation, who are called, and faithful, and chosen,
bear witness unto the name of the Lord in sufferings and tribulations,
whom he will honour, because they honour him,
who is exalting his truth and his people through sufferings.

And now all Friends who are called to suffer for the testimony of Jesus,
and for the exercise of a pure conscience, which you hold,
be valiant for the truth upon earth, and faint not,
but finish your testimony with joy for the Lord, and against all your enemies.
Look not forth at afflictions and sufferings,
but look beyond them to the recompense of reward; neither be offended in Christ,
though ye are called to suffer for him, and for his name sake;
but dwell in the peace with God, which is a sufficient reward.
Take heed to your life which is immortal, that you may feel and enjoy it,
and account that the present sufferings are not worthy
to be reckoned with the glory that is to be revealed,
and of which you have the earnest, even present peace with God.
Look beyond your sufferings, and feel the life of God in you fresh and lively,
which is more than all things, to carry you above all the world, and all its envy,
which is against the seed of God.

Take heed of temptations, for the power of Satan will work,
and is near to tempt you in sufferings, to gain dominion over you,
and to touch your life, and to cast you down.
Therefore mind the life of God in you to have dominion, which Satan hath nothing in,
which is not given him to touch; and that is more than all; yea,
all that a man hath will he give for his life to enjoy, when he is tried.
You are tried by sufferings and tribulations, and your faith and patience are proved;
therefore approve yourselves faithful unto the Lord, by long-suffering and patience,
that Satan overcome you not.
Though he may touch you, and have power to cast some of you into prison,
and otherwise to winnow you, and to try you for your life; yet be faithful unto death,
and you shall receive the crown of life eternal; and keep the word of his patience,
that you may be delivered, and Satan may bow under your foot.

And all you who suffer for well-doing,
who hold fast the testimony which you have received of God,
when your hearts are searched, you are blessed from the Lord;
you shall possess your reward, which no man can take away, even the life, and liberty;
and treasure, which Satan cannot touch or spoil you of.

Ye that suffer because you cannot fulfill wickedness, nor the will of man,
but are of the seed which cannot please man, nor bow to the devil; ye suffer for Christ,
and for righteousness sake, who cannot walk contrary to the light of Christ within you,
but rather choose to suffer under corrupt men and laws,
than to transgress God`'s righteous law, written in your hearts;
you are chosen to fulfill the will of God by sufferings, and are not of the world,
and therefore the world hates you.

All you that suffer imprisonment of body, or spoiling of goods, or travails,
or any other thing, because you cannot pay tithes,
this is the word of the Lord God unto you; you suffer for righteousness sake,
and for the name of Christ, and unjustly, by the oppression of men, for well-doing,
and not for evil; and the Lord will be your exceeding great reward.
Look beyond your outward liberty, and know the liberty in spirit, in the Father,
and in the Son, where is everlasting peace and freedom,
which none can bring into bondage.
Look beyond all outward treasure and riches, and see God`'s treasure, and possess it,
which never waxes old, which none can spoil you of.

As witnesses for the Lord, and for his truth and covenant you suffer;
and it is for a testimony against all your enemies,
and against oppression and oppressors.
For the cry of that oppression the land groans, and for ages hath done;
but the Lord is now risen against it; for its cry reacheth to heaven,
against the unrighteous exactors, whose cruel hands have heavily oppressed the just,
and the poor in this particular.
Your suffering is for a testimony against your cruel adversaries,
whether priests or others, and against the unjust judges and lawyers,
and their whole train of oppressors; for this end are you called to suffer,
and to you it shall be made easy, if you abide in the counsel of God,
till vengeance overcome your adversaries.
Therefore lift up your heads, and fulfill the will of your Father in patience,
and in faithfulness, till the Lord appear for you, who hearkeneth to the cry of the poor,
and regardeth him that suffereth unjustly,
and will recompense the oppressors into their bosoms; will break every yoke,
and be a terror to all the cruel hearted.

And all you that suffer,
who are moved by the power of the Lord to bear witness against the false worships,
and against the false teachers, and idol temples, of which the land is full;
and who are moved to testify against sin, in rulers, priests or people;
whether your sufferings be imprisonment, or beating, and stoning,
or other abuses or cruelties whatsoever, which the devil hath power to lay upon you;
you suffer for righteousness sake, and for the name of Christ, and for well-doing,
if in the wisdom of God you be guided,
and the Lord will be your reward and peace forever.
Lift up your heads, and rejoice in him, and abide in his counsel,
ye that suffer herein for him, and for his name`'s sake.
Your suffering is for a testimony against all this generation;
against the idol worships and ways, which God`'s soul loathes,
and which he will confound; and against the idol teachers, and false prophets,
and priests, who preach for hire, and make merchandise of souls,
against whom God`'s wrath is kindled, and upon whom his indignation will be poured.
It is a testimony against the sins of rulers and people, which abound in this generation,
till the measure of it be fulfilled through persecuting you, who warn them of the evil,
and bear witness against their evil deeds,
that God may be justified when he condemneth them.

He is risen against the worships, and ways, and teachers, and people,
whose abominable iniquities have overgrown the world,
and profaneness hath gone forth from them, through nations, rulers, and teachers,
and people are all out of the way, and given to vanity, to covetousness, and idolatry;
and the breath of the Lord shall consume all who do oppress the just.

Therefore Friends, be patient and content under all tribulations and suffering,
and feel God`'s living presence near you, to overshadow you, and to be your hiding place;
and know the life, which the wickedness and cruelty of man cannot touch or reach unto;
and dwell in the power of the Lord, which moves to bear witness for him,
and against all those abominations;
and that will keep you above all the afflictions which can be cast upon you,
and you will be on the top of your enemies,
and the seed of the serpent shall hardly bruise your heel.

Woe unto the idol worships, and temples, and teachers, to all the hirelings,
and deceivers, who feed themselves and not the flock, who abound in the world,
and in this nation.
The Lord is risen against them all, to pluck up by the root,
that the branches may wither; and his arm shall watch over them, to overthrow them all,
and to make them desolate, that the just may be delivered.

All you who suffer imprisonment, or finings, or reproaches, or any thing,
because ye cannot swear for conscience sake; nor respect persons,
according to the vain customs of the heathen,
but are redeemed out of the customs and superstitions of men, which are of the world,
and are evil, and not of God, nor justified by him;
you suffer for righteousness sake and for Christ`'s sake,
and are witnesses for God herein, against the superstitions, and wickedness, and pride,
and high-mindedness of men.
The Lord is with you, if you be ruled in his wisdom, and are faithful to him;
and he will lift up your heads, till his and your adversaries be confounded.

I charge you all in the presence of the Lord, who suffer for righteousness sake,
in these things, or in any other, who are moved of the Lord to bear witness of the truth,
and against the deceits of the world, be not exalted in the flesh in your sufferings,
lest you forget God.
Neither be cast down into sorrow, lest ye be overcome of the devil;
but dwell in the measure of the power and life of God, which is above all,
and more than all.
Feel God`'s living arm to stay your hearts, to watch his own in you,
to refresh you continually.
Resist the devil on every hand, with the armour of light and truth,
that your life may be preserved in dominion over all things,
even the life which is not of this world in you, that it may not be veiled or overcome;
for to enjoy the life of God with you is enough.
If you pass through the fire, and through the water,
it keeps you and carries you above all, +++[+++this I witness]
and it is more than all outward freedom, or liberty, or riches, or treasure of this world.

Walk herein in boldness, and faithfulness, and patience,
as you have us for an example in Christ Jesus, who are in jeopardy every hour;
often in trials, sufferings, and dangers, and love not our lives unto death,
for the testimony of Jesus, which we hold,
and that his name and truth may be exalted in the earth; but, as the Lord moves,
are carried through nations, among lions and devourers,
such as seek our life for their prey, and yet the Lord is with us, our defence, and arm,
and preserver above all.
Therefore look you to the Lord in all affliction and distress,
and know his reward with you, that your burden and yoke may be easy, and not hard;
for his presence makes all things joyful.
And know, that it is for the name of the Lord, and for his honour, and for his kingdom,
which God will set up through suffering, for this cause are ye called to suffer;
and neither your life, nor liberty,
nor any other thing is to be measured or compared herewith.

So unto every one of you I am moved to write, and to warn you all in the fear of God,
be content, and long-suffering, and patient, and finish your testimony with rejoicing,
if ye seal it with your blood.
Dwell with the Lord in his holy habitation of peace, out of respect to time, or places,
or things; and give up yourselves, that his will may be fulfilled in you.

And think it not strange though you have fiery trials;
neither be moved at any suffering without you, or troubled in spirit;
neither let it break your peace nor fellowship with God by any impatience or murmurings,
or temptations, for then will your sufferings be grievous to you,
and the enemy within and without will have ground against you to overthrow you.
Know it is that which ever was in all ages,
and no new thing for the seed of God to suffer by the seed of evil-doers,
for the wicked always strengthened their hands in cruelty against the righteous,
and laid heavy burdens upon the just, and caused the innocent to groan under them,
for a time, till iniquity was fulfilled, that they might be broken,
and the oppressed delivered.
And always the Lord exalted his name by the sufferings of his people,
as we have a cloud of witnesses of our forefathers that went before,
who did bear witness to the name of the Lord through faithful suffering.
So it is no strange thing that hath happened unto you,
but that which is common to all the saints, who enter the kingdom through tribulation.
Blessed are you, if you be faithful unto the end,
that you may reap the reward of your works, of your sufferings and patience,
even the crown of life that never fades away; so the Lord God of life preserve you.

And all Friends everywhere, I am moved to warn you, dwell in love and unity,
and fellowship one with another in the light, and in the spirit of the Father,
and fulfill the law of Christ, and bear one another`'s burden and suffer with one another,
that none be oppressed among you in any thing, whilst others are free;
but that the burden of all things, and the care of all things, in relation to the truth,
be equal among you, according to every one`'s freedom,
and as every one is moved of the Lord, so to administer to one another`'s necessities,
as members of one body, to the honouring of the Head, and spreading of the truth,
that there be no complaining, but equality and justness,
and the government of Christ ruling among you, and his wisdom in all things.
Feed no excess, nor the lustful devouring mind in any;
neither suffer the distressed to perish for want; but reach one to another in love,
and like mindedness; suffering for one another,
and all caring for the truth above all things, that God may dwell among you,
and be known that he is in you of a truth.
And in this, the wisdom of God guide you all, Amen.

[.signed-section-closing]
By a companion in tribulation to all the saints everywhere.

[.signed-section-signature]
Edward Burrough.

--

During this same month (3rd), Edward Burrough wrote a paper, which he terms,
A Measure of the Times,
in which he takes a view of the glory of the first
Christian churches,--their subsequent declension,
and the final triumph of mystery Babylon,
by which the true church was obscured or driven into the wilderness.
In this, whilst describing the introduction of the Christian religion,
and the glory of the primitive church, he says:

[.embedded-content-document.paper]
--

In the days of Christ and his apostles the power of the Lord was felt,
and he got him a name and glory; he caused his marvellous light to spring forth,
and his day to dawn, which many prophets and wise men had desired to see,
but it was not seen by them.
In that day his glory was spread abroad, his truth and way were exalted,
his glorious gospel was declared through the earth,
and the sound of his marvellous works went forth into all the world.
Judgment and mercy, righteousness and peace were witnessed among men,
and life and immortality were brought to light through the gospel.
The word of life, by which all things were created and by which they stand, was handled,
seen, felt and tasted,
and the Lord God was known to dwell with his people and to walk in them.
His covenant was established, and his promises were fulfilled.
Redemption, deliverance and salvation were revealed, even Christ Jesus, the Son of God,
the Prince of peace!
Many who saw God`'s glory, were witnesses of his majesty and dominion,
and were gathered to him in the bond of peace, and were his sons and daughters,
led by his spirit in the ways of truth and righteousness.
God spake unto them from heaven by his Son,
they were filled with the Holy Ghost and with power,
and many went forth and declared through the nations the things of God`'s kingdom,
which was come to them.
Their weapons were mighty through God; strongholds were subdued,
the powers of death and darkness were subjected,
and the hearts of thousands were turned to God, and brought out of darkness into light.
The mighty and the wise were confounded, the bonds of cruel oppression were broken,
and they who set themselves against the Lord and his way,
were scattered and brought to nought.

In that day the Lord was with his people, while his people were with him.
He loved them while they stood in his counsel, and gave them dominion over their enemies.
They were a terror to the world,
while the churches stood in the dread and terror of the Lord of hosts.
Their feet trod upon the high places of the earth, and they were blessed,
until they waxed fat and increased in treasures, and thought they had need of nothing.
Then they forgot God, and rebelled against him: they became perverse in their ways,
fell into error and idolatry, and left the way of truth,
and cast the law of God behind them.
The form grew and was exalted more than the power of godliness.
As love waxed cold, iniquity abounded;
and men became lovers of themselves more than of the Lord.
The churches were corrupted, they lost the life and power of godliness,
and became worshippers of idols.
As Paul predicted that many should depart from the faith,
giving heed to seducing spirits and doctrines of devils,
and grievous wolves should enter, not sparing the flock, but seeking to devour it,
making merchandize of souls through covetousness and filthy lucre;
so it came to pass in that generation, and soon after his decease.
Peter and Jude foresaw the entrance of false prophets,
and John both in his epistles and the Revelations describes them more fully.

The baptism of the spirit being lost or not known,
several sorts of baptism were brought forth; as sprinkling of infants,
with which the nations have been deceived by the false prophets.
When the gift of the ministry, through the Holy Ghost, was lost and no more received,
men began to make ministers, by learning arts and languages and human policy.
They began to study, from books and writings, what to preach, not having the Holy Ghost,
without which none are ministers of Christ.
When men lost the knowledge of God, that their bodies were his temple,
then they began to build temples without, and to set up false worships in them.
Having lost the sense of God`'s true worship, which is in spirit and in truth,
they began to worship in outward observances, which is not the worship of God,
but superstitious and idolatrous.
When the word of God was not received immediately from his mouth,
nor the gospel by the revelation of Jesus Christ, as in the apostles days,
they used their tongues, though the Lord had not spoken to them,
and they said that the letter is the Word, the letter is the gospel,
and it must be received by the scriptures, and by natural learning and arts;
and none can be ministers of Christ, but those who are learned in the languages.
When singing in the spirit and with the understanding ceased,
then people began to introduce the form of singing
David`'s experiences in rhyme and metre,
and thus in the apostasy,
the form grew as a substitute for that which the saints had enjoyed in power;
shadows were set up instead of the substance, and death instead of life.

Thus we see John`'s prophesy fulfilled,
that the holy city was given to be trodden under the feet of the Gentiles;
and we also know the time is now approaching,
that the dominion of the beast is near at an end,
and the saints shall possess the holy city.
For he also foretold the restoration of the holy city,
wherein new Jerusalem should be made manifest from heaven,
and should be again adorned as a bride for her husband;
the tabernacle of God should be with men upon earth,
and the Lord would dwell forever with his people.
This day is approaching nigh at the door, for the fig tree hath blossomed,
and we know it is near at hand; the summer,
wherein the glory of the Lord shall be revealed to all nations,
and they shall know that he is the Lord God Almighty,
who will take vengeance on mystery Babylon,
that hath made all nations drunk with the cup of her abominations.

--

The popular preachers of that day,
with an evident desire to stop the spreading of the
religious principles of the Society of Friends,
stirred up persecution against those who promulgated them.
The severity with which justices,
judges and juries treated the members of the new society was very great,
and was often not only incompatible with the spirit of the Christian religion,
but with a just interpretation of the laws of England,
and the provisions of Magna Charta.
Many of those who now suffered at the hands of bigoted Presbyterians and Independents,
unconstitutional outrage and legalized oppression,
had been actually engaged in overturning the regal government,
because of its infringements of the rights of the subject.
How deeply were they disappointed,
in finding the great principles of civil and religious liberty no better secured,
by the government they had laboured to set up,
than they had been in the days of the Star chamber, and Episcopal domination.
A revolution had taken place,--but it had brought to the Christian citizen
a mere change of masters,--a substitute of another code of state divinity,
by which to fashion his worship, principles and practice,
leaving liberty of conscience as little protected as ever.

Many found, and bitter was their disappointment at finding,
that the power and the disposition to invade their rights, civil and religious,
still continued, although the rulers had been changed.
The king had given place to the Parliament,--the Parliament to
the army,--the army to Oliver Cromwell;--a succession of power-holders,
none of whom seemed disposed to support, upon a broad and Christian basis,
the principles of religious toleration, or civil liberty.
Cromwell, whilst he was ascending towards the supreme authority,
professed great attachment to religious liberty.
But when once he had grasped the sceptre of rule,--in violation of the
oath he had taken when inaugurated as Protector,--and in violation,
we must believe, of the convictions of his own conscience, he connived at,
if he did not sometimes prompt,
the cruel treatment which the members of the Society of Friends were, without justice,
receiving at the hands of his officers.
He knew the principles of the Society,--and having expressed
his satisfaction with the declaration of George Fox,
which showed that they believed it wrong to use the sword in any case,
he could have been under no fear of their injuring his person,
or unsettling his government.

The hireling preachers had greater cause of apprehension.
The influence of the doctrines of the new society, was felt by them to be great,
and increasing,
and they knew that influence was operating against their pecuniary interest.
The scripture testimony against preaching for hire, and against paying for preaching,
either in money or in tithes of kind, was beginning to be understood by many,
and with the powerful ministry of the Quakers,
was drawing off numbers everywhere from the parish places of worship,
and the gatherings of other religious societies where hirelings officiated.
The loss of their flocks,
and the bold and truthful denunciations against the
immoral conduct which disgraced many of the clergy,
stirred them up to acts of hostility and hatred against Friends.
These priests appear, in many instances,
to have been more eager for the loaves and fishes,
the recompense pertaining to their office by human law,
or by congregational agreement apportioned for hire, than to win souls to Christ.

Oliver Cromwell felt that his government was in its foundation unstable,
and only to be maintained by vigilant watchfulness,
supported by the prompt action of the military force.
His policy was to cultivate the good will of those,
who had the greatest influence to incite opposition to him among the people,
and he did not choose to irritate the clergy,
by protecting the persecuted Quakers from their power.
Edward Burrough, who was well acquainted with the history of Oliver Cromwell,
and who had closely studied his character,
had with his pen called the attention of the Protector,
to the vows he had made before he was exalted to power;
and how he now permitted grievous oppression and cruelty to be acted in his name,
even by those who were his enemies.
He told him that he was not ignorant of the merciless proceedings acted against Friends;
and as he did not restrain them, the divine judgments would overtake him,
unless he repented.
The first address presented to Oliver Cromwell by Edward,
was written whilst he was in Ireland in 1655;
and as the cruelty practised against his fellow members continued to increase;
in the year 1657, he again employed his pen in various addresses,
laying before the Protector a view of the state of things in England,
in a strain of mingled entreaty and warning.

In one written early in the third month,
whilst Cromwell was yet debating in his own mind
whether he should accept the title of king,
which the parliament offered him, the following passages occur:

[.embedded-content-document.address]
--

As one that hath obtained mercy from the Lord, and unto whom his word is committed,
being moved of him, I do hereby in his presence yet once more warn thee,
that thou fear before him, and diligently hearken to him,
and seek him with all thy heart,
that thou mayest know his will and counsel concerning thee, and mayest do it,
and find favour in his sight, and live.
Now is the day that his hand is stretched forth unto thee,
to make thee a blessing or to leave thee a curse forever.

If thou rejectest the counsel of the Lord, and followest the desires of thine own heart,
and the wills of men, and wilt not have the Light of the world, Christ Jesus only,
to rule thee, and to teach thee, who condemns all evil,
then shall evil surely fall upon thee.
The judgments of God, and the day of his last visitation with vengeance,
thou mayest not escape.
Therefore consider and mark my words, and let this counsel be acceptable unto thee;
let it move thee to meekness, to humbleness, and to fear before the Lord;
assuredly knowing, that it is He that changeth times and things, and that bringeth down,
and setteth up whomsoever he will; and how that thou wast raised from a low state,
and set over all thine enemies.

And it was not once thought concerning thee,
that the hands of the ungodly would have been strengthened
against the righteous under thee,
or that such grievous and cruel burdens and oppressions
would ever have been laid upon the just,
and acted against them in thy name, and under thy dominion,
as unrighteously have come to pass in these three years.
This thy suffering of such things is thy transgression,
and thou hast not requited the Lord well for his goodness unto thee,
nor fulfilled his will, in suffering that to be done under thee and in thy name,
which the Lord raised thee against and to break down,
hadst thou been faithful to the end.

Again, consider, and let it move on thy heart, not to exalt thyself,
nor to be high-minded, but to fear continually,
knowing that thou standest not by thyself, but by another,
and that he is able to abase thee,
and give thee into the will of thine enemies whensoever he will.
How hath the Lord preserved thee, sometimes wonderfully, and doth unto this day,
from the murderous plots, and crafty policy of evil men, who seek thy evil,
and would rejoice in thy fall, and in the desolation of thy family and countries!
How have they, and do they, lay snares for thy feet,
that thou mayest be cut off from among men, and die unhappily, and be accounted accursed!
And yet to this day he hath preserved thee, and been near to keep thee,
though thou hast hardly known it.
The Lord`'s end is love to thee in all these things, and yet a little longer to try thee,
that thou mayest give him the glory.

O that thy heart were opened to see his hand, that thou mightest live unto him,
and die in him, in peace.
Beware lest hardness of heart possess thee, if thou slight his love,
and so thou be shut up in darkness and given to the desires of thine enemies,
and left to the counsels of treacherous men, who may seek to exalt thee by flattery,
that they may the better cast thee down, and destroy thee,
and blot out thy name in reproach, and make thy posterity a people miserable.

But now, consider, and let it enter into thy heart, for thou hast not answered the Lord,
but been wanting to him, for all this, and hast chosen thy own way and glory,
rather than his, and not fulfilled his counsel in raising thee.
For the bonds of cruelty are not loosed by thee,
and the oppressed are not altogether set free;
neither is oppression taken off from the back of the poor, nor the laws regulated,
nor the liberty of pure consciences altogether allowed;
but these dominions are filled with cruel oppressions,
and the poor groan everywhere under the heavy hand of injustice;
the needy are trodden down under foot, and the oppressed cry for deliverance,
and are ready to faint for true justice and judgment.
The proud exalt themselves against the poor,
and the high-minded and rebellious contemn the meek of the earth;
the horn of the ungodly is exalted above the Lord`'s heritage,
and they that are departed from iniquity, are become a prey to oppressors;
and the cruel-hearted deal cruelly with the innocent in these nations.
Many are unjustly, and woefully sufferers, because they cannot swear on this,
or that occasion; though in all cases they speak the truth,
and do obey Christ`'s commands.
Such are trodden upon, by unjust fines charged upon them;
and this is by the corruptness of some that bear rule under thee,
who rule not for God as they ought, but turn the sword of justice.

Some suffer long and tedious imprisonments, and others cruel stripes and abuses,
and danger of life many times, from wicked men, for reproving sin,
and crying against the abominations of the times,
(which the Scriptures also testify against,) in streets, or other places.
Some have been sent to prison, taken on the highway, and no evil charged against them;
and others committed, being taken out of peaceable meetings, and whipt,
and sent to prison, without transgression of any law, just or unjust,
wholly through the rage and envy of the devil,
and such who have perverted judgment and justice.
Some in prison have suffered superabundantly from
the hands of the cruel jailors and their servants,
by beatings and threatenings, and putting irons on them,
and not suffering any of their friends to visit them with necessaries.
Some have died in the prisons, whose lives were not dear to them,
whose blood will be reckoned in account against thee one day.
Some have suffered hard cruelties, because they could not respect persons,
and bow with hat or knee;
and from these cruelties canst thou not altogether be excused in the sight of God,
being brought forth in thy name, and under thy power.

Consider friend, and be awakened to true judgment, and let the Lord search thy heart;
and lay these things to mind, that thou mayest be an instrument to remove every burden,
and mayest at last fulfill the will of God.
O be awakened, be awakened, and seek the Lord`'s glory, and not thy own;
lest thou perish before the Lord and men.
Nay, if men would give thee honours, and high titles, and princely thrones,
take them not;
for that which would exalt and honour thee in the world would betray to the world,
and cast thee down in the sight of the world.
And this is God`'s word to thee: What! shall the whole nation be perjured men,
and thou the cause of it?
And wilt thou transgress, by building again that which thou hast destroyed?
Give heed unto my words, and understand my speech: be not exalted by man,
lest man betray thee.
Deal favourably, and relieve the oppressed! boast not thyself,
though the Lord hath used thee in his hand; but know that when he will, he can cast thee,
as a rod, out of his hand, into the fire; for in his hand thou art.
If thou wilt honour him, he will honour thee; otherwise he can, yea,
and will confound thee, and make thee weak as water before him.
His love through my heart breathes unto thee: he would thy happiness,
if thou willfully contemn it not, by exalting thyself, and seeking thy own glory,
and hardening thy heart against the cry of the poor.

This I was moved in bowels of pity to lay before thee, who am thy friend,
not in flattery, but in an upright heart, who wishes well unto thee in the Lord.

[.signed-section-signature]
Edward Burrough.

--

It is said that Cromwell in a public prayer offered up by him,
when about to attack the Scottish army at Dunbar,
declared that if the Lord would give him the victory that day,
he would relieve the country from the great oppression of tithes.
This promise in the day of his power, he had hot fulfilled,
and the members of the Society of Friends at this time,
(1657,) were enduring great persecution,
because they felt conscientiously restrained from
paying for the support of a hireling ministry.
In the fourth month Edward Burrough had an interview with Cromwell,
in which he laid verbally before him the sufferings of Friends.
The protector endeavoured to justify himself by saying,
that all persecutions and cruelty were contrary to his will,
and that he was not guilty of the injustice done to the Quakers.
On reflecting on this assertion of Cromwell, Edward again wrote to him.

[.embedded-content-document.letter]
--

Consider what the cause is, that what thou desirest not to be done, is yet done.
Is it not that thou mayest please men;
making it appear thou art more willing to do the false teachers of this nation,
and wicked men, a pleasure, than to own the people of God, in relieving them,
and easing them in their cruel burdens and oppressions, laid upon them by unjust men?
For a word of thy mouth, or a show of thy countenance,
in dislike to these cruel and unjust persecutions,
would bind the hands of many bloodthirsty men.
Therefore consider: thou canst not be cleared in the sight of the Lord God from them,
being acted under thee, and in thy name:
for there seems rather to be a favouring of them in thee,
by forbearance of the actors of cruelty, by which their hands are strengthened,
than any dislike showed by thee, in bearing thy witness, as thou oughtest to do,
against them.
For thou knowest of some in the city, and elsewhere, whom we know to be just men,
who suffer imprisonment, and the loss of their liberties,
because for conscience sake they cannot swear; and many others in this nation,
suffering cruel things upon the like, or same ground; even for well-doing,
and not for evil; which oppression might be removed,
and their unjust sufferings taken off by thee, by a word from thy mouth or pen;
and this makes that thou canst not be clear in the sight of God in these things,
because not helped by thee, who hast the power to help them.

[.signed-section-signature]
Edward Burrough.

--

In the sixth month,
as no action appeared to be taken by Cromwell for
relieving those oppressed for conscience sake,
Edward once more visited him by a letter of remonstrance and warning,
in which he told him, that the good name Protector which he bore,
was abused and subverted, through the great oppressions and injustice acted under it.
He says,
that several justices of the peace and others had been cast out of places of trust,
because they owned the people called Quakers,
though they had not refused to serve him and the commonwealth,
and though no unfaithfulness to their trust had been proved against them.

In the seventh month he again addressed the Protector.
In this letter he said, and Cromwell well knew the truth of the assertion,
that many persons were plotting his destruction, some of whom,
if they could take his life,
regarded not the danger they might encounter in effecting that purpose.
He adds, that as Cromwell was allowing tyranny and oppression,
the Lord might permit other wicked men to plague the present wicked rulers,
and suffer other oppressors to overcome the present enactors of oppression.
