== Chapter VII.

Robert Mayo, the priest of Kingston on the Thames, about the beginning of the year 1657,
sent a message to Edward Burrough, requesting a visit from him.
Edward accepted the invitation,
and was told by Mayo to speak freely whatever he had against him.
The priest also offered to meet him to dispute either in public or private,
and challenged him to come to his steeple house and call him a deceiver if he dare.
Edward was not easily frightened,
and soon afterwards went to the place of worship where Mayo officiated.
The priest, probably because Edward was present,
made some assertions which he perhaps deemed as antidotes to Quakerism; one was,
"`that Paul, as a minister of Christ, exhorted the saints to follow and obey a light,
which was not Christ; nor the Light of the Gospel.`"
Another, "`that people ought to follow and obey a light which is not Christ,
nor the Light of the Gospel.`"
The third, "`that a man may be a righteous man, and not a godly man.`"
The fourth, "`that the Light of Christ, which every man is lighted withal, John 1:9,
is carnal, and darkness.`"
The fifth, "`that Christ was not the Word that David walked by.`"

After Mayo had finished his discourse,
Edward declared these doctrines to be erroneous and damnable,
and he who promulgated them was a deceiver.
It does not appear that any attempt was made by the
priest to defend the assertions he had made,
but he commenced a suit against Edward for slander.
Edward was arrested and cast into prison,
but does not appear to have been detained there very long.
The case was not tried until the fifth month in the following year,
when we shall again advert to it.

On the 15th day of the sixth month 1657,
Edward Burrough either wrote or finished a testimony concerning London.
It contains a close reproof against treachery, flattery, hypocrisy, pride,
wantonness and wickedness, as well as a warning to flee from them,
and a tender invitation to come unto Christ Jesus, that salvation may be experienced.
He says:

Ignorance abounds in thy old men, and rudeness and wildness in thy youth.
Thy people are without the knowledge of God, and perish for lack of knowledge.
Thou art even as a wild untilled garden, which bringeth forth no pleasant fruit.
Thy vines are as the vines of Sodom, and thy fruit is loathsome to the Lord`'s taste.
Wild grapes and sour grapes are brought forth in thee, which the Lord hath no pleasure in.
Ye bring forth fruit unto yourselves, and not unto the Lord; ye kindle a fire,
and warm yourselves with your own sparks; ye sacrifice to your own net,
and think to be heard for your much babbling and your many performances.
Abundance of the first-man`'s wisdom is among you; it leads you, and guides you,
and not the spirit of God.
Through your own wisdom, which is devilish, you conform to the saints`' words,
and to their practices in outward appearance, and make yourselves like the saints,
and bow unto your own images and likenesses which ye make, and are grown wise,
and full of knowledge, but it is not the wisdom of God,
nor the knowledge that will endure forever;
for ye neglect the one thing which is only needful to eternal life.
Your buildings are high, but they are not upon the true foundation,
for many of you stumble at the corner stone.
Your sprinkling children is a cheat, all that believe therein are deceived.
Your singing of David`'s experience in rhyme and metre is a very lie unto you.
Your worship is but idolatry, and it will not cover you in the day of the Lord.
Though none be like unto thee, O London! in profession,
nor any city hardly can compare with thee in respect
of the multitude of thy gathered assemblies,
and self-separates; yet all this will not avail thee, when the Lord searcheth thy heart,
which is found not perfect, but full of vain glory, and lust and pleasures of the flesh.

All ye that thirst for the Lord, and desire the knowledge of his ways,
unto whom iniquity is a burden, which you desire to be freed from;
who have long sought the Lord, and have not yet found him; who have prayed,
and had no answer, and have been weary and heavy laden and found no rest; I say to you,
save yourselves from this untoward generation.
Come ye out of these abominations, that ye may be delivered from the wrath.
Fear the Lord, and do not offend him in any thing.
Stand in awe, and transgress not.
Love righteousness and truth.
Touch no unclean thing and the Lord will receive you.
Meddle not with their worships, bow not to their images, nor sacrifice to their idol gods.
Have no fellowship with them in their profaneness, nor yet in their hypocrisy;
but hearken ye to the voice of the Lord, that ye may know his judgments in your hearts,
and his law and covenant established with you.
Depart from all iniquity, cast away all your idols, and forsake all your lovers.
Give not yourselves to the ways and pleasures of this world,
but give yourselves to charity, to soberness, and meekness, and above all things,
be upright in heart toward God and toward man.
Speak the truth one to another, and let no guile dwell in your lips,
nor a deceitful tongue in your mouth.
Cease from all vain glory, and vain customs and fashions of the world, which are evil.

Attached to this "`Testimony concerning London,`" is the following, viz.:

A Warning to All Sorts of People

Ye merchants and traders, and traffickers, and all ye that buy and sell,
be plain and upright-hearted; and lie not, swear not,
dissemble not for gain unto yourselves, for that is cursed of the Lord,
and the gain that is thereby received.
Speak the truth every man to his neighbour;
flatter not such with whom you deal by feigned words of guile,
whilst secret over-reaching lodgeth in your hearts,
to make a prey upon your neighbour or brother, for this is evil in the sight of the Lord;
but speak the truth in all things, and let your yea be yea, and your nay nay,
in all your common occasions, for whatsoever is more is evil.
What is advantaged unto you through deceit, or lying, or multitude of vain words?
It shall be a curse unto you, and not a blessing to you, or to your children.
Let the truth guide you in all your dealings one with another,
and let the fear of God be in your hearts in all your enterprises both by sea and land.

I warn you all, seek not by any evil means to enrich yourselves,
neither oppress one another in any thing wherein you deal;
for you know not how long your time shall be upon earth,
nor how soon the day of account will come,
wherein every word and every work shall be brought to judgment,
yea for every idle word shall ye give an account,
and all those words are idle which are not spoken in the fear of the Lord;
therefore live and act in the fear of God, that you may be blessed in all that you do.

And all ye whom the Lord hath blessed with riches and increase,
see that you abuse not that which God hath blessed you withal,
but in all things that it be used to the glory of the Lord,
and not wasted in excess upon the lust of your own minds;
for the creation is the Lord`'s, and all things are given by him,
and taken away at his pleasure, and he maketh rich,
and he maketh poor whomsoever he will.
Therefore every man be content with his own, and covet not one another`'s,
nor defraud one another to enrich yourselves, for it is cursed of the Lord.

And all ye handicraft-people, and labouring people, fear ye the Lord continually,
and use no deceit, nor craft, nor policy in what you do.
Seek not to blind men`'s eyes by fair outsides,
neither to cozen and cheat the simple by slighty work; but let the truth guide you,
and that will teach you to do for all men as ye would they should do for you,
and this is acceptable in the sight of God.
Let your commodities be just and right, and let all your labour be with a single heart,
and do all things as in the sight of the Lord, and then you cannot do evil,
if the fear of God be before your eyes.
The evil in all things will be denied,
and the corruption that is entered into all callings and trades, will be judged out;
and be examples one to another of truth and righteousness; and cozen not,
nor cheat one another, nor use many words, nor vain gestures,
but own the Lord to be your teacher, who will teach you truth, to do it,
and to speak it in all things.

And all ye young men and apprentices, learn ye the fear of the Lord,
and take heed of temptations, lest ye be destroyed both soul and body by them.
Learn not to dissemble, nor to defraud, nor take instructions how to cozen and cheat,
but first seek the kingdom of God and its righteousness,
and then all outward things shall be added unto you.
Give not yourselves to any evil.
Beware of wine and women, which steal away the hearts of many.
Give not yourselves to vanity, nor fulfill the desire of your own minds in any thing.
Covet not after riches, neither study how to be proud and vain-glorious.
Give not yourselves to craft and human policies, nor to deceive any people;
but fear God and keep his commandments, and be subject to your masters,
and obey them in all things that are good,
and be dutiful to them in that which is just and righteous,
but deny them in whatsoever is evil.
Learn not craft and policy from them, neither vice, nor drunkenness, nor cozening,
nor any other thing which is evil, but rather reprove those things,
than in the least to follow them.
If you do the truth, and speak the truth in all things,
and keep yourselves from whatsoever is evil, then will the Lord bless you outwardly,
and inwardly, and the knowledge of God will be your crown in old age.
Cease from all gamings, and vain sportings, and from all wantonness and vain pleasures,
and from all the works of the flesh;
for they that follow such things shall neither prosper in this world,
nor be blessed in the world to come.
Wherefore take heed unto yourselves all ye that are young in the world;
be not overcome of evil, nor follow evil devices, but stand in awe continually,
and offend not God, who gives you life, and health, and all good things.

And all ye masters and heads of families, this is a warning to you.
Be examples of all good in your families unto your children and servants.
Rule in authority in the fear of God, but not in tyranny nor a rigorous mind;
teach and instruct in fear, and not in cruelty.
Give no bad example in pride, vain-glory, drunkenness, dissimulation,
or any other evil thing, but stand as a terror over all evil,
and as encouragers of all good.
Bind not the conscience of any under your power, curb sin only,
and reprove not righteousness.
Seek ye to be taught of God, and then may you instruct all under you in his way;
be pitiful towards your children, and servants,
and pass by offences rather than punish them with cruelty.
And make not a prey upon your servants, to serve your own ends only,
seeking your own good only, and not theirs; for such things are evil in the sight of God,
and are to be condemned.
Let no excess, neither let want be in your families, but that which is honest and right.
Love that in all things, and follow it.
Let not your anger and passion exceed when offence is given you,
and do not correct in cruelty, but in a good understanding; and walk in the truth,
and fulfill the will of God, and not your own,
and this is of great price and acceptable in the sight of the Lord.

And all ye tavern keepers, and inn keepers, fear the Lord God,
and oppress not your guests, neither feed the lust of any till they be drunk,
for that is cursed of God both in you and them, and that which he will be avenged of.
Oh great is that abomination among you.
Much of the good creatures is vainly and wickedly spent and abused in your dwellings.
+++[+++You think]
your advantage stands in the abuse of the creatures by excess,
and the Lord is grieved with you because of that.

And all sorts of people, rich and poor, high and low, masters and servants,
parents and children, buyers and sellers, tradesmen and labourers,
hearken to the counsel of God, and seek to know his will to you in all things,
that you may do it, in following all that is good, and denying all that is evil,
that your souls may live.
Let not the devil lead you, nor his temptations overcome you in any thing,
but resist him in whatsoever he would lead you into,
which is against God and contrary to him.

Repent of all evil that ever you have acted, and let the Lord be your guide,
that you may not utterly perish, and your city be destroyed for your sakes.
The Lord`'s love is towards you, and he waits to be gracious unto you,
and desireth your return, rather than your destruction,
and would heal you if you did wait upon him, and would bless your city,
and make you happy in it, if you do his will, and deny your own.

I am a friend unto all your souls, and a publisher of peace,
and of glad tidings to all that thirst for the Lord,
and he hath given me power to warn you of all your iniquities and abominations,
to deny them, and to warn you to follow that which is good.
Oh that ye knew in this your day the things which belong to your peace,
which now ye may know, before they be totally hid from your eyes,
and there be no place for repentance, nor time of returning.
This day will come upon many, and they cannot escape it,
who now harden their hearts against the way of their own peace,
and even scorn to be reproved for their transgression.
Such my soul pities, who are going in the way of destruction,
and run hastily into perdition.
I have many times been made sad by reason of such,
when I have measured the condition of all people; upon my bed,
I have pondered what abomination was in thee, and what would be the end thereof,
and I have desired nothing so much, as that I might faithfully warn thee,
and free myself, and the Lord from the blood of all men.
Deep thoughts have been upon me, concerning what the counsel of the Lord is unto you all,
that I might manifest the truth, and discover the abominations,
and I have not spared to cry repentance unto sinners, that sinners might be converted,
and turn unto the Lord; and thus far I am clear of the blood of all men,
and the Lord is clear, and if the wicked perish, it is because of their unbelief,
and gainsaying of the Lord.
This is the testimony which I give unto thee, and unto all thy people; O London,
hearken and consider! this is the day of your visitation,
and there is not another way to life, nor to escape everlasting death and destruction,
than that which the Lord hath showed you.
Blessed is he that can receive it, and they that deny it do utterly perish without mercy.

I am as a stranger among you, yet well known to the Lord,
and the testimony of God concerning you shall stand forever, for it is true,
and shall not be confounded, though the wicked reject it to their own destruction.

Edward Burrough.

London, the 15th the of Sixth month, 1657.

Edward Burrough appears to have remained in London and neighbourhood,
most of the summer of 1657, and was as usual industrious,
both in his vocal labours and with his pen.
In "`a just and lawful trial of the teachers and professed ministry of this age,`"
he draws a striking contrast between the hireling priests of his day,
and the ministers of the apostolic ages.
"`The last were made ministers of Christ by the gift of the Holy Ghost,
and by power from on high only; and what they ministered to others,
they freely received from Christ, and had handled, felt and tasted of the word of life.
The former are made ministers by natural learning, education, the knowledge of arts,
and by the ordination of men.`"
"`The ministers of Jesus Christ went up and down through the world,
declaring the word of the Lord freely in the market places, in the synagogues,
and in the streets.
They went from country to country, and were strangers upon earth.`"
"`The hireling priests settle themselves to preach at one place,
receiving so much a year for what they do.
The ministers of Christ sought to make people Christians
by bringing them into fellowship with God,
through conversion and a knowledge of the truth.
Neither did they account any as such who had not experienced repentance,
and their hearts changed by the Holy Spirit.
The hirelings pretend to make Christians by sprinkling them with water while infants.`"

A priest in London, whose name was John Jackson, in 1657,
published a book against Friends, entitled, Hosanna to the Son of David.
In this much was said about James Nayler and his fall,
and the truth was held up in derision because thereof.

Richard Hubberthorn wrote an answer to the book, with the title,
The Cause of Stumbling Removed From All that will Receive the Truth,
and From Before the Wise Men of London.
To this book, on the 3rd of ninth month, Edward Burrough wrote a preface,
in which he says: "`Though the Lord`'s people be a suffering people,
yet woe unto them that cause them to suffer.
And though he +++[+++John Jackson]
and some others in their spirits were elevated,
thinking thereby to trample upon the innocent,
by that occasion happening concerning +++[+++James Nayler,]
yet it was not suffered of the Lord to be as an occasion to destroy his people,
but as an occasion to try them, and to prove them, and thereby they are tried and proved,
and the more settled rather than confounded.
John Jackson and such like may glory in such things for a moment;
because the appearance of it seems evil, yet the Lord will make their glorying void,
for he hath ways enough to preserve his people.
This we have found in many needful times.
As concerning this thing, which was looked upon as a breach among us by many,
yet it is over, and truth stands atop of it,
and the beauty of truth appears through it all,
for truth is more lovely when it is proved and purged.`"

In this year he also wrote a doctrinal work, entitled A Standard Lifted Up,
and an Ensign Held Forth to All Nations;
in which he sets forth some of the principles and
testimonies of the religious Society of Friends.
This work contains the following, viz.:

Concerning the True God

The true God is a Spirit, and is infinite, eternal, and everlasting,
the Creator of all things, the life and being of all things,
the power by which all things stand.
All creatures have a being in him, and by him, and without him no creature is,
or doth move upon the face of the earth.
This is He whom we worship and fear, and obey,
and he brings to pass by his counsel whatsoever he will,
and nothing can prevent the purpose of his mind, but his counsel stands forever.
He is the righteous judge of all things,
and before him must all mankind come to judgment,
and the living and the dead by him must be judged:
he is a rewarder of every one according to their deeds,
whether they be good or whether they be evil.
His greatness, power, majesty and dominion are over all and beyond all,
ruling above all in the power of his own will, and who may say what dost thou?
His eye seeth all and his presence filleth all,
and no creature can be hid from his sight; he is near at hand and afar off,
he searcheth man`'s heart and trieth the reins,
and shows unto man his own thoughts--he justifieth
the righteous and condemneth the wicked.
He is light itself, and in him is no darkness at all.
This is the true God whom we worship.

Concerning the Son of God

The Son of God, who is called Christ, the Prince of peace and righteousness,
is one with the Father in power and dominion, and was with him before the world was.
By him the Father created all things,
and without him was not any thing made that was made.
He is heir of all things, and is the prince of the kingdom of righteousness,
of peace and truth.
He is the Word and power by which all things consist, and is the salvation of mankind,
and the very life of the world.
He inherits life and immortality, and is the Redeemer, Saviour,
Deliverer and Restorer of the children of men.
He is the very wisdom and power of the Creator,
and the Father doth nothing without the Son, and by him,
and through him the Father brings all things to pass.
By him the Father will judge the whole earth and all the children of Adam therein.
This Christ Jesus, the Son of God, is the life and light of the world,
and hath enlightened all mankind.
Every one that cometh into the world is lighted by
him with the true light of life or condemnation;
and what the Son doth, the Father doth also.
He is at his right hand exalted, and is the very express image of the Father,
and is the Father`'s gift into the world,
and is given to all mankind that they may have life by him,
and all that receive him have life and salvation.
But many receive him not, and they that receive him not, perish,
even because they do not receive him whom the Father hath given into the world;
for he is the arm of God`'s salvation, and is the leader of his people.

Concerning the Spirit of God

The Spirit is with the Father, and with the Son, is present everywhere,
filleth all places, and is forever and ever.
He trieth all things,
and revealeth the things of the Father and of the Son unto all that believe in the Son.
He makes manifest, and searcheth into the deep things of God,
and witnesseth the salvation of the just, and the condemnation of the unjust.
He is not absent from any place, or contained in any one place.
The Father and the Son work all things through him,
and bring all things in heaven and earth to pass by him.
He works in the hearts of the children of men,
and in every one witnesseth of the Father and of the Son, to the justness, greatness,
righteousness, and power of the Eternal Creator,
that made all things by the Son through his Eternal Spirit,
which is one with the Father and with the Son,
and is the worker of their will and mind in all things.
He worketh in the wicked to reprove them, and to witness against them,
that God is angry with them.
He worketh in the righteous, and witnesseth the love, and mercy,
and peace of the Father unto them.
He that can receive it, let him.
This is the testimony of the spirit of God, and it leadeth into all truth,
and out of all evil, all that are guided by it;
and it is given to be the guide and rule of life to the children of God.

Concerning Man, and All Mankind

Man was created in the image of God, and was without sin or evil brought forth,
to do the will of him that created him, and was Lord over all creatures,
to use them to the glory of the Creator, and all creatures were to serve him.
But man transgressed against his Maker, offended and dishonoured him,
and became degenerate, and grieved his Maker continually,
and was driven out from the presence of the Lord.
He is now a child of disobedience and of wrath,
and an enemy in his mind against the Lord that made him.
He is doing and fulfilling daily the will of the devil, and grieveth the spirit of God,
and vexeth his righteous soul, and is subject unto the curse of woe and destruction.

Being ignorant of the life and power, and wisdom of the creator,
to guide him and to preserve him, he follows the counsel of his own heart,
which is evil altogether.
Though he was made upright, yet hath besought out many inventions,
which are abominable unto the Lord.
The ground in which he stands is corrupted, and all his fruit is unpleasant,
even bitter and evil unto the Lord`'s taste.
Man is fallen into the pit of misery and sorrow, compassed about with desolation,
and is left without help from himself, or from any other creature,
and this in short is the state of all mankind upon the face of the earth.
Man was planted a noble vine, wholly a right seed,
to bring forth good fruit unto his Maker, but he is turned into a degenerate plant,
bringing forth cursed fruits, which the Creator hath not pleasure in.
His best works are not accepted, and his evil deeds are condemned,
because the ground in which he stands is accursed, because of disobedience.

Concerning the World in General, and the State of Things as They Have Been,
and as Now They Are

Darkness hath been over the face of the earth,
and thick darkness hath covered the people for many ages.
The beast hath reigned upon the face of the whole earth,
and all nations have been subject to his power and dominion.
Even the kings and princes of the earth have given their power unto him,
all the world hath wondered after him, as it is written;
and the whole world hath worshipped the beast and his image.
He hath power to kill all that would not worship him.
Both small and great, rich and poor, have been subject to his government;
and he hath had power to war against the saints, and to make war with them,
and to overcome them, even all that would not worship him.
The rule and government of the Son of God hath not been witnessed among men for ages,
nor the true God known, nor manifestly worshipped in spirit and truth;
but he hath been as a stranger among men,
and they have been ignorant of his ways and judgments.

People have been doing that which is right in the sight of their own eyes,
and God hath been forgotten days without number.
The living fountain hath been forsaken, and many broken cisterns have been hewn out,
which have not holden pure water.
Great evils and continual abominations have been acted in the sight of God,
and the measure of iniquity hath been fulfilling through many generations,
and it is grown nigh to the full.
The law of God hath been made void, and his grace hath been turned into wantonness,
and all things have been out of good order.
Kings, princes, rulers, governments, laws and decrees have been corrupt,
and not right in the sight of the Lord.
Oppressions, tyranny, and vain-glory have abounded in the nations,
justice and true judgment have been neglected, mercy and truth have been strangers,
the world hath been filled with violence,
and the earth stained and polluted with oppressions, injustice and cruelties.
The cry of the poor hath not been heard; every one hath sought themselves,
and not the Lord, nor the good one of another.

The kings and princes of the earth have not been perfect nor upright before the Lord,
but vain-glory hath abounded, and superstitions and idolatries have reigned over them,
and unrighteousness hath abounded, and self-seeking.
They have risen up one against another, quarrelling and destroying one another,
to gain one another`'s dominions by craft, and policy, and strong hand,
and the poor have been oppressed and trodden down,
and thousands of thousands destroyed to fulfill the will, and lust,
and pride of their hearts.

All this hath been evil in the sight of the Lord, and his soul hath been weary with it,
by the destruction of his creatures, one by another.
Rulers, teachers, and people have been out of the way,
and subverted from that wherein God hath pleasure;
and the prince of darkness hath ruled in his dominion, swaying his government,
and things both of civil and spiritual concernment,
have been out of the counsel of the Lord.
Oh what cruel injustice and tyranny in civil government!
What abominable superstitions and idolatries have been in (supposed) Church governments.

It is a vexation to the spirit of the Lord, to consider it,
and the righteous soul hath long cried out and mourned under it;
and because of this is the Lord of heaven and earth now risen to overturn;
to overturn kings and princes, governments and laws.
He will confound and break down tyranny and oppression,
under which the poor have groaned; and he will change times and laws, and governments.
There shall be no king ruling but Jesus, no government of force,
but the government of the Lamb, no law of effect, but the law of God.
All that is otherwise shall be ground to powder.
The kingdom of the most high shall rule amongst men,
and the kingdoms of this world shall be changed,
and shall become the kingdoms of the Lord and of his Christ;
and the Lord shall be known in the earth, to be the God of truth and of righteousness.
Justice and mercy, and truth shall be exalted,
and true judgment shall be set up in the nations,
and the worship in spirit and in truth shall be established;
for the Lord is gathering his numberless number,
to stand before his throne without guile in their mouths, and without fault before him.

Concerning Man`'s Restoration, Redemption and Salvation, What They Are,
and by Whom They Are Wrought

Man`'s restoration is a repairing and giving again that which he had lost by transgression.
Redemption is a recovering, and a winning again,
and setting free from that wherein man hath been held, even all the sons of Adam,
because of disobedience.
Salvation is a saving, keeping, and preserving from sin and death, and disobedience,
and all the ways thereof, and also a saving from wrath and misery and condemnation,
which are the effects thereof.
By the Son of God, Christ Jesus, is all this wrought, manifested and witnessed;
and restoration, redemption and salvation are only in Christ Jesus, the second Adam,
and not in any other, and wrought by him, and by no other.

They are the free gift of the Father unto the sons of men,
no way purchased by the works of the creature, or desert of him,
but are freely given unto the creature, through the power and wisdom of the Creator,
and only by Jesus Christ the Son of the eternal God,
and by the eternal spirit are they witnessed in all that believe,
and through the word of life are they handled, tasted, seen and felt, near at hand,
in power, and not in words only.

Many profess them in words, and what others enjoyed of these things,
but have not felt in themselves the working of the eternal spirit,
neither have they the witness in themselves of being restored to God again,
and of being redeemed by him from under the devil`'s power.
Neither are they saved by Christ from sin and transgression, and so are not,
nor can be saved from condemnation and wrath; for who abide in their sins,
and in the state unreconciled to God,
have not any part or portion in those things which belong to their peace;
and without the knowledge of which, by the working of the eternal spirit,
all mankind are everlastingly miserable.

Concerning True Religion, and the True Worship of the True God

This is true religion, to be kept pure and clean from all evil,
and from all that which would defile in the sight of the Lord,
and to walk in his fear in all things.
This is religion, to do good and to do no evil; to speak the truth,
and to do the truth in all things; to do unto all men as a man would be done unto;
and to love God with all the heart, and the neighbour as himself,
and not to love the world, and ways and pleasures of it,
nor to use deceit in words or actions.
This is true religion, and the true worship of God;
to be led with his spirit in all things, and to be guided in the truth at all times,
and on all occasions.
This is acceptable, and well pleasing unto God, above all words, and outward conformity,
and set times, and days, and observances; for the worship of God is not in these things,
but is without respect of days, places, or things.
This religion and worship stands in Christ Jesus the second Adam,
who hath lighted every man that comes into the world,
that all men through him might believe,
and by him have their consciences purely exercised toward God,
and towards man in all things; and this is our religion and worship of the true God:
he that can receive it, let him.

Concerning Justification and Sanctification

Justification is freely by Jesus Christ in the sight of the Father,
and not by the works of man`'s own righteousness.
Such as are taught by Christ and guided by him in all the ways of truth and righteousness,
are justified by him and none else, not in any word or work whatsoever,
but in what they are led to fulfill by him.
It is the new man that is justified, and not the old; he that is born of God,
and none that are born of the flesh.
Such cannot please God, neither can such be justified by him,
for they are not taught of him, nor saved, nor restored, nor redeemed,
and therefore are not justified nor cleared from condemnation in the sight of the Lord.
Those who live in iniquity, and sin, and the ways and works of the world, which are evil,
are condemned by Christ Jesus, and not justified, though in words they profess him,
yet of justification by him they have no part.

Sanctification is by the working of the eternal spirit in the heart of the creature,
which purgeth out and taketh away all unrighteousness.
All the works and fruits of darkness it witnesseth against, and witnesseth unto Jesus,
who takes away all sin and destroys the works of the devil,
that man may be holy and pure in the sight of his Maker.
Every one that hath the witness of his justification,
hath the operation by the eternal spirit of sanctification,
and all that receive Christ Jesus who hath lighted every man that cometh into the world,
receive sanctification and justification by him, and he unto us is made so of the Father.
He that can receive it, let him.

Concerning the Kingdom of Christ, and How it is Set Up

The kingdom of God, and of his Son, is not of this world, but is from above,
and stands in righteousness and in truth, in mercy and in peace,
in true judgment and justice.
This dominion is from everlasting to everlasting, and reacheth beyond all the world,
its government is love and unity and everlasting peace,
and is perfect liberty to the just, and bindeth and chaineth the unjust.
In it there is no oppression but perfect freedom from all unrighteousness,
and it consists not in word, but in power,
to the bringing down of the kingdom of the devil,
and to the breaking off the bonds of all injustice, and all ungodliness,
which is the kingdom of Satan, which hath long ruled in the world.
That kingdom whereof Christ is king, which stands in righteousness,
no unclean thing can have any part in.

This we believe shall be set up and advanced in the earth, but not by might of man,
or arm of flesh, nor the multitude of an host, neither by policy, craft, nor by revenge,
but by the arm of the Lord alone, through the suffering and patience of his people,
and by faithful witness-bearing unto Jesus Christ, by doing and by suffering.
By his will in all things in a pure life and conversation,
and upright walking in the sight of the Lord,
and by patient suffering under the injustice and oppression of men,
and of their unjust government and laws, till they be overturned and confounded.
And further we give testimony,
that suffering in patience under the cruelty and
oppression of the devil`'s government and kingdom,
more reaches to overthrow them,
than the rising to rebel in any way of outward offence toward them, or defence from them.
The kingdom of Christ is near to come, and the kingdoms of this world shall be changed,
and none shall have any part therein, but they that are redeemed out of kindreds,
tongues, and people.

Concerning Governors and Governments, and Subjection to Them

Governors, rulers, and magistrates we own, and do respect in the Lord;
(and yet cannot respect any man`'s person whatsoever)
such as be a terror to all evil in their government,
and that fear God and hate covetousness, and delight in equity, in justice,
and true judgment, who give diligent heed to try the cause of the poor,
and will judge justly, without respect of men, who justify the good,
and give praise to the well-doer.
Such government and governors we reverence, where sin and iniquity are kept under,
drunkenness, swearing, murder, quarrelling,
and all the ways and works of the flesh are terrified,
and a well-doer praised and justified.
This government of men reaches to the witness of God in every man,
and that answers to the justice and righteousness of all such governors and government,
and these witness that they are of God.

But the witness of God in every man, beareth witness against all unjust men and laws,
and rulers, and governments, which strengthen the hands of the wicked,
and oppress the just where the making and execution
of laws are in the power of proud men,
and covetous men, who fear not God, neither hate covetousness,
nor respect the cause of the poor; but rule by their wills and tyranny,
and not by just laws in righteousness;
but make unrighteous decrees to oppress the poor and innocent,
letting the wicked go free.
Such who uphold unrighteous worships and teachers, by oppression,
and cause the innocent to suffer, and make them offenders,
because of the exercise of a pure conscience towards God and man;
such rulers and government we cannot be subject to for conscience sake,
but do rather fulfill the law and will of God, though we transgress their wills,
and unrighteous laws.
Yet we do not rebel against them, nor seek defence from them,
but patiently suffer under them, and bear their injustice and cruelty,
without seeking any revenge, but leave vengeance to the Lord to whom it belongs.

This is our judgment,
the government and laws which we cannot obey nor fulfill for conscience sake,
we choose rather to suffer under for disobedience to them,
than to transgress the righteous law of God, written in our hearts, by obeying them.
So that what we cannot obey for conscience sake, for conscience sake we resist not,
but suffer the punishment of it patiently,
and herein are we subject to every ordinance of man, for conscience sake.
In fulfilling the good, the just, and righteous;
and in patience suffering under the cruelty and oppression of the unjust,
and unrighteous.
This we do and teach everywhere, subjection to every ordinance of man,
and are not destroyers of true government, or rebellious against just governors,
but are exalters of true justice and judgment in the earth.

Concerning the True Ministry of Christ, and the False Ministry,
and the Difference Between Them

The true ministry is sent of God, and is the gift of the Holy Ghost,
and it stands in the power of the spirit of God, and not in the words of man`'s wisdom,
that wisdom which is from below.
It brings people to the knowledge of God, which is life eternal,
and it turns people from darkness to light,
and from the power of Satan to the power of God.
It is freely received of God, and freely given forth of us.
It proclaims peace on earth, unto such as are of a broken and upright heart,
and it proclaims war against all the wicked upon earth.

It is a good savor unto God in setting the way of life and the way of death,
before all people.
The ministry of Christ is free, and cannot be bought or sold for money;
it is without hire, and gifts, and rewards from any man.
It is given freely into the world,
and it ever was and is persecuted by the generation of the unjust,
and by the powers of the earth.
He that comes in the Father`'s name cannot be received of the world,
but the world is at enmity against him in this generation, as ever;
it converts people unto the knowledge of God, and many did,
and many do receive the knowledge of God thereby,
though some thereby be hardened against God unto destruction.
The word of the Lord and the ministry returns not in vain unto God,
but all by it are left without excuse,
the witness of Christ in every creature being reached to,
which gives testimony to the power, and to the truth of the ministry of Christ.

But the false ministers and ministry are not such;
for their ministry is received by natural learning and arts,
and is not the gift of the Holy Ghost, but stands in the wisdom of man`'s words,
and not in the power and life of God.
It profits not the people at all, neither do any come to the knowledge of God thereby,
neither are turned from darkness to light,
but teachers and people continue in the power of Satan, and in the unconverted estate.
The witness of God is not reached to,
to bring to the understanding of things which are eternal,
but people are ever learning by it, and never coming to the knowledge of the truth.
But the blind lead the blind, and like teachers like people; all out of the way,
given to iniquity and unrighteousness.

Such are they who preach for hire, and divine for money,
and seek for their gain from their quarter, and through covetousness, by feigned words,
make merchandise of souls, going for gifts and rewards, and teaching for filthy lucre,
having settled places and so much a year.
These are not the true ministers of Christ,
but false ministers of antichrist and deceivers, and were never sent of God,
and never bring any to the knowledge of God.
Such we bear witness against to be of the devil,
and that for many generations the world hath been deceived by them,
who had the form of godliness, but not the power,
and Christ`'s words and the Apostles`' words without the life.
They have served themselves, and not the Lord Jesus;
but now they are made manifest with the true light, which approveth the ministry of God,
and disapproveth such who are ministers of antichrist.
All that are in the light, and walk in the light, can receive this testimony,
which is given by the spirit of God, to that ministry which is sent of him,
which fulfils his will, and against the false ministry which is not of God,
which runs and was never sent of him.

Concerning the Gospel of Christ

The Gospel is the power of God,
and it is sent of him into the world to reconcile people unto him,
that have been in the enmity against him.
It is peace to the poor in spirit, and judgment to the fat, and to the high-minded.
It is to be preached to every creature under heaven without respect of people, nations,
or generations.
It is the manifestation of the love of God to the whole world,
to gather people out of all unrighteousness, into the living way of life,
peace and truth, to walk with God in purity and holiness,
and to deny the world and all its ways, and works and worships, which are evil.
By it some are brought to God, and to salvation, and life eternal;
and some through disobedience to it are hardened against God,
that they may be destroyed and condemned, who are reprobates,
and believe not in him from whom the gospel comes.

It cannot be received by any other way or means than by
the revelation of Jesus Christ in the hearts of his people,
and many have the letter who know not the gospel, nor receive it.
This gospel which is everlasting, have we received from God,
and this is the sound of it which we give unto the world; fear God,
and give glory to him, for the hour of his judgment is come.

Concerning the Word of God, and Concerning the Scriptures

The Word of God was in the beginning before any creatures were made,
and by it all things stand and remain unto this day.
The Word endures forever,
and by it all things in heaven and in earth are brought to pass which God doth.
It is from everlasting to everlasting, without beginning and without end.
It is powerful, dividing and discerning all things,
even the secret thoughts of every man`'s heart.
It is as a two edged sword, and as a fire, and like a hammer to cut up, to burn,
and to beat down.
The Word of the Lord reconciles man again to him,
and this word is in the mouth and in the heart.
The servants of the Lord handled, tasted, saw and felt the word of life,
and from it spoke forth the Scriptures, as they were moved by the Holy Ghost,
through the eternal spirit.
They are a declaration of the word of life,
which was in the beginning and endures forever, and declare what the saints received,
believed, and enjoyed.
None can understand without the same spirit that gave them forth,
and to such who have the same spirit the Scripture is profitable.

The Word of God, which was in the beginning, and which endures forever,
is not the Scripture which was not in the beginning,
but the Scripture testifies of that Word, and that Word witnesses to the Scriptures,
and they are not contrary one to the other, but gives witness each of the other.
But many have the Scriptures that have not the Word, neither know it;
but they that have the Word cannot but own the Scriptures,
and this is the truth as it is in Jesus, testified to all the world by us,
who deny them that hereof give any other testimony.

Concerning the Devil and Damnation

There is a devil which is out of the truth, who abode not in the truth,
but is a liar from the beginning, and the father of all evil doing,
and the author of all unrighteousness, and whatsoever is contrary to God in thought,
word and action.
He is the enmity against God, and against all good,
and by his power subverts creatures and things to another end,
than that wherefore they were created, even to the dishonor of the Creator.
He is the god of this world, the prince of darkness,
and he rules king in all the children of the first Adam, who are in evil.
He was the cause of the first transgression,
and is the cause of disobedience to God to this day in all people, who are led by him,
moving them to envy, wrath, pride, drunkenness, theft and murder,
and all the works of darkness, sin, and death.
He is the fountain and root of all these,
and the leader and ruler in the exercise of them,
and of every evil word and work whatsoever, which are contrary to God.
He abode not in the truth, and he hath led all mankind out of truth,
into all deceit and unrighteousness, and into every evil way; and he dwells in darkness,
is out of the light, and is separate from the presence of God forever,
bound in chains of darkness and ignorance, and unbelief.

He hath power in the earthly part of man, and a law in the members,
and he possesses him that is born of the flesh,
and his covenant is with him who is not born of the seed of God.
Those who are cannot sin.
Such are in covenant with God and renewed into his image; but such as are not,
the devil hath power to captivate and lead their minds into vanity,
and their affections and desires into all that is evil, by which the spirit of God,
the creator of all things is grieved, and his soul vexed.
All murder, and deceitful works of the world, and whatsoever is contrary to God in words,
thoughts, or actions, is of the devil, that wicked one, and from him.

All that follow his movings and work evil thereby, serve him and obey him;
he is their god, and their king, and they are his people, and his subjects;
he is their father, and they are his children; he is their root,
and they are his offspring, and they bring forth fruit unto him,
and serve and worship him, and not the true God that made all things.
All such must be cast into utter darkness with him,
and shall have their portion with him in the bottomless
pit of darkness forever and ever,
where there is no end of woe, and sorrow, and misery.
For in the anger of God, the worm dies not, nor the fire is quenched,
and out of that there is no redemption for the unclean.

All such who are led of him who is out of the truth, and in evil,
are judged and condemned by him who is the Truth, who judgeth righteously.
The devil hath not ceased to work evil, and to draw the children of men into evil,
for he continually tempteth to lead from God into rebellion against him.
They that are led by him are destroyed, and shall not cease to have sorrow, woe,
and misery forever, as he hath not ceased to work evil.
He liveth and moveth in the anger of God, and all his works are in it,
and it shall be the reward of him, and all that obey him,
in separation from God`'s everlasting presence, forever and ever.

Concerning all Creatures that God Made

All creatures that God made,
in their creation and beginning were very good in his sight that made them,
and unto man that was to use them, and no creature was evil or defiled in its creation.
But man transgressing against his Maker, became evil,
and did evil in the sight of the Lord, and being possessed with evil, and corrupted,
makes all creatures evil in the exercise of them, corrupts them,
and perverts them to another end than wherefore they were created, and by the creatures,
dishonours the Creator, who should have honoured him by them.
Thus they are become a curse unto man, and not a blessing,
though in themselves are neither cursed, nor evil, nor defiled,
but are become so unto man, because of his transgression and disobedience.
For he being in the curse and defiled, all things are so unto him,
and in his exercise of them he is wicked,
abusing them upon the lust to satisfy his devilish mind,
and ruling over them in oppression and cruelty, and hard-heartedness,
and not in the wisdom of God, as he ought.

He subverts them from their pure virtue, feeding his lust in pride and voluptuousness,
with that which should keep him from hunger and nakedness,
and so pleasing the lust in all things more than satisfying +++[+++the]
pure nature.
This ought not to be, for it is out of the covenant of God,
in which all creatures were made, and in which they stand, except the creature man,
who is degenerated out of God`'s covenant, and subverts all things to his own end,
and not unto the glory of God, while he continues in that state, unreconciled to God.

But man being restored and redeemed, and renewed again into covenant with God,
through the condemning of the evil,
then all creatures are restored to him and made blessed.
The curse being removed out of his own heart, the creatures are no longer cursed to him,
but good, and enjoyed and received in the covenant of God,
in the life and virtue by which they were created.

By the wisdom in which they were made, man comes to order them,
and exercise himself in them, and they are no more spent upon the lust,
nor on the vain mind, nor ruled over in oppression.
All that is condemned, and all creatures are seen to be the Lord`'s,
and the whole earth is his, and the fulness thereof,
and the abuse of all creatures is ceased,
and they are enjoyed in the pure virtue to feed and to clothe the creature,
and not to be destroyed upon the lust,
but for the health`'s sake are they used to the glory of the Creator,
and to the end wherefore he created them, and are pure as they were in the beginning,
and the blessing is felt which is more than all creatures.

Concerning the New Covenant, and How Man Comes to the Knowledge of God

The covenant of God is unity between God and man, and a binding each to another,
to serve each other.
The one is bound to obey, and submit, and worship; and the other to bless, and keep,
and lead, and preserve.
This covenant is established with his own seed forever, and there is no teacher but God.
All are taught of him, from the least to the greatest who are in this covenant.
His just law is written in their heart to condemn all transgression,
and his pure spirit is put into the inward parts,
to be the rule and guide of life in all things.
None need to say, know the Lord, but all know him in the spirit,
and worship and obey him, and follow him in spirit and in truth.

Such are come into peace and reconciliation with God,
and the covenant with hell and death is broken.
In this covenant there is no priest, or offering,
but Christ Jesus the high priest of God, the one offering for sin;
he takes away sin and makes intercession.
In it is no temple, but our bodies are the temple of God, and he dwells in us,
and he walks in us; and there is no circumcision, but the circumcision of the heart,
which is the putting away of all the uncleanness of the flesh.

In it there is no means of salvation but Christ, the only way, the truth and life,
and none comes to the Father but by him.
He declares of the Father, and there is no light but the light of the Lamb.
All that are saved shall walk in the light of the Lamb,
and there shall be no need of any other light, no need of the light of the sun,
or of the moon or of candle, but the Lord is unto them an everlasting light,
and God alone is their glory.

This covenant is forever, and cannot alter or change,
but is sure unto the seed of his own inheritance.
He that is born of the flesh hath no part in it,
but is shut out from the knowledge of God, who is not known to the wisdom of this world,
which is foolishness with God.
The knowledge of God is received no other way but only by the revelation of Jesus Christ,
and by the working of the spirit of the Father in the heart.
He opens the blind eye, and unstops the deaf ear, and changeth the heart,
and causeth it to understand,
and he removes that which hath stood in the way between God and the creature,
which hath caused ignorance in the creature,
that the Lord could not be seen nor perceived.

Christ Jesus the second Adam lighteth every man,
and all mankind that come into the world, with the true light.
But some hate the light, and they will not come to the light,
lest their deeds should be reproved, and their deeds are evil,
and they are in a condemned state.
Such cannot receive Christ, nor the knowledge of God.
But such who love the light with which Christ hath enlightened them,
they bring all their deeds to the light, and walk in the light,
and their deeds are wrought in God, never to be condemned.
Such as love the light receive Christ, and the knowledge of God, which is eternal life;
and none come to the knowledge of God, and of Christ, any other way,
but through the light of Christ, and by the operation of the spirit of God.
Evil is condemned out of the heart, and the heart is made clean by the word of God,
and the knowledge of God is received into the clean heart, and not into the impure.
For without holiness none shall see God, nor ever come to the knowledge of him;
neither can the knowledge of God be received by the traditions of men,
nor any outward observance in the will of men;
but only by the teachings of the eternal spirit, is the living God known in the creature.

Concerning Faith

Faith is the gift of God, and by it Christ is received and enjoyed.
It is the substance of things hoped for, and the very evidence of things not seen.
It gives the creature to believe God in all that he hath promised.
All that is acted and spoken in it, is well pleasing unto God,
and that which is done without it is sin.
It is the strength of the creature to act for God, in all things.
It is that whereby the world is overcome, and all the powers of hell and death.
It is the armour against the devil, and the defence of all the children of God.
By it they overcome all their enemies, and through it they reign over all the world.
It carries through all sufferings and tribulations with joy and patience.

Faith is an act of God in the creature.
Through it peace and righteousness, and the crown of life, are received from God.
By faith all things are received, that are received of God by any of his children.
He that hath faith sees and feels the Lord`'s presence at all times,
and through faith we do and suffer gladly for the name of Christ in all things.
This is our testimony given by the spirit of the Father,
of those things of which we have received the knowledge from God,
who hath given us his treasure; and we have this treasure in earthen vessels,
even the knowledge of those things which are eternal, which is not our own,
but the Lord`'s, to give forth according to his movings,
and of those things have we handled, tasted and felt.

Concerning What Works are Accepted of God, and What Works are Not Accepted

Whatsoever work man is moved and led unto by the spirit of God,
and guided and ruled in the practice of, to speak or act by the same spirit,
which moveth and leadeth into all the works of righteousness, and not unto any evil,
this is acceptable in the sight of the Lord, and these works are well pleasing to him.
Where the Lord goes before, and is the leader in all things;
this man and his works who is led with the spirit of the Father,
are justified and accepted of God.
Not for the creature`'s sake, for He respects not the person of any,
but for his own name sake, because they are wrought in him through faith, and moved unto,
and guided in, by his own spirit;
and they arise from God`'s righteousness revealed in the creature,
and not from the righteousness of the creature.

For man being changed and replanted into the living vine, and the root being good,
every work which springeth forth from it, is good also, and accepted of God,
because the root is so.

But whatsoever works are brought forth by any creature, though the same in appearance,
+++[+++as those]
which are accepted of God from another, yet not being moved unto, nor guided in,
by the spirit of the Father, but brought forth in the will and wisdom of the creature,
which is from below, and acted in imitation, from the saints words;
these works are not accepted and well pleasing unto God, but are an offence unto him,
and sin against him.
Even the sacrifice of the wicked is an abomination unto him.
If a man come before the Lord with thousands of rams, and ten thousand of rivers of oil,
and if he give the fruit of his body for the sin of the soul,
and cover the altar with tears, and is not led with a measure of God`'s spirit,
none of all these works are accepted.
Neither his preaching, praying, baptism, breaking of bread,
nor any other observances towards God whatsoever, are good in his sight, but evil,
and to be condemned, and the root from whence they spring;
because man is in the enmity against him, and not changed out of the old root.

In that state he is not led with the Holy Spirit of the Father, and the root being bad,
the branches are evil.
None are accepted of God in any thing which they perform towards him,
but such as are in Christ Jesus, the second Adam, and such are new creatures.
So that it is not for the creature`'s sake that any work is accepted of,
or an offence against God, but only for his namesake, and because of being guided, or,
of not being guided, with the measure of God`'s pure spirit.
Therefore are man and his works good, and accepted; or evil, and not regarded,
but condemned of God.

Concerning Man`'s State in the First Adam, Before Conversion,
and His State After Conversion, and What Conversion Is

Man`'s state in the first Adam, in transgression,
is a state of perfect enmity against God.
Death reigns in every man, and he is possessed with blindness and ignorance,
and unbelief, and is wholly imperfect to receive the things of God`'s kingdom,
or to act any thing for God, acceptable to him.
Man in that state is wholly dead to God, and insensible of the presence and power,
and life of his Creator, for he is driven from God, and is not led by him.
He hath no power to perform any good in the sight of God, but is possessed with evil,
and led into all evil continually.

He is free from righteousness, and free to all evil, being the servant of the devil,
and subject to him, and overcome of him every moment,
and is led by him to transgress against the Lord.
His heart is unclean, and out of it proceeds continually uncleanness,
in all manner of words, thoughts, and actions, which flow out of the corrupt fountain,
which grieve and vex the Lord and his spirit.
He is dishonoured daily by man, through his abuse of God`'s creatures,
who is a devourer and destroyer of them, and not a preserver as he ought to be,
who abuseth them upon his lust, and not to the glory of the Lord.
He loves the creature, and worships the creature, and is gone after the creature,
and hath forgotten God, that made him and all things,
and hath lost his own dominion wherein he was set in his creation.

His state in his transgression is cursed of God, and without the peace of God,
being in the enmity against him;
and in all things he is wholly unprofitable to his Maker, and only profitable to himself,
and to the devil.
This in short is the state of every man in transgression before conversion.
But his state after conversion is a state more blessed.
For man is changed and renewed, and translated by the power of the Lord,
through the working of the eternal spirit.
Through conversion his mind is changed and his heart is renewed.
The old is done away, and a new heart is given, and all things are become new,
even every word and work.

Every intent and purpose of his mind is converted unto another end,
and guided by another spirit, than before his conversion.
Man is again returned to God, into the sense and feeling of his Maker,
and into covenant with him, where he is blessed, and all things to him.
Reconciliation is made with God, and the evil is judged and condemned,
and sin is taken away, and blotted out, and not remembered.
Man is become a servant unto God, and serves him only in all things,
and not himself or any other creature in any thing.
He hath received power to become a son to God,
and hath received power over the devil and his temptations, and death is destroyed,
and the effects of it are ceased, and the sting of it is taken away.
Life and immortality are brought to light,
and man is made capable to act in all things for the glory of his Maker.

God hath made Christ wisdom to him, to rule him and guide him in all things,
and righteousness to cover him, and justification to him, to clear him in his sight;
and the new man is brought forth; the creating in Christ Jesus unto good works is known,
and the birth which is heir of God`'s kingdom is witnessed.
Unto this man is the Lord become an everlasting light, and a sure hiding place;
for he is not the servant of sin, but of righteousness,
nor an offence to God in any of his works.
But for his name sake, he is well pleased with him.
He is his teacher in all the ways of peace, he is his helmet and his shield,
and his hope of salvation; his shepherd to feed him and preserve him at all times.

Though he may be tempted, yet he is not overcome, for God is his strength.
Though he may be tried, yet he is not forsaken of the Lord.
Though he may be cast into the fire, it is not to consume him, for the Lord is with him.
All things he receives as from the hand of God,
and all creatures he enjoys in the covenant with God, and peace is in all his ways,
for it is the Lord that works in him both to will and to do of his own good pleasure.

This is the state of the new man brought forth in conversion,
which is a turning of the creature from the power of Satan (which rules in every man,
before conversion) to the power of God,
who is the ruler of every man that is truly converted.
This is the truth as it is in Jesus, which I have received from God;
he that can receive it let him,
and if any have an ear let him hear what the spirit saith.
This conversion of the creature is wrought by the
spirit of God through the ministry sent of him;
and even for this cause have we received the ministry of God through the Holy Ghost,
that we might publish these things abroad,
that all people may come to the knowledge of them, and may taste, and handle,
and feel of the same word of life in themselves,
which will reveal the knowledge of these things to them,
that they may have fellowship with us,
and truly our fellowship is with the Father and with the Son.

And now be it known to all the world, and to all people in it,
that the Lord hath raised up a people, and brought forth a seed,
to bear witness of his name, and of his dominion and power in all the earth.
Of these truths, with many more, which are but one in Christ Jesus,
hath God given us the perfect knowledge, even wrought them in us,
and revealed them to us by the eternal spirit; and as that same spirit doth,
and shall move in us, do we, and shall we,
bear witness of these truths unto all people upon earth whatsoever,
both by doctrine and conversation,
holding forth the testimony unto others which we have received of God,
that Christ may be exalted, and his kingdom set up in the world.

In comparison of this, that we may serve God in our generation,
by bearing witness of these things, which we have heard and seen; nothing of this world,
our liberty, our life, nor any other thing whatsoever is dear unto us.
Yea, even for this cause, that the name of the Lord may be testified of,
do we give up ourselves continually to suffer all manner of evil in words or works.
We love not our lives unto death, that truth and righteousness may be exalted;
and this is the cause wherefore we pass through many dangers on every hand,
and are in perils often.

We are not, nor can be afraid of the face of any man,
even that the Lord alone may be exalted, whose name, and honour, and truth,
is more dear unto us than any other thing.

For it have we forsaken all, and counted it as nothing,
in comparison of the knowledge of Christ and his truth,
herein declared and witnessed to the whole world to whom it shall come;
and the light of Christ in every one shall give testimony to it,
unto which I do commend myself and these truths to be witnessed.

And know ye assuredly, that God who is just and righteous in all his ways,
setteth the way of life and the way of death before every man.
He hath appeared in this generation, and caused his voice to be heard in the earth,
and set the way of death and the way of life before you,
and all that perish it is through unbelief;
and because they despise the way which God hath prepared.
He hath prepared a way for life and salvation unto all people,
that all may come to life and salvation, and may not perish.

He hath not shut out any creature, but giveth to every one that cometh into the world,
a day of visitation and a time of repentance and returning,
that healing may be received from the Lord, who is the restorer of lost man,
and there is not another.
So that if man perish it is of himself, and not of God, who hath so loved mankind,
that he hath given his Son, his own wisdom and his power, into the world,
that all that receive him, Christ Jesus, may have everlasting life.

They that receive him not, perish, because of unbelief;
whereby they are hardened for destruction.
Unto such, our gospel, the gospel of God, is hid;
whose eye is blinded by the god of this world,
that they cannot see the things which be eternal,
nor believe in him from whence life comes.
Such are stumbling at Christ the foundation, and therefore shall be broken,
and must not inherit the kingdom of God.
Unto such, though they be wise in the kingdom of this world,
are we become fools for Christ`'s sake; and our testimony cannot be received by them,
nor approved of them, even them that seek after a sign, and them that seek after wisdom.
To such we are not known, nor can our testimony be acceptable to them,
which is not with enticing words of man`'s wisdom,
but in the demonstration of God`'s spirit, and in the simplicity of the truth.
This is of great price with the Lord, even above knowledge,
and all wisdom which is of this world, which comes to nothing;
but the Lord will confound that, and bring it to nothing.

For the world by its wisdom doth not know God, neither can it receive the things of God,
but is foolishness in the sight of God;
and the wisdom of the world must be offended in him,
and in the testimony which is given of him, and the princes of this world.
The wise men must stumble and fall, the powers of the earth must be offended at him,
that they may be confounded and brought to nought.
All the heathen shall rage, and the people shall imagine a vain thing.

But what of all this?
The testimony of the Lord is true which he hath given us to bear of his name,
and of it we are not ashamed before the face of the whole world.
We are armed to suffer for it,
and not only to subscribe to the truth of it with our hand,
or to declare of it with our tongue and pen; but also, if we be called to it,
may seal it with our blood.
Wherefore this is sent among you all, rulers, teachers and people,
to give you the certain knowledge of what we hold and bear witness to,
which is received of us from God, and borne witness of, to you by his spirit;
even those things, with many others, which we have not received from man, but from God,
are we purposed in the Lord to declare abroad.

He hath put it into our hearts to fulfill his will herein; for he hath spoken,
who can but prophesy.
He hath given the word,
and many are they that publish it in faithfulness against the kingdom of the man of sin,
which hath long been exalted in the earth over the seed of God,
which the Lord is now gathering, and establishing his covenant with.
Jerusalem that hath long lain waste, shall be made the praise of the whole earth,
and the Gentiles, who have polluted her, shall be cast out,
and the saints shall rejoice over all their enemies.

And know assuredly from us, who know the Lord,
that God is doing great things in the earth; he is begun to work,
and his arm shall bring it to pass.
He will overturn, and overturn, till he comes to reign whose right it is,
who will change times and things, even that which cannot be believed,
though a man declare it unto you, is the Lord bringing to pass.
The eye shall bless that sees it, and the heart shall praise that can understand;
and behold the Lord comes quickly, and they are blessed that wait for him.
His reward is with him, and his glorious work is before him,
to be wrought by his own hand without the help of any other;
who need not the help of man; and he that doth oppose him, shall be overthrown,
confounded and destroyed.

All ye kings, princes, rulers and people whatsoever,
know ye assuredly that we are not enemies against, but friends unto,
all civil government, and to all just and righteous orders and decrees,
and wholesome laws and customs of any commonwealth; and no way are we destructive to,
or destroyers of the peace and welfare, and wholesome laws, which are according to God,
of any nation whatsoever.
But we are preservers of the peace of all people,
and wait in patience for the establishment of justice and true judgment;
that righteousness may spring forth,
and the government of all nations may be according to the law of God.

Neither are we such who make void the just government of any nation or city.
Neither are we such who through evil purposes, plot, or conspire,
or contrive evil in our hearts against any governors or government whatsoever;
but wish peace and truth, and the fear of the Lord unto all men and nations,
and desire not the overthrow or evil to any people, or their government.
We are subject to just government everywhere by obedience to it;
and subject to evil government by suffering in patience under it.
So that righteousness alone we wait to see set up through the world,
and for that cause suffer patiently under our enemies, not seeking revenge against them,
nor envying the persons of any; but pity our enemies,
and desire their repentance rather than their destruction.
Yet this we give all to know,
that the Lord will be avenged on all them who hate the way of righteousness,
and all that oppose the Lord and his way, and despise his truth which he hath revealed.
They shall be confounded and broken to pieces, and shall confess to the Lord,
and his way, and his truth, in the day of their destruction.

Again, let all the earth know, that against all unrighteousness, injustice, oppression,
murder and drunkenness, and all sin whatsoever we do declare,
and acknowledge ourselves to be enemies against all sin, and they that commit it.
We cannot hide sin and iniquity in any, but give our testimony against it,
and against all that live in it, without respect to men or places.
We cannot flatter any man in his transgressions, but say, that lying, swearing,
drunkenness, covetousness, injustice, dissimulation, hypocrisy, murder and envy,
lust of the flesh, pride and wantonness, and all the works of the flesh whatsoever,
are contrary to God, and of the devil; and they that live in them and bring them forth,
are the servants of the devil, and must not inherit the kingdom of God,
who bring forth those works, which grieve the Spirit of God, and vex his righteous soul.
This is that government only, viz. the government of sin and death,
which we declare ourselves enemies to, which is of the devil, and not of God.

This is that government which we testify against, and war against,
by the sword of the Spirit of God, and by his power, and not by carnal weapons,
or subtle conspiracies, or violent insurrections; for this way, and by this means,
shall not the government of Satan be overthrown,
or the kingdom of Christ ever be exalted.

We are not such as disannul, or make void the covenant and bond of relations,
or teach any so to do, or give any example, by our practice,
to any subjects to be rebellious to their governors; or children,
to be disobedient to their parents; or that servants be undutiful to their masters.
But on the contrary, do say, and affirm it, that it is the duty of subjects,
to be obedient, and subject in the Lord to their rulers and governors, whether kings,
dukes, or others, who have rule over them; and also,
that children should be obedient to their parents; and servants to be dutiful,
and subject to their masters in the Lord, in all things;
and that husbands and wives live in all unity and peace in the Lord.

Provided only, where rulers, parents, or masters, or husbands, require of their subjects,
children, or servants, or any other whatsoever, that which is unjust,
and contrary to God, and his righteous law; in such a case we say, that subjects,
children, servants, and all other whatsoever are free.
We say, where man requires any thing contrary to God,
and God requires another thing contrary to man,
the obedience to God is rather to be chosen,
and the obedience to all men is to be denied.
This is our judgment, which is according to truth,
and is the mind of God concerning subjection and obedience,
and the duty of relations one to another.

And lastly, know ye assuredly,
that we do not hold and maintain any thing by conversation or doctrine,
but the very same truth in word and practice, as all our forefathers did;
but bear witness of the same salvation, by the same Christ, as they did,
and are not setters forth of strange gods.
For no other God is worshipped by us than he whom Abraham, Isaac and Jacob,
and all the rest of the servants of the Lord in every generation worshipped,
served and obeyed.
Neither are we such as do maintain heresy, error or idolatry,
or the worship of any strange god, though hereof we are accused falsely,
yet against us it cannot be proved truly.

We give the whole world to know, that no other end, or purpose,
or design is in our hearts, but only to fulfill the will of God in all things,
as it is to us made manifest.
Even this is the resolution of our hearts, and the full purpose of our minds,
to give testimony through the world, as we are moved,
both by writing and declaring of these truths which to us are known from the Lord,
that truth and righteousness may come to reign.
This may we do as the Lord provideth way for us, not fearing the face of any man,
nor being afraid of the threatening of high looks;
and that we may finish the testimony given us of God, our life,
or any other thing is not dear unto us.
And all ye people everywhere, for your sake is this written, to give you warning,
and true information of the work of the Lord, and what he is about to do,
that you may hear and understand,
and may receive the knowledge of those things which belong to your peace,
and may be saved with an eternal salvation; or otherwise,
through this are you wholly left without excuse, if you perish.
And unto this was I pressed in spirit for many days, that all the world may be satisfied,
what we are, and what we hold, and what the purpose of the Lord is.

I whom God hath warned, do warn all people upon the face of the earth, that you prepare,
prepare to meet the Lord, for he is coming, and his day is nigh at hand,
and his judgments shall be revealed in the earth, and all flesh shall tremble before him,
and all the inhabitants of the world shall be confounded at his presence.
The proud shall be abased, and the poor shall be exalted;
the high and lofty shall be brought down, and the meek and upright shall be set up.
Truth shall reign as king, and deceit shall utterly be confounded.
They that now suffer all manner of evil, for the name of Jesus,
shall possess everlasting freedom, and the dominion shall be in their hands,
and they that now cause the just to suffer, shall go into endless captivity.
The seed of God shall spring forth and flourish,
but the seed of evil doers shall never be renowned.
And between these two seeds is an enmity put, and they can never be reconciled.
Each seed hath its fruit, the one is cursed and the other is blessed,
and each seed is known by its fruit, and must receive from the Lord accordingly.

Quaking and trembling at the word of the Lord, by the servants of the Lord, we do own,
when the power of God reacheth to the witness of God in the creature,
which brings condemnation upon all high looks, and upon the lofty nature,
which causeth the earthly part to tremble.
We do own, and many of us do witness,
the quaking and trembling which is by the operation of the Spirit of God,
and the several operations by the one spirit we own; which brings down proud flesh,
whose honour God will lay in the dust, and bring it to everlasting contempt.
When this comes to pass, quaking shall not be a strange thing, nor the name reproached,
as it is at this day by the proud spirits of men, who know not the work of the Lord,
nor the operation of his spirit.

Moreover and beside all this, let all the world know, that our conversation,
life and practice is one and the same with what we hold forth in words,
and that we give as large a testimony of God amongst us, by pure conversation,
as doctrine, and do deny them who give testimony in words only,
and answer not in their conversation.
That is hypocrisy, and our souls loath it,
and it is abomination in the sight of the Lord, where he is professed in words,
and not walked to in purity and righteousness of life.
For righteousness being brought forth in the heart,
works of righteousness will spring forth in the world;
and where righteousness springs not forth in the world,
and the fruits of the knowledge of God, it shows that righteousness is not in the heart,
and that God is not known.

Also concerning our government, it is according to Christ,
whom we own to be head amongst us, and no other head we have, or do bow unto,
and we are but members of his body, joined to him, through the spirit,
as head over us all.
The greatest of us is but a member of Christ, who is the head alone.
We have not another, neither can we be subject to any other government but his,
or obey any government, but what is justly according to his,
whose government must be set up in the earth, and for it we wait, and labour,
and travail, and count nothing hard, but all things are easy to us,
for this prize which is before us, even the government of Christ to be set up,
and all governments of men established according to it;
and this is our testimony which we give forth in words and practice,
and if it be required can seal it with our blood.

Given forth by a servant of the Lord,

Edward Burrough.

Sometime about the ninth month of this year, Christopher Fowler, a priest at Reading,
in Berkshire, challenged Edward Burrough to a public dispute.
This challenge was accepted,
but appears to have been conducted on the part of
Christopher with little decency or decorum.
Edward says;
"`many in that town may well remember how he hooted and clapped his hands in the pulpit,
as if he had been hunting on a mountain, and also his ungodly speeches,
and revilings toward me; calling me dog, villain, and such like names.
When some of his own people reproved him for such words, he said:
'`the worst words he had in his mouth were too good for me.`'`"
The principal part of the dispute appears to have been,
an attempt on the part of Fowler, to prove the scriptures to be the Word of God;
whilst Edward endeavoured to show,
that the scriptures are a declaration and witness of the Word of God, which Word,
Christ Jesus, was in the beginning, and endures forever.
He says, that the worlds were made by the Word of God;
and the scriptures did not make the world, neither were they from the beginning;
having been commenced by Moses.

To the false charges and unsound doctrines of his opponent,
Edward Burrough returned sound and cogent replies,
so far as he could procure opportunity, but he complains,
that liberty of speech was not fairly allowed him,
Fowler endeavouring to persuade the mayor that he
might insinuate his doctrine into the people.
As Edward pressed him about tithes, he became very uneasy;
three times went out of the pulpit, and finally went away.

After the dispute, Edward returned to London,
where in the tenth month he finished a work entitled
The True Christian Religion Again Discovered,
After the Long and Dark Night of Apostasy.
It commences thus:

Forasmuch as Oliver Cromwell, called Lord Protector of England, Scotland and Ireland,
chief ruler according to man, hath bound himself by an oath, and sworn,
that he will uphold and maintain the true reformed
Protestant Christian religion in the purity thereof,
as it is contained in the Old and New Testament of the scriptures;
which oath he is bound to perform before the Lord and unto all men.
Now it remains to be tried and proved, what the Christian religion is,
and who they are in these nations that are of the
true reformed Protestant Christian religion,
in the purity thereof, as it is contained in the scriptures.
There are abundance of sects and diversity of judgments,
and many assemblies and gatherings of people, who are diverse in their ways,
in their practices, and in their forms of religion in these nations,
who do all profess the scriptures, and that their form of religion is according thereto.
But this cannot be, for the scriptures, which were given forth by the one spirit of God,
bear not witness of many true ways, or unto many true religions, but unto the one truth,
and unto one true religion.
It is the declaration of one way of life and salvation by one, Jesus Christ.
There is no other name under heaven given for salvation, and they that believe on him,
and receive him, these are they only that are of the true religion.
They are guided by the spirit, and changed thereby from death to life;
such have unity with the Father, and with the Son, and one with another.
They are not of this world, but heirs of the kingdom of God.

Therefore, come all sorts of people,
and let us try and prove who it is that is of the true religion,
and who it is he is bound to maintain and uphold by his oath.
Come, I say, all sects and sorts of people, and appear to trial.
Dare you join issue with me in this matter,
and try your profession and practice of religion,
whether it be according to the scriptures in the purity thereof, yea or nay?
The Lord hath put it in my heart, to lay you all to the line of true judgment,
and to prove you, whether you must be upholden and maintained in your religion, yea,
or nay.
Come claim your privilege;
if your profession and practice in religion be according to the scriptures,
then you may own your right, and the benefit of the Protector`'s oath.
But if your profession and practice in religion be otherwise,
and not according to the scriptures, then you must stand back,
and defend yourselves if you can,
for the Protector is not bound to maintain and uphold you in your practice of religion.
And with this argument I shall try you all.
Whatsoever is professed and practised for religion,
for which there is neither command nor precedent in scripture,
is not according to the scripture.
Let this fall where it may, it is truth; and therefore all people come to trial,
and receive your judgment by this rule.

And first, the true religion is walking with God in purity and holiness;
a performing of good to him, and not doing any evil: a belief in Christ,
and receiving of him,
and through the operation of his spirit to be changed into his image;
and the body of sin and death put off, and a living to God in all things,
and not a living to this vain world in any thing;
but in all things to be guided by the Spirit of Christ.
This in short, is a description of the true religion;
and they that are of this religion shall be saved in the day of the Lord,
and in equity and righteousness should be protected according to the oath before mentioned;
or else the oath is not performed in justice, but rather broken through transgression.

And first of all, as concerning that profession and practice in religion,
which is most general in these nations, I mean such as sprinkle infants,
and are sprinkled being infants;
professing it to be the baptism into the faith of Christ;
and that it is a seal of the new covenant, and of remission of sins,
and that thereby people are made capable of union with Christ,
and that it is a sign of regeneration, etc.
This is practised and professed by many for religion;
but this practice and doctrine are not according to the scriptures; therefore all ye,
through all these nations, that are made Christians, and own your title in Christianity,
and a right to fellowship with Christ; and that ye are joined to the church,
and become members of Christ, because you were sprinkled when you were infants,
and all ye that preach this for doctrine, and practice it for religion,
you are not of the true Christian religion, in the purity thereof,
as it is contained in the scriptures; this I do affirm.
Therefore stand you by; for what you practice and profess,
there is neither command nor precedent in scripture; if you could show any,
you are now called, and a necessity is put upon you, to make use of your knowledge,
if you would be protected in this commonwealth, in your practice of religion.

Likewise you sing, and give to sing David`'s Psalms in rhyme and metre,
professing it is to the glory and honour of God.
Ye practice this as an ordinance of God, as a part of his worship,
and as a part of your religion;
but this practice and profession also are manifest not to be according to the scriptures;
because it was never commanded;
neither is there any precedent for this practice in the scriptures, in gospel times.
Therefore in this part of your religion you cannot
justly claim to be protected and maintained;
because the Protector`'s oath reacheth not to uphold
and maintain any such practices in religion,
which are not according to the scriptures.

Likewise, all ye, whose ministers preach for hire, and have hire for preaching,
so much a year, and so much a sermon at a town, or a parish in a settled place;
and who take tithes, and compel people to pay tithes by a law;
such are not the ministers of Christ.
And ye that uphold such for the ministers of Christ, are false in judgment,
and blind in understanding; and are not of that Christian religion,
which is according to the Scriptures in the purity thereof, neither ministers,
nor people; for the ministers of Christ never acted any such thing.
They were the false prophets, and false apostles, that preached for hire,
and for gifts and rewards;
neither did the saints and churches of Christ look upon them that acted those things,
to be ministers of Christ; but on the contrary, declared them to be deceivers.
So that all you people, and you professed ministers,
that act those things that the false prophets acted;
and you people that love to have it so, and give hire to your ministers for preaching,
and consent unto it; none of you are of the Christian religion,
as it is held forth in the Scriptures;
because this part of your practice in religion is not according,
but contrary to the Scriptures.

On the 18th of the eleventh month 1657,
Edward Burrough had a dispute with Richard Goodgroom, at Drayton in Middlesex.
The principal points in the controversy, appear to have been,
whether the Scriptures were properly the Word,
and whether Christ justified sinners as sinners; or in other words,
whilst remaining in sin.

In the first month following, another dispute was held at the same place,
between the same parties, which appears to have been more public than the first.
One point disputed on this last occasion, was the truth of a proposition,
which Edward had laid down in the first, viz.: "`Temptations or motions unto evil,
are not sin to any man,
who doth not consent and obey to serve temptations or evil motions,
and they are not sin to the man, except they be consented to by the man.`"
In defending this proposition,
Edward appealed to the experience of all sober people who heard him,
"`Whether many times there had not been evil motions in their hearts,
presenting themselves, to which they had not consented;
but the Lord had given them power over them, and they were not overcome of them?
And whether they were ever accused or condemned for
such motions which the Lord gave them power against?
or, whether rather they had not peace and joy in the Lord, who had discovered to them,
and given them power over the evil which had presented itself?`"
Edward says, "`I also gave them that which I had witnessed concerning the thing,
as a testimony, agreeing with the Scriptures, to that particular.
From ten years old, till many years after,
many times I had evil motions arising in my own heart, which sometimes overcame me,
and sometimes the Lord gave me to overcome them, so that I consented not to them,
nor obeyed, nor followed them.
When they overcame me and led me aside, then I was troubled and condemned of the Lord;
for they were reckoned to be my sins, when I consented;
and many times the Lord gave me power over them, and I consented not, but resisted them,
and denied them, and then I had great peace and joy in the Lord, and no condemnation.`"

On the subject of Sanctification and Justification, Edward said;
"`Sanctification is a witness of justification,
and no man can further know himself to be justified, than he is sanctified;
nor justified, than he is restored.`"

We find little trace of Edward Burrough after this dispute for several months,
but it is probable he spent the time principally in London and Kingston.
He doubtless attended the general meeting of Friends
held towards the close of the third month 1658,
at the house of John Crook, in Bedfordshire.
He probably accompanied William Caton there, who says he went with Friends from Kingston.
In the fourth month he delivered,
or caused to be delivered into the hands of the Protector, at Hampton Court, a letter,
in which he proposes that Friends might have a public opportunity,
of answering such objections as he felt, to their doctrines or practices.
It was probably in the same month, that in company with George Fox and Nicholas Bond,
he had a dispute with a Jesuit at the house of the Earl of Newport, in London.
The Jesuit had recently arrived from Spain,
in the suite of the ambassador from the court at Madrid,
and in the pride of head knowledge, challenged all the Quakers to dispute with him.
George Fox hearing of this, let him know that Friends would meet him.
The Jesuit then restricted his challenge to twelve of the most learned Quakers.
Soon he reduced it to six, and finally sent them word that not more than three must come.
A discussion of much piquancy took place; but the letter-learned Jesuit,
with all his subtlety,
was altogether unable to stand against the honest
straight forward simplicity of George Fox,
and he most signally failed in the controversy.
The following account of this interview is from the Journal of George Fox, viz.

When we were come to the house, I bid Nicholas Bond and Edward Burrough go up,
and enter the discourse with him; and I would walk awhile in the yard,
and then come up after them.
I advised them to state this question to him, "`Whether or no the church of Rome,
as it now stood,
was not degenerated from the true church which was in the primitive times,
from the life and doctrine, and from the power and spirit that they were in?`"
They stated the question accordingly: and the Jesuit affirmed,
"`That the church of Rome now was in the virginity and purity of the primitive church.`"
By this time I was come to them.
Then we asked him, "`Whether they had the Holy Ghost poured out upon them,
as the apostles had?`"
He said, "`No,`" "`Then,`" said I,
"`If ye have not the same Holy Ghost poured forth upon you,
and the same power and Spirit that the apostles had,
ye are degenerated from the power and Spirit which the primitive church was in.`"
There needed little more to be said to that.

Then I asked him, "`What scripture they had for setting up cloisters for nuns,
abbeys and monasteries for men; for all their several orders; for their praying by beads,
and to images; for making crosses; for forbidding of meats and marriages;
and for putting people to death for religion?
If,`" said I, "`ye are in the practice of the primitive church,
in its purity and virginity,
then let us see by scriptures wherever they practised any such thing?`"
(For it was agreed on both hands,
that we should make good by scriptures what we said.) Then he told us of a written word,
and an unwritten word?
I asked him what he called his unwritten word?
He said, "`The written word is the scriptures,
and the unwritten word is that which the apostles spoke by word of mouth;
which,`" said he, "`are all those traditions that we practise.`"
I bid him prove that by scripture.
Then he brought that scripture where the apostle says, 2 Thess. 2:5,
"`When I was with you, I told you these things.`"
"`That is,`" said he, "`I told you of nunneries and monasteries,
and of putting to death for religion, and of praying by beads, and to images,
and all the rest of the practices of the church of Rome; which,`" he said,
"`was the unwritten word of the apostles, which they told then,
and have since been continued down by tradition unto these times.`"

Then I desired him to read that scripture again,
that he might see how he had perverted the apostle`'s words;
for that which the apostle there tells the Thessalonians,
"`he had told them before,`" is not an unwritten word, but is there written down; namely,
that the man of sin, the son of perdition,
shall be revealed before the great and terrible day of Christ, which he was writing of,
should come:
so this was not telling them any of those things that the church of Rome practises.
In like manner the apostle, in the third chapter of that epistle,
tells the church of some disorderly persons, he heard were amongst them, busy-bodies,
who did not work at all; concerning whom he had commanded them by his unwritten word,
when he was among them, that if any would not work, neither should he eat:
which now he commands them again in his written word in this epistle,
2 Thess. 3. So this scripture afforded no proof for their invented traditions,
and he had no other scripture proof to offer.
Therefore I told him,
"`This was another degeneration of their church into such inventions
and traditions as the apostles and primitive saints never practised.`"

After this he came to his sacrament of the altar, beginning at the paschal lamb,
and the show-bread, and came to the words of Christ,
"`This is my body,`" and to what the apostle wrote of it to the Corinthians; concluding,
"`That after the priest had consecrated the bread and wine, it was immortal and divine,
and he that received it, received the whole Christ.`"
I followed him through the scriptures he brought till I
came to Christ`'s words and the apostle`'s. I showed him,
"`That the same apostle told the Corinthians,
after they had taken bread and wine in remembrance of Christ`'s death,
that they were reprobates if Christ was not in them;
but if the bread they eat was Christ,
he must of necessity be in them after they had eaten it.
Besides, if this bread and this wine, which the Corinthians ate and drank,
was Christ`'s body, then how hath Christ a body in heaven?`"
I observed to him also, "`That both the disciples at the supper,
and the Corinthians afterwards,
were to eat the bread and drink the wine in '`remembrance of Christ,`' and to
'`show forth his death till he come;`' which plainly proves the bread and wine,
which they took, was not his body.
For if it had been his real body that they ate, then he had been come,
and was then there present,
and it had been improper to have done such a thing in remembrance of him,
if he had been then present with them,
as he must have been if that bread and wine which
they ate and drank had been his real body.`"

As to those words of Christ, "`This is my body,`" I told him,
"`Christ calls himself a vine, and a door, and is called in scripture a rock.
Is Christ therefore an outward rock, door, or vine?`"
"`O,`" said the Jesuit, "`Those words are to be interpreted;`" "`so,`" said I,
"`are those words of Christ, '`This is my body,`'`"

Having stopped his mouth as to argument, I made the Jesuit a proposal thus;
"`That seeing he said, '`the bread and wine was immortal and divine, and the very Christ;
and that whosoever received it,
received the whole Christ;`' let a meeting be appointed
between some whom the pope and his cardinals should appoint,
and some of us; let a bottle of wine and loaf of bread be brought,
and divided each into two parts, and let them consecrate which of those parts they would.
Then set the consecrated and the unconsecrated bread and wine in a safe place,
with a sure watch upon it; and let trial be thus made,
whether the consecrated bread and wine would not lose its goodness,
and the bread grow dry and mouldy, and the wine turn dead and sour,
as well and as soon as that which was unconsecrated.
By this means,`" said I, "`the truth of this matter may be made manifest.
And if the consecrated bread and wine change not, but retain their savour and goodness,
this may be a means to draw many to your church.
If they change, decay, and lose their goodness,
then ought you to confess and forsake your error, and shed no more blood about it:
for much blood hath been shed about these things; as in queen Mary`'s days.`"

To this the Jesuit made this reply; "`Take,`" said he, "`a piece of new cloth,
and cut it into two pieces, and make two garments of it,
and put one of them upon king David`'s back, and the other upon a beggar`'s,
and the one garment shall wear away as well as the other.`"
"`Is this thy answer,`" said I? "`Yes,`" said he.
"`Then,`" said I,
"`by this the company may all be satisfied that your
consecrated bread and wine is not Christ.
Have ye told people so long, that the consecrated bread and wine was immortal and divine,
and that it was the very and real body and blood of Christ,
and dost thou now say it will wear away and decay as well as the other?
I must tell thee, '`Christ remains the same today as yesterday,`' and never decays;
but is the saints`' heavenly food in all generations, through which they have life.`"
He replied no more to this, being willing to let it fall;
for the people that were present saw his error, and that he could not defend it.

Then I asked him, "`Why their church did persecute,
and put people to death for religion?`"
He replied, "`It was not the church that did it, but the magistrates.`"
I asked him,
"`Whether those magistrates were not counted and called believers and Christians?`"
He said, "`Yes:`" "`Why then,`" said I, "`are they not members of your church?`"
"`Yes,`" said he.
Then I left it to the people to judge from his own concessions,
whether the church of Rome doth not persecute, and put people to death for religion.
Thus we parted, and his subtlety was confuted by simplicity.

On the 31st of the fifth month came on the suit of Parson Mayo, against Edward Burrough,
for defamation.
Edward demurred to the jurisdiction of the court to try causes
"`of a spiritual dependency`" and showed as he thought,
conclusively, from the laws of England,
that those before whom he was brought had no power to try the case.
In reply, one of the judges told him, they would overrule that, and would try the matter.

On the day of the court, when the jury were to be chosen,
Edward told the judges that as it was doctrine which was to be tried,
the jurymen should be such as had the gift of the holy spirit.
The judges however took the ground,
that the jurymen had nothing to do but to try whether
the words charged had been spoken by Edward.
When the trial came on,
Edward Burrough easily proved that the priest had laid down the before-mentioned propositions,
and then offered to show from Scripture, the doctrines therein contained to be unsound.
The court directed the jury to give the priest damages,
and they brought in a verdict in his favour for 100. At the next court,
held seventh month, 25th following,
Mayo by his council moved for a judgment on the verdict.
Edward being present, was allowed to speak,
and so clearly proved the truth of all he had said, and Mayo so lamely defended himself,
that the court did not give the judgment.
It remained for some time under advisement,
but it is believed that Mayo never obtained any thing.

In the sixth month, Edward Burrough once more addressed a letter to Oliver Cromwell.
It commences thus: "`Know that there is a God that doeth whatsoever he will.
All power is in his hand, and he bringeth to pass the counsel of his own heart,
and he ruleth in the kingdoms of men, and bringeth down and setteth up:
he killeth and maketh alive; and he changeth times, and seasons, and governments,
and bringeth to nought the counsels of men;
for all power in earth and in heaven is in him.
All his doings are right, and his ways are equal,
and thou and all mankind are as clay in the hand of the potter.
He can honour and exalt as he pleaseth, and he can mar, and break to pieces,
and dishonour whensoever he will.
Wherefore be humble, and low in heart before him, for he is the highest power,
that subdueth all things under his feet.
If he wound, who can heal?
If he kill, there is none can make alive.
Know thou, it is the Lord God Almighty that doth this,
in whose hands are the issues of life and death; and he it is who can break thee down,
and build thee up; who can wound thee, and restore thee: and bring thee to destruction,
and say unto thee, return; and to know him that doth this, belongs to thy eternal peace,
etc.`"

Edward then entreats Oliver to hearken to the word of the Lord,
that his soul may come out of death and live.
He says, "`Fear the Lord God, before whom thy heart is naked and bare.
He can mold thee and change thee, and fulfill his pleasure upon thee,
even according to his own will; and who can say what doest thou?
Now come to consideration, and let thy heart be more upright before him.
Choose his way and counsel, that he may bless thee,
and seek his face that thy soul may be satisfied by his word,
and the milk of the word may nourish thee unto life immortal.
Mind his pure presence, which is life, even God with thee, Christ the Emmanuel,
to dwell with and walk in thee, which is the promise of the Father.
First come to the principle of God, and feel the Word of God, in thy heart,
that will beat down the nature into which temptations enter.
The word will bring thee to war against and overcome all thy enemies,
which would defile or betray thee.
It will bring thee to know a birth immortal in thee, a crown immortal received from God,
that dies not nor fades away.
Then he who rules over heaven and earth will be thy shepherd to feed thee,
thy teacher to guide thee; thy counsellor to direct thee in all things.
Thy immortal soul will be satisfied with the bread that cometh down from heaven;
the covenant of God and the sure mercies of David, will be revealed,
and his promise be fulfilled in thee.`"

He then tells him what need he has of the wisdom of God;
entreating him to remove oppression, and warns him to take heed of the teachers,
who flatter, and yet hatch mischief against him;
and also of the magistrates into whom great corruption had entered.
He thus concludes: "`Be thou faithful in what the Lord calleth thee to,
and thou shalt have thy reward.
Seek his honour and he will honour thee.
Let thy mind be to the Lord in all things, and feel his word, power and presence in thee,
to quench all that is contrary, then thou wilt be blessed in this life,
and in the life to come;
but if thou continuest in oppression the Lord will suddenly smite thee.`"

Oliver was too busy with his own schemes of family aggrandisement,
to care much what persecution fell upon the Quakers,
and the hands of the oppressing magistrates and persecuting priests were not stayed.
Soon after this he sickened,
and great anxiety reigned throughout England as the tidings spread abroad,
that it was likely to prove his last illness.
Some of the fanatical preachers concluded he should not die,
and very absurd petitions and remonstrances to the Most High were made by them.

Edward Burrough on the 1st of the seventh month,
addressed the following letter to the Protector`'s family.

Friends,

Remember, that by the Lord you were raised from a low state,
and when he will he can abase you, and bring you down; he gave you the palace of princes,
and threw out them before you.

O, remember this, every one of you, and come to the witness of God in you, and be humble,
and meek, and lowly, and let the Lord`'s fear be in your hearts;
and be of a tender spirit, having your minds exercised in purity, in holiness,
and in righteousness.
Exalt not yourselves, nor be lifted up in your hearts in the pride and vain glories,
and honours of this world, lest the Lord cast you down,
and make your name and posterity a reproach, as he hath done to many before you.
If you walk in the same steps, and do the same things,
and become guilty of the same abominations,
and suffer the children and servants of the Lord to be persecuted,
as many are at this day, some unto death, shall the Lord spare you?
Nay, he will cause you to feel his hand of judgment, and bring you down with sorrow.
He will vex you in his wrath, and smite you with his rod more and more,
till you learn his fear, and depart from all your iniquities.
The Lord will deface your glory, and pull down your crown; and he will make you know,
that he is Lord, that doeth whatsoever he will.

Wherefore humble yourselves under the hand of God, and search your own hearts,
and cast out the abominations that vex the Spirit of the Lord;
and suffer not the people of the Lord`'s precious flock to be devoured,
and made a prey to the wicked.
Because of this the rod of affliction cometh upon you,
and may suddenly break you to pieces; but mind the seed of God in you,
which is oppressed.
Wait to know the power of the Lord, which will redeem you out of sin and death,
and reconcile you to God, and bring you into fellowship with himself,
to enjoy peace and rest for your souls,
that you may be made heirs of the inheritance of an endless life.
This will make you truly honourable, and will be more satisfaction to you, and joy,
and content, and true rejoicing, than all the worldly crowns and worldly glories;
which will waste and consume away, and leave you miserable.

The Lord hath warned you, by a friend unto you in the Lord.

Edward Burrough.

On the 3rd Oliver Cromwell died,
and outward lamentation and inward mourning were that day felt amongst many,
whilst secret joy was indulged by not a few.

Oliver had named his son Richard to be his successor,
and he was proclaimed Protector on the 6th of the month.

A few days after this, Edward Burrough addressed a letter to Richard Cromwell,
chosen to be Protector, etc. of these nations; and speaking of the rulers, he saith thus:

As for magistracy, it was ordained of God to be a dread and terror,
and limit to evil-doers, and to be a defence and praise to all that do well;
to condemn the guilty, and to justify the guiltless.
But the exercise thereof at this day in these nations, is degenerated,
and some that are in authority are greatly corrupted,
and regard not the just and pure law of God, to judge only thereby;
but oppress the poor by injustice,
and subvert the good laws of God and men to a wrong end and use, abusing authority,
and turning the sword against the just.
Hereby true judgment is turned backward,
and the innocent made unjustly to suffer for righteousness sake,
through the corruption of men in authority;
and didst thou but know what we know in this particular, it would pierce thy heart.

It is frequent among some of the judges and magistrates, to commit a man to prison,
and impose some great fine upon him, and to cast him into a dungeon, or hole,
among thieves and murderers, for a long season; for no other offence,
or breach of any law, but because he cannot put off his hat to them,
and respect their persons, by the hat or bowing the knee.
Many others also that fear God, and for conscience sake cannot swear upon a book,
by kissing it, and laying hands upon it, because Christ saith,
"`Swear not all;`" though they deny not to speak and do the truth in all things,
as in the presence of God and all men; and many others,
because they are moved to cry against sin,
and declare against the iniquities of the times, in teachers, rulers, and people,
that highly abound; perhaps in a market or steeple-house, or highway, or other places,
as they are moved of God; others, because for conscience sake they cannot pay tithes,
nor give money and wages to maintain a priest, or false teacher,
that they receive no profit by; or to maintain a steeple-house,
where the world worships in vain traditions, and not in the spirit and power of God.
Many have been taken out of peaceable meetings, where they were waiting upon the Lord;
and some out of their inns and friends`' houses; and many have been taken on the way,
travelling about their lawful occasions; and some from their callings and labours.

For these causes through the envy of wicked men,
and without any just conviction of the breach of any law,
or any lawful trial or examination, have hundreds of just men, being wholly innocent,
been sent to prison, and lain many months, and some for years; or whipped,
or put into the stocks,
and grievously abused by cruel executioners of wicked men`'s envy or injustice.
And upon such grounds only, and for such causes mentioned,
and without the transgression of any just law, have and do at this day,
many hundreds of faithful subjects suffer hard and cruel things,
long and sore imprisonment, and cruel and sharp whipping, and stocking,
and unjust banishment out of towns and cities; yea, friend, it is hard to be expressed,
and large to be declared, how many of the Lord`'s servants do,
and have suffered great injustice in these nations, through the abuse of good government,
and degeneration of magistracy from its perfect state and place,
whereunto it was ordained of God in the beginning, etc.

In this year he wrote a short statement of the principles
of the religious society of which he was a member,
as follows; viz.:

A Declaration to All the World of our Faith; and What we Believe, Who are Called Quakers.
Concerning God, Christ, and the Spirit, Thus we Believe.

First, That there is only one true God, who is a spirit;
and his presence filleth heaven and earth; and he is eternal and everlasting,
the Creator and preserver of all things; that heaven and earth,
and all things therein by him were framed and brought forth;
and all things remain unto this day by his power;
and whatsoever he willeth in heaven and earth, he brings to pass by his word and power.

And we believe, That this God only is and ought, to be feared, loved,
obeyed and worshipped by all creatures;
and no other thing besides him in heaven and earth.

And we believe, That his worship and obedience,
and fear and love is to be given in spirit,
even in what his own spirit moveth and leadeth his people unto.

And we believe, his true worship, required and accepted of him,
is not by the tradition of men in outward observances, or set days, or places;
but he is worshipped only in spirit and truth, without respect of time, places or things;
and that none can worship him in righteousness, but his children,
who are born of his spirit, and are led and guided thereby.

And we believe, That this God hath given his Son Christ Jesus into the world,
a free gift unto the whole world;
and that every man that cometh into the world is lighted by him,
that every man might believe, and be saved.

And we believe, That he is given into the world, and no nation,
country or people excepted; but unto all mankind is he given of God,
and hath lightened them, and every man through the world, that believeth in him,
and receiveth Christ, who is the wisdom and power of the Father,
shall be saved with eternal salvation; and every one that believeth not in him,
shall be damned, and shall possess everlasting misery.

And we believe, That salvation, justification and sanctification, are only in him,
and wrought by him, and no other: for there is no other name given under heaven,
but him alone, by which salvation is.

And we believe, All that receive him, and believe in him, are reconciled to God,
and are made alive to God, to live to him in all things,
and do receive the forgiveness of sins, and are set free from all unrighteousness,
and from the body of sin and death, and have the witness of the spirit in them.
The spirit of the Father they have received,
and it witnesseth in them of the Father and of the Son,
and of the things that belong unto their peace.
It is the earnest of the inheritance, and the seal of the promise of eternal life,
and by it are the deep things of God revealed to mankind,
and by it the Father and the Son dwell in the saints,
and by it have they fellowship one with another; and the Father, Son, and Spirit are one.
And this we faithfully believe.

Again, concerning Christ, we believe, That he is one with the Father,
and was with him before the world was; and what the Father worketh it is by the Son;
for he is the arm of God`'s salvation, and the very power and wisdom of the Creator;
and was, is, and is to come, without beginning or end.

And we believe, That all the prophets gave testimony of him,
and that he was made manifest in Judea and Jerusalem, and did the work of the Father,
and was persecuted of the Jews, and was crucified by his enemies; and that he was buried,
and rose again, according to the Scriptures.

And we believe, He is now ascended on high,
and exalted at the right hand of the Father forevermore;
and that he is glorified with the same glory that he had before the world was;
and that even the same that came down from heaven, is ascended up to heaven;
and the same that descended is he that ascended.

And we believe, Even that he that was dead is alive, and lives forevermore;
and that he cometh, and shall come again, to judge the whole world with righteousness,
and all people with equity, and shall give to every man according to his deeds,
at the day of judgment, when all shall arise to condemnation or justification;
he that hath done good shall receive life, and he that hath done evil,
everlasting condemnation.

And we believe, He is to be waited for in spirit, to be known after the spirit,
as he was before the world was.
This is the knowledge unto eternal life, which all that believe in him do receive;
and he subdues death, and destroys him that hath the power of it;
and restoreth from death to life,
and quickeneth by his spirit all that the Father hath given him.
We believe such he justifieth and sanctifieth, and such are taught of him;
but he condemns all that believe not, but continue in unbelief,
and are not taught of him.
And this we faithfully believe.

And we believe, That unto all people upon the face of the whole earth,
is a time and day of visitation given, that they may return and be saved by Christ Jesus,
who is given of the Father to call the worst of men to repentance;
and the most ungodly of sinners are convinced by him of their ungodly deeds,
that they might believe, and be converted and saved.

And we believe, Herein is the love of God manifested to all mankind;
and that none are shut out by him before they were born into the world;
but unto all men is a visitation given.
They that do perish, it is because they do not believe in Christ;
and his destruction is of a man`'s self, but salvation is of God,
through believing in his Son, who takes away sin, and reneweth into his own image,
that they may become heirs with him.

And we believe that there is a crown of eternal glory,
and an inheritance of eternal life to be enjoyed forevermore by all that believe,
and are chosen of God;
and that there is an everlasting misery and destruction
to be possessed by all that believe not,
but continue in the state of reprobation,
and are not changed from the ways of sin and death;
but walk after the ways of their own hearts`' lusts, fulfilling the will of the flesh,
in the evil of this world, and follow not Christ, the light of the world,
that they may be saved.
And we believe upon all such the wrath of God abideth,
and that they have no part in the inheritance of God.

And we believe, That it is only he that is born again of the spirit,
and that walks after the spirit, who is changed from death to life,
and who is redeemed out of the world, and all its ways;
that must inherit the kingdom of God.
They only have a right thereunto, and none besides,
even they that are washed and cleansed from all unrighteousness by the blood of Jesus,
by which their sins are remitted.
For his blood cleanseth from all unrighteousness and sin; yea,
all such that walk and abide in the light,
which Christ Jesus hath lightened the world withal.

And we believe, That the saints upon earth may receive forgiveness of sins;
and may be perfectly freed from the body of sin and death,
and in Christ may be perfect and without sin, and may have victory over all temptations,
by faith in Christ Jesus.

And we believe every saint, that is called of God, ought to press after perfection,
and to overcome the devil and all his temptations upon earth.
We believe they that faithfully wait for it shall obtain it,
and shall be presented without sin in the image of the Father.
Such walk not after the flesh, but after the spirit, and are in covenant with God,
and their sins are blotted out, and remembered no more; for they cease to commit sin,
being born of the seed of God.

And we believe, The gospel of Christ is the power of God unto salvation,
and that it ought to be preached freely unto people,
and Christ to be held forth unto all mankind, by the ministry sent of him.
We believe this ministry is received by the gift of the Holy Ghost;
and all they that receive it, are lawfully called to the ministry;
and they may preach the Gospel of Christ freely, as they have received it freely.
And this ministry is not of man, but of God,
and is made powerful to the converting of sinners, and to the bringing of people to God,
and to the knowledge of his ways.
We do not believe, that any man is a minister of Christ,
without the gift of the Holy Ghost;
or that the gospel can be received by natural learning or education.

And we believe, Such as preach for hire, and have hire for preaching,
are not the lawfully called ministers of the gospel of Christ; such as are proud,
and high-minded, and covetous men, who do not profit the people at all; such as have run,
and never were sent of Christ, who calleth by his spirit into the work of the ministry;
and as every one hath received the gift of that, his spirit,
so he may administer to others.

Concerning rulers and governors, we believe,
That there ought to be rulers and governors in every nation, city, country and town.
They ought to be such men as fear God and hate every evil way; who will judge for God,
and not for man; and will judge righteously, equally and justly,
and will give true and sound judgment unto all men, without bribery,
or respect of persons, not regarding the rich above the poor;
but being a praise unto all that do well, and a terror to all evil-doers whatsoever;
having knowledge in the pure law of God, and themselves continually exercised therein.
We believe, that every law of man ought to be grounded upon the law of God;
pure reason and equity being the foundation thereof,
that God`'s witness in every man may answer to it.
The law ought to be known unto all people,
before transgression be charged or punished in any man.

We believe that every transgression ought to be punished according to its nature;
and that the punishment exceed not the greatness of the transgression;
neither ought any transgressor to escape unpunished;
neither ought any upon false suspicion or jealousies, to be caused to suffer,
without the testimony of true men, or the confession of the party.
We believe, that the executors of the law ought to be just men, and not given to pride,
drunkenness, or any other evil whatsoever.
They ought to be chosen every year, or otherwise, by the consent of the people;
and that no man be stopped of his free choice, except justly taxed.

We believe, that all governors and rulers ought to be accountable to the people,
and to the next succeeding rulers, for all their actions,
which may be inquired into upon occasion;
and that the chiefest of the rulers be subject under the law, and punishable by it,
if they be transgressors, as well as the poorest of the people.
Thus true judgment and justice will be brought forth in the earth,
and all that do well will have praise, and live in rest and peace;
and all evil doers whatsoever may stand in awe, and be afraid of God, and just men,
and the execution of just laws.

Concerning religion, we believe,
That it is only the spirit of the Lord that makes men truly religious.
That no man ought to be compelled to, or from, any exercise or practice in religion,
by any outward law or power; but every man ought to be left free,
as the Lord shall persuade his own mind, in doing,
or leaving undone this or the other practice in religion.
Every man, of what profession in religion soever, ought to be protected in peace,
provided himself be a man of peace, not seeking the wrong of any man`'s person or estate.

We believe, That to oppose false opinions, and unsound doctrines and principles,
seeking to convince them that oppose themselves, by exhortation, or sharp reproof,
by word or writing, ought not to be counted a breach of the peace;
or to strive about the things of the kingdom of God,
by men of contrary minds or judgments.
This ought not to be punishable by the magistrates and their laws.
For we believe,
the outward laws and powers of the earth are only to preserve men`'s persons and estates,
and not to preserve men in opinions.
Neither ought the law of the nation to be laid upon men`'s consciences, to bind them to,
or from, such a judgment or practice in religion.
We believe that Christ is, and ought only to be,
Lord and exerciser of men`'s consciences; and his spirit only must lead into all truth.

And we believe, That obedience and subjection in the Lord belongs to superiors,
and that subjects ought to obey in the Lord those that have rule over them.
That children ought to obey their parents, and wives their husbands,
and servants their masters, in all things which are according to God,
which stand in the exercise of a pure conscience towards God.
But where rulers, parents, or masters, or any other,
command or require subjection in any thing which is contrary to God,
or not according to him, in such cases all people are free,
and ought to obey God rather than man.
We believe, That herein God will justify them,
being guided and led by his spirit in all that is good, and out of all that is evil.

Again, We believe concerning election and reprobation, That there is a state of election,
and a state of reprobation, a state chosen of God, and a state rejected of God,
and that all mankind are in one of these states.
All that are elected, are elected in Christ;
and all that are out of him are in the reprobate state,
bringing forth fruits of death and darkness, being children of wrath and disobedience,
in the alienation and separation from God.
They are in the transgression, unreconciled to God, the enmity ruling in the heart,
being in the fall, and not restored to God again, but ignorant of his power,
and of his wisdom, having the understanding darkened,
that they cannot see nor perceive the things that are eternal.

In this condition man`'s best works are sin, and whatsoever he doth,
he cannot be accepted of God; for he is dead to God, and alive to all evil,
bringing forth all his works out of that ground which is cursed.
This is the condition of all mankind upon the face of the earth, in the first Adam,
and this is the state of reprobation; and all that abide herein are rejected of God,
and shall never inherit eternal life, but go into perdition.

Yet have all such a day of visitation,
that they may return out of the state of reprobation; but hating knowledge,
and despising the love of God, they continue in the reprobate state,
and the wrath of God abides upon them.
But they that are chosen of God, are delivered from wrath; for they believe in the light,
and become children of the light, and are renewed in mind and heart,
and receive the love of the Father, and become planted into Christ, the second Adam.
They are chosen in him to bring forth fruit unto the Father,
and all their fruit springeth from that ground which is blessed.
For they are led by the spirit of the Father; and such are in the state of election,
who are made heirs with Christ of the everlasting inheritance, that never fades away.
And this we faithfully believe, That mercy is not showed to the reprobate,
nor judgment to them that are chosen of God.

Edward Burrough.

On the 22nd of the ninth month, Edward Burrough was at Kingston; on the 23rd,
as he was entering London, at Charing Cross,
he beheld a great multitude of people pressing upon one another exceedingly.
Which ever way he looked, the whole streets were filled,--every window was crowded,
and balconies and house tops were thronged.
He could not well pass through such a crowd; and guards of soldiers,
both foot and horse were on duty there,
who stopped his horse and told him he must not pass that way.
Tarrying but a short time he turned about and passed away,
wondering what this great stir meant,
and what it was which occasioned such excitement in the spirits of the people,
as plainly appeared.
He says, "`I felt the spirits of men, women and children were all on fire.`"
Although living in London, and labouring abundantly in his own vocation there,
he appears to have had no notice of these pompous
preparations for the funeral of Oliver Cromwell,
of whom an image was to be carried along in view of the multitude.
This was the day of the funeral, and this crowd was gathered to see it pass.

As Edward went on he turned his mind inward,
seeking to know of the Lord "`what this thing might be, what might be the end of it,
and why was this gathering and running, and thronging of multitudes in this manner.
Presently I perceived +++[+++says he,]
that an image, an invented picture would be carried that way;
and that all this pressing and stir, and the gathering of this great multitude,
was only to see an image without life or breath.
Then my spirit was grieved and my soul was vexed within me; and it ran through me,
vanity, folly and madness.
What is all this setting of guards, gathering of people in such thronging multitudes,
and gazing of men, women and children, high and low, rich and poor,
that are come together?
Is all this but to see a dead invented image of wood or
wax arrayed and decked with some foolish inventions?`"

The idea of a carved or moulded representation of Cromwell being carried at his funeral,
reminded Edward of the time when Oliver and his soldiers
found pleasant work in the old parish steeple-houses,
the rich cathedrals, whenever and wherever they were to be found,
in breaking up and destroying carved images, crosses and other relics of popery.
Hereupon Edward began, as he tells us,
in "`a testimony against a great idolatry committed,`" to talk to himself on this matter.
He said, "`I knew the man, when he was living, and had a knowledge of his spirit;
and I am persuaded if it had been asked him in his life time,
if such should be acted about him, such an image made like him,
and laid for so long time in a sumptuous place and manner,
and then carried by his friends, and children, kindred and army,
I think he would have said; '`nay!
What! make an image of me, and deck it diversely, and visit it;
and then carry it up and down from place to place!
This will be a shame to my children, a disgrace to my kindred, a reproach to my officers,
and the whole army.
The nation will mock and be offended, and may say,
these are they that were once enemies to all images and dead idols,
and pulled them down and brake them.
Are these now making an image, and setting it up, wondering after it from place to place?
If thus it be done, they at Rome may laugh us to scorn, and the papists may say,
we have learned of them, put their persons from among us, banished and killed them,
and set up their practices.`' Sure he would have said this.
I am certain the witness of God in his conscience might truly have said it.`"

In the tenth month Edward addressed the following to Richard Cromwell and his council:

To the Protector and his Council

The Lord God will shortly make you know that we are his people;
though we be accounted as sheep for the slaughter,
yet our King of righteousness will break you to pieces, if you harden your hearts,
and repent not.
And though that love will not draw you,
neither the gentle leadings of our God have any place in you,
yet judgments shall awaken you,
and his heavy hand of indignation shall lie upon your consciences,
and you will be scattered and distracted to pieces.

Edward Burrough.

In this year he also wrote the following Epistles, viz.:

An Epistle to go Abroad Among Friends, in Westmoreland and Cumberland,
and Elsewhere Among the Flock of God

Friends, my love and life, which is not of this world, but is in the living God,
doth reach unto and salute all you that are in the light of life,
and in the truth itself, which changeth not, but endureth forever,
which we receive of God the everlasting Father, through the gospel,
which came unto us in the demonstration of the spirit, and of power,
changing us from death, which reigned over us, to life,
in which we have power over death, and turning us from the power of Satan,
wherein we were held, unto the power of the living God, wherein we became fruitful,
and a good savour unto him through the nations.

Dearly beloved, in the same truth be faithful unto death, in that which cannot sin,
nor be overcome of the tempter, in which Satan hath nothing,
wherein only stand our fellowship and union one with another,
as we abide in the living vine Christ Jesus, the light of the world,
in whom you have believed unto eternal life,
and have entered into the rest which is prepared.
As you continue therein, you cannot be moved or shaken, but are as Mount Zion,
established in the power, and life, and wisdom of the everlasting God,
which condemns darkness, and all its works,
and gives dominion and rule over all the powers of death and hell,
which work in the children of disobedience, who know not God, nor receive the truth,
much more in them who turn from the light and knowledge of the truth,
into the liberty of the flesh, to serve sin, having made shipwreck of fear,
and of faith and a good conscience.
These shall bear their own shame and condemnation in the sight of God and man,
and shall have no part with us in the inheritance of peace and righteousness;
but the latter end of such is worse than the beginning.

Wherefore you that are in the covenant of peace, where sin is not remembered,
nor committed, nor the unclean thing touched, dwell and abide in the life of God,
and in his strength, which reigns over all the world, with its temptations,
and over all false brethren, and over all deceitful workers, whose eye becometh darkened,
and their heart hardened through the deceitfulness of sin,
turning the grace of God into wantonness, and giving liberty to the unclean thing,
which is accursed.

In the counsel of the Lord God walk before him, and keep yourselves pure and undefiled,
and partake not of the deeds of the wicked, neither give place to the devil,
to be perverted by him from the truth of the living God,
which is truth in itself forever, though the backsliders despise the way of it.
Every one abide in your own, and know a measure of the strength of Christ Jesus in you,
to defend you from the enemy, who seeks to beguile and to devour,
and to divert from the perfect way of life and peace.

Dwell in your own measure of the grace of God, which is perfect,
which is sufficient to teach and lead and preserve in all the ways of God,
which the unclean cannot walk in.
He that keepeth you, reproveth, and condemneth, and casteth out the devil,
and all his works and workers, who abide not in Christ Jesus, nor in the truth,
wherein we worship the Father, who are called of him,
and are faithful and chosen followers of the Lamb, who taketh away our sin,
and giveth power over it, and over the tempter, who seeketh to betray the Just One.

From the eternal God I warn you, every one know a hiding place in God.
The day of great shaking cometh upon the garden of God.
The beast that had a wound by a sword, whose deadly wound is healed, may live,
and power may be given him for a moment, to make war against the Lamb and his followers;
and Satan may prevail to winnow you, and try you for your life.
Therefore be armed with the whole armour of light,
which manifesteth the mystery of iniquity,
and the working of spiritual wickedness in high places,
and which defendeth you from his power, out of the snare of the devil, in the simplicity,
as it is in Christ Jesus, who is our rock and our strength,
by which we overcome the fiery darts of the enemy, which come against us.

Dwell in the truth, that you may know the life which standeth in God,
with whom there is no shadow of turning.
He is the same forever, and keepeth covenant with his own elect,
who cannot be overcome of the devil, nor deceived; in whom, you abiding, cannot sin,
but are kept from being touched with the wicked one in the way, and in the truth,
and in the peace of God, lively and precious in his sight,
to serve him in fear and faithfulness.

If any go out from the light, the living way, they become as withered branches,
to be cut off from the body, no more to have fellowship in the body,
but are reproved and judged with that which keeps us in the body.
Though some go from the Lord, yet his faithfulness endureth forever,
and his promise is yea and amen to his own seed, which keep covenant with him,
and fulfill his law of righteousness and judgment.
He that breaketh covenant let him be condemned,
that the creature may be saved in the day of the Lord; for in them who draw back,
God hath no pleasure, but is oppressed with, and his soul vexed.
Therefore all walk in God`'s wisdom, which is pure and peaceable.
Let not the name of our God be spoken against through any of you,
who have been partakers of the word of truth,
through any disobedience or ungodly walking; but rather deny your own liberty,
than make it an occasion to the flesh, wherein Satan`'s strength stands.
So you will receive God`'s blessing, and his nourishment unto your souls,
and will be preserved in faithfulness, not to end in the flesh,
you that have begun in the spirit.

This in pure love towards you all,
as a testimony of my love to the seed of God in you all, I was I moved to write;
as seeing in the light the day cometh upon you, of which some may not be aware;
and I am clear thus far of the charge committed to me of God towards you,
and am in the truth itself, which cannot change,
and I am in it your friend in the service of the Lord God.

Edward Burrough.

A Second General Epistle to all the Saints

A servant of the Lord and minister of Jesus Christ,
thereunto ordained and called through the powerful operation and gift of the Holy Ghost,
unto all his brethren in the same life, who are born of God, and witnesses of his power;
and unto all the saints and churches of Christ,
who have believed and received the sure and faithful testimony,
and are called with the heavenly call, to follow the Lamb whithersoever he goes;
who is given to you, and received of you, a light, a guide,
and a teacher in all the ways of God.
Unto you all that are scattered abroad in the world, whether in bonds or at liberty,
whether strong men or children in Christ, I send greeting;
and above all things desire and pray unto the Father,
for your increase in the knowledge of him, and faithfulness in all his ways,
and that the increase of his government may abound among you; and that grace,
mercy and peace may be plentifully enlarged,
that nothing may be lacking to you in any thing of that which maketh perfect;
but that in Christ Jesus you may be complete, and through him you may receive power,
and thereby be strengthened to do all things.

My dearly beloved and longed for,
in the fellowship of that spirit which hath begotten
you to be sons and daughters of one Father,
and heirs and fellow-members of that inheritance of life, peace and rest,
which abideth forever.
Oh, how I long to meet you all in this,
and to find you perfectly settled and established upon the sure foundation,
which God hath laid amongst you, beyond all doubts, and fears and stumblings,
above the world and all its temptations, and above hell and death,
and all the ways thereof, having all the powers of darkness subjected under you,
serving the Lord in perfect holiness, walking in his strength and wisdom,
showing forth his light in the world, as his redeemed people.

My desire is more and more kindled and enlarged towards you all,
that you may perfectly attain to the knowledge of the great mystery of salvation, to wit,
God dwelling in you!
I say, my desire is, that you may know even as you are known,
and that you may receive him as you are received of him;
and that you may be a perfect body, growing up together,
and springing forth in all good fruits of truth and righteousness unto the Father,
who is glorified through your bringing forth much fruit.
You very well know, that for this end he hath called you,
and in this his appointed day caused his glory to shine forth,
and hath visited and brought us to the knowledge of the hidden mystery of eternal salvation,
which mystery hath been sealed up for many ages, and is kept secret forever,
from the wisdom of this world.

But unto us that have believed in the light of the world is it clearly discovered,
as at noon day;
being revealed to us by the spirit which worketh in us the will and mind of the Father,
and is powerful and mighty, and subdueth and breaketh down the hardness of heart,
and through the working thereof every high thought is brought into subjection to Jesus.

This same spirit quickeneth and maketh alive to God,
and changeth and reneweth into his image and likeness,
and raiseth up from under the bondage of corruption,
to live to God in all things in newness of life, old things being done away,
and all things being made new through the working thereof.
In this same spirit is the Father alone worshipped, and by it God is known;
and his promise is fulfilled, it witnessing in all things unto the Father,
and is the earnest of the inheritance which fadeth not away.
By it know we the deep things of God, which the world by wisdom knoweth not;
and thereby are we sealed and bound up in covenant with the Father.
This is known to you that are children of the light,
and hereof you have the witness in yourselves, and of God you are approved,
and not of men.

And all ye my brethren, who are called into the work and ministry of the gospel,
unto whom the word of the Lord is come, and the gospel of Christ to you committed;
dwell in the life of God, and feel his power and authority.
Live in the same life of which you minister to others, that you may bring people to God,
and may effectually turn them from the dominion of sin unto the dominion of Christ Jesus,
that people may be guided out of darkness into the marvellous light.
Cry aloud, spare not, proclaim the mighty day of the Lord in all the earth;
and fear ye not, neither be ye dismayed at the face of any man,
but be bold and valiant for the truth upon earth,
and give your testimony as you have received from God.

Preach Christ Jesus the light of the world unto all people, that they may receive him,
and be converted, and live.
For blindness and darkness have covered the whole earth,
and all have gone astray from the Lord, as sheep with out a shepherd.
Therefore awake ye them that sleep, and cause the deaf to hear, and the dead to rise,
that such as have strayed may be gathered.
For this is the fullness of time; he is now seeking his sheep that have been lost,
and bringing them home that have strayed; and you, as instruments in the Lord`'s hand,
hath he chosen to this work.

Therefore go on in the strength of the Lord, and preach the gospel of peace,
even the power of God, that sinners may be converted, and the wounded healed,
and the weak may be strengthened,
and they that are ready to die may be restored to life and salvation.
This is the work of the Lord, whereunto you are called;
therefore all who are called unto it, be faithful unto the end, and not only by word,
but by life and conversation also, hold forth the way of life.
For you must feel that in yourselves, of which you minister to others;
and you must hold forth in life, the same which you minister in words;
and thereby shall you be made manifest to that of God in all people,
and God`'s testimony shall answer for you.
See that in all things you divide God`'s word aright, not crying peace to the wicked,
nor healing up the wound falsely;
but that true judgment in all things may be brought forth by you to all people;
judgment to the fat, and bread to the hungry.
They that are naked must be clothed, and they that are falsely covered must be made bare.

Improve the gift which God hath given you, to him only, and not unto yourselves.
Be not hasty to utter words before the Lord, but wait for power from on high,
that the way of God unto salvation,
may be faithfully and truly held forth by you unto all people.
Faint not, though your burdens and trials be many, but bare all things patiently.
Love not your lives unto death, that the good work of the Lord may be accomplished,
which he hath begun by us,
and made prosperous and powerful in our hands unto this very day.

Our cause is good.
We seek truth and righteousness, that it may be established in the earth,
and people maybe brought unto God.
Unto this God hath called us, and hath owned us in it, and will never forsake us;
for the work is his, and the power is his, and whatsoever he will, he bringeth to pass;
and therefore why should we doubt, or be weary?
For we shall see the travail of our souls.
The scattered shall be gathered, and a remnant of the seed shall be brought in,
which is scattered in every nation, as dry bones, unable to live.
How shall we hide that treasure which God hath given us,
from them that perish for want thereof?
Or, how shall we rest satisfied till the scattered sheep be brought home to the fold?
Our hearts are troubled to see so many thousand walking in thick darkness,
and to see the seed of Israel devoured by the destroyer.

Therefore my brethren, let us put on strength, the Lord is with us;
let us make war in righteousness for the Lord, against all the powers of darkness.
Let us continually be armed to do and to suffer all things for the name of the Lord,
that people may be instructed in the right way.
We know no man can have power over us, but what is given him from above,
and all that comes to pass against us is not worthy
to be compared with the crown of glory,
and that inheritance of which we have already received the earnest,
and had sealed with the spirit of promise.
The Father`'s name is written upon us;
therefore in all things unto which he hath called you, be faithful and obedient,
that his work may be accomplished.

And all ye children and babes in Christ, that are begotten of God,
and are thirsting and seeking after him in truth and righteousness,
he whom ye seek is coming to reign amongst you,
and his dominion shall be set up and enlarged,
and the desire of your hearts shall be fulfilled.
Righteousness and truth shall meet in one, and judgment and mercy shall be exalted.
Wait upon the Lord, and feel his power and his presence continually,
that you may grow as plants of righteousness,
and may partake of the heirship with Christ, being crucified to the world,
and become dead to all its ways, and no more you to live, but Christ to live in you.

Through the light which he hath enlightened you withal,
hath he given you an entrance into the inheritance of the Father.
As you walk in the light, you grow into fellowship with the Father, and with the Son.
Abiding in the Son you cannot sin; for he keeps you from the wicked one,
and he hath no power over you that abide in Christ, who is the power of God,
and the salvation of all that believe, and a condemnation of all that believe not.
Therefore all you that are convinced everywhere, hearken to the voice of the Lord,
that your souls may live.
Mind the power of God, and the workings thereof in your hearts,
which conquereth hell and death, and subdueth all the powers and ways thereof.

Every one be obedient to the Lord, as children of one Father,
that of his fulness you may receive, and be filled therewith.
Meet together in every place; and as the day approacheth exhort one another,
that you may grow up in unity as members of one head.
Mind always the testimony of truth, and walk therein, and you cannot stumble.
Have not respect to persons, but to the truth only; for persons may change,
but the truth abides forever.
So let not an evil eye look at evil, when it comes to pass,
to take occasion thereby against the truth; for then you stumble and fall.
I say again, have respect only to the pure testimony of truth which is sure,
and cannot err or alter, though man may change and err.
That is the testimony which is held forth for salvation, even the testimony of God,
with whom there is no shadow of turning.

Therefore all take heed unto yourselves, that you give not, nor receive,
any offence against the Lord, and against your own souls;
but know the seed of God in which stands the election, where the covenant of God is sure,
and unalterable.
A birth you must all know to be brought forth in you, which must inherit,
and that is it which is born of the spirit, and doth obtain the promise.
It is not that birth which is of the flesh, which works by willing, and running,
and thinking.
That obtains not the promise of God, neither is salvation showed unto it,
but in patience, and in long-suffering is the victory received,
over all the powers of darkness which make war against the kingdom of God.

So all Friends, dwell in that which stops and limits all strife in the mind,
and gives you victory over it.
None must glory in the flesh, for that glory must be confounded;
but let him that glories, glory in the Lord, in the spirit, and not in the flesh.
And take heed that none of you abuse your liberty, which is in Christ Jesus,
neither turn it into fleshly bondage, and thereby the just come to suffer,
and the fleshly part come to rule above the seed of God;
but dwell in the cross which suppresseth every high thought,
and whatsoever is against God, in the first motion.
Thereby you will be preserved from the enemy, which watcheth for evil against you,
and seeks occasion against the way of the Lord.
Mind that which keeps you pure; for it is the pure in heart that see God,
and it is he that is of clean hands and of a pure heart,
that inherits God`'s holy mountain.

And as concerning your afflictions, and sufferings, and trials, and persecutions;
and whatsoever is laid upon you by the Lord, or by men; I say, bear all things patiently,
and endure all things in long-suffering.
These things are but for a moment,
and they are not worthy to be compared with the price of God`'s inheritance;
and if you dwell in the counsel of the Lord,
all these things will be turned unto your good.
In all trials and sufferings, the Lord`'s arm will be revealed,
and these things must come to pass, that truth may appear in its beauty,
in victory over all that doth oppose it.
Vengeance is the Lord`'s, and he will repay; for he doth inquire after our blood,
though no man lay it to heart,
or consider the cause or unjust sufferings of the innocent,
who are become a prey to the ungodly and unjust men, till God arise to plead our cause.
Afflictions and sufferings are but to try and prove.

They are not to confound or destroy the Lord`'s people,
and therefore in patience they must be borne, and the life of God felt,
which gives dominion over all these things.
And receiving all things as from the hand of the Lord,
then in all things your peace will remain,
and God`'s testimony will witness peace and acceptance with God.

And of all injustice, and abuses and cruelty acted upon you by any, at any time,
keep account of it, and draw up in short and plain words, the occasion and manner of it,
and at every quarter sessions let a true declaration of all unjust sufferings
be presented in prudence and singleness of heart to the justices,
or grand jury, by such as are wise and faithful.
Appeal to the witness of God in them in such cases,
that that of God in all men may witness for us.
Let this be done, as cause is seen, at every sessions,
in the wisdom and authority of God,
that in all things justice and true judgment may be sought after,
and in patience waited for, till the Lord alone, our King, and Judge, and Lawgiver,
comes to reign over all his enemies; when all that now suffer for him,
shall reign with him.

A servant to the churches of Christ,

Edward Burrough.

To the Elect and Chosen Seed of God in London

To the elect and chosen seed of God, most dear and precious, who are redeemed to God,
and joined in covenant with him, and have tasted, and felt,
and heard of the love and peace of the Father; and to all the faithful and called of God,
who are partakers of the power and presence of an endless life.
In particular unto you the flock of God, in and about London, who fear the Lord,
and wait upon him, and over whom he is the chief Shepherd.
The salutation in the Father`'s love,
by me a brother and companion unto all the children of Zion,
and chiefly unto you a friend in heart; and nothing more desiring for you,
than your increase in God, and that grace, peace,
love and fellowship from the Infinite Father of heaven and earth,
may be largely increased, and abundantly multiplied amongst you, and in all your hearts,
that you may shine forth in the beauty of the Lord,
and the garment of righteousness and truth may be spread over you all;
and that the spirit of holiness may rest upon you,
that the fruit thereof may greatly abound in you, and spring forth from you,
whereby the Father, who hath begotten you, may be glorified through the nation,
and among his saints through the world.
My soul wisheth, that the fear of the Lord may be amongst you,
and his terror upon all your enemies, Amen.

Dearly beloved, and much desired after in the Lord, the spirit of the Father is upon me,
to put you in remembrance of these things of the greatest price,
which belong unto your peace, which have been hid from you in the time of darkness,
but now are revealed unto you, whereof your eyes have seen, your ears have heard,
your hands have handled, and your hearts have perceived.
Be not unmindful thereof, but take heed unto the precious treasure of life eternal,
which the Father hath given unto you; I mean the knowledge of himself,
who is manifest to dwell in you, and to walk in you, and to lead you,
and to guide in all his ways of peace and truth.
This is a treasure more desirable and of greater price, than the glory of the whole earth.
Yea, it is peace to the soul, and gladness to the heart, and refreshment to the life,
to feel and witness the teaching of the spirit of the Father, leading into all truth,
and preserving out of all transgression.

Wherefore I beseech you all, let this be your whole desire,
and the full practice in your life.
Then shall the countenance of the Lord shine upon you, and his face shall make you glad,
if in all things you look unto him for counsel, and wait upon the teaching of his spirit,
which dwelleth in you, which the Father hath given unto you,
because you are his children.
This he requireth from you, that his own spirit in you, which hath begotten you,
may be the root and moving cause of all your works and words,
and herein will you receive acceptance with him, and peace from him,
and righteousness in him, and everlasting joy by him continually.
This is the inheritance, unto which you were begotten heirs, to possess forever.

Therefore let your love, unity and fellowship be in the spirit, and let your knowledge,
judgment, meeting, and waiting be in the spirit,
and let your ministering and receiving be in the power of God, and in the spirit,
and so shall you never suffer loss or condemnation;
but all your works shall abide the fire,
and shall not be consumed when the trial of all things comes,
and the foundation of every work is discovered.
I say again, if the spirit of life, even the spirit which quickens to God,
the second Adam, who is the quickening spirit, be your guide,
your leader and teacher in all things, then you shall have perfect peace with God,
and your fellowship will be increased, and his presence shall go before you,
and his righteousness shall be your justification and defence,
and his covenant of life and peace shall be confirmed unto you.

There shall be no more going forth,
but the tabernacle of God shall remain with you always,
and his habitation shall be in you forever,
and the promise of the Father shall be sealed unto you, and his mark,
and express image written in your foreheads.
He that quickeneth shall live in you, and not you unto yourselves;
and hereby shall all know that he is your God, who liveth in you in power and dominion,
and that you are his people who live unto him in truth and righteousness.
This is the covenant and the promise to be waited for by you all,
that you may be married to the Lord in righteousness and lovingkindness,
and your Maker may be your husband, and you subjected under his power, to rule over you,
and to govern you in the way of peace.

And now, dearly beloved,
mind that word of God which hath begotten you from death to life,
and to be heirs of his inheritance of life.
Feel the word which is quick and powerful dwell in your hearts,
always dividing in you between the precious and the vile, and as a hammer and a fire,
beating down, and burning up that ground and fruit which is in the disobedience,
from which the cause of condemnation springs.
So shall you be saved from every appearance of evil, and shall not be overcome thereby,
nor led captive at the will of the enemy, but shall be saved from sin,
and the wages thereof, and no condemnation shall be unto you,
if your hearts be kept clean and undefiled, by the word of God which is pure,
and sanctifieth, and is but one in all his children.

It begetteth unto one life, and to be of one mind and soul,
and by it dwelling in the heart, is the increase of God received;
though by the ministering of it, one may plant and another may water,
yet it is the Father that gives the increase, who is greater than all.
Unto Him the ends of the earth must look for salvation, and unto him must you all look,
to partake of the increase of his hidden treasure daily,
that you may be refreshed as the heritage which he hath chosen, and may grow therein,
as plants planted by his own right hand, growing from strength to strength in him,
and renewing your strength in him, and may not faint nor be weary.

And forasmuch, as mighty hath been the power and presence of the Lord amongst you,
and his love great unto you, and caused his voice to be heard, when you were dead,
to raise you unto life; and many of you have had the taste and feeling thereof,
who have seen the way of life before your face, that you should walk therein, and live:
I do warn you all in the name and by the spirit of the Lord,
therein to continue unto the end, having your faith established in the power of God,
and your building standing on that true foundation which can never be moved or shaken,
that perfect victory over death and the grave may be yours,
and the powers of darkness may be trodden down through the obedience of the cross,
whereby victory is obtained over all the world,
and the affections and lusts thereof condemned.
But such as go from the cross, perceive not the power of God, neither can overcome,
but are overcome of the enemy, and shipwreck is made of faith, truth,
and a good conscience, and the latter end of such is worse than their beginning;
for the Lord is dishonoured, and their condemnation will be great.

Wherefore, my friends, be watchful and be armed with the strength of Christ Jesus,
and feel his strength in you to resist the wicked one, that he may not touch you,
to betray you of your life and peace, and bring you into condemnation;
for I am not ignorant of the many temptations which are near unto you in that place.
I say again, feel the strength and arm of God reaching to you,
by which you may do all things; and dwell in his life and power,
that ye may overcome by the Word of God, and by the testimony of Jesus.
Then will your peace be increased, and your fellowship with God.
As you overcome the enemy which would subvert your minds from the obedience to the truth,
your rest in God will be sweet unto you, as you dwell where nothing can make afraid;
sin and transgression being removed far from you, not having a place in you,
but the life reigning which Satan hath nothing in.

This is the freedom of the sons of God, who are redeemed unto him, to live in him,
who being dead to sin, cannot live any longer therein;
but are washed and separated from all the works of death.
Death having lost his sting, cannot hurt or wound you;
and the grave having lost its victory, it cannot overcome you who do witness this;
for transgression is hid, and iniquity is put under,
and life itself reigns through righteousness over all.
Here the seed is brought forth, in which there is no iniquity seen,
nor transgression charged against it, for it sins not; but rules over the sinner,
and fulfils the righteous law of God, and doth his will in all things;
and for this you must all wait to feel God`'s promise perfectly fulfilled in you,
and sealed unto you by the Eternal Spirit.

Friends, feel the life of God in your own particulars,
even the bread of life which comes down from heaven,
which nourisheth the birth that is immortal unto eternal life, never to taste of death;
and therein have fellowship in the covenant of life, and be at peace with God,
and one with another.
That is blessed of the Lord, where brethren dwell in unity, showing love,
kindness and subjection one to another, being of one spirit, and like-minded,
serving one another in love, not exalting yourselves,
nor accounting yourselves one above another, for that must come down with shame.
But every one approve yourselves to God in all things, and be known to him,
and not unto the world.
Let his spirit witness for you, and approve you, and not man;
and let the work of the spirit springing through you be the evidence unto all people,
that you are by grace what you are, for this is well pleasing unto God,
that his spirit witnesseth for you, and that love, unity and humility are amongst you.

None think of themselves above what the spirit of the Lord witnesseth,
and worketh in them.
Thus a sweet savour will be amongst you to the Lord,
you being kept in his wisdom and counsel, in good order, and subject unto him,
walking as examples of righteousness, to edify one another,
and to be a strength one to another;
and in all your conversations to be manifest to God`'s witness in all people.
Thus shall you have praise of God, and be approved of him,
and he will justify you in the sight of all your enemies.
I write this unto the faithful, who do not minister self,
but self your servant for Jesus sake.

And as concerning disorderly spirits, who are not subject to the wisdom of God,
or to the law of Christ, such have no part with us, but are judged with the life of God,
and cast out.
Such as are not faithful in the Lord`'s treasure, and hear the word, but do it not,
having the words, without power, and hold the truth in unrighteousness,
have no reward in God, but their iniquity stands uncovered,
and their transgression is manifest, and not hid.
For death reigns through disobedience, and they are not circumcised in heart,
but live in the flesh, and their portion is of this world,
and the inheritance of life is not their heirship;
for the birth which should inherit it is not brought forth, but an untimely birth,
which receiveth not the possession of life.

But, Friends, dwell in the dominion over such, and in peace above them,
and be not troubled, but believe in the truth, and bear all things patiently.
Be not offended in Christ, though hitherto you have seen occasion of stumbling,
yet the Lord will remove them, and the path of life hath been plain before you.
To such as walk in the light there is no occasion of stumbling,
but offences are seen through, and beyond, and the ground thereof judged.
Therefore be diligent in the work of God;
that is his work which his spirit calleth you unto,
and that is his worship which his spirit leads you in,
which exerciseth your hearts always to God.
Keep your meetings in the dread of the Lord over all your enemies,
that the weak may be strengthened, and the lambs fed; and watch over one another,
as the family of God, among whom his dwelling is, who is the good Shepherd,
that keeps his flock, and feedeth them unto eternal life,
whose presence and arm be amongst you forevermore.
Feel Christ the power and wisdom of God to reign in you, and govern you all.
Farewell.

Edward Burrough.
