== Chapter X.

On the 10th day of the third month, 1661, on the coronation of the king, he,
as an act of grace, gave forth a royal proclamation,
by which he discharged from prison all who were in confinement
under the act for refusing the oath of allegiance,
or for meeting for worship, contrary to his former proclamation.
Religious liberty was not yet heartily approved of by the rulers,
and in a few days after this an attempt was made in Parliament
to obtain a special act to crush the Society of Friends.
Edward Burrough says; "`The 26th day of the third month,
it was moved by a certain member of the House of Commons,
whose name I shall not now mention, that whereas the Quakers were a numerous people,
and growing more numerous daily,
and upon the king`'s indulgence and fair promises towards them,
especially that proclamation for their release out of prisons,
were very high and confident; and met together in great numbers,
and were of dangerous consequence,
and prevailed much to the seducing of the king`'s subjects;
that therefore that House would be pleased to take into consideration,
by what way and means to proceed to check and restrain their confidence;
and to enact somewhat concerning their refusing to take oaths, and their great meetings.
Whereupon it was put to the question in the House, and resolved upon the same,
that it should be referred to a committee to prepare and bring
in a bill to prevent the ill consequence to the government,
by Quakers, Anabaptists, and other schismatics, refusing to take oaths,
and numerously and unlawfully convening together,
with such penalties as may be suitable to the nature of those offences,
and profitable to work upon the humours of such fanatics.`"

About six weeks after the appointment of this committee they reported a bill,
which being twice read, was committed again to a committee.
To this committee Edward Burrough, George Whitehead,
and Richard Hubberthorn obtained access;
and presented to them in writing their reasons against such a bill being enacted,
and also had liberty to speak of its unreasonableness,
and the woeful consequences which would follow.
The committee met again on the 13th, and Friends again were admitted to address them.
George Whitehead has recorded what he said to the committee,
and one sentiment spoken by his friend Edward Burrough,
which the latter has more fully given us.
Edward says, "`The last thing that was said by one of us was,
that if ever this bill now under debate was finished into an act to be executed,
he was so far from yielding conformity thereunto, that he should,
through the strength of Christ, meet among the people of God to worship him;
and not only so, but should make it his business to exhort all God`'s people everywhere,
to meet together for the worship of God, notwithstanding that law and all its penalties.
And he desired this might be reported to the House.`"

The committee were more moderate with the Friends
at the second opportunity than at the first,
and the spirits of some of them seemed brought down
and subjected under the power of truth;
although one called Sir John Goodrich inveighed very bitterly at first against Friends.
The bill was finally reported to the House on the 19th of the month,
and the three Friends who had attended the committee
being joined by Edward Pyott of Bristol,
presented themselves at the bar of the Commons,
requesting permission to give their reasons against it, which was granted.
Edward Burrough insisted "`That our meetings were no ways to the terror of the people,
as was suggested in the preamble to the bill, but peaceable,
only for the worship and service of Almighty God,
as we are required by the law of God placed in our hearts and consciences,
which they ought not to make any law against.
No human law ought to be made contrary to the law of God;
for if they did make any such law, it would not be binding.`"
He quoted their ancient law book, [.book-title]#Doctor and Student,# which he had in his hand,
wherein treating of the law written in the heart of man, it says,
"`Because it is written in the heart, it may not be put away,
neither is it ever changeable by diversity of place or time;
and therefore against this law, prescription, statute, or custom may not prevail;
and if any be brought in against it, they be not prescriptions, statutes, nor customs,
but things void and against justice.`"
After reading this Edward said, "`If they made such a law against our meetings,
which are appointed for the worship of God, it would be contrary to the law of God,
and void, or ought to be void, __ipso facto.__`"

The others then each spoke freely their objections to the bill.
Edward, on summing up the whole, says, "`The Lord opened our mouths,
and we showed divers sound reasons unto the House against the aforesaid bill,
and why it ought not to pass into an act;--first,
because of the falsity and unsoundness of it in its ground; 2ndly,
because of the unreasonableness and injustice of it in itself; and 3rdly,
because of the evil effects of it, which must needs follow if it passed.
Divers other things were spoken in the name and authority of the God of heaven,
as concerning our peaceableness, etc.,
and of the absolute proper right that belonged to us, both from God and men,
to enjoy the liberty of our consciences in the exercise of our religion, etc.
And we had a good time to clear our consciences to them as about that bill,
showing how it was contrary to the law of Christ, and to the king`'s promises,
and destructive to many thousand good people.`"

The House heard what the Friends had to say with patience,
and afterwards long debated the bill, but at last they passed it.
When the bill came before the House of Lords,
Edward Burrough presented some reasons and considerations against it.
They were the same in substance as he had urged before the Commons,
and are forcibly expressed.
The bill did not become a law until the third month of the next year.

About the beginning of the seventh month, 1661,
information reached London of the martyrdom of William Leddra at Boston,
and the probability that other members of the Society of Friends,
would shortly suffer the same fate.
On learning this, Edward Burrough, on behalf of his fellow members in England,
whose hearts were touched with sympathy for their distant brethren,
obtained an audience with king Charles on the subject.
He told the monarch, that a vein of innocent blood was opened in his dominions,
which if not stopped would overrun all.
The king, who, though dissipated in his morals, was yet good natured,
and willing to grant a favour, if it did not give himself much trouble, replied,
"`But I will stop that vein.`"
Edward requested him to act speedily in the case,
"`for we know not how many may soon be put to death.`"
Charles said, "`as soon as you will;`" then addressing some one present he said,
"`call the Secretary, and I will do it presently.`"
The Secretary came at the summons,
and at the will of the king drew up a mandamus which was properly and officially executed.
A day or two afterwards Edward called again on the king; the mandamus had been prepared,
but the case slumbered.
Indeed it probably would never have been attended to,
if he had not been further pressed on the subject.
In excuse for delay, the king said he had no occasion to send a ship to New England.
Edward,
who knew there were many chances of getting such a thing conveyed to its destination,
by those who had a heart in the matter,
enquired if he would be willing to grant his deputation to one called a Quaker.
The king answered, "`yes, to whom you will,`" Edward then named Samuel Shattock,
an inhabitant of New England, banished from thence on pain of death,
and the king made him his deputy.

Samuel Shattock was soon ready to sail,
for Friends made an agreement with Ralph Goldsmith, one of their members,
who was master of a good ship, to sail in ten days, with or without freight.
For this they paid him three hundred pounds.
He reached his destination in safety, and at the sight of this mandamus,
the proud rulers of Boston were forced to yield up their prey.
All then in prison were discharged.

Edward Burrough,
after seeing the deputy with the mandamus in a way to be speedily forwarded,
set out to visit Friends in the north of England.
Whilst in Westmoreland he appears to have found various
manuscript essays written by him at different times,
which on reading over he now concluded to publish,
and called his book [.book-title]#A Discovery of Divine Mysteries.#
The preface bears date the 25th of the seventh month.
Whilst still in the north he addressed another general epistle to the saints.

He continued labouring about the place of his nativity for some time,
and on the 28th of the eighth month,
addressed another epistle to Friends of the truth in and about London.

We have no further account of the labours of Edward Burrough,
until we find him in the latter part of the tenth month,
or the beginning of the eleventh month in Oxfordshire, visiting Thomas Ellwood,
then sick of the small pox.
From Oxfordshire he went to his old field of labour, the city of London.
Here in the twelfth month he wrote "`an epistle to the rulers in the Christian
world,`" as a preface to a new work he was about publishing,
entitled _Antichrist`'s Government Justly Detected of Injustice, Unreasonableness,
Oppression and Cruelty._

About this time John Perrott began to lay claim to greater spirituality than his brethren,
and to be elevated with spiritual pride and self conceit.
He does not appear ever to have been qualified for,
or called to much service in the church.
Yet when he was humble,
he was without doubt accepted in that little which his heavenly Father required.
Now, however, being puffed up, he put on, to draw attention and admiration,
the appearance of great sanctity.
He declared himself not easy to take off his hat in the time when
any of his fellow ministers engaged in public prayer,
unless he felt a particular sense of duty thus to uncover his head.
This began to create some diversity of feeling amongst Friends,
and some unpleasant scenes in their meetings.
Edward Burrough was favoured to see the root,
from whence the affected singularity of John Perrott in this particular had its rise,
and as one instructed in the ways of righteousness, administered to him a sharp rebuke.

Edward Burrough once more felt his mind drawn to visit Friends about Bristol.
He was but a young man, and in years and bodily strength was in the prime of life,
yet he felt as if his day`'s work was nearly over.
In his ministerial labours in several meetings,
and whilst parting with particular friends, he bade them farewell with unusual solemnity,
saying many times that he did not know that he should see their faces any more,
and exhorting them to faithfulness and steadfastness,
in that wherein they had found rest to their souls.
His last words to some were; "`I am going up to the city of London again,
to lay down my life for the gospel, and suffer amongst Friends in that place.`"
London had ever had a strong hold on his affections,
and he had said to his friend Francis Howgill, at a time when persecution was hot there,
"`I can freely go to the city of London,
and lay down my life for a testimony to that truth,
which I have declared through the power of the Spirit of God.`"

Thus under a sense of the near approach of death he came up to London.
Soon after arriving there, about the close of the third month,
being at a meeting at the Bull and Mouth, which Francis Howgill says,
"`the people of the Lord had kept for many years,
to hear and speak of the things of God to edification,`" he was arrested whilst preaching.
Those who arrested him violently pulled him down, and carried him to the guard,
and from thence before Alderman Brown, who committed him to Newgate.
He was taken to the sessions in the Old Bailey, and his accusers,
and those who had personally abused him, were the sole witnesses against him.
His case was before the court at two or three sessions, and at last he was fined,
and sentenced to lay in prison until the fine was paid.

Many Friends were in Newgate at that time, shut up among felons,
and not having sufficient room to accommodate them, and being in filthy places,
their health and strength gave way.
Richard Hubberthorn, arrested shortly after Edward Burrough, soon grew sick;
and about the time he had been two months in prison his spirit was released.
He had been in a holy state of waiting, looking for his change,
and lifted up above all the pains of nature.
To some Friends who visited him he said, "`There was no need to dispute matters,
for he knew the ground of his salvation,
and was satisfied forever in his peace with the Lord.`"
Of this Friend, Edward Burrough wrote a memorial.
Although confined in prison, he was busy with his pen.
One of his productions is entitled,
_A Testimony Concerning the Beginning of the Work of the Lord,
and the First Publication of Truth, in this City of London;
and also Concerning the Cause, End,
and Service of the First Appointment and Setting
Up of the Men`'s Meeting at the Bull and Mouth;
That it May be Known to All Perfectly,
How the Lord Hath Begun and Carried on His Work to this Day._

About the middle of the ninth month he addressed the following
letter to some of his friends in the country.

Dear and beloved Friends!

The lively remembrance of you dwells always with me,
praying for the increase of peace and blessing to you from the Father.
I know ye have learned Christ,
and are acquainted with the teachings of his grace and spirit,
which leads you into all truth, and is a comforter unto you in all conditions,
which is present with you, and in you, in all times and places,
even the Spirit of the Holy God, which is given you, because you are children of him,
who is God, blessed over all.

Dearly beloved, my heart is filled with fervent love towards you at this time,
and the lively sense of the Lord`'s suffering people rests upon my spirit,
with the dear embraces and salutations in the same
love with which I am loved of Christ Jesus my Lord,
whom I hope ye have so learned as never to deny his name and truth.
I am persuaded concerning you, that the greatest tribulations,
afflictions and sufferings, can never move or shake your hope or confidence in God,
nor separate you from his love, life and peace,
which many of you have had large manifestations of,
and some the assured possession of forevermore;
and I hope nothing can separate you from that love which is of God,
or divide you from it in the absence of the Father`'s presence,
which is full of joy and peace.
Nothing, I say, can be able to break our fellowship with the Lord, but that he is ours,
and we are his, whatsoever wars, actions or tribulations may pass upon our outward man.
I write unto the faithful, and I need not say unto you, "`know the Lord,`" but I may say,
"`stand fast, faithful and valiant unto death,
for the knowledge of God which ye have received, and give yourselves to be destroyed,
rather than to renounce or deny Christ before men,
or to cease from the exercise of your consciences in what
his Holy Spirit persuades your hearts in the verity of.`"

Friends here are generally well in the inward and outward man,
and the presence of the Lord is manifest with us through great trials,
and sore afflictions, and grievous persecutions,
which we have met withal this last half year.
It would be too large to relate, and piercing to your hearts to hear,
the violence and cruelty which Friends have suffered in this city in their meetings,
and in prisons; it hath been very hard to bear the persecution inflicted every way,
though the Lord hath given strength and boldness,
and his power alone hath carried through, else many would have fainted,
and not have been able to stand.
Many have given up their lives in faithfulness in this place,
and their faithfulness in keeping meetings,
and in patiently enduring many tribulations and cruel exercises,
is a crown upon Friends in this city.

Here are now near two hundred and fifty of us prisoners in Newgate, Bridewell,
Southwark and New Prison.
In Newgate we are so extremely thronged,
that if the mercy of the Lord had not preserved us, we could not have endured.
There are near an hundred in one room on the common side among the felons,
and their sufferings are great; but the Lord supports.
For about six weeks the meetings were generally quiet in the city,
but these last three weeks they have fallen on more violently than ever,
and imprisoned many Friends.
But through all this truth is of good report,
and the nobility of it gains place in many hearts,
which are opened in pity and compassion toward innocent sufferers,
and truth is increased through all trials.
Our trust is in the Lord, and not in man;
and we desire the same spirit may dwell and abide in you also,
that ye may be likeminded with us, and we all of the mind of Christ,
who seeks men`'s salvation, and not their destruction.

King Charles, who appears to have entertained much respect for Edward Burrough,
hearing of the crowded condition of the prison,
and the number who were sick or dying in it,
sent a special order for the release of Edward Burrough and some other of the prisoners.
This order, however,
the cruel and persecuting alderman Brown and other London magistrates contrived to thwart;
and Edward, who had become quite weak and sickly, from the pestilential air of the jail,
rapidly grew worse.
It soon became evident that this faithful and devoted servant of Christ,
was hastening to the close of his labours on earth,
to enjoy the crown immortal in heaven.
The same meek,
enduring and fervent spirit which had shown forth in his active and useful life,
was apparent in the approach of death.
As his sickness increased, he abounded in patience and composure,
and the spirit of supplication rested richly upon him.
By night and by day he poured out his prayers to God, for himself and for his people.
His heart being replenished with grace,
he uttered many expressions indicating the heavenly frame of his soul,
greatly to the comfort of his surviving friends.
At one time he said,
"`I have had the testimony of the Lord`'s love to me from my youth up;
and my heart has been given up to do His will.`"

His deep interest in the city of London,
and the prosperity of the Society of Friends there, continued with him;
and on one occasion he exclaimed, "`I have preached the gospel freely in this city,
and have often given up my life for the gospel`'s sake.`"
"`There is no iniquity lies at my door, but the presence of the Lord is with me,
and his life, I feel justifies me.`"
His heart overflowing with the love of God,
and with a precious sense of God`'s love extended to him,
he seemed borne above his weakness and sufferings,
already enjoying a foretaste of that heavenly rest and peace,
into which he was soon to enter.
In addressing his heavenly Father, he would say,
"`I have loved thee from my cradle--from my youth unto this day;
and have served thee faithfully in my generation.`"

Filled with a lively sense of the preciousness of that love,
which is the fulfilling of the law, he exhorted his friends to "`love one another,
and to live in love and peace.`"
He prayed for Richard Brown, one of his principal persecutors, by name;
thus showing forth the spirit of his divine Master, who,
when suffering on the cross for the sins of mankind,
interceded for his murderers in this affecting language; "`Father forgive them,
for they know not what they do.`"
Thus calmly and peacefully he drew toward the close of life,
the spirit of his Lord and Master being in dominion in him,
and his faculties bright and clear, notwithstanding the violence of his disorder.
Sensible that his death was near, he said, just before it occurred,
"`Though this body of clay must return to dust,
yet I have a testimony that I have served God in my generation;
and that spirit which has acted and ruled in me shall yet break forth in thousands.`"
Thus sustained by the power of God, in the faith and hope of the gospel of Christ,
he closed his life, a martyr for the name and testimony of the Lord Jesus,
on the 14th day of the twelfth month, 1662.

Those who have followed this undaunted soldier in the Lamb`'s army,
through his life of laborious dedication to the gospel,
and his peaceful and triumphant death,
can subscribe to the language of George Fox respecting him:

His name is chronicled in the Lamb`'s book of life, a righteous spirit, pure,
chaste and clean.
Who can tax him with oppressing them, or burdening them, or being chargeable to them,
who through suffering hath finished his course and testimony;
who is now crowned with the crown of life,
and reigns with the Lord Christ forever and ever.

In his ministry in his life-time he went through sufferings by bad spirits.
+++[+++He]
never turned his back on the truth, nor his back from any out of the truth.
A valiant warrior, more than a conqueror,
who hath got the crown through death and sufferings.
Who is dead, yet liveth amongst us.
