== Testimonies Concerning Edward Burrough, Deceased

In a testimony given forth concerning him by Francis Howgill,
his companion and fellow traveller in the ministry of the gospel, we find the following,
viz.:

Shall days, or months, or years wear out thy name, as though thou hadst had no being?
Oh nay!
Shall not thy noble and valiant acts,
and mighty works which thou hast wrought through
the power of Him that separated thee from the womb,
live in generations to come?
Yes! the children that are yet unborn shall have thee in their mouths,
and thy works shall testify of thee in generations who yet have not a being,
and they shall count thee blessed.
Did thy life go out as the snuff of a candle?
Nay thou hast penetrated the hearts of many,
and the memorial of the just shall live forever,
and be had in renown among the children of wisdom.
Thou hast turned many to righteousness,
and shall shine as a star of God in the firmament of His power, forever and ever.

They that are in that, shall see thee there, and enjoy thee there,
though thou be gone away hence, and can no more be seen in mutability.
I cannot but mourn for thee, yet not as one without hope or faith,
knowing and having a perfect testimony of thy well-being
in my heart by the Spirit of the Lord;
yet thy absence is great, and years to come shall know the want of thee.
Shall I not lament as David did for Abner, when in wrath he perished by the hand of Joab,
without any just cause?
Died Abner as a fool dieth?
Nay! he was betrayed of his life;
even so hast thou been bereaved of thy life by the hand of the oppressor,
whose habitations are full of cruelty.
When I think upon thee, I am melted into tears of true sorrow,
because of the want that the inheritance of the Lord hath of thee.

It was my lot, which I cannot but say fell in a good ground,
to be his companion and fellow-labourer in the work of the gospel,
whereunto we were called for many years together.
And when I consider, my heart is broken;
how sweetly we walked together for many months and years!
in which we had perfect knowledge of one another`'s hearts,
and perfect unity of spirit.
Not so much as one cross word, or one hard thought of discontent ever rose, I believe,
in either of our hearts, for ten years together.
Our souls were bound up in unity and peace,
having the frame of our hearts bent after one and the self same thing, to wit,
the propagation of that truth by which liberty was obtained,
and salvation received through Jesus Christ the true light of the world.
Seeing through his light the whole world to lie in wickedness;
a necessity lay upon this person of whom I am speaking,
being constrained by the Spirit of the Lord,
by which he was made an able minister of the everlasting gospel, to preach repentance,
conversion, salvation and remission of sins.

Accordingly he went forth in the name and power of the Lord Jesus,
the Saviour of mankind, and was an able minister of the glad tidings of salvation,
in many, or most parts of this land;
and also he travelled again and again through the whole nation of Ireland;
in some part of Scotland, and part of Flanders; and his ministry was made effectual,
through the Almighty power of God, in turning many from darkness to light,
and from the power of Satan to God.
There are many thousands living in the body, and alive in the truth,
who can in the Spirit of the Lord bear testimony to the power and verity of his ministry,
in many countries where he travelled; for he laboured much in divers places,
even in the heat of the day, though he began early in the morning.

In the beginning of his travels and labours,
it was his share to break up rough places and untilled ground,
and to walk amongst many briars and thorns, which scratched and pricked.
He often trod the paths and ways which had not been occupied in the truth;
and where darkness had the dominion and was as a covering,
he broke through as an armed man, not minding the opposition, but the victory,
and the good of all souls,
though to my knowledge his sufferings and trials have not been small,
nor his exercise a little.

He was in travels often, oftentimes buffeted, sometimes knocked down by unreasonable men,
who had not faith; loaded with lies, slanders, calumnies and reproaches,
besides the exceeding weight of service from week to week,
insomuch that he had seldom many hours of repose;
and he often suffered by those spirits who lost their first love, and rose in opposition.
He was very diligent and faithful, true-hearted and valiant,
and the yoke at last came to be easy unto him, though no ease at all in the body,
as to the outward man; for he made the work of the Lord his whole business,
without taking so much liberty unto himself, or about any outward occasion in this world,
as to spend one week to himself, to my knowledge, these ten years.
He had ventured himself often, for the body`'s sake;
and a great care I know was in his heart, that those to whom he had ministered,
and others that had believed in the same truth,
might prosper and walk as becometh the gospel of Jesus Christ.

He was of a manly spirit in the things of God.
He engaged himself often upon the Lord`'s account singly in great disputes,
when there were many opposers.
He hath stood in the door, and in the gap, against all his enemies,
for the worthy name of God, and took the whole weight of things upon his own shoulders,
that others might be eased, though often to the weakening,
and almost destroying of the outward man, yet doing all in love to the Lord,
and for his people`'s sake.
He did it with cheerfulness,
and it was a grief to him if any opportunity was missed of doing good.
He was a man of no great learning in natural tongues, which men so much applaud;
yet his heart was full of matter, and his tongue was as the hand of a ready scribe.

He had the tongue of the learned, having had experience of the work of the Lord,
and being acquainted with many conditions which God had carried him through,
he could speak a word in season unto all who declared their conditions to him or otherwise.
In his public ministry he was elegant in speech, and had the tongue of a learned orator,
to declare himself to the understandings and consciences of all men with whom he conversed,
by which many received great profit, and their understandings came to be opened;
for his words ministered grace to the hearers, and were forcible and very pleasant,
as apples of gold in pictures of silver.

This young man, of whom I am speaking, was one of the first, with some others,
who came to the city of London, where he met with no small opposition,
both from professors of divers forms, and also profane, who heeded no religion at all.
The way of truth seemed contemptible, and without form or comeliness to them all.
This made the opposition so great, and the labour hard,
notwithstanding it pleased the Lord to reach to the consciences of many,
and many were pricked to the heart, so that they cried out,
"`What shall we do to be saved?`"

God made his ministry very effectual to the conversion of many in the city of London,
whereby a great change was wrought in the hearts of many,
and many hundreds brought to know the Lord their teacher,
which are as seals unto the word of life through him unto this day.
He continued in this city very much at times, between eight and nine years together,
preaching the word of God,
and speaking of the things of his kingdom to all that look after it;
with great watching travail and exercise in the work of the Lord;
and his earnest desire was, that all might have come to know God`'s salvation,
and the redemption of their souls.
His great diligence was known unto many,
that his only rejoicing was in the prosperity of the work of the Lord,
and the increase of faith amongst them that did believe.

His heart was much drawn towards this city,
and oftentimes hath he said to me when sufferings did come for the gospel`'s sake,
which he knew would come, "`I can freely go to that city,
and lay down my life for a testimony of that truth which I have declared through
the power and Spirit of God:`" which in the end indeed came to be his share,
and will forever be his crown,
who loved not his life unto death for the testimony of our Lord Jesus Christ.

In the same year, 1662, being pressed in his spirit to go visit them,
who were begotten unto the faith of God`'s elect at the city of Bristol,
and in divers other counties, he took his leave of them, saying to very many,
"`that he did not know he should see their faces any more;`" exhorting them all to faithfulness
and steadfastness in that wherein they had found rest for their souls.
To some he said, "`I am going up to the city of London again,
to lay down my life for the gospel, and suffer amongst Friends in that place.`"

A little after his return to the city, at a public meeting,
which the people of the Lord have kept these many years,
to hear and speak of the things of God to edification,
at the Bull and Mouth near Aldersgate--by certain soldiers,
under the command of Richard Brown, then General of the City of London,
he was violently plucked down, and haled away in a barbarous manner,
and carried to the guard, and so committed to Newgate; not for evil-doing,
but for testifying unto the name of the Lord Jesus, and for the worship of God;
as though this were become a great crime, worthy of bonds, and at last, death.
He was had to the sessions in the Old Baily, and his accusers were witnesses against him,
and they that had abused him violently,
their testimony was received as good proof against him.

After two or three sessions he was fined by the court one hundred marks,
which at last was reduced to twenty marks, and to lay in prison until payment;
where he continued a pretty long season, about eight months,
with six or seven score prisoners besides, upon the same account;
many being shut up among the felons in nasty places, and for want of prison room,
the natures of many were suffocated and corrupted; till at last they grew weak,
sickened and died.

After relating the circumstances of his sickness and death,
which have already been given in the memoir, he thus concludes:

And after a little season he gave up the ghost and died a prisoner,
and shall be recorded and is in the Lamb`'s book of life,
as a martyr for the Word of God, and testimony of Jesus, for which only he suffered,
and gave up his life, whose death was precious in the eyes of the Lord.
But now he ever liveth with God, and his works follow him,
and his labours shall testify of him in generations to come;
and thousands beside myself can bear witness, his life and death was to the praise,
honour and glory of the grace of God; unto whom be the glory of all his works forever,
Amen.

George Whitehead Says Respecting Him:

As for Edward Burrough, our dear brother and companion in travel,
suffering and consolation for the everlasting gospel`'s sake in his day,
his testimony lives with us.
He was a preacher of righteousness,
and one who travailed for the redemption of the creature from under the bondage of corruption,
and proclaimed liberty to the captives, in the power and authority of God.
Therein he was a true witness against oppression,
and all the antichristian yokes imposed in the night of
apostasy upon the persons and consciences of people.
Truly and valiantly he held forth the liberty of conscience,
and vindicated it to the great men of the earth,
in things appertaining to God in matters of religion and worship,
against persecution and compulsion which had their
original and rise from the power of the beast,
which hath made war against the righteous seed,
that men might be left free to the guidance of the infallible spirit of God,
which is not to be limited in these matters,
and not be compelled or brought under the corrupt wills of men,
nor their fallible judgments nor invented forms in these cases.

The name of this minister of righteousness is written in the Lamb`'s book of life;
and all the enemies of his life can never be able to blot it out,
nor extinguish his memorial.
The remembrance of his integrity, uprightness and sincerity,
hath deep impression upon my heart;
and that tender love and affection in God`'s truth
which he was filled with towards all the upright,
who are lovers of peace and unity in the Lord,
is never to be forgotten by us who are yet remaining in the work of the Lord,
and the everlasting gospel, for which he hath left a glorious testimony,
the glory of which shall never be extinguished,
but thousands shall praise the Lord our God because thereof.

To live, was to him Christ, and to die was gain.
And though in his time many were the sufferings and afflictions which he underwent,
and his upright spirit suffered by,
both from his open enemies and persecutors in the world,
because of his valour and courage for the truth of God,
and from deceitful and transforming exalted spirits, which burden the holy seed;
yet now his life is caught up above them all,
and is out of their reach in the transcendent and unspeakable glory,
in the everlasting habitation of God`'s power, where he hath shined,
and doth shine among the stars that have kept their habitations,
as one that hath turned many to righteousness,
and that hath overcome by the blood of the Lamb and the word of his testimony.
And though he be ceased from his labours, his works do follow him,
which will be had in living remembrance, and precious esteem among the upright.

And they who, in a prejudiced spirit of enmity, are lifted up because of his decease,
are not worthy of him, nor of his testimony.
They have cause to mourn and lament amongst those that have pierced the just,
and slighted and despised the messengers of truth and righteousness,
whom God hath therein honoured;
and God will debase such and their vain glory unto the dust,
and exalt the testimony and life of his faithful witnesses over all their heads.
But we, who have been well acquainted with the deep suffering of the righteous seed,
and with the worth of true unity, in the weighty body and Spirit of Christ,
and therein do behold the glory and completeness of the city of our God,
which is at peace within itself, cannot but prize the ministers of righteousness,
and every member of the same body.
How blessed and precious is the memorial of the righteous in our eyes!
and how deeply is my soul affected with that comfortable communion,
and those many and living refreshments that we have enjoyed one with another,
even with him and others, who have finished their course.

In this I am satisfied, that though we be left in travel,
and our days have been days of affliction and suffering,
for Christ and the gospel`'s sake, as in the world; yet in him,
whom the prince of this world hath nothing in, we have peace;
being come into communion with the spirits of just men, who are the family of God,
written in heaven, and called by one name both in heaven and earth.

George Whitehead.

London, the 12th day of the first month, 1663.

[.the-end]
The End
