== Introduction.

The materials for compiling a life of Edward Burrough are extremely scanty.
His death occurred so early after the rise of the Society;
and at a period when Friends were enduring such severe persecution,
many of them being shut up in prisons,
that it is probable but little care was then taken to collect or
put on record the incidents of his short but laborious life.
It does not appear that he kept any account of himself,
except the few particulars which are scattered through
his controversial or other religious writings.
These, with the scanty materials furnished by incidental notices of him,
in the journals of other Friends of that day, and in Sewel`'s History,
are all that can now be obtained.

From this circumstance the reader will not expect to find a minute or closely
connected biography of this remarkable man--yet with all the paucity of material,
there is enough to form a narrative deeply instructive and interesting.
Perhaps there are few instances on record,
of more full and entire devotion to the cause of Christ and the good of souls,
more fervent zeal, more untiring industry,
more patient and meek endurance of reproach and persecution, than marked his character.

From the day of his espousal to Christ, his course seems to have been straight forward,
never looking back or flinching amid all the afflictions
and sufferings which beset him for the gospel`'s sake.
Bold, ardent, and devoted in pursuing the path of Christian duty,
he was clothed with a dignity and divine authority which made him a terror to evil doers,
while the meekness and gentleness of Christ softened and adorned his whole character,
and qualified him to administer the balm of divine
consolation to the afflicted and contrite mourner.
Cheerfully surrendering every prospect of worldly ease and profit at the call of duty,
he devoted the prime and strength of his days to the service of his Lord,
labouring night and day for the good of souls and the spread of vital religion,
and crowding into the narrow compass of a few years,
a greater amount of labour than is often accomplished in a protracted life.

Undaunted by the frowns and cruel persecution of his enemies,
he never flinched from fines, imprisonment or any species of personal abuse, or violence,
but nobly stood as in the forefront of the battle; and at last,
actuated by that Christian sympathy which is ever ready to share
the sorrows and sufferings of brethren and sisters in Christ,
he repaired to London, during a time of extraordinary severity against Friends there,
and being seized and dragged to jail from one of their meetings,
the pestilential atmosphere caused by the crowded state of the apartment,
soon undermined his health; and he gradually sunk away, in peace with God and man,
a martyr for the name and testimony of Jesus;
exchanging a prison on earth for an incorruptible crown in heaven.
