== Chapter II.

Prior to the year 1654, the religious labours of George Fox,
and of such of his fellow believers as had received gifts in the ministry of the gospel,
and who had been sent forth by the Lord to proclaim
the spirituality of the religion of Jesus Christ,
had been very much confined to the northern parts of England.
George himself had travelled as far south as Leicestershire;
and his earliest female co-labourer in the ministry, Elizabeth Hooten,
had preached the gospel and suffered imprisonment therefor in Derbyshire.
Towards the close of the year 1653, Elizabeth Williams and Mary Fisher,
both from the north, entered Cambridge;
and having faithfully reproved some of the vain and rude students there,
who sought to entrap them in argument, were taken up on a charge of preaching,
and publicly whipped by order of the mayor of that city as "`vagabonds.`"

The sight of the blood drawn from the bodies of these innocent women,
by the lash of the executioner;
their patient endurance of the ignominious and unjust punishment thus inflicted on them;
their prayers for their persecutors, together with their meek rejoicing,
because they were counted worthy to suffer for the name and testimony of the Lord Jesus,
had no doubt prepared the minds of some of the spectators to examine with serious attention,
the principles of that religion, for which they so patiently suffered,
and which yielded such support and consolation, under the cruel treatment they received.
Thus the brief tarriance of these two Friends at Cambridge,
opened the way for the spread of the Truth.
In most of the southern counties of England, the Society was little known at this period,
except through the vague, contradictory and often false reports,
which had been put into circulation respecting them.

In the spring of 1654,
several ministers left their former field of labour in the north of England,
and travelled into the southern counties, publishing the message of life and salvation,
to those who were seeking deliverance from sin,
and longing for a more pure and spiritual religion,
than that held forth by the hireling ministers, and formal professors around them.
Among these ministers was Edward Burrough;
and as the city of London was the field in which he laboured long and abundantly,
it may not be amiss to give some account of the rise and progress
of the principles of Quakerism in that great metropolis.

It appears that the first person professing the doctrines of Friends, who visited it,
was Gervase Benson.
He was there in the autumn of 1653;
and a letter written by him from that place to George Fox and James Nayler, is preserved,
bearing date, ninth month 29th, of that year.
He tells them that he was brought there by the love of God,
and was kept there waiting on the Lord, to do whatever he might require of him;
though he found little among the people with which he could have fellowship,
except a growing testimony in some against the "`carnal actings of magistrates and ministers,
so called.`"
At that time many public meetings were held,
for the purpose of discussing religious subjects.
The different fabrics of religious organizations were shaken to their foundations;
the minds of the people were in a state of great unsettlement,
and many were labouring in their own wills and wisdom,
to construct something better than the old hierarchal structure, with its rites,
ceremonies and expensive priesthood.
To one of these meetings, Gervase Benson went, where there were several ministers,
and members of Parliament.
He found them spending their time in debating questions,
and contending about things which they had not witnessed in themselves.
Becoming dissatisfied, he left them, first telling them however,
that their meetings were for the worse, and not for the better.

A spirit of enquiry concerning Friends, had been awakened in many individuals in London,
about this time, who had heard of their rise,
and of the spread of their principles in the north of England.
With such, Gervase Benson had some service.

It is probable that some person in London had acted for Friends,
in superintending the printing of their works,
before Gervase Benson`'s visit to that city;
for of the books mentioned in Whiting`'s Catalogue, seven were printed in the year 1652,
and twenty-five in 1653.
Most of these, if not all, bear this imprint, "`London, printed for Giles Calvert,
and sold at his shop at the Black Spread Eagle, at the west end of Paul`'s.`"

Towards the close of 1653, Isabel Buttery, with a female companion,
both of them Friends from the north of England, came to London on a religious visit,
where they found a few individuals, who were willing to receive them and their testimony.
Robert Dring opened his dwelling, in Watling Street,
and Simon Dring his house in Moorsfield, for them to hold meetings.
In these meetings, Isabel sometimes spoke a few words;
and thus a knowledge of Friends and of their principles,
began to find its way into the great city,
although this knowledge was confined for a time, to very few.

John Camm who had been travelling through the northern counties,
during the latter part of the year 1653, turned his face southward near its close,
accompanied by Francis Howgill; and they entered London in the first month 1654.
A few days before the end of that month,
they sought for and obtained an interview with Oliver Cromwell, then recently installed,
"`Lord Protector of the Commonwealth of England.`"
They had no personal advantage or favour to seek from him,
but desired rather to admonish him for his own good,
and that he might promote the good of all.
They exhorted him to look to his own condition,
if happily he might be favoured to see his standing,
in the sight of the Lord God of heaven and earth; that pure and holy Being,
who is clothed with power to punish sin, and who will not acquit the wicked.
They bade him take heed to the light of Christ Jesus, in his conscience,
which would guide him in the great affairs of the nation,
as he abode in the fear of the Lord.
Then remembering their brethren who were suffering in various parts of the country,
for faithfulness to their religious principles, they exhorted the Protector,
to use his influence to take off from the necks of the Lord`'s people,
the yoke of oppression.
They assured him, that if his power was exerted to maintain true liberty of conscience,
the Lord would honour him, by making him an instrument of good in England.

Cromwell affected to believe that they desired some
form of religion to be established by law;
but they assured him that they had no such desire; adding,
"`We witness that the coming of Christ in his kingdom, is not by might, nor power,
nor pomp, nor glory from without; nor by any law which is in the will of man.
Our desires are that there should be no law upon the subject of religion,
for it needs no law, to protect it.
Pure religion and undefiled is this; to loose the bands of wickedness,
to set the oppressed free, and to take off every yoke.`"
"`We are none of those who despise government, and defile the flesh;
who pull down others to exalt themselves.
All unfruitful works of darkness we deny,
and seek to advance the government of Jesus Christ alone.
We honour all men in the Lord, and have fellowship with those,
whose conduct is as becomes the gospel of Christ.`"

Cromwell,
then in the fresh enjoyment of that high station which he had long so ardently desired,
and which gave him the power his ambition coveted,
was not disposed to exercise that power in a way that would
give offence to those who had raised him to a kingly height;
and to more than kingly authority.

The rights of liberty of conscience, were then but imperfectly understood,
and as little regarded.
Blinded by prejudice and sectarian attachments,
many were opposed to all liberty of conscience,
except that which tolerated their particular notions,
and considered it only the exercise of a Christian virtue,
to punish men for differing from them, either in doctrine or practice.
Cromwell and some of his adherents,
seem to have had a glimpse of more liberal and Christian sentiments,
and even to have desired a larger measure of toleration; but there were others,
whose good opinion they desired, and perhaps needed,
who entertained widely different views,
and strenuously opposed every indulgence to dissenting consciences,
however sincere and tender.

It is not surprising therefore,
that Cromwell treated the application of John Camm and Francis Howgill,
on behalf of their friends with much coolness,
questioning the authority under which they came to speak with, and advise him.
Finding difficulties in the way of a second interview, on the 30th of the first month,
these advocates for liberty of conscience, each addressed a letter to him,
setting forth their concern for him,
and for the cause of truth and universal righteousness.

We have but little information respecting the ministerial
labours of these two Friends in London,
while there on this visit.
George Fox tells us, that they went to some meetings, "`declaring the day of the Lord,
and word of life, and where it might be found.`"
They however very soon returned to the north; but Isabel Buttery and her companion,
still continued in London,
and a few persons who attended their meetings were
convinced of the truth under their ministry.
From a letter, dated London, fourth month 27th, 1654, written by an apprentice,
Alexander Delamain, it appears that those who were newly convinced there,
of whom the writer was one,
were anxiously looking for and expecting Friends from the north,
who might confirm their faith,
and strengthen their hands in upholding the testimonies of Truth.
He mentions that Isabel Buttery had gone to Westminster the preceding first-day,
"`to some to whom her heart was drawn forth;`" and that on her way back,
she was arrested by order of the mayor, together with Robert Dring`'s maid,
who accompanied her; and that they were committed to Bridewell.
The charge against them, was for letting people have Friends`' books.
Such was the situation of things in London, at the close of the fourth month.
Some of the inhabitants had obtained a little knowledge of Friends, from their writings;
the ministers and magistrates had taken one step against the spread of their principles,
and there was as yet but few persons so convinced of them,
as to make a public profession.
For the most part, the inhabitants of that great city,
knew or cared but little about them, or the great principles of life and salvation,
which they were called to proclaim to the world.

The recently convinced, and the seekers after Truth,
did not look in vain for the visits of Friends from the north.
The Lord soon sent forth his servants into the south of England,
to labour in the ministry of the gospel of his dear Son.
About sixty left their homes, during the fourth and fifth months in this year,
and passed onward, as they were led from day to day, proclaiming the day of the Lord,
and demonstrating with power, the spiritual nature of the Christian dispensation.
Their general course was south, through the eastern, western,
and middle portions of the island.
About the beginning of the fifth month, several of them drew near to London.

We learn from Thomas Camm`'s account of his father,
that Edward Burrough and John Camm were fellow travellers from the north;
and that as they journeyed southward, down through the middle of the kingdom,
they met with John Audland, to whom John Camm joining himself,
turned westward towards Bristol, while Edward Burrough proceeded to London,
where he arrived in the fifth month.
Francis Howgill and Anthony Pearson must have entered the city about the same time.
On the next first-day of the week, which was probably the 8th of the month,
Francis Howgill and Anthony Pearson attended the meeting of the newly convinced people,
which was held at the house of Robert Dring.
Edward Burrough the same day was at a meeting of those called Separates,
which name was given them,
because they had withdrawn themselves from other religious societies.
They do not seem to have settled upon any common ground of religious belief;
and allowed great liberty in their assemblies to strangers and others,
both in preaching and exhortation.

Richard Hubberthorn soon joined the little band of labourers in London;
who in that great city found a large field for the exercise of their various gifts.
Many public stated meetings for religious controversy, with the freest scope;
and many others for religious edification, equally liberal in their character,
were held there in those days.
To both classes of these meetings Edward Burrough found his mind drawn;
sometimes going alone,
while at others he was accompanied by one or more of his fellow-labourers.
They all appear to have been diligently engaged in attending these large public meetings,
or the smaller gatherings of those who made profession with them.
As they thus were led from one congregation to another, among individuals,
many of whom they had never seen before, they were furnished with a word of exhortation,
admonition, entreaty or warning,
adapted to the various states of those whom they found assembled.
Many were reached by their ministry; and not a few were effectually convinced,
so that the meetings held at Friends`' houses, increased in numbers rapidly;
and a great sensation was produced among that portion of the professing religious world,
which was seeking after a nearer acquaintance with God,
and a more sure way to his kingdom.

John Camm and John Audland, after parting with Edward Burrough,
proceeded onward to Bristol, which they entered on the 12th of the fifth month.
On the 13th they held two meetings in that city,
in which they were enabled powerfully to preach the everlasting Gospel,
so that through the effectual assistance of the Lord`'s Holy Spirit,
the witness in the hearts of many people was reached.
John Audland, in company with Thomas Airey, proceeded to Plymouth,
where they left some seals to their ministry.^
footnote:[See the account of Priscilla Cotton in [.book-title]#Piety Promoted.#]
John Camm turned westward to London, where we soon find him banded,
in the fellowship and labours of the Gospel,
with the faithful workmen who had for some weeks been engaged there.

Although these early preachers of the word of life were
generally listened to with respectful attention in London,
yet this was not always the case.
About the 20th of the month,
Edward Burrough and Richard Hubberthorn were at a meeting of the Baptists,
held at a place called the Glasshouse;
where Edward was permitted to unburden his mind freely.
The congregation however, was not equally courteous to Richard.
He may perhaps have given utterance in his communications to some truths,
so disagreeable to their pre-conceived opinions or prejudices,
that they could not very well bear them.
Whatever may have been the cause, they became excited against him,
and forcibly expelled him from their place of meeting.
They had then a few words of dispute with Edward, who soon after withdrew.

Richard Hubberthorn having been thus ejected from the meeting of the Baptists,
joined John Camm, who was that day with a people called Lockers,
whose hired preacher had proved himself to be "`a
hireling,`" by leaving them in order to obtain promotion.
Here our Friends had full liberty to speak,
and they were largely opened to declare the Truth among them.
The same day Francis Howgill and Anthony Pearson
attended the meeting of a religious sect,
known by the name of Waiters.
When they entered the meeting, a man was addressing the company,
but he ceased speaking on seeing them come in.
Francis soon felt the influence of that anointing
which qualifies for labour in the Gospel vineyard,
and a large portion of the work fell to his share that day.
He opened to them the doctrine of the Light of Christ inwardly revealed,
by giving heed to the restraining and directing influence of which,
men would be led to Christ Jesus, and enabled to attain salvation.
When he had finished the testimony then given him to bear,
a man by the name of Rich made a few remarks.
He acknowledged that the Light was '`a guide, and that it led into innocency;
but told them that he looked for a greater guide, which would lead into glory.
This sentiment was not satisfactory to Friends.

The Light which they preached is the Spirit of our Lord and Saviour Jesus Christ,
revealed in the hearts of all mankind, and being himself the Truth,
He leads those who follow Him, out of all error and into all truth,
and not only brings these faithful servants of Christ into fellowship here on earth,
but through the redemption which is in Him,
opens to them a glorious resting-place in the Paradise of God,
in the world which is to come.
This divine Light, therefore,
is not only a guide into innocence and purity of life on earth,
but also a guide to that eternal glory which shall be revealed hereafter in heaven.
Anthony Pearson felt himself constrained more fully to elucidate
the views of Friends on this very important doctrine,
and afterward Francis Howgill and Edward Burrough, who had just joined his friends,
severally added their testimonies to the Truth.
The opportunity was satisfactory,
and at the conclusion they took an affectionate leave of the auditory.

The next point of time at which we can trace these
indefatigable labourers in the Lord`'s vineyard,
was the following sixth-day,
when they attended a meeting for religious worship with
those who were newly convinced of Friends`' principles.
There were now many such in London,
and the hearts of the faithful ministers and fathers in the Truth,
yearned over these with earnest desires that they might
not only be established in knowledge but grow in grace,
and thus be enabled to walk worthy of their vocation whereunto they were called.
On first-day, the 22nd,
Edward Burrough and Francis Howgill were at a meeting held in a large place called Ely-house.
A man, who in the account left us of this opportunity,
is spoken of as the governor of the house, first spoke to the people assembled.
Then a Ranter addressed the company.
While he was still speaking, Edward Burrough,
whose heart was full of deep religious concern on behalf of those present,
rose on his feet.
At the sound of his voice the Ranter ceased speaking.
Edward, though quite a young man,
was clothed with a divine authority which reached the hearts, touched the consciences,
and convinced the judgment, of many who heard him.
When he ceased, the Ranter again spoke; and then Francis Howgill,
in a measure of the same power, which had quickened the ministry of his younger brother,
laboured among them for about the space of an hour.
As he closed, the Ranter being full of that self-sufficiency,
which is the common attendant of those whose religion is more in word and imagination,
than in life and power, appealed to the people to decide,
whether he had not spoken to their consciences,
as thoroughly as Edward and Francis had done.
To this the people with one consent answered, "`No.`" The governor,
indignant at the thought that his own reputation, as well as the Ranter`'s,
had suffered in the opinion of those gathered,
refused to grant the request made by Friends,
for liberty to hold a meeting in the house in the afternoon.

That morning,
John Camm was with a company of people who were engaged
in preparing a new translation of the Scriptures,
for the purpose of making it support certain doctrinal views.
At mid-day these Friends met together, under feelings, no doubt,
of gratitude to the Lord who had strengthened them for their
several portions of service during the morning.
In the afternoon Richard Hubberthorn attended the meeting of Friends;
while Francis Howgill and Anthony Pearson,
feeling their minds drawn to sit with those translators of the Scriptures,
of whom we have already spoken, went to their meeting,
where they had some seasonable service.
Before they left, a dispute concerning some point arose,
and they mutually agreed that all doctrines should be tested by the Scriptures.
Friends were so well furnished by the great Head of the Church with wisdom in argument,
and the memory of apposite texts, that their opposers were confounded.
Edward Burrough was that afternoon at a place of worship in Lombard street,
at which many of the highest professors of religion in the city attended.
Here he sat in silence,
until the priest had gone through his accustomed round of singing, praying, etc.,
which constituted, in the general estimation, the service of a meeting.
Before the priest closed his performance, Edward was joined by Richard Hubberthorn,
Francis Howgill and Anthony Pearson.
The usual exercises of the meeting being now finished, Edward stepped upon a seat,
and in a loud and animated voice addressed the congregation.
There was such sensible evidence of the baptising power of the Holy Spirit,
accompanying the word preached,
that the whole congregation listened to him with quiet attention.
He addressed them about an hour; and when he closed,
his nearly united friend and companion Francis Howgill,
was also permitted to relieve his mind among them.

In the mean time, John Camm was at a meeting of Baptists,
where his mouth was opened to preach the freeness
of the grace and gospel of our Lord Jesus Christ.
In the evening they all met together in sweet unity of spirit,
and closed the day in peace, enjoying the communion and fellowship of the saints,
and the fresh feeling of the Heavenly Father`'s love.
This is a history of one of the many days of faithful and laborious service,
which those ministers of Christ spent in London.

On one occasion they held an appointed meeting on the fourth-day of the week,
in a room in Southwark,
which on first-days was occupied by Anabaptists as a place of worship.
Many of those who usually attended these meetings were present,
and were well pleased with the doctrines which were then preached.
But while these were satisfied, some who had not been present,
found fault with the principles of Friends, and with their fellow-professors,
who had permitted the meeting to be held in their room.
Their preacher, or as he was termed.
Teacher, spread many false reports against Friends,
to which those who had heard for themselves gave no credit.
Dissatisfaction on this account and dissensions arose among them,
which resulted in a secession of many of the flock.

On the 23rd of the fifth month, Anthony Pearson left his fellow-labourers in London,
and returned to his family in Westmoreland.
Writing to George Fox, at the close of this month, he tells him,
that they found many in London, with a true principle of honesty in them.
But, he says, the people of that place,
are "`for the most part so high-flown in wisdom and notions, it is hard to reach them.`"
Trusting in their own strength and attainments, they were apt,
if these were called in question, or judgment placed upon them, to become angry.
Anthony expresses his conviction, that much true wisdom was needful in those,
who attempted to labour among them.
He thinks that the only effectual mode of bringing them to the truth,
would be by reaching, through the convicting power of the Holy Spirit,
the witness for God in their consciences;
and while broken and contrited under its operations, to pass judgment upon them,
and keep them out of disputing and questioning.
"`This,`" he says "`we found the most profitable ministry.`"
"`Few words must be used, for they have the Truth in notions, and all cry out,
'`What do these men say, more than others have said?`' but to bring them to silence,
confounds their wisdom.`"
"`Oh that none might come to London, but those who are raised up into the life of Truth;
who dwell in the living power of God, whose words may have authority:
for there are so many mighty in wisdom to appose and gainsay,
that weak ones will allow the Truth to be trampled on.
And there are so many rude savage apprentices, and young people, and ranters,
that nothing but the power of the Lord can chain them.`"
"`Great is the harvest likely to be in that city.
Hundreds are convinced, and thousands wait to see the issue,
who have the persuasion that it is the Truth.`"
"`Many honest hearts are among the Waiters, and some that are joined to the Ranters,
are a good people.
The living power of God was made manifest, to the confounding of all,
and we were carried above ourselves, to the astonishment both of ourselves and others.
We were made to speak tremblingly among them, in dread and much fear.`"

Edward Burrough in a letter to Margaret Fell, written about this time, informs her,
that "`We were at a meeting of the people called Waiters,
where Richard Hubberthorn spoke about an hour in much power and authority.
Francis was moved to go to an assembly of people called Seekers, and they were,
as all this generation practices,
jangling and contending about the meaning of the scriptures.
He stood silent among them a little, and then spoke the word of the Lord,
in power with boldness an hour or more, and confounded their wisdom,
and crushed their meaning of the scripture.
He said, there were some good people among them.`"

John Audland and Thomas Airey, having fulfilled their visit to Plymouth,
and the west of England, early in the sixth month, came eastward to London.
Here John remained for a few weeks, and as ability from on high was given him,
entered into that extensive field of labour which
his faithful brethren in religious belief,
were so zealously and successfully cultivating there.
It was now past the middle of summer the sixth month old style,
corresponding with the eighth in the new.
At this period of the year, many of the tradesmen and mechanics of London,
were in the habit of assembling in the fields, on the outskirts of the city,
near the close of dry and pleasant days, to amuse themselves in wrestling,
or in watching others so engaged.

One evening as Edward Burrough was passing by,
his attention was drawn to a company of people assembled round an athletic man,
who had already thrown several j competitors, and was then waiting for another.
As no one offered to enter the ring with him,
he seemed flushed with pride at his success, and full of vain glory,
because of that strength and activity of body,
which was given him by his Creator for nobler purposes.
As the wrestler thus stood in the pride of his strength,
with the crowd of admiring spectators around him, Edward Burrough stepped into the ring.
The successful champion looked with surprise at this new opponent,
whose serious countenance and solid demeanor, seemed so little like the usual light,
and unmanly deportment of the competitors, in these trials of strength and agility.
If the wrestler was astonished, the idle gazers around him were not less so;
and they watched with intense interest, to see the result.
But the object of this youthful minister of Christ,
was not to wrestle with flesh and blood.
The weapons of his warfare were not carnal,
though mighty through God to the pulling down of the strong holds of sin and Satan.
He had been redeemed by the effectual workings of the grace of God, in his own heart,
from the spirit of the world, with all its vain pleasures and pastimes,
and he was now enlisted under the banner of the Prince of Peace,
the captain of salvation, in making war with the spirit of antichrist,
and against all the corruptions which abound in the world.
It had become his food and drink to do his Master`'s will; and he felt it his pleasure,
no less than his duty,
to labour to gather souls to Christ--to turn men and women from darkness to light,
and from the power of Satan unto God.

Clothed with authority from his divine Master--after standing a few moments,
he addressed the bystanders in a powerful and awakening manner,
to which they listened with attention and wondering admiration.
He told them that their heavenly Father had not left
himself without a witness in the heart of man;
but had placed in everyone a measure of his grace or holy Spirit,
by which man was at times enlightened to see his fallen condition,
and to feel the necessity of regeneration.
Many of his hearers were deeply affected by his discourse, for he was very aptly called,
"`A breaker of stony hearts; a son of thunder,
as well as a consoler of the contrite in spirit.`"
The labours thus bestowed, in this strangely gathered meeting, was made,
through the divine blessing qualifying the instrument,
and preparing the hearts of the hearers for the reception of the seed sown,
effectual in turning the feet of some of them into the way of peace,
and leading them to a knowledge of the truth as it is in Jesus.
Thus this spiritual wrestler was made victorious in this new arena,
and having been faithful to the requirings of duty,
in thus publicly wrestling against wickedness, he retired from the ring in peace.

Of the inhabitants of London, it might have been said at that time in truth,
"`Many were daily added to the church.`"
Gilbert Latey, was one of these.
He was of an honest, sober life,
and had been earnestly engaged in seeking after spiritual good,
even durable riches and righteousness.
Being informed that some men come out of the north,
were to have a meeting at the house of Sarah Matthews,
a widow who lived in White-cross Street, he went there, and heard Edward Burrough,
who was that day led in his ministry to set forth the free gospel of Christ Jesus.
Being effectually reached by the power and authority which accompanied the word preached,
his heart was opened and prepared to receive with gladness the Truth, in the love of it.
He believed in, and turned to the light of Christ Jesus in his conscience,
and followed its leadings, "`greatly rejoicing that he had found his soul`'s beloved.`"
He was strengthened to take up the cross to worldly honour,
to deny self and the praise of men, and to despise the shame,
which the men of the world are ever ready to cast upon the true disciples of Christ.
Being thus humbled,
and having been made willing to be despised for Christ`'s sake and the gospel`'s,
he was united to the flock of newly convinced Friends in London;
and in due time became eminently useful among them.

The following letter to Margaret Fell,
exhibiting a little of the labours of Friends in and about London,
during the sixth month,
was written by Edward Burrough on behalf of himself and Francis Howgill,
who also signed it.
This will account for the alteration of the singular to the plural pronoun,
which is to be found in it.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
London, 29th of Sixth month, 1654.

[.salutation]
Dear Sister,

Great is our care and charge.
Pray that we may be kept in faithfulness and boldness
in the work of the Lord committed to us,
and that wisdom may guide us to handle the sword;
that we may clearly discern what to spare and what to destroy.
Great is our travail, till Christ be brought forth in this people;
and our suffering is ever with and for the pure seed, which lies in bondage.
We two are constrained to stay in this city; but we are not alone,
for the power of our Father is with us, and it is daily made manifest through weakness,
even to the stopping the mouths of lions,
and to the confounding of the serpent`'s wisdom.
Eternal praises to Him forevermore!

In this city, iniquity is grown to the height, the serpent`'s wisdom is grown fully ripe.
Here are the subtlest serpents to grapple with and war with; but in the eternal light,
which is our shield and buckler,
are they comprehended and their deceits made manifest to us;
and by the light they are judged and condemned.

We have three meetings or more every week, very large,
more than any place will contain which we can conveniently meet in.
Many of all sorts come to us, and many of all sects are convinced, yes,
hundreds do believe; and by the power of the gospel declared among them,
is the witness of God raised, which shall never die.
There are some brought under the power exceedingly,
which strikes terror in the hearts of many; and many lie under true judgment,
and a true life is raised up in many, and the time of redemption is drawing near.
As yet we know little of our departing from here; to all, do we, and shall we,
clear our consciences, and be free from the blood of all men, and finish our testimony.
Many begin to consider of us, and think there is something more in it than a bare notion;
at the first they looked upon it as no more; but it sinks deep inward in many,
for to that we speak, which brings us in remembrance when they see us not.

The last first-day but one, (sixth month 19th), I was at a steeple-house in the forenoon,
and had liberty to speak what I was free, and past away to the meeting in the afternoon.
Last first-day, (26th) Richard Hubberthorn and I went twelve miles out of the city,
to a great meeting of Separatists, to a place called Theobolds,^
footnote:[This is near Waltham Abbey.
Richard Hubberthorn passed on after this meeting to Cambridge, where on the 28th,
he was arrested, and with James Parnell, cast into prison.]
where many great men were, and officers in the army, and such like:
and we had much liberty to let forth ourselves, but at the end,
the heads of them put us violently forth, which many simple minds owned not in them.
The fourth-day of last week (22nd) we had a meeting in Southwark, in a large room,
where some Anabaptists meet on the first-days; several of them were there,
and many hundred people.

Our dear brethren John Audland and John Camm, went from us the last sixth-day,
out of the city towards Oxford, to be there the last first-day, (26th);
our hearts were broken in separating one from another, for our lives are bound up in one,
and we partake of one another`'s sufferings, and of one another`'s joy.
We receive letters every week from the prisoners^
footnote:[These probably were Edward Ogden and Richard Costhorph,
and perhaps there were some others.
Richard was fixed in the place of torture, called little ease.
Besse says, "`It was a hole hewed out in a rock, the breadth across from side to side,
was seventeen inches; from the hack to the inside of the great door,
at the top seven inches; at the shoulders eight inches;
at the breast nine inches and a half.
From the top to the bottom one yard and a half, with a device to lessen the length,
as they minded to torment the person put in,
by drawing boards which shoot over the two sides to a yard in height, or thereabouts.`"
Many Friends, during this year, suffered in this place.]
at Chester.
The work of the Lord goes on gloriously in that county.
There is precious seed there;
and Anthony Pearson writes to us of the like in the county of Bishopric (Durham),
It is ever our reward to hear that the Lord is raising that up in power,
which was sown in weakness: to the Lord be glory, be glory forevermore!

Remember us dearly to all Friends, for we are refreshed in the remembrance of you.
Our chiefest care is, that we may be preserved in obedience, in power and in wisdom;
that the Lord may be glorified by us.
We rest from writing, but continue to be your dearly beloved brethren in the Lord.

[.signed-section-signature]
Edward Burrough

[.signed-section-signature]
Francis Howgill.

--

Edward Burrough and Francis Howgill were still usefully occupied in London.
Those who had been co-workers with them there, had all left them,
and were now labouring in various parts of England,
as the Lord led and qualified them for his work and service.
John Camm and John Audland, after visiting Oxfordshire, passed on to Bristol,
where a rich harvest awaited them.
They held various meetings in that city,
the first of which was on the 10th of the seventh month;
and many were convinced of the Truth under their ministry.

From the following letter, written by Francis Howgill to Robert Widders,
we may gather some further particulars of the labours
of Edward Burrough and himself in London.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
London, 23rd of Seventh month, 1654.

[.salutation]
Dear Brother,

E+++.+++ B. and I stay still in London.
Large is the love of God to us, and the work of the Lord prospers in our hands: eternal,
living praises to Him forevermore.
We are here among this great people in much weakness; and when we see such multitudes,
we are often put to a stand where one might get bread to satisfy so many.
But the wisdom and power of God has been with us, and there are hundreds convinced;
but not many great or noble do receive our testimony.
Yet there are many put to a stand, and brought into silence;
and many are under deep judgment, and a true power.
We have had many great giants to encounter,
but by the power of the Lord the mouths of lions have been stopped,
and our adversaries have been put to flight.--We have been in great
service continually since we came into this filthy place.
Here is the trimmed harlot, the mystery of witchcraft; the devil rules,
and is head in all sorts.

We have been at the most eminent societies in the city,
and we have had strong fightings with them over and over, and at some steeple-houses;
and, but that they have our persons in contempt, they say none speak like us;
but the devil cannot stoop so low.
We have two or three meetings in the week, but no place large enough;
so that we are much put to it.
We have been guided in much wisdom,
so that all them that hate us have nothing to accuse us of,--as of tumult,
or disorder in the least.
Some want to entrap us, but in wisdom we are guided; praised be the Lord!

Miles Halhead and James Lancaster^
footnote:[Miles Halhead and James Lancaster, early in this year,
left Westmoreland to labour in the northern parts of England.
They also visited Scotland; and afterwards travelled south, and entered London,
early in the seventh month.]
were here, and came to visit us.
They stayed one first-day, and so were moved towards Cambridge.
We are much refreshed; we receive letters from all quarters;
the work goes on fast everywhere.
Richard Hubberthorn is yet in prison, and James Parnell, at Cambridge.
Our dear brethren, John Audland and John Camm, we hear from,
and we write to one another twice in the week.
They are near us--they are precious; and the work of the Lord is great about Bristol.

Pray for us, dear brother, that we may be kept in wisdom and power;
that the living God may be exalted forevermore.
My dear yokefellow salutes you.

[.signed-section-closing]
Your dear friend in the work of the Lord.

[.signed-section-signature]
Francis Howgill.

--

Under date of the 2nd of the eighth month, Francis Howgill writes: "`Our burden is great,
we cannot get any separation, +++[+++that is of Friends from others], for the multitude,
and so Friends do not know one another.
We cannot conveniently get any place to meet in, that Friends may sit down.`"

Through the divine blessing on the labour bestowed, many had been convinced,
and several small meetings of Friends were set up about this time in London,
and regularly held.
On first-day mornings,
some of the Friends collected together at the house of Sarah Matthews, widow,
residing in White-cross street;
and in the afternoons of that day they met at Simon Dring`'s in Moorfields.
It would seem that there were meetings also at the houses of other Friends,
and sometimes at Glazier`'s Hall.
Be sides these meetings, some were appointed, in almost or quite every week,
at such suitable public places as could be procured for the purpose.
A great sensation had been made in the minds of the people throughout London.
The convincing power that accompanied the ministry of Friends had produced such results,
that the priests beheld with dismay, many of their congregations leaving them.
The doctrines preached by Friends were not new,
they were primitive Christianity revived in its ancient spirituality;
and the quickening power which attended their ministry,
awakened and aroused the lukewarm,
while it met a ready response from the sincere seekers after truth.
Instead of calling the attention of their hearers
to curious speculations and outward forms and observances,
they directed them to Christ Jesus their Shepherd and Bishop,
who had given them a measure of his Light and grace to profit withal, and which,
as they obeyed and followed it, would lead them out of all evil,
into holiness of life and conduct, and that living faith in Christ Jesus,
as the Redeemer and Sanctifier of his people,
which is the gift of God and the saints`' victory, over the world,
the flesh and the devil.
It is a practical, heart-changing religion,
adapted by Infinite Wisdom for the recovery of man out of the fall,
and for preparing him, through sanctification of the Spirit and a belief of the truth,
for the blessedness of heaven.
