== Chapter IV.

After a few weeks spent in fervent labour in London, Edward Burrough and Francis Howgill,
went out again in the service of their divine Master.
While they were absent George Fox was brought to the city,
to be examined by Oliver Cromwell.
Although nominally a prisoner, yet he was not restrained from going abroad,
and attending the meetings of Friends.
He was as yet a stranger to the great body of the young converts there,
and kept himself much retired, not mingling among them, except at meetings.
The way of this eminent man, was soon open among them,
and they could but take notice of the respectful
deference paid him by the faithful brethren,
his fellow-labourers in the gospel of Christ Jesus, who met him in London.
Many of these had been effectually reached under his ministry,
and having had evidence of the wisdom, that had been given him from above,
they could not but consider him as a father in the truth, worthy of double honour.
This honour was not manifested in flattering words,
which tend to exalt the creature,--but there was a disposition
to hear and observe the remarks he made in social minglings,
as well as in religious meetings;--and Alexander Parker informs us,
that the London Friends, all took notice of one thing; "`if George be in the company,
all the rest are for the most part silent.`"

On the 6th of the first month 1655, George Fox was set at liberty by the Protector,
and about that time, Edward Burrough and Francis Howgill, met him in London.
There were many other ministers gathered there, Edward informs Margaret Fell,
that on the next first-day, the 10th, George Fox was in private with Friends,
that is he attended the small meetings in private houses,
where Friends gathered by themselves.
He adds, "`we two were in the general meeting place,^
footnote:[Probably the Bull and Mouth.]
among the rude world, threshing and ploughing.
The rest of our brethren were that day at several meetings,
some at one and some at another, and some among the Baptists, and gathered people;
and great service there was that day.
Then shortly after that first-day, the brethren separated into the field,
to reap and to gather in.`"
After describing the field of labour, into which several of these brethren had entered,
he continues,

We believe that George Fox will return to this city again;
we two are too few for this service, for truly it is very great;
at present many come in daily to the acknowledgment of the truth.
Friends are so many, that not one place can hold them on the first-days,
where we can peaceably meet, for the rude people;
for since we came they have been very rude,--very often to pull us down,
when we have been speaking.
George was at the great meeting place, two first-days before we came;
and his voice and outward man was almost spent among them.
We have thus ordered it since we came,--we get Friends on the first-days,
to meet together in several places out of the rude multitude, etc.;
and we two go to the great meeting place, which we have,
which will hold a thousand people, which is always nearly filled,
there to thresh among the world; and we stay till twelve or one o`'clock,
and then pass away, the one to one place, and the other to another place,
where Friends are met in private; and stay till four or five o`'clock.

Truly dear hearts, our care is for the whole body,
that all things may be ordered in the wisdom of God,
to the confounding of all our adversaries, who seek for our halting.

The number of ministering Friends, who were now frequently in London,
many of them persons of very small means,
and who could illy afford to bear their own travelling expenses,
furnished an opportunity to their brethren of that city,
for contributing occasionally to their necessities;
yet a care rested on the minds of the travellers, not to be burdensome to any.
Alexander Parker writes, "`We do not lack anything;
here are many precious Friends in this city, who would do anything for us,
or let us have anything, but George Fox is not very free, but rather keeps clear.`"
It is probable that Friends in other places, particularly Margaret Fell,
sent of their abundance to Edward Burrough and Francis Howgill,
for their care in furnishing supplies to the faithful travellers,
who had not of their own.
Alexander Parker says, "`If any are in need, our friends F. and E. supply them.
The charge truly is great, but our desire is to make it as easy as possibly we can.`"

George Fox, who had left London before the middle of the first month 1655,
returned to it again on first-day the 31st of the same month.
Alexander Parker thus writes of the services of that day.
"`We had five meetings, three of Friends that met in silence,
and George was at one of them, where many of the world came in, but were sober.
Francis and Edward were at the great meeting place, where many came to hear.
Gervase Benson and I were at a meeting beyond Westminster,
where there are many convinced:
in the forenoon having such short notice there were not many;
but in the afternoon there came very many, and they were sober, quiet people.`"

Just before the middle of the second months Edward Burrough left London,
and went to Edmundbury in Suffolk, where he was soon joined by Francis Howgill.
They passed on together to the Isle of Ely,
where at the time of the court sessions they had a very favoured meeting.
Here they found James Parnell,
who informed them that the Baptists at Cambridge had challenged him to a public dispute.
Feeling a willingness to be present,
they accompanied him to that place at the time appointed.
It was the 20th of the second month.
The steeple-house had been selected by the Baptists as the most suitable
place for accommodating those who might wish to witness the controversy;
but when the hour came they found it shut.

In the mean time the whole town was in an uproar,
and the scholars as usual rude and turbulent.
The Baptists, finding that James Parnell had two such able assistants with him,
were unwilling to carry on the dispute.
Edward and Francis, perceiving the commotion to increase about them,
with intimations of personal violence,
and no present appearance of the dispute being allowed,
returned to the house of justice Blakeling.
James continued with the Baptists, who retreated to the house of one of their number,
whose wife behaved in a very unchristian manner toward himself and friends,
on which James said, that as she was nothing departed from the old nature,
it was evident she had not been made better by her baptism in water.
Followed by many rude scholars and people, he then returned to a Friend`'s house,
probably the one at which his companions were; and there he preached to the multitude.
The Baptists finding that the common people, and the rough mob were with them,
felt their hands strengthened, and went to the shire-house, in the castle yard,
and sent for James Parnell, who quickly came to them.
The jailer at first would have refused James Parnell permission to enter,
but he at last obtained it.
The multitude now became quiet, and Edward and Francis soon joined their friend.
The Baptists and the Independents, each chose one to represent them,
and the dispute opened.

The Baptists put but one question, which was this,
"`The writings of the Prophets and Apostles, which are called scriptures,
whether are they the word and sayings of the Most High God?
yes or no?
To this James replied, "`The word of God, which is God,
which dwelt in the Prophets and Apostles,
from it they spoke forth the things which are recorded in scripture.`"
The Baptists declared this was no answer,
and finding nothing how they could take hold of it, they after a time departed,
enjoining the jailer not to allow James to speak to the multitude.
James was hustled and abused by the rude scholars,
although the Baptists had been allowed to go away unmolested.
On this he remarks, "`It appears that the world loves its own.`"

Edward and Francis returned to the house of a Friend,
and sending for their brethren in religious profession and some others,
they had a meeting with them in the evening.
On seventh-day the 21st, they had two meetings in the yard of a house in the place,
at which many were convinced of the truth,
even some of those who had been wild and turbulent.
The next day, they were at a meeting previously appointed in the Isle of Ely.
It was large, there being as was supposed, seven hundred persons present.
The father of Cromwell`'s son-in-law Russel, a colonel in the army, who resided near,
sent two priests to the meeting, probably to dispute with them.
But so clearly did the two Friends set forth the spirituality
of the gospel and unfold the way of life,
that the priests were confounded, and had nothing to say.
Their hearts were touched, and on returning to Russel they told him,
the Quakers were far before them.
On this the colonel invited Edward and Francis to his house, where they went,
and had a kind reception.
When the family gathered about them, they were afresh qualified to preach to them,
in the demonstration of the spirit and with power.
Some of those present were seriously affected, and the colonel`'s wife wept freely.

The next day the colonel sent them word,
if they would go to the house of one of the priests,
whom he had sent to dispute with them, who was an Independent,
he would send the priest word, and acquaint his congregation.
This message they received with gladness, and had a satisfactory meeting,
at which were the colonel`'s family, the public preachers of the parish,
and many of the people.
The Lord whom they served was near them by the word of his grace,
and qualified them to speak the truth, with boldness and convincing power.
The priests hung their heads in confusion, but the hearts of the people,
being in measure opened by the Lord`'s good spirit, they greeted the Friends in love.

Early in the third month, we find them once more in London labouring,
with their elder brother George Fox.
On third-day, the 8th of third month,
Edward and Francis had a dispute with "`the chief of the Baptists`" in London,
and the next day with "`two of the chief of the Water Baptists.`"
Of these meetings, Alexander Parker writes,
"`Many of their hearers who are not satisfied, came, and some of our Friends,
and the power of the Lord was over them;
though they are a very wise and subtle generation,
yet the Lord by his wisdom in weak ones, confounds and overturns them.
A great shatter is among all the forms and gathered churches as they are called;
and many are inquiring after the truth.`"

As Edward and Francis were returning from their tour, they addressed from Cambridge,
a letter to James Parnell, which it Would seem recommended him to remember]
the awakened ones in the Isle of Ely.
To this letter, he replied under date of third month 18th,
acknowledging the love which dictated it and the evidence it bore of care and wisdom.
Soon after receiving it, he went to the Isle of Ely, and had various meetings.
At Ely-town many were convinced.
Of Littleport in the Isle, he says,
"`there are about sixty that are brought to meet together, in that town alone.`"
At Soham, he also had an open opportunity of proclaiming the truth to the people,
who received the word gladly, and many were convinced.

On the 21st of third month, Francis Howgill writing to Margaret Fell, says:
"`Pray for us, for our work is doubled,--our care is doubled;
but our strength is also renewed.
The work is great in this city, but even few are fitted for it.
The last first-day, (20th) there were ten meetings in the city,
and the work lies upon George Fox, and us two.
Here are a precious people; they grow up in wisdom and life, and many are added.
All the priests, and all the gathered congregations in the city preach against us,
and are bent in great rage, and print lies, and incense people much.
Edward Burrough and I have ordinarily two public disputes with the heads of them.
They lose their members so fast, they know not what to do;
yet the city is pretty calm and quiet: and wisdom begins to grow among Friends,
and several are moved to go forth in the ministry.
Two young men and two young women are moved to go to Barbados, out of the city.`"
"`Here are many Friends come up about tithes.
There are nearly thirty in the city, and much care lies upon us to order them,
and for the brethren abroad that are in the work of the Lord, or in bonds.`"
"`Our liberty here, is of much advantage to all of the churches of Christ everywhere,
glory be to him that preserves us in his bosom, and under the shadow of his wing.`"

On the 29th of third month, these two gospel labourers left London,
visiting Friends and holding meetings in various parts of Norfolk and Suffolk.
But little account of this journey has been preserved.

Oliver Cromwell, now Protector of England,
was conscious that the standing he had assumed,
could only be maintained by skill and energy.
The Presbyterians were dissatisfied with him,
as well as the Episcopalians and Roman Catholics;
and the Independents themselves were not hearty in his support.
They were zealously attached to a republican form of government,
and Oliver gave evidence of an intent to assume monarchical powers,
even if prudence should deter him from taking on himself a kingly title.
In this situation he displayed his customary vigour of mind.
It would be foreign to this work, to trace the manner in which he quelled insurrection,
and secured and increased his power.
But one of his acts, intended to support his usurpations,
occasioned much suffering to the Society of Friends.
With the sanction of his council, he issued a proclamation, directing that an oath,
abjuring "`Popish supremacy,`" should be required of the people of England.
While George Fox, Edward Burrough,
Francis Howgill and other concerned Friends were in London,
during the early part of the third month, this year,
they prepared "`a declaration against popery.`"
This was intended to show,
that though they could take no oaths to evidence their feelings,
they were yet opposed to all popery, popish rites and observances,
whether found in the church of Rome, or in those called reformed churches.

This declaration commences with showing, that the people of God, in scorn called Quakers,
could not swear, because they observed the doctrine of Christ Jesus and his apostles,
who said, "`swear not at all, neither by heaven, neither by the earth,
neither by any other oath; but let your yes be yes, and your no no,
lest you fall into condemnation.`"
It then stated,
that they denied and condemned all popish ways and supremacy over the Catholic church,
and in confirmation of this condemnation alluded
to the many Friends who had suffered in England,
under laws made to protect the Jesuits, crucifixes and images,
which laws the priests of nominally reformed churches, now kept as their guard.
They bear a decided testimony against that power in England,
which would force men`'s consciences, either to take oaths,
or to conform to their outward established ordinances.
"`Bread and wine, say they, are carnal; which our Lord Jesus Christ`'s body is not,
but is precious.
He saw no corruption, and is a mystery, which bread and wine are not,
let them consecrate them ever so.`"
"`We deny the sacrament, for we know there is no scripture for it.
The Lord`'s supper is not carnal.
He will make his abode with us, and sup with us.
His body is glorious, and not beggarly elements, as outward bread and wine.
This is the blood of Jesus, which washes away our sins;--and this is the body of Jesus,
which makes us free from the law.
So we do deny and condemn all that worship, that sacrament of elements of bread and wine,
and that supper which stands in those things.
We witness Christ to be come, who is the sum and substance,
and need not have a remembrance of any element.
We which be dead with Christ, live in his life, out of the beggarly elements.
Again, we deny that there is any purgatory, and declare against it,
knowing the blood of Jesus, which cleanses from sin; and him who takes away our sin,
and destroys the works of the devil.`"
"`We do deny all their consecrated host, crucifixes and images,
and they are not to be worshipped.`"
"`We declare against the Papists, and them which say salvation is to be merited by works,
for then it is not of faith in him, who was not born by the will of man.
We deny the word merit, and know that man does not attain anything by his will.`"
"`Who are in Christ, are new creatures.
To them there is no condemnation, who walk not after the flesh, but after the spirit.
So everyone shall have a reward according to his works, whether they be good or evil.`"

After warning the people of England against persecution,
and giving two instances of suffering for not swearing,
they sum up the declaration by saying, they deny "`the Pope,
and his supremacy and authority over the Catholic church in general,
and over every one of themselves in particular.
And do believe and know,
that there is not any transubstantiation in the called sacrament of the Lord`'s supper;
or in the element of bread and wine, after consecration thereof by any person whatsoever.
They and every of them, the people of God called Quakers,
do believe and know that there is not any purgatory: and that the consecrated host,
crucifixes or images, ought not to be worshipped,
neither that any worship is due to any of them.
They and every of them also believe and know, that salvation cannot be merited by works,
and all doctrines and affirmations of the said points,
we do renounce and witness against.
They do deny all equivocation, mental reservation, and secret evasion whatsoever;
speaking the words of truth in plainness by the help of God;
and in so doing are persecuted, stoned, stocked, mocked, reproached and imprisoned,
by those who cannot endure plainness of speech; who are equivocators, mental reservers,
and secret evaders.`"

Anthony Pearson,
Gervase Benson and Thomas Aldam took a copy of this
declaration and presented it to Oliver Cromwell,
on the 28th of the third month.
They told him that though the oath of abjuration was given forth for Baptists to take,
yet many corrupt justices, knowing that Friends could not swear,
would make a spoil of them, by tendering it to them.
Oliver replied, "`It was never intended for them: I never so intended it.`"
He was very moderate in his demeanor towards the Friends,
and promised to read the papers they brought.
