== Chapter V.

On the 10th of the fourth month 1655, Edward Burrough felt an impression on his mind,
that it would be right for him to pay a religious visit to the inhabitants of Ireland.
By a memorandum he made on the occasion, it appears,
he received a promise that his life should be preserved,
although he was required to give up that and all things else,
to the keeping of him who was calling him to this field of labour.

On the 30th day of the month,
he submitted himself to the will of his divine Master in this matter, and at that time,
he knew not that his friend Francis Howgill was under a like concern.
It was however in the ordering of the Lord, that these two Friends should perform,
at least part of this service together.
He had caused a similar concern to take hold of the mind of Francis Howgill,
to whom he gave an inward assurance that Edward Burrough should accompany him.
The prospect thus clearly opened to both was soon afterwards entered on.
Francis Howgill came to London in the fourth month,
where he probably found Edward Burrough.
A great change had taken place in the condition of Friends, throughout England.
Persecution had arisen almost everywhere,
and most of the active ministers were now in bonds.
To use the language of F. Howgill, "`our army is most scattered and broken,
and cast into prison.
I know none almost at liberty but George Fox and Alexander Parker, Edward, I and Gervase;
except John Stubbs and William Caton, John Wilkinson and John Story,
and it is likely they cannot be long out; yet truly the power of the Lord is over all.
The work of the Lord is great, and goes on fast,
notwithstanding ail the rage of the heathen.`"
"`Edward Burrough is gone to Edmondsbury,
I shall take care for the supply of Friends in these parts, while I am here;
and truly I fear, lest the burden should be heavy upon the north,
for the charge is great, and our camp great.`"
Having received a packet of letters to deliver, from Margaret Fell, he writes to her,
"`those to Oliver Cromwell are both delivered into his hand,
but he is full of subtlety and deceit; will speak fair, but he hardens his heart,
and acts secretly underneath.`"

The two travellers intending for Ireland, took Swarthmore in their way,
that they might be refreshed with Margaret Fell`'s company.
From there they went to Warrington, where on the 8th of fifth month,
they had "`an exceeding great meeting.`"
Going to Chester they visited the prisons and stayed one night in the town.
They sailed the next day, but had a tedious passage of two days,
the wind being at first contrary, and afterwards but light.
On fifth-day the 12th, they had a meeting at Dublin, in the house of a captain Rich,
and on the following first-day, at the residence of a captain Alan.
Many persons attended and were quiet listeners.
F, Howgill says of the captains, "`they are loving, but there is not much in them.`"
Edward Burrough went several times to the house of Deputies and spoke to Fleetwood,
who was moderate with him.
They had pretty full meetings on first-days, but say of the inhabitants of Dublin,
"`they are a careless, dissolute, proud people.`"
Beneficial effects however appear to have attended their labours in that place,
some of their hearers being convinced of the truth.

Soon after arriving in Dublin,
Edward addressed the following epistle to Friends in London;

[.embedded-content-document.epistle]
--

[.letter-heading]
A General Epistle to Friends in London.

My dear beloved friends and brethren, in the everlasting unerring truth,
of which you are made partakers, who are called of God to be witnesses of his name,
and of his truth; with my dear love I do salute you, dearly and tenderly,
and all the rest of the begotten of God, in that city, whom my soul longs after,
even for your growth in the inward man.
The everlasting Father strengthen you,
and refresh you with the living streams from his presence;
and his love and power and grace, be multiplied among you,
unto whom he has opened a door, and made an entrance into the true rest,
which remains for you, unto which the Lord of glory is gathering you, and leading you,
and carrying you as lambs in his arms, into the fold of everlasting refreshing.

My dear hearts, walk worthy of the love of God, with which he has loved you,
and let your lights show forth into the world, that your good works they may see,
who watch over you with an evil eye.
Dear friends, to you that believe, he who is the light of the world, is precious.
Therefore in the light wait, that your understandings may be opened,
and your feet prepared to walk in the ways of the Lord,
which to all the children of light are pleasant ways.
Be not entangled with any yoke of bondage,
which may burden you from running the race that is set before you;
but in the death of all that is mortal stand,
and there the life of immortality you will see and witness,
and the daily food you will receive,
to that life which the love of the world does crucify.

Do you not know that the friendship of this world is at enmity against God;
but you are called not to serve the world, but God, who is the light,
and the world must serve you; so take heed lest your affections, and desires,
and hearts be drawn aside from the pure way of life into that which is visible,
which will not endure forever; for that life is death, and that glory is shame.
In the light I read you,
and do behold many pleasant plants springing up in the garden of God;
and I bear you record, some of you have laid your crowns down at the Lamb`'s feet,
and have scorned the glory of Babylon and Egypt; surely your reward will be everlasting,
and your cups will the Lord fill in the sight of your enemies,
and your glory shall be above the glory of the earth,
and your crowns shall never wither.

Therefore press on, and look not back, spare not the fat, nor the best from slaughter,
but to the sword bring all your enemies, which have been they of your own house,
which have prevailed over you; but now the Lord is arising among you,
and you have seen the shaking of the earth, and the heavens,
and of the darkness of the sun, and of the felling of the stars;
therefore wait to the end, that the crown of immortality you may wear.
The day begins to dawn among you, therefore put off every work of the night,
and walk all in the day; for you are the light of the world, and a city set upon a hill,
which cannot be hid.
The Lord prosper you, and preserve you, and be with your spirits, and establish you.
Amen.

[.signed-section-signature]
Edward Burrough.

[.signed-section-context-close]
Dublin, the 14th of the Fifth month, 1655.

--

After they had been about three weeks in Dublin,
Francis Howgill felt a concern to travel to the south-west,
believing there was religious service for him in that part of Ireland.
He writes, "`But now, my beloved yokefellow and I must part,
who have borne the yoke so long together,--the cross is great,
in so strange and barbarous a nation; yet it is not so great,
as if any other had parted us:--in the will of God we are.
I am moved to go a hundred miles west in the nation towards Cork;
there is a service and a people to be gathered that way; and at Kinsale,
and Bandon-bridge, at the end of the land.
Edward Burrough must stay here, for this city we cannot leave yet;
but I am given up to lay down all for Him, who has made me a conqueror;
glory unto Him forevermore.`"

In the latter part of the sixth month, or the 1st of the seventh month,
Francis departed from Dublin, being accompanied by Edward Cook,
a cornet in the Protector`'s own troop.
Edward was an inhabitant of Bandon, but had been convinced at Dublin,
under the ministry of these two Friends,
and now he was willing to do what he could towards furthering their gospel labours.
Perhaps in going with Francis to the south,
he might have had a view of drawing him to his own house at Bandon,
in hopes that his beloved wile might also be led thereby
to a knowledge of what he now considered the truth.
Whatever his views were, it pleased the Lord his Saviour,
to grant that his wife also might have her spiritual
eyes anointed to see things as he saw them.
Both of them were afterwards faithful sufferers for the truth.

Edward Burrough remained in Dublin, and soon after his companion left him,
he thus wrote to Margaret Fell;

[.embedded-content-document.letter]
--

With heaviness of spirit, I write unto you, yes, and with my eyes full of tears;
for I am separated outwardly from my dear beloved brother Francis Howgill,
who was my right-hand man in the war, before whom many Philistines have fallen.
And truly when I consider what the Lord has done by us, my heart is rent and broken.
Many glorious days we enjoyed, and many pleasant hours we had together,
in dividing the spoil of our enemies; for our hand was always strong in battle,
and our ensign was lifted up above our enemies,
and even thousands have fallen on our right hand, and on our left.
But according to the will of God, we are now separated;
he into the west of this nation one hundred or six score miles from Dublin,
where I must stay a season, for ought I see, and truly under great suffering,
for few are here that hunger after God, and blindness and deafness have possessed all.
Little Elizabeth Fletcher,^
footnote:[Elizabeth Smith afterwards arrived in Dublin,
and joining company with Elizabeth Fletcher,
they then went out into various parts of the country,
labouring successfully as they found ability, even amid much oppression and abuse.]
is at present here, but I know not how long she stays; her dear love is to you,
and to all the flock of God.
Truly I suffer for her, she being as it were alone,
having no other woman with her in this ravenous nation,
where it is very bad travelling every way a foot, and also dangerous;
but we are much above all that.
If it were the will of the Lord, that any woman were moved to come over to her,
it might be serviceable.

I was glad that Francis Howgill, had so good an opportunity of passing on his journey;
he went with a cornet and some others, who were very loving to us,
and came to meetings while they stayed in the city.

Let your prayers be to the everlasting Father for us,
that his dread may go along with us, over all.
As you can, at opportunity, write to us, it will make me glad;
the face of one Friend would rejoice my soul.

--

[.offset]
In a postscript he adds,

[.embedded-content-document.letter]
--

Here is a Friend come from England since I wrote this, from Oxford,
who says he was moved to come, and I believe it.
I am refreshed by him.

--

This Friend from Oxford was without doubt Thomas Loe.
Edward Burrough was diligently employed in Dublin, in waiting on his ministry,
and writing to his friends and others.

In a general epistle to his brethren in England, written while in that city, he says:

[.embedded-content-document.epistle]
--

[.letter-heading]
To the Camp of the Lord in England.

To all you called, chosen and beloved of the Lord,
who are of the circumcision made without hands, of the seed of Abraham,
who are Jews indeed, not after the flesh, but in the spirit;
unto whom belongs the everlasting promise and covenant, which God has,
and is fulfilling in you, and establishing with you.
We your fellow citizens of the heavenly Jerusalem, which is the mother of us all;
and of the same body, and of the same seed, and same birth,
begotten and brought forth by the immortal word of life, which lives forever,
do send greeting, and do embrace you in the arms of our Beloved, who is, and is to come,
God blessed forever.
You who are called Quakers, who are so, not only in word, or in show,
but in life and in power; whom God has called and chosen to place his name in,
and to take up his habitation among, above all the families of the earth;
the tabernacle of God is with you, his dwelling place is among you,
and among you is God known, and his name is great in your assemblies.

We who are of the same root and offspring, do bring in our witness,
and do set to our seal, that God of a truth is with you, and among you;
and he is the God of the living that answers by fire.
He is the I Am, and there is none besides him, the first and the last,
the beginning and the end of all things.

Praise him forever you redeemed of him; lift up your heads, your Redeemer is come;
clap your hands, and shout for joy,
and let the everlasting praises of God be in your mouths forever and ever.
Exalt his name above all gods, and glorify him in the sight of all the heathen,
and let his marvellous works stand upon record from generation to generation.

Wonderful has his work been among you, and that my soul knows right well;
you that were scattered in the cloudy and dark day,
and were a prey for the wild beasts of the forest,
and were driven away as lost sheep in the wilderness, has God gathered into the fold,
to lie down by the springs of living water in fat pastures forevermore.

Your bread is sure, and your water never fails; a feast of fat things is made unto you,
of wines well refined; the Lord is become the lot of your inheritance,
and the portion of your cup forever.

Your crowns have you laid down at the feet of the Lamb,
and your lives and liberties have not been dear unto you; and let this never repent you,
for now the Lord will exalt you, and crown you with immortal glory.

The everlasting Day-star is risen among you, which gives light unto the nations;
and the light of the sun is as the light of seven days;
and there is no need of a candle in your dwelling, but the Lamb is the light thereof;
fair as the moon, clear as the sun; yes, it is he which was dead and is alive,
and behold he lives forevermore.
Praise him all you people, praise him you holy host;
let all that has breath praise him forever.
Who can express his noble acts`'? And who can declare his wondrous works?
Oh, my soul is ravished, and my heart is overcome! let me speak, that I may be refreshed,
and let me declare his wonders among all people.

The Lord is our king, our judge, our lawgiver, and our rock of defence.
Just is he in his judgments, who has avenged us of our enemies; mercy and judgment meet,
righteousness and peace do embrace each other.
Rejoice forevermore you saints of the Most High, and tell it to your children,
that they may tell to another generation what the Lord has wrought among you,
and what his hand has brought to pass.
Salvation is come, and plenteous redemption,
and the dead has heard the voice of the Son of God, and lives.

Let sorrow and mourning flee away, and be comforted you that have mourned,
and be refreshed, you that have been weary; for God has opened the everlasting fountain,
and the streams run pleasantly, which refresh the city of our God.
He is come and his reward is with him, even he for whom we have waited; this is he,
who is our life, our peace and our exceeding great reward.
The light of the world is our Saviour, but the world`'s condemner; our peace,
but the world`'s torment.
Glad tidings, glad tidings!
The acceptable year is come; praise the Lord you sons and daughters of Zion;
beautiful is your dwelling place, and abounds with pleasant fruit,
for you are dug and pruned and enclosed, a garden of lovely branches.

Let the wonders of the Lord never be forgotten,
nor his works pass out of your remembrance, for he has wounded and healed,
killed and made alive, raised the dead and slain the living,
brought out of captivity and bound with chains, gathered and scattered,
brought low and exalted, saved and condemned.
All this has your eye seen, and your ear heard;
and the heavens and the earth have been burned as a scroll,
and the indignation of the Lord you have borne: but the winter is past,
and the summer is come, and the turtle dove,
and the singing of birds is heard in our land.
O magnify his name forever.

You are made vessels of honour wherein the everlasting treasure abides,
which never waxes old.
The voice of the bridegroom is heard among you, and how can you have any more sorrow?
Instead of weeping, rejoicing; and instead of heaviness of heart,
fulness of everlasting joy.
The Lord has fulfilled his promise and made good his word,
and his law and covenant is with you.
From you does the law go forth, and the powerful word of life,
and death sounds out of your dwelling, and you are God`'s witnesses,
to testify of him in the presence of all nations, some of you by suffering,
and some by declaring.
Oh endless love, and life, and riches!
An eternal crown is upon your heads, and your suffering, which has not been a little,
is not worthy to be compared with the glory that is and shall be revealed.
I speak to you who have an ear to hear.
My soul is comforted in you, in the midst of my burdens and sufferings,
who am separated from you outwardly,
yet joined and united to you by the spirit which is unlimited,
which does comprehend all nations.
I behold your beauty afar off, and my heart is ravished with it, and I am sick of love:
let his works praise him forever, which he has wrought,
for his dwelling is with you in the light, unto which no mortal eye can approach.

The new Jerusalem is come down from heaven, and no unclean can enter;
but you are made white with the blood of the Lamb, and purged as silver,
and purified as gold in the burning; and unto you an entrance is given,
and the way is prepared, and the marriage of the Lamb is come,
and his wife has made herself ready, and the way of the Lord is pleasant to you,
and his commands are not grievous.
No unclean thing can pass over, no lion`'s whelp can tread therein,
but it is called the way of holiness, where only the ransomed of the Lord do walk;
even your mountain is established upon the tops of all hills,
and all nations shall flow into it.
Sing praises forever, for the kingdom of endless peace is come,
which passes understanding, and of glory which no mortal eye can behold,
and of life which no flesh can live in.

Oh my beloved, come up here, and I will show you what God has done for you.
He has rebuked the sea, and driven back the floods of waters which compassed you about,
and he has scattered your enemies with a whirlwind,
and he has given you to feed upon the flesh of kings, and of captains.
Can you call to mind the doings of your God, and his marvellous works brought to pass,
and not cry out in praises forevermore.
O drink and be refreshed, and eat and be satisfied forever,
and let your soul delight itself in fatness; the planting of the Lord you are,
and his own purchased possession.
He has separated you from the world, and has called you out of kindreds,
and you are the royal seed of the offspring of the Lord Almighty,
and all nations shall call you blessed.

And you north of England, who are counted as desolate and barren,
and reckoned the least of the nations, yet in you did the branch spring,
and the star arise, which gives light unto all the regions round about.
In you the Son of righteousness appeared with wounding and with healing;
and out of you the terror of the Lord proceeded,
which makes the earth to tremble and be removed;
out of you did those come forth in the name and power of the Most High,
who uttered their voices as thunders,
and laid their swords on the necks of their enemies,
and never returned empty from the slaughter.
Though I be as by the waters of Babylon, in a strange land;
and as a pilgrim and stranger, destitute but not forsaken; as dying but behold I live;
yet if I forget you, let my right hand forget her cunning,
and let my name be blotted out of the book of life.
O how I love the holy seed, which in my eye is precious!
No man can hinder my boasting of you,
for I am sealed among you in the record of eternal life,
to be read among you in the light where I am known to you,
and where my unity stands with you in the love and life, which never changes,
and you are my mother, and my brother and sister, who do the will of my Father.

Our God is a consuming fire, and his habitation is compassed about with dread and terror.
The heathen shall see and fear, and the inhabitants of the earth shall tremble.
Our God is everlasting burnings, and it is tempestuous round about his throne,
and he reigns forevermore; and though you be despised and set at naught,
and counted as the off-scouring of all things, and the scorn of the heathen,
yet your King reigns upon mount Zion, and if he utter his voice, all flesh shall tremble.
Before him your adversaries shall fall, and your persecutors shall be confounded,
for you shall never be forgotten of your God, but with his arm will he defend you,
and compass you about, and your seed shall be increased.
You, Jerusalem, shall be made the praise of the whole earth,
for among you is laid the sure foundation, and the tried stone,
Christ Jesus the light of the world, in whom you have believed,
which unto the nations is a stumbling stone; but unto you precious.

Bring in your testimony, and set to your seal; is there salvation in any other,
but in him who is the light of the world?
No, there is no redemption wrought but by him, nor any deliverance but through him.
His is the kingdom, the power and the glory, and he is become all in all.
You are no more of this world, but are of the chosen generation,
and of the royal priesthood, a people redeemed,
unto whom there is none like among the thousands of Israel and Judah,
whose God is the Lord, whose Saviour is the prince of righteousness,
who covers your heads in the day of battle, and smites your enemies in the hinder parts;
and wounds them in the fore-head.

And now my beloved, let his name be had in remembrance forevermore,
and let his praises be declared throughout ages to come,
and walk worthy of his everlasting love,
with which he has loved you more than your brethren.
Let his name be exalted by righteousness, by purity, and by a blameless life,
and bring forth the fruits of righteousness and peace,
and let your light shine forth into the world, and your good works abound plentifully;
for you are as a city set on a hill, and as a lighted candle to shine abroad;
and are created unto good works.
Let faith, hope, love and unity, be increased among you;
and let mercy and judgment and equity flow down and be established forever;
never to be removed.
Let joy, long-suffering, meekness and temperance spring out;
and be you perfect as your heavenly Father is perfect.

Stand upon your watch tower, and be not shaken nor drawn aside to follow any other gods,
nor to bow to any image, nor join yourselves to strangers.
Mingle not with the adulterous generation; neither take, nor give in marriage with them;
but keep yourselves from the idols of the heathen.
Be not defiled with them; but abide in your strength, you know where it lies,
by which you may work good, and be preserved from evil;
and you need not that any man teach you, for you are taught of God,
and are far from oppression.

You children of light, worship your God forever, who is light,
and in him is no darkness at all, who is the same and changes not,
whose mercy endures forever.
Be followers of the Lamb as undefiled virgins,
and let your soul scorn the glory of Babylon and Egypt forever; for you are not your own,
but are bought with a price, no more to serve yourselves,
but the Lord of Israel forever.

And you false prophet, which have deceived the nations,
and scattered the inhabitants thereof, and built by fraud,
and daubed with untempered mortar; your judgment is past upon your head already,
and the decree of our God is sealed against you;
your smoke shall ascend forever and ever; and of your sin there is no forgiveness,
and of your torment no remission.
Over you we do, and shall forever, rejoice and sing, and over your god and your king,
the dragon that old serpent; cursed be he and his memorial forever.

You lambs of the true Shepherd`'s fold, with whom my soul rests,
whether ever I behold you outwardly, yet my heart is with you, and I am one of your fold,
and I lie down with you under the shadow of the rock,
upon the mountain which the beast cannot touch, where we are safe from all our enemies,
and am to you well known, to be read in your hearts,
in the record of the Lamb`'s book of life, and known only to the world by the name of,

[.signed-section-signature]
Edward Burrough.

--

It was, perhaps, toward the tenth month before he felt released from that city.
He appears first to have gone to the north, and then to the south and west,
passing through Dublin, and spending two weeks there on his way down.
At Kilkenny he spent sixteen days, labouring among the inhabitants generally,
and being twice among the Baptists.
He says, "`a few in that city received our report.`"
Passing on to Waterford, he writes at that place,
"`Our service lies only in great towns and cities;
for generally the country is without inhabitants,
except bands of murderers and thieves and robbers,
which wait for their prey and devour many; from which yet we are preserved.
I had great opposition in this city; five times opposed by the rulers who are Baptists,
and once was I tried for a vagabond, and once examined by them for a Jesuit;
but to this day, out of snares and plots am I preserved,
and walk as a bird among fowlers`' snares, and as an innocent dove which has no mate; no,
none unto whom I can open my cause, but the Lord my God only.`"

On the 5th of the eleventh month, writing from Waterford to Margaret Fell, he says,

[.embedded-content-document.letter]
--

[.salutation]
Sister beloved, whom I forget not, but do remember with kindness,
and of whom I am not forgotten.

We are joint heirs of the incorruptible inheritance of the Son,
who in us lives and works of his own will; in whom we are what we are,
and by whom we do what is done; to Him we give his own, glorifying Him with his own,
world without end.
Though far distant from one another,
yet my love is hereby increased unto all the children of light;
with tears rejoicing in the unity of the Spirit with you all,
who am to you a brother and companion in the kingdom and patience of Jesus Christ,
and in labours and sufferings more abundant; but as in suffering with Christ I do abound,
so my joy by him and consolation in him are increased also.

I have not long heard from my chiefest companion F. H.,
whose love in the same measure salutes you with mine.
It is now four months since we parted at Dublin,
and what I have said in respect of suffering and trials, he can seal the same with me;
who have been companions in tribulation and in patience,
and are now in joy and rejoicing; hoping to receive the end of our labour,
and to see the travail of our souls,
that we may bring in the sheep with us unto the fold,
and may return to our camp with victory from our Lord.
We have not spared to wound on the right hand and on the left; and victory, victory,
has been our word of watch.
Though this nation be as a heath in the desert, yet there is a seed and a remnant,
for whose sake we are sent.
Seldom have I heard from him since we parted at Dublin.
He is about Cork and Kinsale and Bandon, sixty or eighty miles from this place;
and he has written for me to come that way, if I had freedom, for there was service.
But yet I have not had freedom to leave these parts,
for here is a harvest and but few labourers; and a war is begun in this nation,
and but very few on our part to manage it.

Our dear sisters Elizabeth Fletcher and Elizabeth Smith are also in the west,
valiant for the Truth; and some from London arrived at Dublin,
who are going into the north of this nation.
Of all our work and labour, which is doubled upon us since we parted,
have we a reward into our bosoms; and herein will our joy be more enlarged,
to hear how the war prospers in that nation.
Write and let us know, that we may partake with you in your rejoicing;
and assuredly you may praise the living God on our behalf.
Here is a great lack of books in this nation,
which might be very serviceable in spreading forth the truth.

--

In the tenth month of this year, a company of priests in the south of Ireland,
finding that many of their flocks were leaving them,
went to Dublin to obtain some remedy from Henry Cromwell and his council.
At their suggestion a warrant was issued,
ordering the magistrates to send "`all that are called Quakers`" to Dublin.
A copy was sent to the governor of Kinsale, and another to colonel Phayre,
governor of Cork, and it would appear other magistrates besides were furnished with them.
Phayre was convinced that Friends were true Christians,
and he declared that more good had been done by those who were then there,
than "`all the priests in the country had done for a hundred years.`"
He had no mind to meddle in persecuting them,
and supposing that he would be able to protect them against other magistrates,
he sent a letter privately to Francis Howgill, who was at Kinsale,
desiring him to come to Cork.
The magistrates to whom the warrants were addressed were not desirous of acting,
and one called major Stoding was turned out of his commission, for refusing to obey it.
Many Friends were now imprisoned in Dublin,
and a spirit of persecution seemed spreading through the land.
Yet at Cork and Kinsale the men in authority continued generally favourable to Friends,
and many officers of the army attended their meetings.

In the eleventh month Edward Burrough went to Cork,
where he and Francis Howgill once more joined company.
From Cork they went to Limerick, accompanied by James Sicklemore and Edward Cook.
They reached that place on a seventh-day of the week.
The next day they were not permitted to speak in the public places of worship,
and on second-day they were expelled the place.
As they rode along on horseback Edward Burrough preached to the people,
and after they were out-side of the gates,
he had an opportunity of addressing a great multitude.
His three companions each spoke a few words, directing the hearers "`to Christ Jesus,
a measure of whose light was given to everyone to profit withal,`"
and a number of persons were convinced that day.

They also visited Kinsale, where among other fruits of their labour, Susanna Worth,
wife of the priest Edward Worth, who was afterward Bishop of that place, was convinced.
For her obedience to her conscientious convictions
she suffered much at the hands of her husband,
but remained a faithful Friend until her death.

Edward Burrough and Francis Howgill returned to Cork in the twelfth month,
where they were arrested by the high sheriff of the county,
under a special order from Henry Cromwell and his council.
They were taken by armed men from garrison to garrison, until they reached Dublin,
having had many opportunities by the way, of preaching Christ to the soldiery and others.
In Dublin they were committed to the care of Mortimer, the sergeant at arms,
in whose house they had a large chamber allowed them,
where none of their friends were hindered from visiting them.

They arrived at Dublin about the 20th of the twelfth month,
and being brought before Henry Cromwell and his council, they were examined,
but no charges of any kind were brought against them.
They answered with freedom the questions put to them, and Edward Burrough says,
"`Mighty was the power of the Lord with us, to the confounding of our enemies.`"
Although no cause of imprisonment could be proved against them,
they were kept in close confinement, until forcibly banished from the island.
While in confinement, Edward wrote various addresses, one of which entitled,
"`The unjust sufferings of the just declared,
and their appeal to the just witnesses of God in all men`'s consciences,`" is here introduced,
which is as follows:

[.embedded-content-document.address]
--

[.blurb]
=== To all you colonels and commanders and officers, and to all the honest-hearted in the city of Dublin and elsewhere, to whom this may come.

Hereby,
we the prisoners of the Lord for the testimony of
Jesus and for the exercise of a pure conscience,
do lay down our cause before you; and to the light of Jesus Christ,
in all your consciences, we appeal in this our cause of righteousness and innocency,
to be judged thereby.
We are men fearing God, and working righteousness,
and are friends to the commonwealth of Israel,
and are exalters of justice and true judgment in the earth,
and are subject to all just power, and every just ordinance of man for conscience sake.
We have suffered the loss of all, and have borne part of the burden with you,
that we might obtain the freedom of the righteous seed,
and the liberty of tender consciences, to serve the Lord in his own way.

We are well known to the Lord, though strangers to you,
and are free men in the record of heaven,
though now sufferers unjustly under your present authority,
who have taken the place of exercising lordship, over our pure consciences,
and have imprisoned us, and endeavoured to give judgment of banishing us,
only upon false accusations, and information and slander,
without the proof or testimony of any accusation of evil, justly laid to our charge.
And to you hereby be it known, that not for evil doing, do we thus suffer;
for to this present, no man has convinced us of any evil,
nor justly proved the transgression of any law, martial or civil, against us,
though we stand accused of many grievous things,
of which we are clearly innocent in the sight of Him that lives forever,
and do nothing more desire herein,
but to be tried by the law of equity and righteousness, and judged according thereunto.

By virtue of command given unto us, by the eternal spirit of the Lord,
came we into this land of Ireland, contrary to the will of man; not to seek ourselves,
nor our own glory, nor to prejudice your nation or government,
nor to be hurtful to your commonwealth,
but with the message of the gospel of Christ Jesus,
we came to turn people from darkness to light,
and from the power of Satan to the power of God,
and to minister the word of reconciliation and salvation freely, without gift or reward,
unto lost souls.
Hereof God is our witness, and also we have the seals of our ministry,
which unto us herein can give testimony by the same spirit,
and this are we ready to seal with our blood.
These six months and upwards, have we laboured in travels and sufferings, and reproaches,
and have passed through your cities and towns in soberness;
and in meekness have we preached the kingdom of God,
and have held forth the word of truth, and the testimony of Jesus;
and our lives have we not loved till this day,
though sometimes dangers on every side have beset us,
that we might hold forth the faith of Jesus the author of our profession,
in the exercise of a pure conscience, both by doctrine and conduct.
Herein are we justified in the sight of God, and who is he that condemns us?
We call heaven and earth to record, and the light in all men`'s consciences,
who have heard our doctrine and seen our conduct, to witness for us herein.
We challenge all your nation of Ireland, our very enemies, to prove the contrary,
though otherwise we stand falsely accused,
and falsely reputed to be disturbers and makers of disorders,
to the breach of public peace, and such like grievous things.

Upon the false information hereof,
a warrant was issued out from the chief ruler and council of Ireland,
and we thereby were apprehended in the city of Cork, and haled by guards as malefactors,
before the council in this city, where none of all these false accusations were,
or could be proved against us,
nor of the transgression of any known law could we be convicted.
Though occasions were sought against us,
yet none could be found;--and though snares were laid for our feet,
yet were we not entrapped; but were cleared in the sight of God,
witnessed by the light in all their consciences; and were found innocent,
and without reproof in the eye of the Lord.
And by our innocency, were their orders of false accusation made of none effect;
and we thus far proved to be guiltless before the throne of true judgment.

Yet notwithstanding, contrary to the light in their own consciences,
and contrary to the just laws of the nation,
which afford freedom to the free-born and righteous,
were we committed to prison without conviction, or any guilt charged upon us,
or the least appearance of evil towards any man`'s person.
Though falsely accused, yet no true testimony was given against us,
whereby our boldness in the way of the Lord could be discouraged,
as having the testimony of the spirit of God, bearing us witness in the Holy Spirit,
that in all good conscience towards God and towards man, we have lived to this day;
also are we without reproof in the sight of God and all just men.
Though upon search and examination, we are found guiltless thus far,
yet farther has the enemy, the devil, prevailed in cruelty against the innocent,
that it is endeavoured that we be banished under the account of vagabonds.
This last accusation is most false and unrighteous; for we challenge this;
of whom have we begged?
or to whom have we been burdensome?
or whose bread have we eaten for nothing?
or what evil have we done?
where is the testimony of your slanders?
But innocently do we suffer these things, bearing reproaches,
and binding the cruelty done unto us as chains about our necks,
and as crowns upon our heads; having the assurance,
that for well doing we suffer these things from the hands of the rulers,
through the lies and slanders of the teachers, who are in Cain`'s way of persecution,
till they have fulfilled their measure of wickedness;
and be laid waste as the wilderness.

This is our cause, and hereby it comes before you,
by the light of Christ in your consciences to be judged,
if your hearts be not altogether hardened, and your minds wholly blinded;
and we lay it at your door to receive sentence from you,
and without respect of persons hold forth our guiltless cause before you,
not begging anything from you, but herein to clear our consciences,
that you may save yourselves from this rebellious generation, whose root is corrupt,
and fruit bitterness.
While we have breath from the Lord, we shall bear witness against injustice,
and all cruelty and oppression,
and shall appeal to receive justice from the present power that now rules.
In the name of the Lord we challenge our privilege of freedom, as being free-born,
till we be accused guilty by the just law of equity,
unto which we are subject for conscience sake, and not to any man`'s will.
By word and writing, are we bound by the law of God,
to bear witness against the unjust proceedings herein of the heads and rulers of Dublin,
and shall seal our witness against them, and against their unrighteous decrees,
is sealed in their cruelty against the innocent,
with our blood if thereunto we be called.

[.signed-section-signature]
Edward Burrough.

[.signed-section-context-close]
Dublin, the 26th of the Twelfth month 1655.

--

On the 23rd,
Edward Burrough sent a general challenge to all the priests in Dublin and its neighbourhood,
at whose instigation he understood he and his companion were confined,
to give them a public meeting, in order to debate the doctrines of either,
that so the honest enquirers after truth might be satisfied, who were right,
and who were wrong.
Of this paper no notice was taken, but the council after a few days,
issued an order to the mayor of the city,
that he should send Edward Burrough and Francis Howgill, with all speed to England.
About the last of the year,
they were by force placed on board a vessel bound for Chester,
at which they arrived the 2nd of first month 1656.

During the course of this year, Edward Burrough and Francis Howgill,
addressed several epistles to their brethren in London and other parts of England,
evincing much lively concern for their spiritual
welfare and preservation in the unchangeable Truth.
The excellent counsel and pertinent exhortation, they contain,
render them well worthy of a careful perusal.

[.asterism]
'''

[.embedded-content-document.epistle]
--

[.blurb]
=== Several Epistles to Friends in London: written in the year 1655, by Edward Burrough, some of which were subscribed by Francis Howgill, who was fellow-labourer with him, in the work of the Lord.

Friends of God in the truth,
whom the Lord is gathering as desolate stones to build unto himself a habitation;
whom the Lord is bringing back out of captivity,
wherein you have been held under the chains of darkness,
in the land of the shadow of death, the Lord is calling you, and choosing you,
to place his name in you, and to spread forth his glory among you.
Therefore all dear Friends, whose hearts the Lord has touched by his love,
and by his power, be faithful unto God, who has called you;
and look not out at anything that is mortal,
to draw you from the obedience of the eternal light
of Jesus Christ which shines clearly in darkness.
Resist not the drawing of the Father, but take up the cross, and abide in it daily,
that your wills may be crucified, in which the ground of enmity lodges.
Wait in the fear of the Lord, in singleness of heart and in simplicity of mind,
for the powerful appearance of the Son of God to be revealed in you,
to destroy the works of the devil; for where he is not witnessed,
the works of the devil stand, and the nature of the earthly man in the fall.

All of you whose minds are turned within,
where the pearl and the lost money is to be found;
dwell and walk in the pure fear and obedience to
that Spirit of God which is made manifest in you,
and made known unto you,
and there will peace flow in from the presence of the Lord unto you,
and refreshment and strength to the seed, and the pure will live,
and the corrupt will die daily.

Beware, everyone that have put their hands to the plough,
that you look not back at anything which you have left behind in the world,
but press on in the strait way, which is the light,
which gives no liberty to the fleshly man,
but which judges and condemns all that hate it and turns from it.
The light is the way that leads to life, and by it as you wait in it,
the life will be made manifest, which is immortal, and your redemption will be witnessed.
Dwell in the judgment and in the burning, that the dross may be consumed,
and the pure may be refined, and the earthly carnal minds may be confounded and judged.
The Lord is near unto you; wait for his powerful presence in his own light to see him,
and in it to comprehend all the world, with all its profession, which leads not to God,
but keeps in the separation from God.
Your way is near; walking in the light you will see it,
and in the light you will see all the paths,
and all the ways which lead into the chambers of death.

Look not out at words, for that which feeds there is for the famine;
but dwell in the light, joining with the immortal principle,
which receives nourishment from the eternal fountain, which the world knows not,
nor comprehends.
As you grow in the pure, and in the life, so you are unknown to the world,
and your growth will appear by your obedience in the cross of Christ.
Leave off stumbling at the cross; for such as do have no part in the eternal inheritance;
but walk in the cross, which is life to the new man, and death to the old,
and so through death life is made manifest, and the pure life of God arising in all,
the world will be trampled upon, and denied by you.
But such among you that choose the world, wrath from God I declare against you;
and you who know the way, and cast off the truth,
and for the love of that which is visible, turn from the truth,
you cannot escape the damnation of hell.

So all dear and tender hearts, abide in the counsel of God,
and let not the world overcome your minds, but wait for a daily victory over it,
that so you may with the saints possess the eternal riches,
and that in you which is carnal and corrupt may be overcome,
by that which is eternal and holy, as you abide and walk in the truth,
and grow up in the knowledge of the eternal God.
So our joy will be fulfilled in you, and our rejoicing will be increased by you.
Therefore walk and live in that which God has made manifest in you, which is of himself;
and the eternal God of life and power prosper you, and lead you up unto himself,
to dwell and walk in his love forevermore.

Be not troubled at the rage of the world, nor at temptations,
but stand in the will of God, which has been declared among you;
that you may all be established and guided by that which is not of this world;
but by the principle of life, which is eternal,
which judges all the fruits and grounds of darkness.
Our love salutes you all who walk in the truth, and our prayers are for you,
that life may spring up in you, to praise the Lord forever.

We are servants unto you, and unto all the elect seed of God everywhere,
for whose sakes we give ourselves to be spent.

[.signed-section-signature]
Edward Burrough.

[.signed-section-signature]
Francis Howgill.

--

[.asterism]
'''

[.embedded-content-document.epistle]
--

Friends, whose minds are turned to the Lord, by that which is pure,
which comes from him who is the light of the world; all mind it,
that with it your minds may be turned to him, from whom it comes,
out of all the perishing things, and out of all the visible to the invisible,
that so you may all come to know the word of the Lord, which endures forever;
which is as a fire and a hammer, which breaks down the mountains,
and burns up and destroys all that is acted in that nature which leads into transgression,
and into the curse from God.
Therefore dear friends, who have tasted of his power, dwell in his fear,
and keep your minds from gadding abroad,
from that which has discovered the lusts and filthiness of your minds,
and turned your minds from these things and from
that nature that rules in the children of disobedience.
So you may all come to know the life, and that he may lead you,
and direct all your minds in his fear and wisdom,
that so you may be preserved out of those paths that lead to destruction,
and out of all the deceitful profession of the world.
In the light of Christ you will see the rise and ground of all deceivers, and dreamers,
and all them that speak their own imaginations, and yet boast of great things,
and strive and contend about words, and feed upon wind, and bring no fruit unto God.

And all you that are not of the light, and walk not according to the light,
but are lending your ears to such who act and speak in that nature,
you turn from your guide which is near, and lend your ears to the wicked,
and so walk in darkness.
But now you who have tasted of the love and power of God,
which the world knows nothing of, in it dwell, and abide in that which has convinced you,
and in that which judges you, that so you may witness the fallow ground ploughed up,
and the earth shaken, and the rocks rent, and the veil taken away,
that so there may be a way for the pure to pass through the earth,
and so the earth may waste, and wither, and decay, and the lions may suffer hunger,
and the gods of the earth may be famished, and the lusts destroyed.

All keep low in the fear, and wait in silence upon the Lord,
to be near you to direct your minds, and stay and establish you;
and as you have received the truth, so walk in the truth,
we do charge you all in the name of the Lord.
Be faithful everyone to your measure, and improve and wait for power,
and stand in the cross to the earthly, that whatever your minds have delighted in,
in the first nature, may be denied and crossed.
The cross is to the lust; and as you nourish the lust,
and let your minds and wills at liberty, and deny the cross,
then that which is pure is vexed and darkened, and so the deceit and lust get up again,
and the guide is lost, and condemnation comes upon you.
Therefore all be diligent in the work of the Lord, and watch over your actions,
and you will come to see Satan has many strong holds,
and would spare the best and the fat; but in that which is a cross to all mortal,
stand and dwell,
that so you may be preserved and kept out of all the snares of the devil.

And now take heed of judging the power of the Lord, and be silent and wait,
that you may come to see in the light, and be partakers of the same.
And all who have tasted of the power, wait, and keep out of imaginations, and thoughts,
and false voices, that so the enemy may not be hearkened to, nor the deceit;
but all in the measure wait upon the Lord in singleness of heart, out of all deceit;
and form nothing in your minds; but all dwell in purity and uprightness.

And all Friends take heed of carelessness, slothfulness, and sluggishness of mind,
and of giving liberty to the flesh, and ease to the carnal mind.
We charge and command you in the presence of the Lord, whose power is dreadful,
that you meet together in silence, and wait,
and none to speak a word but what he is moved to speak from the Lord.
Take heed of adding to it, but only what you are moved;
and take heed of striving and contending, or letting out yourselves to strange spirits,
but everyone keep in his own tent, and sit down under his own vine;
and eat not that which dies of itself, but feed upon the eternal,
and so you will be nourished, and grow up in wisdom and power, in that which is pure,
that all deceit may be kept out.

And all children and servants, be diligent in your places, more willing,
more ready to labour in love and diligence,
that so the name of God may not be dishonoured.
And all you who have callings, throw off nothing hastily or rashly,
but wait and flee not the cross, for if you do, you will be darkened,
and the name of God dishonoured.
Therefore all dear Friends, who have owned the truth, wait upon the Lord in diligence,
that so you may grow in the life, in the power of the Lord,
that nothing may be spared that is for destruction; and so God Almighty bless you all,
and keep you out of all deceit, in the pure life which is made manifest,
that you may have victory over all, and witness him who puts all under with it;
if you wait, you will see him present and near you.

The everlasting God of power keep you all; for great is our care over you,
and our love is to you that abide in the truth, of which you are already made partakers;
and when joy springs up, keep in it, and run not forth, and spend it not;
and take heed of exalting, for then pride and presumption get up,
if you keep not in his fear, and so darkness will come upon you.
But all dwelling in that which is pure, you will be preserved out of all snares,
and temptations, and your minds kept clear and pure, out of all things that defile;
and so the everlasting God of life and power be with you all.

[.signed-section-closing]
Your dear brethren in the unchangeable love of God.

[.signed-section-signature]
Edward Burrough.

[.signed-section-signature]
Francis Howgill.

--

[.asterism]
'''

[.embedded-content-document.epistle]
--

Dear and beloved Friends, in that which is pure, of God, and made manifest in you all,
wait and abide; and walk in the light, which comes from Jesus,
who is the Judge of the quick and the dead,
and condemns all unrighteousness into the pit.
Therefore all wait in that which is pure,
which has turned your minds from darkness to light, and from Satan to God,
and has convinced you of all unrighteousness,
and has let you see all that ever you have done; behold, he is the very Christ.
Mind that which is pure of God, which shows you the deceits of the heart;
the light of the eye which discovers all the secrets of your hearts,
and will show your present condition, and that which would lead aside;
and temptation as it arises it will discover, and resisting it in the light,
you will escape the pits and the snares which they who err from the light fall into.

Dear Friends, great is our care on every side, and we are jealous over you,
lest you depart from the simplicity of the gospel, and so the deceit lead and guide,
and you come under condemnation.
Therefore in silence wait.
Be swift to hear, slow to speak; and all wait upon the light in diligence,
and take heed of forward minds and wills, which would go before the light,
and run before the guide.
There is the deceiver and false prophet within, the same that is without,
and therefore we charge you all in the name and power of God,
to take heed of forward wills in speaking,
lest your minds be drawn out from the moving of the pure spirit within,
to hearken to words without, which are spoken from that which is above the light.
This feeds the carnal reason, and the earthly wisdom, and lets in the enchanter,
and so your minds being turned without, you feed upon the husk, and not the life.
That nature that cannot live without words, is for the plague and for the famine,
and must be famished and stopped.

As the power arises in you, dwell low in it, and sink down in the same,
and as things open in you, speak not forth, where your minds would run out,
but as things open treasure them up in your hearts.
All keep in that which separates between light and darkness;
and be not hasty to do anything, lest your wills betray you, and all keep in patience,
for there the crown is obtained.
Flee not from the trouble, nor from that which judges; but dwell in it,
and pray that your flight be not in winter.
Despise not the cross, even the death of the cross,
that all your iniquity may be nailed to the cross,
and the righteousness may be set up within, and the land kept in peace.

And dear Friends, whose hearts the Lord has touched; meet together, in silence wait,
and you will see the Lord present among you, and his power made manifest,
and the earth broken up, and the fallow ground, and a passage for the seed.
We charge you all take heed of many words, or feeding upon that which is torn,
and dies of itself.

We charge you by the Lord, that none speak without divine motion; for if you do,
the false prophet speaks, and his words eat as a canker, and darken;
and veil them that hearken to it.
All wait to have salt in yourselves, and savour and discerning,
that you may come to know the voice of the Lord from the voice of a stranger,
and so you may be kept out of all deceit, for there thorns and briars,
and the cursed fruits are brought forth.
But in the light of Christ dwell and wait, and grow up in it, and walk in it,
that you may come to know your Redeemer, and what you are redeemed from,
and see him near you, and in you, else you are reprobates.

The Lord God of life and power preserve you all, for we have kept nothing back,
but are free from the blood of you all,
and of all that hear us! but our desire to the Lord is,
that what has been sown in weakness may be raised in power,
and that you may grow up in the truth, and walk in the truth,
that we may see the travail of our souls, and be satisfied;
and if the Lord give us to see your faces again, we may rejoice in you, and with you.
The everlasting God of life and power, keep you all in his wisdom and power,
to have victory over all your enemies, that you may serve him in uprightness of heart,
and be faithful to that of God made manifest in you all.

Your dear brethren in the gospel of Christ committed to our charge,

[.signed-section-signature]
Edward Burrough.

[.signed-section-signature]
Francis Howgill.

--

[.asterism]
'''

[.embedded-content-document.epistle]
--

[.blurb]
=== To be read at meetings of Friends in London.

Friends of God, called by him out of the dark world, into his marvellous light;
to all you who by the power of God are kept faithful,
to walk and abide in the measure of the gift of God received; grace, mercy,
and peace from God the Father of life, be multiplied in you, and among you,
that you all may grow up in the power of God, out of darkness and the shadow of death,
wherein you have been held captive in a strange land.

Dear Friends, our souls are poured out for you,
that you all may abide in that which you have received and heard,
which is the way and path of life, and righteousness, and peace eternal.
Therefore, walk worthy of the calling, whereunto you are called,
and wait in the light by which you are enlightened,
that all deceit in particular and in the general, may be seen, and judged.
We bear you record, there is a witness of God manifest in you, and true desires which,
flow to God from you: therefore take heed to the measure of God,
that by it you may hear the voice of God, and see his powerful presence;
for by that which is manifested of God in man, God speaks, moves, and acts,
and is known unto man.

They that neglect the measure of God, to walk in it, all their knowledge, experiences,
and profession are for condemnation by that which changes not.
So all dwell in the measure which is the light,
in the cross which keeps under and judges the fleshly man;
so the understanding will be kept open to receive the mercies of God,
and to walk worthy of the mercies received; but turning aside from the light,
you neglect the mercies, and follow lying vanities,
and err from the way of righteousness, and bring yourselves under condemnation.
For no longer is God enjoyed by man, than while man abides in his counsel, in his fear,
where the secrets of God are manifest and received by the light,
which is the first entrance unto God, and the fulness of the enjoyment of God.
Beware of the world, where all the temptations lie,
to draw away your minds into the carnal and visible things,
out from the light by which the life is enjoyed, and so death passes over you,
and condemnation comes upon you, and the life be lost,
and misery be revealed against you.

Large is the love of God unto you, in calling you and choosing you,
and therefore forget not this love, but walk in it, up to God,
from whom free redemption is manifest unto that which has lain in death,
overcome by the darkness.
Follow not your own wills, nor the voice of the stranger and false prophet,
which draws out into visibles here, and there;
but have salt and discerning in yourselves, that you may try every motion,
and every spirit, and may by that which is infallible and errs not,
comprehend and judge that which is fallible and erring, which flourishes for a time,
but comes to an end and is withered.
This your own knowledge and consciences will set seal to,
who have been scattered upon the mountains in the cloudy and dark day;
but now the light is breaking forth, and the day begins to appear;
and all you who abide faithful shall see the glory of the Lord,
and shall enjoy him in the land of the living.

We charge you all in the Lord, that you who profess the truth walk in it;
and as you profess a change, let it appear by putting off the works of darkness,
which by the light are made manifest unto you,
and testified against by the witness of God in you.
Know this, that that which lives in you which is contrary to God,
witnessed against by the light of Christ, shall be as a prick in the eye,
and as a thorn in the side forever.
Wrath is to be revealed upon him that spares the best, and saves the fat from judgment,
for to the slaughter all must come, that life and glory may be made manifest.
He that looks back by the way is not fit for the kingdom;
and he that returns again to the pollutions, his latter end is worse than his beginning,
and the judgment of God cannot be escaped.

Therefore wait in the power of God, and stand in the light,
which is the armour against all temptations, whereby the darkness and death,
and he that has the power of death, is overcome,
and all that love the light are guided by it.
And all dear Friends, who have tasted of the love and power of God,
and do witness the rending of the earth, dwell in the power and pure fear of the Lord,
that so all deceit may be kept down, and under.
Take heed of the false prophet`'s speaking,
or allowing your minds to run out in the openings,
and so you will speak that which is opened in the light.

We charge you all in the presence of the dreadful God of life and power,
that you all wait in silence, and wait to have salt and savour in yourselves,
to know the voice of Christ from the voice of the stranger,
for till that be known in yourselves you are not able to judge.
Therefore all wait in the light, which is the eye,
which sees into the mysteries of the kingdom; and none to utter a word,
but what you are divinely moved unto,
or else that in everyone`'s conscience will bear witness against you.

Be not hasty, when you see things open in your minds, dwell in them,
and run not forth and speak, but treasure them up in your hearts, and take heed,
and keep low in the fear of the Lord God, that pride and presumption get not up,
nor anything be exalted above that which is pure.
Dear Friends, you are upon us as a great weight and burden,
lest we should have bestowed our labour in vain,
but we hope and trust the Lord will preserve you,
if you stand in obedience to that of God made manifest in you, and so you will grow.
Take heed of striving and contending, but judge that spirit, everyone in yourselves,
that you may all grow up in the pure life of God.
The everlasting power of God bless you all,
and keep you in his everlasting love and power, and give the victory over your enemies,
that you may come to witness eternal life made manifest in you, from God.

[.signed-section-closing]
Your brethren in the work of the Lord,

[.signed-section-signature]
Edward Burrough.

[.signed-section-signature]
Francis Howgill.

--

[.asterism]
'''

[.embedded-content-document.epistle]
--

Dear Friends, in the everlasting covenant of life and peace whom we bear witness of,
and unto whom we have declared and preached in season and out of season; yes,
and have often come unto, in much weakness and fear, and trembling;
and have not ceased day by day to watch over you,
lest any should start aside from the hope of the gospel,
which was declared among you in demonstration of the spirit,
whereby your understandings came to be opened, even by the word of his power,
which we directed you to wait in, and for.

You are witnesses yourselves of the love and mighty power of God,
which was made manifest among you; which made the heathen to rage,
and confounded the wisdom of the wise.
So dear children of light, of whom we have travailed in pain, and great burdens,
that Christ might be formed in you; fulfill our joy,
make our hearts glad in your growth up in him,
who has called and spoken to you from heaven by his Son, in the light.

Your ears have heard, your eyes have seen,
and you have been made to understand the mystery of the kingdom of God,
which is a parable to all the world, and sealed, and cannot be read,
but by you who continue and abide in the grace of God, which has appeared to all men,
which brings salvation to all that walk and abide in it, and leads to the entrance,
and earnest, and the sealing of the spirit,
until the time of the finishing transgression, and making an end of sin,
and so the everlasting offering be witnessed,
which perfects forever them that are sanctified.

Therefore all Friends whose minds are turned to the light,
and do witness a change in you, by the working of the spirit,
and now a door of hope being set open, abide in that measure everyone,
and stay your souls upon him, who is your hope;
and keep low in the fear to the just principle of life;
that you may have savour and discerning,
to know the voice of Christ from the voice of a stranger in yourselves and in others,
and so grow up in the discerning; and comprehend all spirits,
and judge them by the light that makes all things manifest.

And all meet together in your several meetings, and watch one over another;
and be diligent in your measure, and take heed you neglect not;
and none be of a careless mind to meet, and wait upon the Lord in silence;
for such whose life stands only in words without, we deny,
for their eyes and ears are without, and they would be ever learning,
and that is the silly woman that is laden with lust.
Take heed of taking liberty to the flesh; give no ear nor liberty to the earth,
but in the cross dwell to the carnal mind,
and so you will witness the plant of the Lord watered, and a growth in the immortal,
and the seed you will see, which is one in all, which the promise is to.

All be still, and cool, and quiet, and of a meek spirit, that out of boisterousness,
and eagerness, and feignedness, and self-love, you may be preserved in your measures,
up to God.

If any be moved to speak a few words in your meetings--this we
charge you all--that you speak nothing but that which is given,
and in the sense, and in the cross; and do not add your own words,
for then you will burden others who dwell in the life.

Take heed of whispering, and back-biting one another, but if any see one to be overtaken,
or walking disorderly, reprove such a one privately, and exhort privately,
and bear and forbear one another; and so love will increase, and your joy,
and your wisdom, and your I strength will grow.

The Lord God of life preserve you all in his wisdom:
and take heed of imaginations or running out: do nothing hastily;
but wait at wisdom`'s gate, that so you may do all things in wisdom;
and all be faithful in your measures, and give up all freely unto the Lord,
that he may take away your enemies, and bring you into everlasting righteousness.

All Friends in your places, masters, parents, servants, and children in your places,
be diligent in that which is just unto the Lord, that so the name of the Lord,
by whom you are called be not dishonoured,
but that you may all dwell single in the counsel of the Lord, in the light of Christ,
which keeps you out of all pollutions, and out of that nature that starves you,
and darkens you.
The living God of life preserve you, for you are dear to us, even all of you,
without respect of persons, who walk with the Lord;
and we cease not to make mention of you to the Lord, and he hears us,
that you may grow in the life of Christ Jesus, to follow the Lamb wherever he leads you,
or moves you: for truly our hearts are bound to you in the Lord, by one everlasting cord,
and if you make us sorry, who shall make us glad?
for you are our crown of rejoicing in the Lord.

We are your brethren, no, your servants for Christ`'s sake.

[.signed-section-signature]
Edward Burrough.

[.signed-section-signature]
Francis Howgill.

--

[.asterism]
'''

[.embedded-content-document.epistle]
--

[.blurb]
=== To all the beloved friends, and brethren, and sisters, who are made partakers of his eternal Lord of life, by which you are gathered into one light and power, in which is life eternal abiding in it.

Dear Friends of God, who have received and heard the word,
the immortal word with gladness and readiness,
who are accounted worthy to receive the testimony of our Lord Christ;
our love in the eternal life of God which endures forever,
which is not limited to nations, kindreds, tongues, or people,
is shed abroad in all and to all that wait upon Christ Jesus, who is the light, the love,
and the gift of the Father, which we are made partakers of, by which gift,
eternal life and peace forevermore are witnessed,
unto all them that continue and dwell in him, who is love.

Beloved in the Lord, our thirsting is great after you,
that you may be steadfast in the truth you have received
from him whom we declared unto you,
contrary to our own wills, in much weakness, and much fear, and often in tears,
and much trembling, and walking before you in uprightness,
without fraud and dissimulation, as patterns and examples;
and the Lord by his eternal working of his mighty power,
made his own ministry powerful unto you, unto whom be glory forevermore.

So dear hearts, in the grace of God which has appeared unto you,
which did convince you of sin, and condemned sin in the flesh,
by which power you are saved from sin, and brings salvation unto you who walk in it;
in it dwell and wait for the day star of Jacob to arise,
and the babe of glory to be brought in you, and made manifest,
that the government may be upon his shoulders, who rules in righteousness forever.
There is a crown before you; and therefore our dearly beloved ones, all wait,
and press on to the work before you, in the cross,
and give up all to be slain on the cross, and keep nothing back, for if you do,
the Canaanite will vex you, and trouble you, and be a thorn in your eyes,
to blind the eye, and so turn you into darkness.

All keep low in the fear, and wait, that the Head may be exalted and uncovered,
that so he may bear rule who is not in the transgression,
and so in the living hope which is come to you from
him who is the life of men you may purify yourselves,
and all the old leaven may be purged out.
Wait for the faith of the Son of God, which is born of God, by which the just lives,
and so the everlasting you will come to see.
The everlasting God of life and power preserve you all in one, out of all jar and strife,
pure to himself, in one, that you may bear witness to his name by your holy conduct,
in that great place; for I see there is more yet to come into the fold in that city.

Be diligent in your meeting together, and his eternal power and presence you will see,
as you have done continually.
Grow up in the life of God, and here you are unknown to the world.
Salute us to all the church of Christ in the city, without respect of persons,
whom we love and own in the life that never dies; and as many as are free, write to us,
for a friend here were precious indeed; but none knows us here, nor are we known to any,
but well known to the elect and precious, in whom we wait to hear from you,
to be refreshed to hear of you, of the works of the Lord everywhere.
The grace of God, by which you are saved from sin, be with you, and in you,
to give you dominion over all: in it, we lie down with you,
and are your brethren and servants for Christ`'s sake, to whom be glory forevermore.

[.signed-section-signature]
Edward Burrough.

[.signed-section-signature]
Francis Howgill.

--

[.asterism]
'''

[.embedded-content-document.epistle]
--

Dear Friends in the truth of God, without respect of persons, grace,
mercy and peace from the everlasting Father be multiplied among you,
that in the faith and love, and every good work, you may abound towards God and man,
and may show forth the praise of the Lord, and walk as people redeemed by him,
in all holiness and pureness, that your good works may be seen,
and your light may shine before men.

Dearly beloved in the Lord, my love does salute you all,
who are kept in faithfulness to the gift of grace received, in which you walking,
salvation it does bring, and redemption it does manifest, out of the world,
and out of its nature, into the image and likeness of the Son of God.
Therefore dear friends and babes of God,
by the immortal word of life begotten and nourished, who wait upon the Lord,
blessed are you that wait to the end,
till he who is the light of the world has put all things under him,
and he be exalted your head.
If in that you dwell which from the beginning has been heard,
you need no man to teach you, but the way you know, and the word of life is your victory.
So keep to the measure, that self-will and self-love may be judged,
and your neighbour loved as self; and the living God, who is light, above all,
who has begun his work in you, and among you with his right hand will finish it.

Dear Friends keep nothing back, let not the best, nor the fat,
be spared from the slaughter; but let the sword pass upon all,
that your peace may be forever, and your righteousness may never perish.
Oh, how does my soul long to know and understand of the growth
and unmovableness in the truth manifested among you,
and gladly received by you, even your crowns you laid down at the feet of the Lamb,
and your glory and renown in the world!
You are despised for the light`'s sake, but your reward shall be everlasting,
and your inheritance shall never wither.
I speak not to puff you up,
but but that you may the rather be kept low in subjection to the light of the Lord Jesus,
by which self, and that which would be exalted, must be crucified.
This is the victory and precious faith which will purify you,
and sanctify you throughout, from all filthiness of flesh and spirit,
in that faith to stand as witnesses for the Lord God in that great city,
and against all its pollutions and idol gods, which neither do hear, see, nor taste.

In wisdom, as examples one to another in love and unity walk, as children of the day,
being past through the dark night where the works of darkness were committed;
but now being separated from the world, join not yourselves anymore to strange women,
which entice from God, but sit under your own vine in peace, dwelling with the Lord,
who is light, of whom you are become the temple and tabernacle.

Watch in diligence one over another, that as the day appears, you may edify one another,
and may be made one in the light, which is Christ, upon whom you have believed,
who unto you is precious, but a stumbling stone, and a rock of offence to all the world.
The grace of the Lord Jesus Christ preserve you,
that by it you may walk in the pure religion, where your own will is not to be done.
The power of God Almighty fill your hearts with joy, and peace, and love in him;
and this is the desire of my soul,
who am a labourer among you in the work and travail of the gospel of Christ.

[.signed-section-signature]
Edward Burrough.

--

On landing in England, they heard of a meeting to be held at Preston, in Lancashire,
and being desirous to attend it,
they left Chester on the 3rd of the first month for that purpose.
The meeting was probably held on the 4th,
for Edward Burrough says that they "`made haste, much desiring to be there,
which also was brought to pass by the hand of our God.`"
At Preston they unexpectedly met John Audland and Alexander Parker,
and the meeting was held to the great advantage of Truth.
Recurring to the recent field of labour which he and Francis had been engaged in,
Edward writes:

[.embedded-content-document.letter]
--

Truly great service for the Lord we had in Ireland, for near seven months;
the particulars would be very large; but in short,
there is a precious work begun and seed sown, which shall never die.

Francis`' dear wife, we hear, is departed this world,
which will be a little hindrance to him at present,
as to settle his children and the like;
but truly he is wholly given up to do our Father`'s will, through great and many trials,
and dangers and sufferings.

--

From Preston, Edward Burrough and companion proceed to Lancaster,
and from there to visit Friends in the counties still further north.
Here, it appears, they parted for a while, Francis Howgill looking after his children,
while Edward Burrough proceeded to London.
Besides his labours in the ministry in that great city,
he published the Epistles written by him in Ireland,
and those prepared jointly with Francis Howgill.
On the 6th of the third month he finished and dated a work, entitled,
"`A description of the State and Condition of all mankind on the face of the earth.`"
Francis Howgill soon joined him, and they continued labouring together in gospel unity.
A letter from Francis Howgill to Margaret Fell,
which was probably written early in the fourth month of this year, says;
"`In this city Truth has dominion over all; none will stand now to dispute,
but they turn away.
We have about twenty meetings in a week;
and ten or twenty miles about there are great desires; and if we can we go out,
but we cannot stay; great is our care.`"
"`Edward Burrough salutes you; he is almost spent: few know our condition.`"

From London they went to Bristol, and had a great meeting there on a first-day, (fifth mo.
27th), at which about five thousand persons attended.
Soon after, Edward returned to London,
and it was not long before he was joined by his faithful companion,
and for many months they had sore trials and conflicts,
in contending with some who had gone out from the Truth,
and others who had never attained it.
The ranters, a body of people acknowledged by no religious society,
were a disturbance to all.
Particularly were they so to Friends,
whose places of worship were not in anywise protected by the civil authorities.
These ranters would come into the meetings, screaming or singing with loud voices,
interrupting the ministers in their solemn services,
and at times using very indecent language and actions.

William Caton, who came to London about the 1st of the seventh month of this year,
writes of the exercises they had in the city,
from some who had left the Truth and gone into extremes,
but adds that the faithful had comfort in one another.
Although Edward Burrough and Francis Howgill had much suffering to endure in London,
they yet felt sympathy for their brethren under suffering in other places.
On the 19th of the seventh month they addressed a
joint letter to Thomas Aldam and others in Yorkshire,
on whom much abuse had been bestowed for their faithfulness.
Francis Howgill held the pen.
This communication bears witness to the unity and fellowship subsisting among them.
They say,

[.embedded-content-document.letter]
--

Dear brethren, we are with you in your bonds, in your reproaches and imprisonments,
and in your rejoicings: your joy is ours,
for we eat with you and drink with you at our Father`'s table,
where there is plenteous nourishment for all those who wait in his counsel,
and are obedient to his commands.

--

[.offset]
In respect to things in London they say;

[.embedded-content-document.letter]
--

Dear brethren, our care is great; the harvest is great;
who are sufficient for these things?
Here are fields white unto harvest, and much of the power of God has been with us.
Great has been our burden and our work since we came here, and our reward is great.
Much have we been drawn out to administer in power and wisdom.
We have exceeding great meetings of all sorts,
and we labour and travail until Christ be formed in them.
Pray for us that we may be kept in His power, which reigns over all:
by the power of the Lord the mouths of lions are stopped, kings are bound in chains;
eternal living praises forevermore to Him who rides
on conquering in power and great glory!
Many are brought under great judgment and true power,
and many have learned their own condemnation.

The last first-day, (seventh month 14th),
my dear yokefellow and I went in the forenoon to two of the highest
notionists and the greatest deceivers in the city,
at two steeple houses, where the wise of the city come; and I had great liberty,
and spoke toward an hour: all were silent,
and some confessed they never heard so much truth in power delivered.
Many would have had me to their houses; but we lay hands on none hastily.

--

James Lancaster and Miles Halhead were at this time in London, but tarried not long there.
The parliament had met on the 17th,
but it was no longer a meeting of the free and independent representatives of the nation.
Those only of its members who were approved by Cromwell and his council,
were permitted to enter the House, or to sit therein.
This high handed measure of arbitrary power occasioned
great excitement throughout the community,
particularly among those who were attached to republican principles.
In this public agitation Friends look no part.
In reference to it Francis Howgill says; "`As for these things, they are nothing to us,
we are redeemed from them.
Praises to the Lord forevermore, who has made us to reign above the world,
and to trample upon it.`"
