== Chapter VIII.

On the 18th day of the first month 1659, while passing through Warwickshire,
Edward Burrough fell into deep meditation on the sufferings
and wrongs which his brethren in religious profession,
were at that time enduring in England.
While thus engaged, he says; a cry ran through him,
"`The Lord will be avenged! the Lord will be avenged upon his enemies!
He will avenge the cause of his people.`"
The feeling which accompanied this opening was such,
as to seal on his mind an assurance of its truth.
He meditated upon it for a time,
and the remembrance of the unjust and grievous persecutions
which the infant society was undergoing,
awakened a sympathetic feeling, so that his heart was much tendered and broken.

While in this state, he received this command; "`Write unto the rulers,
and yet once more warn them of that recompense, and of that indignation,
which is at hand upon them, even a just recompense for all their deeds;
and as they have done, even so shall it be done to them;
as they have sought to destroy the generation of the righteous,
even so shall they be destroyed from off the face of the earth;
and as they have unjustly judged and condemned the innocent, so shall they be condemned,
and justly judged of the Lord;
and as they have cast the bodies of the poor lambs of Christ into prison,
and been a snare upon them, even so shall they be ensnared,
and into captivity shall they go.
And as they have caused the goods and possessions of the innocent to be spoiled,
and made a prey,
even so in like manner shall the curse of the Lord spoil their substance.
And as they have done, so shall it be done unto them;
and as they have administered to others, so shall it be administered to them again.`"
"`And I saw a great misery and desolation near at hand, even the sword of the Lord;
and that it should slay them; and I beheld it was made ready for the slaughter;
and in the sense of these things a sadness fell upon my spirit,
considering the desolation and the judgment that is at hand,
to be executed upon the cruel oppressors.`"

Edward Burrough`'s prediction of trouble, to the then rulers in England,
was amply fulfilled when under Charles the 2nd,
the late persecutors were persecuted in their turn; when Episcopal priests,
drove Presbyterian and Independent preachers from the parish steeple-houses;
when the judges of king Charles the 1st were put to death,
and fear and terror caused the chief leaders in the
late commonwealth to hide in secret places,
or to flee the country.

Passing on into Somersetshire, he had a meeting at Glastonbury, at the Market Cross.
To this came Samuel Winney, the priest of the parish,
attended by a band of drunken men with a drum.
The priest addressed himself to Edward,
and demanded by what authority he came there to preach?
He received a prompt answer, couched in the scripture language,
"`As every man has received the gift, even so minister the same one to another,
as good stewards of the manifold grace of God.`"

Edward then returning the query to him who put it forth;
asked him to prove his call to the ministry from scripture.
This question Winney was not pleased to hear, and did not feel prepared to answer;
so he retired from the field of contest,
leaving his drunken followers to dispute for him.
This they did after their manner, by beating on the drum, by hallooing with strong lungs,
and by knocking the Friends about in a rude and barbarous manner.

Leaving Somersetshire, Edward returned towards the eastern part of England,
and soon felt a religious obligation to go over to Dunkirk, on the French coast,
a town at that time in possession of the English.
For many days he says, it appeared to be his duty to "`visit and warn the papists,
the Jesuits, friars,
and that whole company of idolaters,`" and "`to sound
the mighty day of the Lord among them.`"
He went to Dover, and being accompanied by Samuel Fisher,
who felt a similar religious concern, took shipping on the 6th of third month,
and reached Dunkirk, on the 7th.

On arriving at this place, at which they were both strangers,
"`We waited in the will of the Lord,`" says he, "`to be guided by his wisdom what to do,
and how to act and speak to his glory.`"
The next day as they were walking the streets, the mayor of the place came to them,
and demanded their names, and the business which had brought them there.
To these questions the Friends gave "`sober answers, and a reasonable account.`"
It was soon known throughout the town, that two Quakers had arrived,
and much curiosity was felt by the inhabitants, as to the occasion of their coming.
The deputy governor Alsop, with his council of officers, sent for them,
and conversed with them for some hours.
The Friends were treated kindly, but Alsop told them,
"`he thought there would be danger attending their stay in that place.
He was fearful lest divisions and contentions should arise among the inhabitants,
and the safety of the English garrison be brought into jeopardy.`"
This result he probably thought would follow,
if the principles and practices of the friars and Jesuits,
should be openly and honestly assailed by the Friends, in that Roman catholic city,
the inhabitants of which were sunk in gross superstition.
Alsop requested them to depart from the place.
In reply, they frankly told him,
that as they apprehended they had been divinely led there,
they could not obey his command to depart, until they felt Him to lead them away,
who they believed had sent them there.
Some preachers were present at this interview, probably army chaplains.
One of them wished to enter into a public dispute with the Friends,
on the call to the ministry, but the lack of time,
and the challenger`'s lack of patience, prevented the discussion of the matter,
although Edward much desired it.

On the 11th of the month,
the two visitors addressed a letter to the deputy governor and his officers,
in which they call themselves,
"`travellers in the labour of the gospel of Christ Jesus.`"
They say, they came to Dunkirk "`to be made manifest openly in the sight of all men,
in our doctrines, principles, and practices, which are of, and from the Lord,
and fully agreeing in all things with the scriptures of truth,
which were given forth by the Spirit of Truth, as the holy men of God were moved.`"
They add, that they came there in love to the souls of the people, and principally,
as far as the Lord had shown them, "`to discourse with the Jesuits, friars, and priests,
and to discover to them the errors of their ways, and the falseness of their worship;
and to testify unto them, in the fear and power of the Lord, concerning their church,
that it is not a true church of Christ, but a false church, come up in the apostasy.`"

They further say, they did not come to cause grief or disturbance to any; but add,
"`we dare not promise to you, nor ourselves, what we will do, or what we will not do;
only this we say, if the transgression of any just law can be charged upon us,
we refuse not to suffer what shall be imposed; and this we do believe,
that the Lord will so help us, and order us by his Spirit of Truth,
and carry us in meekness, and righteousness, towards you, while we stay among you,
be it weeks, or months; that you will have no just occasion against us,
by any offence ministered by us.`"
They add, that if any offence is taken by the unthinking, without just occasion given,
the shame and condemnation will be on those who take the offence.

"`We do give unto the Lord, and cannot unto men,
the exercise of our consciences,`" say they,
"`to be obedient unto the teachings of his Spirit in all things.
If he commands to do, or not to do anything, and you the contrary, we must obey him,
though we disobey you, for it is better to obey God than man.
When he bids speak, in whatever place or season, we may not be silent,
for to keep our consciences clear in the sight of God in all things, by obedience to Him,
is our care and study.
No other promise can we make for ourselves, but to do and speak among you,
as the Lord our God shall move us and lead us.
And this testimony we do bear for the Lord, he does not move us,
nor lead us to do anything, saving to what is just, good and holy,
which may tend to the happiness and peace, and welfare of your souls and bodies also.`"
In conclusion,
the Friends offered to have a public dispute on the true call to the ministry,
with the priest who had spoken to them on that subject the evening before.

The same day they went to the convent of the Capuchin friars,
and in the garden belonging to the establishment,
had a discourse with the chief man among them.
The subject first spoken of was, the Light of Christ,
with which all men coming into the world are enlightened.
After this, Edward and his companion spoke to him of the mighty day of the Lord,
when all would be searched and tried,
and all popish idolatrous ways and worships would be destroyed.
The next day, the 12th, Edward addressed a few queries to the Capuchin friars.
He wishes them to tell him,
"`whether there was such an order of men and women as themselves,
in the primitive church?
Whether they can find authority from Jesus Christ for their worships,
idleness and practices, unprofitableness to God and to man?
Whether they are willing to have their religion tried by the scriptures?
And if they are not, whether any are bound to follow them?
Whether the world in your hearts, and the world`'s nature, even the root of lust,
the root of pride, covetousness, and the love of this world and it vanities,
and the root of idolatry, are subdued in you?
To the light in your consciences I speak.
What is the root of all these things?
And what is it that subdues it?
Is it an outward abstinence by the force of locks and doors, and bolts,
or self-separated and secret places, that subdue the world`'s nature in men and women?
Is it by such means that Christ gives victory over sin, and overcomes it in his people?
Or is it not by the power of God in the heart only?`"

"`It does not appear to me, that you have denied the world, as the apostles did.
Where had they any such seats in the finest and fattest places of the cities and towns,
as you have?
Such great, fine houses and gardens, and such revenues by the year as you have,
staying all their days in a great house,
and spending their time in sloth and idleness as you do?
They went up and down the world preaching the gospel, and had no certain dwelling place,
but followed the Lamb of God in the spirit,
and did not settle themselves in fat places of the earth,
continuing all their days as you do.
Therefore we judge you are out of the life, and not in the spirit the apostles were in,
but in a form of righteousness and holiness, without the power.`"

He further desires to know of them, whether they have come to Christ Jesus in themselves?
Whether they expect to be free from sin in this life?
Whether they believe that men may come to be restored by the second Adam,
into the same state as was lost by the first Adam?
In concluding he says; "`If you be in the perfect truth,
and would convert others to your religion,
be plain with us and use your best spiritual weapons in your zeal towards us,
and defend your cause, and appear for your God.
If you doubt of your ways and practices, and be not able to defend your religion,
then let your mouths be stopped, and turn from idolatry.`"

While they remained in Dunkirk, they had various interviews with the Capuchins,
the friars of the Recollects, and with the Jesuits.
They called to visit the nuns, but these after hearing a few words, interrupted them,
to inquire whether they were of the order of those called Quakers.
Receiving an affirmative answer, the nuns retreated from them, saying,
they must not hear them.
The Capuchins were light and scornful,
and soon growing tired of the Friends and the truths they promulgated,
they declined giving them an opportunity of conversing with them.
The rector of the Jesuits would not meet them, until Lockhart the governor of Dunkirk,
who had been absent when the Friends arrived, had returned to that city.
Lockhart spoke to the rector, and he then consented to see Edward and Samuel.
He was subtle and crafty, and at first very high in spirit,
apparently despising his opponents.
But the truth in their mouths was too strong for him to contend against successfully;
and after a discourse of three hours,
he pretended that he had other business to attend to, and making his escape,
refused to have any discourse with them afterwards.

On the 20th, Edward addressed to the Jesuits, priests and friars, a paper,
containing assertions to this effect:

1st. That the Romish church was not the true church of Christ.

2nd. That the constitution of the church,
and the chief part of the forms of its worship and ordinances, were of man.

3rd. That there had been a general declension in the world, from true faith and doctrine, etc.

4th. That antichrist had reigned for generations.

5th. That the true church was yet in the wilderness.

6th. That compelling persons by outward law to conform to certain religions,
and to persecute and kill them for matter of conscience, was a worship of the beast.

7th. That none are members of the true church,
but such as are changed and renewed by the power of the Lord God in the heart,
and are joined to Christ the head.

8th. That the time is coming, when Babylon shall be thrown down.

Many meetings Edward and his companion had in the town,
and much service in the English army, with very little disturbance.
Edward says; "`I must commend the spirit of our Englishmen for moderation,
more than the men of any other nation.
I did many times clear my conscience among them, as they were men, sons of Adam;
and in relation to an eternal state, did direct them to the way of happiness,
out of sin and wickedness.
That as they were sons of Adam in transgression, they might come to be healed,
come unto Christ the power and wisdom of God, and might be saved.`"

Understanding that one of the chaplains had spoken against them,
when they were not present, they offered to discourse with him.
He evaded the proposition, but told them,
that if they would state some of their principles in writing,
he would answer them in dispute in some public place.
In conformity to his request, they prepared the following brief propositions:

1st. That Christ has enlightened all men with a light,
sufficient to bring them to salvation, if they follow it.

2nd. That God has given Christ to be the Saviour of all men.

3rd. That none are justified by Christ and his righteousness, without them,
but as they have received Christ and his righteousness,
and witnessed them revealed in themselves.

4th. That the saints of God may be perfectly free from sin in this life,
so as no more to commit it.

5th. That the national ministers and churches, not only of papists,
but of the protestants also, as they now stand,
are not true ministers and churches of Christ.

6th. That the scriptures are a true declaration, given forth from the Spirit of God,
by holy men of God, moved by it to write them, and are profitable;
but are not the foundation, nor the most perfect rule of faith and life, to the saints.

These propositions the Friends tell the priest in an accompanying note,
they are willing and desirous to discourse upon,
with him and any others in a public place,
"`provided it may be in the spirit of meekness, and moderation,
and that all fair and sober dealing may be among us, and the fear of God.`"
The chaplain, it appears, did not wish to engage in a controversy with them,
and endeavoured to shift the responsibility of refusing it from his own shoulders,
saying "`the governor was not willing.`"

Soon after the 20th they took shipping for England, having performed at Dunkirk,
all the service their divine Master laid upon them.
Before the end of the month they had a meeting at Sandwich in Kent,
in the parsonage house, where they met with George Fox and Ambrose Rigge,
who were at this time holding meetings in that county.
Edward and his companion held one also at Dover, in a great house,
situated in the market place, belonging to Miles Temple, a captain of the town band.
This was a good meeting,
but when it was over the rabble set fire to the house in which it was held,
intending to do the strangers an injury.
The Lord preserved them, but the building was consumed.
The two Friends then held a public dispute at the steeple house, with William Russell,
one of the priests.
The dispute was principally managed by Edward Burrough,
and it was satisfactory to the Friends of Truth,
who had reason to believe that it was the means of convincing some present.
From there Edward Burrough proceeded towards London,
which he entered with George Fox on the 16th of fourth month.

A priest of Sussex having sent to a member of parliament,
a manuscript containing a number of railing accusations against the Society of Friends,
with the design of secretly prejudicing their cause,
and the paper coming to the knowledge of Edward Burrough, he wrote a reply,
entitled _Satan`'s Design Defeated,_ which is contained in his works.

Richard Cromwell, in conformity with the wishes of the officers of the army,
and against his own judgment,
had dissolved the Parliament on the 22nd of the second month,
and the political horizon in England began to give evident tokens of a change.
He felt his power diminishing, and he had no mind through blood to build it up.

Edward Burrough had written an address to the Parliament just dissolved,
exhorting them not to allow "`the exercise of pure consciences to be trodden
down,`" "`to remember the cause of God and of his people,
to remember the groanings of the poor, and give ear to the cry of the oppressed,
to relieve the guiltless sufferers, and break the bonds of iniquity,
and let the oppressed go free.
Do this lest you perish.`"

In the fifth month, Edward Burrough delivered, or caused to be delivered,
the following address to Richard Cromwell and his brother Henry,
who now felt that their power and influence had departed from them.

To R. C. and H. C.

Friends,

Yet once more has the Lord given me something to say unto you,
in love to your immortal souls.
You had a glorious day of visitation,
and many precious warnings from the mouth of the Lord, by his servants;
but you rejected the counsel of the Lord against your own souls,
and made no account of the servants of the Lord, which were sent unto you;
but caused them, and allowed them to be persecuted by your power,
and they were made a spoil and a prey to their enemies all your days.

You sought yourselves, and your own honour, and you were exalted in pride and vainglory,
and forgot God, who raised you up from a low state,
and you had no respect to the cause of his people.
Therefore this is justly come to pass upon you from the hand of the Lord.
Not that I rejoice in it, or glory over you because of it,
only I tell you what is justly happened unto you,
that you may learn the Lord`'s just judgments in these things,
like as formerly I warned you of it.

It could not be otherwise but that the Lord would
avenge the cause of his people upon their persecutors,
and the injustice done unto them upon you, in whose name and power it was acted.
In every generation he has had respect unto his people`'s cause,
and did avenge their cause in his season.
This I well remember, I was once moved to speak in the name of the Lord unto your father.
That these things that came to pass in his days,
the cruelty and oppression of the Lord`'s people,
would be recompensed and repented of in his children`'s days.
I saw the cruelty and injustice that was done in his name upon the people of God,
could not escape unpunished in a generation.
It is now come to pass in a measure, and will be more and more,
even for his transgressions and your own.
All of you had a day and a time,
wherein you might have done something for the Lord and his people.
You had a price put into your hands, that you might have improved to the Lord`'s glory,
and to your own renown, to have been a blessing unto yourselves,
and to the people of God in these nations.
But your day is over, and night is come upon it.
Your price is taken from you, and given to others,
and you cannot now work or act on the Lord`'s behalf, as once you might have done.
You have sought honour to yourselves, and you reap reproach.
Because you have despised the counsel of the Lord, therefore the snare has caught you,
which was laid for others.

These things I say in pity for you, rather than in boasting over you;
neither do I commend that spirit which acts in too much severity towards you,
which upbraids you, rather than seeks to amend you.
That is not my way.
As for you, come unto the fear of the Lord God, that your iniquities may be pardoned;
and seek peace with God, and reconciliation,
and seek after the kingdom that endures forever.
While you have time, seek after a crown immortal,
and wait to know that which will make you heirs of
that inheritance which never fades away.
The Light in your consciences,
which Christ has enlightened you with,--which lets you see sin,
and convinces you of your evil deeds;--that Light must you own to be your teacher.
You must become subject to it in all things, or you have no part in the kingdom of God.

About this time Friends at Sabridgeworth, in Hertfordshire,
were suffering much insult and abuse from the rude rabble,
who were encouraged in their evil actions by Thomas Hewit,
a magistrate known as a favourer of King Charles.
The meetings of Friends for religious worship in that place,
were much and frequently disturbed, brickbats were thrown among those assembled,
to the endangering of life and limb, and filth was frequently cast upon them.
The meetinghouse was almost destroyed by the mob,
and when an account of this outrage was made to the said Hewit,
he ordered his servant to turn the complainer out of his house.
At one time he came as the captain of a company of volunteer disturbers,
determined to stop Friends from entering their meetinghouse,
and it was not until he had had a smart brush with some of the Commonwealth soldiers,
that he and his party withdrew.
The tories now deemed that the signs of the times were favourable
to the coming in of King Charles the 2nd,
and they began to talk and to act boldly in many places.

Edward Burrough, about the close of the sixth month, being in Hertfordshire,
attended the meeting at Sabridgeworth.
While going to it, he was much covered with dirt thrown upon him by the mob;
and seeing Hewit just then passing in his coach,
he went to it and complained to him as a magistrate of the
abuse cast upon peaceable people in his jurisdiction.
While engaged in laying the matter before the squire,
one of the rioters came near and jerked off his hat,
and another threw a rotten egg on his bare head.
This so pleased Hewit, that he could not forbear smiling,
although his coach received some of the unsavoury contents.
One of the early Friends,
after detailing the various acts of outrage committed on Friends,
with the sanction and approbation of this magistrate, remarks;
"`He that disdains to be the servant of Christ, will stoop to a worse office.`"

From Hertfordshire, Edward returned to London.
Here again he was full of business,
labouring for the good of the religious Society of which he was a member,
and of every individual of it,
as he found opportunity;--preaching the Gospel as his Master gave him the word,
and defending the doctrines of truth with his pen.
On the 12th of the seventh month,
he addressed the Parliament then assembled--the Long Parliament having
again come into power--in a communication characterized by great plainness.
It commences thus:

To the Parliament of the Commonwealth of England,
the Present Authority of These Nations Assembled at Westminster

A presentation, by a faithful friend to the nation, in the name,
and by the spirit of Jesus Christ, King of Righteousness and Peace;
that you may take off oppression, and free the people from all their cruel bonds,
that have been imposed upon their bodies, estates and consciences,
in the days of the reign of Antichrist.
That truth, justice, and righteousness may come near unto us,
and the kingdom of the Son of God be set up among us; that you and we,
may at last be free subjects of Christ`'s kingdom, where righteousness,
truth and peace may run down, and be established forevermore.

He acknowledges that during the long time that Parliament had borne rule in England,
many cruel laws had been made void,
and the kingdom of Antichrist had received many a wound:

There have been many times the fair blossoms of the glorious appearance of truth,
righteousness and peace.
There have been fair promises and pretences made by many of you,
as if the kingdom of Jesus had been at our door, ready to have entered our nation,
whereby many good hopes we had,
to have been made a perfectly free people before this day, from the chains of Antichrist,
and the false church, and from every branch thereof.
But, alas! the glorious work of reformation has been interrupted before our eyes,
and the precious buds and good appearance of glorious fruits,
have withered and been blasted in our sight.
Our good hopes have perished,--our freedom has been intercepted
through the evil doing of unfaithful men.
Antichrist`'s kingdom has not been rooted out,
nor the oppressive laws of the false church wholly broken down.

The cause of this has been from some unfaithful men,
that have neglected the good work of the Lord, once entrusted with them;
and have sought themselves, and their own honour, and interests,
and have sitten down at ease and rest in the flesh,
glorying in the spoil of their enemies,
and have thereby become unfaithful and unprofitable in carrying on the Lord`'s work.
Some have been of a sincere mind for a season,
and made a good progress towards the attaining a kingdom of righteousness,
and removing all oppressions; yet, when they have begun to seek themselves in this world,
and to take unto themselves the honours, and titles, and possessions of their enemies,
and so have been guilty of their enemies`' sins,
the good work of the Lord by them could not prosper.

He then goes on to point out the yoke of tithes, and the forced maintenance of ministers,
as some of the oppressions of Antichrist not yet abolished.

The long Parliament and the officers of the army could not agree,
and many persons were in favour of a new Parliament;
but Richard Cromwell had been removed from Whitehall,
and with his brother Henry were now private men,
and no power had been vested in anyone to dissolve a Parliament.
It seemed therefore impossible for a new election to take place,
unless the body then sitting should vote themselves extinct,
and make provision for the meeting of a new one.
This they were not likely to do.
The whole nation was agitated, and whether there was any supreme authority in England,
and if there was, where it was to be found, was a matter of doubt and disputation.
In the ninth month, Edward Burrough published an address,
which he styled _A Message to the Present Rulers of England, Whether Committee of Safety,
so called, Council of Officers, or Others Whatsoever._
He had felt a concern to speak the substance of this
to the rulers but no way had opened for it.

Friends,

My Master is a high, and mighty, and powerful prince, and very honourable; and fear,
reverence, respect, and subjection belong to him alone, from you and all mankind.
He is wise, and understanding, and of great strength,
and his dominion is from everlasting to everlasting.
He can do whatever he will in heaven and earth,
for he rules with his iron rod over the world, and whatever he says, it is done;
for his word is an everlasting command.
If he says to a man, live, it is so; if he says to a man, die, it comes to pass;
and if he give peace to a man, or a nation, none can make war;
and if he make war with a person, or in a nation, no man is able to make peace.
For why?
He has all power in his hand, and to him all judgment and authority is given;
he is the Son of the living God, the everlasting Creator.

He was, and is, and is to come; his eye beholds all things,
and his arm compasses heaven and earth; and what his purpose is,
he has always and will ever bring to pass.
If he sets up rulers, they must rule; and if he pull them down, none can hinder.
Whom he will, he honours; and if it be his pleasure, he brings men to shame.
If he break a nation down, none can build it up;
and if he confound powers and authorities in the kingdoms of men,
they all fall as withered grass before him.
Behold, you men!
He is so great and mighty, and of so great authority, that whatever he says, it is done;
and whatever he wills, it comes to pass.
None is able to resist him, and overcome his power,
when his pleasure is to accomplish a work.

By him all things are that be, and all things live that have life,
and through him all things move; and of his fullness,
every creature in heaven and earth receives.
And this, my Master, is altogether honourable in birth and otherwise,
and altogether mighty in all his works.
He is just and merciful, full of goodness, righteousness, and truth.
All virtue dwells in him, and his judgment and mercy, his authority and meekness,
and his wrath and his love, they are companions: and what are you before him?
Or how shall you be able to resist him, or to turn backward what his purpose is,
concerning you, and this nation?
For you have no being or breath without him.

Behold you men!
You are verily as the dust before the wind, so are you to him, soon blown away,
and your place not found.
As the grass before the mower, so are you before him, soon cut down, and withered,
and your beauty utterly extinguished.
As a potter`'s vessel under an iron rod, even so are you to him,
he can immediately break you, never to be bound up; as a drop to the fountain,
so are you to him, soon dried up and made nothing.
Therefore, you men, you mortal creatures, you ignorant persons, sons of a transgressor,
you dust and ashes; for thus you are in comparison of him, this mighty prince;
hearken to his message, which comes to you from him.
Hear and fear, and be not stout-hearted against the Lord God,
that is about to speak unto you.

As for this little island of England, wherein your present place and being is,
it is an island which the Lord has shown great favour unto in ages past,
and in this present time.
I must tell you, he has a purpose of love towards it,
and to honour it in the view of the world, though through great tribulation.
He has an intent of great good unto it; for he has a seed,
a precious seed in it scattered abroad, and he has a people that fear his name,
and have walked in his ways, and he has made them, and elected them, and what they are,
it is by him; that he may dwell among them, and have the whole government over them all.

Yes, he has a speedy purpose verily concerning this nation,
and he will purify it in judgment,
and refine its inhabitants through the fire of tribulations,
that it may be pleasant to him, and fit to do his will.
He has a purpose to work some great thing in it, I must tell you,
as he has said unto me so to do.
He will have his name exalted and reverenced in this island;
and his terror shall be sent out of it through the world,
and his branch from it shall spread over the earth.
He does purpose in his season to take it into his own hand,
and to sway the government thereof with his own sceptre,
and to set up righteousness alone, and to overthrow all oppressors and oppressions;
and the kingdoms of this world must become the kingdoms of the Lord, and of his Christ.

True it is, such has been the coming to pass of time and of things for many ages bypast,
that my Master has been, as it were, banished from the nation,
and has not been permitted to enjoy his right; but has been expelled, even, as it were,
by the force of Satan and antichrist,
who has long usurped authority over the inhabitants of this nation.
In my Master`'s absence, lamentable injustice, cruelty, unmercifulness, tyranny,
and oppression have been exercised upon the inhabitants;
and the poor creatures have been held in great slavery by their rulers,
that have ruled by the dragon`'s power; and been kept in great blindness and ignorance,
and under great oppression, both in body and spirit, by antichristian teachers,
for these many years.

While the great King has been absent, and, as it were, gone into a far country;
even all this time has antichrist and the devil ruled and reigned,
and have made and executed oppression, and tyrannical laws and decrees,
both in church and state.
All the nation has been out of right order, and laid waste and barren of good fruit,
and it has been as a wilderness by reason hereof.
Men that have ruled for many years, have not ruled singly by my Master`'s authority,
but by another power; though not without the knowledge of my Lord,
neither as though he had not power to have done otherwise.
But for his own pleasure he has allowed it thus to be,
and let men go on to rule and govern in their own wills, and after their own lusts;
and people have walked wickedly towards him, and towards one another;
and all this he has permitted.
Not as if he gave toleration for it; for his messengers now and then,
and his witness in people`'s consciences, have been reproving their ungodly ways.
He has often showed his dislike by various ways, and tokens, and many judgments,
and strange overturning, to the way and proceedings of both rulers, prophets,
and teachers of this nation; but yet they have gone on against his mind,
and contrary to his will, notwithstanding his reproofs and judgments.
Not that he had not power to have executed his pleasure in wrath upon them,
and to have destroyed them altogether, and have made the nation a heap,
and as nothing long before this day.
Power was in his hand to have done it;
but he has been long-suffering and of great patience, and borne all things,
and taken the injustice, and cruelty, and wickedness and idolatry,
and all unrighteousness that has abounded in the nation upon himself,
and suffered under it, and borne it for its season,
while woeful and lamentable oppressions have been practised in civil state,
even hellish laws, and devilish executors of them.

Merciless tyrants have borne the sceptre,
and reigned for many years over the inhabitants,
and in church and state have been heinous idolatry and superstitious
vanities committed in a high nature and measure,
and even all men, and states of men,
and orders of men of every degree have been abominably corrupted in the sight of my Lord,
even from the prince to the beggar, even rulers and subjects, teachers and people,
judges and prophets.

They have been corrupted both in heart and hand,
and they have dealt falsely and wickedly towards him and towards one another;
even to the great displeasure and vexation of him and his blessed spirit,
and to the high provocation of him to their own destruction,
if his long-suffering had not prevailed.
All this while he has lain as it were asleep, and at rest in himself.
He has left men to try them, what they will do, and he has given them a day.
Many kings and rulers, he has let them have a little time, to see how they would use it,
but they have abused it, and not ruled for him,
nor accomplished his work nor fulfilled his will, but acted even in defiance of him,
and of his power, and to his great dishonour.

Alack!
I must be plain with you: my Lord has been utterly exiled, and greatly dishonoured,
and highly provoked and vexed by reason of such proceedings,
as have been in this nation for these many years,
through the corruption of all sorts of men in place and power,
who have not ruled for him, but for the devil to their own corrupt ends.
He has allowed men to go on in their course for a season;
some as it were appearing on the stage for a time,
and suddenly cast down again for their iniquities sake;
and his hand has been in all these things, though very privately and secretly,
not known and discerned by the sons of men; yet has he ruled over the kingdoms of men,
and pulled down one, and set up another.

And to forbear the several actings and proceedings of many by-passed ages,
and to come to this generation,
and to speak of things that have happened within these few years,
and of the changing and overturning that has happened in this nation;
such was the cruelty, tyranny, oppression and idolatry both in church and civil state,
that the people of this nation were held under, in the days of papal power; such, I say,
was the exceeding height of the cruelty and tyranny of that time,
that not any that feared or reverenced my Lord, in any measure, could scarcely live,
or have a being in the nation.

Even against every man that did but incline towards him,
and desire the knowledge of his ways, hell`'s mouth was opened, and they were swallowed,
and many of their lives taken from the earth,
by the hellish power that had in that day usurped authority in this island.
When thus it was, then he looked down from heaven,
and his heart was opened in compassion,
for the sake of the oppressed people that desired after him,
in so much that he broke and threw down the power of their oppressors in some measure,
as it stood in papal authority, and when the iniquity of that power was filled up,
he took vengeance upon it.

And I must tell you, it was he that brought it about,
even the destroying of that power in this nation, and freeing the nation from it,
though the men that were instruments in the cause were not his servants,
otherwise than as Nebuchadnezzar served him.
For he has a secret way to have a service from the wicked, and such is his power,
that he can turn the wickedness of the wicked to his glory,
and he can make a rod to whip his adversaries, and burn it when he has done,
and he has often destroyed one wickedness by another.

But to leave that, though he did in some measure,
free the nation from much tyranny and cruelty, in the casting out popish authority,
yet alack! the nation in a few years was nearly as much violated by injustice and cruelty,
under the succeeding power, as ever it was once under the papal power.
Though before, there had been some small reformation and change in outward appearance,
though little in ground and nature; yet oppression, and idolatry, and superstition,
in church and state, and all profaneness and wickedness among people were grown so high,
like as it had been under the papal power before.
All that desired after the Lord, and were weary of iniquity,
and of the then present oppressions and idolatries, were persecuted, and slain,
and destroyed; and injustice and cruelty exercised upon them,
even almost to the rooting out of righteousness,
and to the grieving of the Lord`'s spirit.

Then, because of the cry of the people,
and the oppression of the nation under that authority, my Lord looked down again;
and even for his name`'s sake, and for his seed`'s sake,
he had compassion on this nation, to set it free, and to break off its oppressions.
In a great measure he did deliver the people of this nation in many things,
and there was a part of reformation wrought, and much pretended, and looked for.
All this came to pass through him, and my Lord did accomplish it,
however the instruments by which he wrought proved deceitful, and became oppressors,
as others before them.

And though there was in this nation a day of great troubles, and wars, and contention,
and great strife, and the wasting of much blood and earthly treasure,
and none of these things, I must tell you,
fell without the ordering of my Master`'s hand: yet so it was, and came to pass,
that after this nation was restored to peace,
though much unrighteousness and injustice was removed,
yet there was much also left behind.
Men that he had used as instruments in his hand, in a good work,
and to whom he had given wisdom and understanding,
and appeared in much mercy and in great deliverance,
yet they even turned to seek themselves,
and became corrupted in the spoils of their enemies.

When peace and plenty abounded, the Lord was forgotten again;
and then the land fell under oppressors, and began again to cry out for freedom,
even when other horns of the first beast sprang up, and went on each of them,
after his fellow.
And though one horn has striven to break another, yet after one has been cast down,
another has risen, and made an image to the first;
and ruled and reigned by the same spirit and authority,
derived from the dragon`'s power in cruelty and oppression;
and made laws and executed them to the dishonour of the Lord,
and to the great oppression of his people,
and to the filling of this island with injustice and cruelty,
even from one generation to another, until this day.

Thus up and down have times and seasons been altered,
powers and authorities changed and altered, statutes, laws, and decrees,
changeable and alterable; for as the iniquity of one power was filled up,
that was cast down, and another had its day, till the measure thereof was also filled up,
that it might partake of the same judgments.

In all these overturnings, breakings-down and overthrowings,
the very hand of my Lord has been, though secretly, and not discerned;
yet his power has brought about and permitted all these things to come to pass.
And who shall charge him with injustice?
Or, who shall say, "`What have you done?`"
Or, "`Why have you done it?`"
For, as I have said, he is a high and mighty prince, and can do whatever he will.
He is the supreme power and authority,
who rules and reigns in and overall the kingdoms of men.

What though he has used wicked men as an instrument to accomplish his work,
and made the wicked his rod; and even brought it to pass,
that one wickedness should destroy another, and one oppressor break down another,
and the kingdom of antichrist confound itself; yet what of all these things?
All flesh must be silent before him,
and all people and the whole earth must be subject unto him;
for the government and dominion over heaven and earth is his,
and all power and dominion belongs to him alone, and all judgment is in his hand,
to bring to pass whatever he will, and by whomever, as he pleases.

But now, my friends, though I would not be tedious to you, yet must I tell you the truth,
and faithfully deliver the Lord`'s message unto you.
As concerning this last overturning, there was something of the hand of my Lord in it.
He can, and will bring forth his own work and praise by it,
and it shall be for the good of all his people, that wait upon him,
though there was much ambition and corrupted ends in the instruments,
and neither part were perfectly single to the Lord in their proceedings,
but their work was tainted with the false idolatrous spirit of self-seeking.
Yet notwithstanding, the Lord may bring forth his government and his pleasant plant,
through and beyond all this, even out of another root,
which yet appears not among either of them; and righteousness may arise in the nation,
contrary to both of them, out of another stem, and he will set up his kingdom,
and in the meantime leave one potsherd of the earth to break another.

And as for you, that now sit on the throne and bear rule, whether committee of safety,
so called, chiefly, though it is not without my Master,
for he has the knowledge of it at least, yet you are not the only men of his choice,
truly called of him to the place of government,
neither is your government the government of the Lamb,
neither must it be forever established by him; its foundation is not blessed,
nor can its building be prosperous.
For why?
Alas, it is but another horn of that fourth beast,
that has been made to rule over the world, and upon the earth for many generations.
It is hitherto but a very little refined from the last, and is of the last,
even as the eighth was of the seventh spoken of by that servant, Rev. 17:11,
and it may also make war with the Lamb and his followers for a little season,
and it may have a small measure of injustice and persecution to bring forth in the land,
even till the words of God be fulfilled, and his kingdom be fully come,
the way of which is but yet preparing by all these overturnings.

And this your present government originally is leavened with the spirit of the old dragon,
that has killed the saints, and drunk their blood, and how should the Lord establish it?
Indeed, your kingdom may prove but small and little, and full of uproars and troubles,
and little peace, and satisfaction and establishment in it to yourselves,
or the people under you; but confusion will attend it, and fears will compass it about.

This I must tell you, as you are men, you have your day of trial what you will do,
as many others have had before you; and something you may and ought to do,
if but to make the false church, more naked, and to scourge her,
more than some others have done.
Indeed my Lord requires something more of you, (as such,) to do,
than others before you could do.
You have a price put into your hands, which you may improve to the Lord`'s honour,
and to the nation`'s good, and to your own happiness.

If you will be faithful to the Lord, to do what he requires of you,
and if you become meek and humble men, and fear his name, and deny yourselves,
and not seek your own honour, nor any earthly advantage to yourselves; if you do thus,
then my Lord will show mercy to you, and you shall not suddenly fall before your enemies,
though many may rise up against you.
Your days shall be lengthened,
and the purpose of the Lord may be turned to your longer continuance,
and not to your sudden destruction.
If you walk in this way, and rule only for the Lord,
then shall you be honoured as men if not as an authority,
and you and the nation preserved in peace,
and the force of the wicked shall be turned backward, and you shall not suddenly fall.

And the late sundry overturnings in this nation may be examples to you,
that you follow not the steps of those that God has cast out,
lest you come to the same end of confusion and misery.
For, as concerning that assembly of men, that last sat on the throne,
something was done by them in their day and time, and in both their assemblings,
in some things they served my Lord, and they were a rod in his hand to smite his enemies.
Yet they were not faithful to the end, till all his enemies were destroyed,
but rather joined themselves to fight against the Lord and his people,
and were hastening on towards the way of oppression and persecution.
It was time for the Lord to remove them, and to lay them aside as an empty vessel,
sometime useful; and to break them as a rod,
sometime of service to be a scourge upon his enemies.

And when the day of their trial was over, which God gave unto them, being no longer,
at present, fit instruments for his hand, then he cast them into the fire.
This his purpose came to pass upon them;
so that they and the whole nation may be contented,
and yield themselves subject to what he has done concerning them.
For they entering into the very same spirit of wickedness, of oppression and persecution,
which the Lord had once reproved through them, and cast out by them;
then was a rod raised up against them,
even as they had been against others and they were dealt with as they had done to others.
This was in the justice of my Lord`'s hand;
and what has mortal man to question his proceedings.

And though some of you,
(present rulers,) be looked upon as great traitors
and tyrants in your dealings towards them;
and doubtless the men of that party will seek vengeance against you,
even by preaching and praying, and they will curse you in the name of their God,
and seek continually your destruction, as such as have taken away part of their strength,
and cast down their idol.
But alas! all this is nothing; for the Lord does not account as men;
for these things must needs thus come to pass,
for the furtherance of the kingdom and government of Jesus Christ,
that it may arise through all.
If you were but faithful to what the Lord requires of you, in your proceedings,
what you have done unto them should not be reckoned in account against you,
neither by God, nor good men.

But if you of the army be always treacherous and disobedient towards him,
and abuse your power, and disregard your price that God has given you,
and trifle away your hour about places of honour, and such self-seeking matters,
and the cause of God be neglected by you,
and his people continued oppressed sufferers under you, as they have long been;
even then shall you be cast aside with shameful disgrace,
and the heavy hand of the Lord shall be upon you in judgment.
You shall be smitten more than any before you;
your estates shall not be spared from the spoiler, nor your souls from the pit,
nor your persons from the violence of men, no, nor your necks from the axe.

If you be unfaithful, and continually treacherous to the cause of God,
then shall you be left to the will of your enemies,
and they shall charge treachery and treason upon you,
and your persons and estates shall be given for a prey to your enemies;
and you shall not deliver yourselves,
neither will the Lord deliver you from the execution of merciless men;
for my Lord shall leave the cruel hearted to plead with you.

Therefore, that you may be warned, I advise you to be faithful.
Let not the cause of God fall, nor the cause of his enemies prosper before you;
for there is no other way whereby you can be preserved,
nor any other defence shall you ever find from the wrath of the Lord,
and from the fury of your devouring enemies, than your faithfulness in God`'s cause.
Therefore relieve the oppressed, and take off all oppression, break down all unjust laws,
and set all people free from unjust burdens, and let all oppression cease,
both in church and civil state, and even all oppressive laws, and unjust judges,
and evil men in power.
Let all these be removed, and the nation clean quitted and discharged,
even from all men and laws whatsoever, that have held under oppression the persons,
estates, and consciences of the good people of this land.
Let the nation be corrected, and all orders and places of men,
and laws and decrees be purified.

This my Lord, the great King, requires,
and he will suddenly have it brought to pass in the nation, if not by you,
then contrary to you, and to your utter destruction.
This is the very substance of my message to you,
that my Master has given me to say unto you;
and on his behalf I am come to claim of you my Master`'s long lost right.
Let him have his right, from which he has long been banished.
I demand it of you, all you whomsoever, that seem to bear rule in the nation.
I charge you in his name let him have his title and prerogative,
let him be Lord and King, wholly in his own kingdom.
Let him have the exercise of his people`'s consciences by his own
Spirit in all things relating to his worship and service;
and let him have the full authority by his Spirit
in all things pertaining to church and ministry,
and faith, and religion.

Let his Spirit have the alone authority to persuade and dissuade people from, or to,
such or such ministry, worship, and practices of religion;
and let all forced maintenance to ministers, and tithes, be speedily taken away.
Let all laws and decrees whatsoever, made and practised in the days of antichrist,
upon the bodies, estates, and consciences of the people,
in oppression and unjustness about church and worship, and religion, be utterly repealed,
and made void, and never more be in force in this nation.
But let my Lord be sole ruler and governour,
and have the full authority in his own kingdom,
in all things whatsoever pertaining thereunto.

And let no man henceforth hereafter be entrusted
with the liberties of the members of Christ`'s kingdom,
as they are such, nor to judge over them in any matters of faith and worship,
but give that right and privilege wholly unto the Spirit of Jesus Christ.
Unto him only it pertains to be whole judge, and to have full power in his own kingdom;
and until you give him the right, and deliver up unto him his own kingdom,
and the exercise of peoples`' consciences in all things about religion,
you shall never prosper, nor any that comes after you,
that shall in any measure abridge my Master of his proper right,
from which he has long been banished, as I have said.
Till his right be given him, in the case aforesaid, he will dash one man against another,
and none shall ever be established; but horn after horn shall be broken,
and one power after another brought into confusion.

And, therefore, you men, do not strive with him in this matter,
but yield unto him the exercise of your own consciences by his Spirit in you,
and let him do so unto all others, even as you hope to prosper,
and upon the penalty of his sore displeasure upon you in this world,
and in the world to come.
Let just men, and righteous men, and meek men,
and men that have the fear and wisdom of God in them, without acceptation of birth,
or otherwise; let such men have the power and judgment committed to them,
to determine in things between man and man.
Down with all the false-hearted flatterers, that have ruled for man and not for God,
and for themselves, and not for the good of the people; cast all such out from you;
for the good among you is choked by them.
Down with all that judge for rewards; and away with all hireling rulers,
that execute the law for money,
and will not plead the cause of the poor without great fees.
Down with all that will not serve places of trust without so large stipends.

Away with all these things out of the land, for they are heinous oppressions unto men,
and great abominations in the sight of God;
and the land has long groaned under the weight and burden of these things,
and the earth is weary of them, and my Lord requires their utter dissolution,
as being iniquities fully ripe, and having the guilt of so much cruelty,
injustice and oppression lying upon the nation because hereof.
Therefore this is the Lord`'s season to destroy them, and remove them out of the land;
and if you be the instruments in such a work, it will be your greatest crown,
and your perpetual honour.

The Lord`'s purpose is one way or other to cleanse
the land of all these and other oppressions whatsoever,
that the people of this land may be a free people from all the heavy yokes of antichrist,
which have long sorely pressed them down.
And the purpose of the Lord is to break the yokes of oppression
and tyranny from off the necks of his people;
and therefore it is that he overturns, yes, and will overturn,
all men and authorities that shall oppose his work,
and none shall be able to stand before him.

The presence of my Lord is more dreadful to a nation, when he shows himself in wrath,
than any multitude of armed men; and woe is unto you, if you be found opposing of him;
and if you seek to stop his work, you shall not cumber the earth very long,
nor oppress the nations many days.
Therefore consider, cursed will you be,
if you be unfaithful in what you have to do on the Lord`'s behalf;
for your hour passes over, that is allotted you; and will be suddenly expired,
never to be recalled, and then you cannot work.

And whereas there is a great cry about ministry, for sending forth and maintaining,
and encouraging a godly ministry, as you say:

Now to this I do answer on my Lord`'s behalf, and I must tell you plainly;
as for a true godly ministry, truly called and sent of God, such a ministry,
and such ministers you can never be able to hinder.
The Lord will send them out, maintaining them and preserving them,
whether you will or no; and while you are troubling yourselves about such a matter,
you are but meddling with things above your line, and out of your jurisdiction,
while you act in such a case.
For it belongs to his government to send out ministers, whom, and as he will,
and to maintain them and defend them according to his own pleasure,
and all this without you.

Such ministers, truly called thereunto, and sent of the Lord,
will not seek to you to be sent forth, or maintained by you,
they will not be beholden to you in such a case; but even without you,
and contrary to you, must they be sent out and maintained.
So that the Lord will have a ministry in this nation purely of his own, and not of man,
nor by man, and such a ministry you shall not be able to hinder.

And I must tell you plainly, as for these men called ministers, in this nation,
the way of their setting up, and sending forth, and the way of their maintenance,
and the way of their standing and defence, and in every particular of their being such,
they are the greatest and most woeful oppression in the nation.
Even the most abominable and unjust cruelties and tyrannies are acted through them,
as any other thing in the nation; and they are,
(as such aforesaid,) the woeful cause of the nation`'s groaning under merciless dealing.
There is upon their account, the guilt of blood, injustice,
and oppression lying upon this nation.
Their iniquities, their iniquities, cry for vengeance upon their own heads;
for they are full, they are full, and the measure thereof is near finished,
and God`'s eternal vengeance is their next reward from the eternal God.

What shall I say of them, but this?
The earth is oppressed by them, the inhabitants groan under them,
and the righteous God is vexed through them,
and they are the very men of high indignation and fierce wrath, and all their practices,
as such, are the fuel of his anger, to be consumed by the fire of his jealousy.
The nation is weary, and its inhabitants, and the Lord is weary, because of these men.

And is this the ministry cried up by you as godly and pious?
etc. Are these the men that the nation must be forced
to maintain in their pride and idolatry?
Is this the ministry that must be encouraged?
Well, if these be the men,
and this the ministry which must be established and encouraged by you,
in so doing you shall never prosper,
but thereby gain the displeasure of the Almighty unto you,
to bring a curse upon all your doings, even because hereof.
For I must tell you, the hand of my Lord is against them,
and whoever shall seek to defend them shall not prosper in their doings,
because their oppressions, cruelties, deceits and abominations,
are nearly finished and fulfilled.

Therefore take heed unto yourselves, for this is my Master`'s advice unto you;
let this ministry alone, and join not yourselves to Baal, lest you perish,
neither take part with antichrist any longer,
neither be fighters against the Lamb and his kingdom; but free the nation,
and let all its inhabitants be freed from the cruel tasks and yokes of such men,
and such a ministry as aforesaid.
Uphold it not against the Lord, for if you do, you shall never be established;
this is from the mouth of my Lord unto you.

And, last of all, my Master has a people in this nation, even a suffering people,
that have borne the burden of the cruelty and injustice, and wickedness,
both of rulers and teachers, who have, as it were, trodden them down,
and made them a very prey to their devouring mouths.
The very cry of their sufferings has reached unto heaven,
and the very sound thereof your ears have heard.
This people are greatly beloved, and my Lord will assuredly honour them,
and his hand shall be continued to preserve them
and defend them against all their enemies whatsoever.
He does reserve them to himself, and for a glorious work that he has to do by them;
and he has formed them for himself,
and they cannot join with any of the horns of the great beast,
neither can a place of honour pervert them from their perfect way.

My Lord compasses them about on every side, and has kept them in the midst of trials,
reproaches and sufferings, and covered them in the heat, and in the storm,
till his pleasure is to make further use of them.
They are his, and not their own; and they must fulfill his will, and none besides.
They lie at rest in him, while mountains are overturned,
and while one potsherd of the earth breaks another;
and this must be even till the appointed time.
To say no more of them, though much more might be said,
they are had in remembrance before the Lord, to do with them even for his own glory,
and for the nation`'s perpetual good.

To the authority of the Most High, through them, shall kings of the earth,
and nations of the world bow and tremble.
Therefore, you men, touch them not, neither afflict them, even as you hope to prosper.
Remember their cause, and allow it not always to be rejected, as it has long been.
Keep yourselves free from the injustice and cruelty of them that have gone before you,
who have been merciless, and oppressors of that people,
even till my Lord has confounded them, and brought them into confusion;
for there is the weight of blood, tyranny and oppression,
lying upon the nation in that people`'s cause,
and my Lord will avenge them in his season.

Though they are not weary of their sufferings,
but are in the patience which bears all things, yet the nation can never be happy,
nor its government ever blessed, while this people are held in bondage.
Their sufferings are deeply considered of the Lord,
and the season thereof is drawing towards an end.
When this comes to pass, then woe unto the kingdom of antichrist,
and to the false church and prophet, even when their strength is dried up,
by which they have made war against the Lamb and his followers: yes, woe unto them.
Great fearfulness shall be upon all the world when
the King of that people reigns upon the earth,
and the time is at hand.
Blessed is the man that waits for it,
and blessed is he that is not offended in his coming,
but is prepared to receive him in his appearing, which suddenly comes upon all the world.

Thus I have told the Lord`'s present message unto you, which I received from him,
and thus far I am clear; and whether you accept it or reject it,
my peace and reward is forever with him, who am a subject of his kingdom,
and a friend to this nation, however otherwise judged by ignorant men.

Edward Burrough.

Ninth month, 1659.

How strongly prophetic the language in the foregoing,
"`Your estates shall not be spared from the spoiler, nor your necks from the axe;
your enemies shall charge treason upon you, and if you seek to stop the Lord`'s work,
you shall not cumber the earth very long.`"
Monk was about preparing to move into England with the army from Scotland,
and then came the Restoration, with its train of imprisonments, banishments,
confiscations, and death.
