== Chapter IX.

In the ninth month, 1659,
after writing the Address to the rulers given in our last chapter,
Edward Burrough left London.
In the same month we find him at East Hamstead in Berkshire, at a public dispute,
which was held on the challenge of the priest, Christopher Fowler,
and some of his clerical brethren.
Two positions affirmed that day by the priest,
were that "`The Scriptures are the glorious everlasting
foundation of foundations;`" and also,
that "`A man may at one and the same time, be a minister of Christ and a deceiver.`"
Little good appears to have resulted from this meeting, for Fowler hastily withdrew,
and Edward unavailingly sought to have another opportunity with him.
On the 26th of the ninth month, soon after Edward had passed out of that neighbourhood,
Christopher Fowler drew up a paper against the people called Quakers,
consisting of ten particulars.
He said he was able to sustain these charges against them,
and was willing to let them choose their own time for a public debate,
and it might be as soon as they pleased.
Edward Burrough received a copy of Fowler`'s paper, and sent him word that on fourth-day,
the 21st of the tenth month, he would meet with him at Reading.

Fowler perhaps did not desire to debate with Edward,
at least he declined meeting him at the time and place designated,
although in the challenge he had left this to be fixed by the Quakers.
He said Reading was not a suitable place, proposed Oakingham in the same county,
and suggested another time.
Edward came to Reading two days before the time he had appointed for the dispute,
and there he received the priest`'s reply.
He had appointed meetings at several places,
and he found that he could not be at Oakingham at the time designated.
He also considered Reading, the town where Fowler preached,
as the most suitable place for the dispute.
Accordingly he wrote to Fowler, letting him know that he was at Reading,
ready to dispute with him, but could not be at Oakingham at the time he designated.
Fowler in reply, said, he would not meet him at Reading,
for there was no need of dispute there.
Edward finding that the public dispute would fall through, answered the charges in print.

Thomas Curtis was with Edward in his travels through Hertfordshire,
and perhaps James Nayler.
They passed northward into Buckinghamshire,
and in the tenth month held a meeting at a place called
"`The Grove,`" about a mile from the house of Isaac Penington.
This meeting was remarkable as that at which Thomas
Ellwood was convinced of the truth of Quakerism.
The whole ministerial service of the meeting fell upon Edward.
Thomas says the ministry not only convinced his understanding,
but warmed his heart with a heat,
which till then he had never felt under the ministry of any man.

When the meeting was over the three friends went to the house of Isaac Penington,
where Thomas Ellwood, with his father and sisters, were on a visit.
In conversation with Edward,
Thomas`'s father advanced the Calvinistic doctrine of personal predestination,
in opposition to the universal free grace of Christ Jesus,
but he soon found himself at a loss for argument to sustain his position.
Edward said little in reply to him, but James Nayler took up the subject,
and as Thomas says, "`handled it with so much perspicuity and clear demonstration,
that his reasoning seemed irresistible; and so I suppose my father found it,
which made him willing to drop the discourse.
As for Edward Burrough, he was a brisk young man, of a ready tongue.`"

"`The next morning we prepared to return home, that is, my father, my youngest sister,
and myself; when having taken leave of our friends,
we went forth,--they with Edward Burrough accompanying us to the gate,
he there directed his speech in a few words to each of us severally,
according to the sense he had of our several conditions.
And when we were gone off, and they gone in again, they asked him what he thought of us?
He answered them, as they afterwards told me, to this effect: '`As for the old man,
he is settled on his lees; and the young woman is light and airy;
but the young man is reached,
and may do well if he does not lose it.`' Surely that which he said to me,
or rather that spirit in which he spoke it, took such fast hold on me,
that I felt sadness and trouble come over me,
though I did not distinctly understand what I was troubled for.`"

A few weeks after this interview,
Thomas Ellwood going with Isaac Penington to a meeting at Wiccomb,
again met with Edward Burrough, who had come there from Oxford.
It was a monthly meeting, "`consisting of Friends chiefly,
who gathered to it from several parts of the country thereabouts;
so that it was pretty large,`" Thomas Ellwood says, "`A very good,
meeting was this in itself and to me.
Edward Burrough`'s ministry came forth among us in life and power,
and the assembly was covered therewith.
I also, according to my small capacity, had a share in it.
For I felt some of that divine power working my spirit into a great tenderness,
and not only confirming me in the course I had already entered,
and strengthening me to go on therein; but also rending the veil somewhat further,
and clearing my understanding on some other things which I had not seen before.`"

"`Edward Burrough going home with Isaac Penington, he invited me to go back with him,
which I willingly consented to.
For the love I had more particularly to Edward Burrough,
through whose ministry I had received the first awakening stroke,
drew me to desire his company, and so away we rode together.
But I was somewhat disappointed of my expectation;
for I hoped he would have given me both opportunity
and encouragement to have opened myself to him,
and to have poured forth my complaints, fears, doubts and questionings into his bosom.
But he, being sensible that I was truly reached, and that the witness of God was raised,
and the work of God rightly begun in me--chose to
leave me to the guidance of the good spirit in myself,
the Counsellor that could resolve all doubts,
that I might not have any dependence on man.
Therefore, although he was naturally of an open and free temper and carriage,
and was afterwards always very familiar and affectionately kind to me;
yet at this time he kept himself somewhat reserved,
and showed only common kindness to me.
Next day we parted, he for London and I for home.`"

This was about the beginning of the eleventh month.
In that same month,
Edward wrote a postscript to Francis Howgill`'s Heart
of New England Hardened Through Wickedness.
This contains a sharp reproof to that hard-hearted, liberty-loving,
as well as liberty-restricting people.
It thus concludes: "`O, have you forgotten since you were sufferers yourselves?
Then it was well with you,--far better than now.
You are at ease in the flesh and have forgotten God,
and lost that sincerity which once was in you.
The very spirit of the old Bishops which once persecuted you,
has entered into your hearts, and now lives in you and acts in you.
In the days of your prosperity you are exalted, and have forgotten the Lord,
and you requite him evil for his love.`"
This is very descriptive of the spirit manifested about the time this letter was written,
and for many previous years, by the magistrates and priests of the Massachusetts colony.
Edward`'s feelings were keenly sensitive to the sufferings of his fellow-believers,
and he laboured fervently in various ways to stop
the persecution then raging against them in New England.
On the 24th of the eleventh month, he wrote the following letter to Parliament;

Friends,

All these overturnings, and almost wonderful changings,
were effected through the justice of the Lord`'s hand.
You are now again at the helm of government, and on the throne;
and I dare not but say it is of and by the Lord,
and that he has done it contrary to the expectations of many; and what his end is in it,
remains with him.
But I am sure one cause is,
that you may execute part of his wrath upon that treacherous
generation of hypocritical and deceitful men,
some of the army I mean.
I need not say to you, how that many of them were raised up from a low estate; and,
instead of serving the nation, became their lords and oppressors.
They have abused the Lord`'s mercy to them, and exalted themselves,
and became as great oppressors, and as grievous to the nation,
as ever they were that went before them.
Some of them took the very tithes and estates of their enemies,
and followed their evil spirit also, though the Lord was long-suffering to them,
and gave them a day, and put opportunity into their hands,
wherein they might have done good.

But they also neglected to serve God and the nation, to serve themselves;
and because of the ambition and pride of some of them,
the Lord permitted them to make this last interruption upon you,
which was great treachery in man`'s account,
that thereby their measure might be filled up,
and that he might give you occasion against them,
and allow you to be filled with indignation towards them, to break them to pieces.
What you do to some of them, in casting them out, and afflicting them,
you are but God`'s executioners therein; you are the executioners of his anger,
in what you do to them; and who shall prevent you, or forbid him to go on?
For they have long enough dissembled with this nation, in professing more than others,
and doing less, and their downfall is now.
And God has looked upon you, to be hard-hearted and cruel enough,
and very fit executioners of vengeance upon such men, as I have mentioned.

But now concerning you, and your present state, as you are in present place and power,
I have something to say to you.
Though they are fallen, and you yet stand, and you have a little time after them;
do not glory over their fall, neither glory as though you should stand forever;
for they were not greater sinners than you are,
neither are you one whit more righteous than some of them; but you are as sure to fall,
as they are fallen,
with no less measure of dishonour and affliction than is come upon them;
and you are in your last hour.
I dare not say, that God expects much more from you, than for the end aforesaid, namely,
to be the executioners of justice upon men as sinful as yourselves;
so do not glory over them that are fallen.

But know that your time also is but short, and your fall may prove to your destruction,
and theirs may prove to make them better, and refine them.
If God has chosen you to execute some part of his wrath upon them, for their wickedness,
he will doubtless find instruments to execute his wrath upon you,
else he will do it with his own hands; for he purposes not to spare you;
for your sins cry as loud as any other people`'s,
and the oppressions are as great under you, as under them whom you condemn.
I desire, if there be any good men among you, that such who are wise may consider,
and mind the hand of the Lord in and through all these things that are come to pass;
for God is working as well as you, he is seeking to set up a kingdom as well as you,
and his government and yours cannot stand together;
and he will make you know that he is stronger, and his government of more force,
and your kingdom cannot stand in place with his.

Therefore, Oh that you would take heed!
Oh that you would be wise, if so be some of you may be spared.
And be not too zealous in your way, nor too furious in your proceedings;
do but to others as you intend to receive from others, and from the Lord.
Go not beyond your commission; for a permission at least you have had from God,
even to scourge hypocrites, and to be a judgment upon that hypocritical,
seeming religious generation of men aforesaid,
which have many a time as it were mocked God, and pretended love to him with their lips,
when their hearts have yearned after self-honour, and the treasures of this world.
I say, your present hour and permission is for this end,
but not to persecute the people of the Lord, nor to destroy God`'s heritage;
but if you shall extend your power unto such a work,
and if you do persecute the innocent without cause,
and make war against the Lamb and his followers,
and make laws and execute them to the oppression of the saints of the Most High,
then you go beyond your commission; for God has not called you unto this,
but to be instruments in another cause.

The children of Zion, trust in the living God and fear not the terror of mighty men,
neither can they be afraid at the roaring of the sea,
nor at the present threatening of the heathen, for God is with them.
I say unto you,
the servant of the Lord has pondered and considered all these proceedings,
and viewed the present state of things at this day,
and there is no vision from God unto you of peace and comfort,
nor of a happy and lasting government, as you stand.
If any prophet shall divine this unto you, he speaks what he has not from the Lord,
but the vision of his own heart, and he deceives you and himself;
for you are not established upon a right foundation,
neither are you acted by a right spirit, which can truly govern for God;
but the spirit of wrath and fury is put into you, for the work to which you are called.
I know not how to warn you, that you do not persecute the people of God.
For why?
It may be you must fill up your measure of wickedness thereby,
that God may break you perpetually; yet the less will be your judgment, if you do it not.
But if you do it, the Lord will take occasion against you, to wound you,
and you shall never be healed, and as you do afflict others,
so and much more shall it be done unto you from the Lord.

Therefore, consider what I have said; for this is the vision of the Almighty unto you,
that shall not go unfulfilled.
What you do, you must do it quickly; for your time is short,
and your power will God subdue;
and his kingdom and power will he speedily exalt over your heads,
and make you and the nations know that he is God, and that all power is with him,
and that he can do whatever he will; and it is his right alone to reign,
and his children`'s portion to possess the kingdom with him.
Let the whole earth, and all the powers thereof, bow and tremble before him;
let not your hearts be stout and rebellious against him, for he can grind you to powder,
and sink you into confusion and misery, as a stone into the sea.

This was directed for the hands of the speaker in Parliament,
and accordingly was given to William Lenthal,
being enclosed to him with these lines following:

Friend,

The enclosed I do commend unto you to present unto the House,
and to endeavour sincerely the reading of it in your assembly;
for it is of special concernment to you all.
In the name of the Lord, and by his Spirit,
I do charge you not to be negligent in this matter,
as though it were not of worth to you.
I lay it upon you, as you will answer the contrary at the dreadful day of God,
when the King of righteousness shall judge you and all mankind.

Edward Burrough.

The 24th of the eleventh month, 1659.

About the close of 1658 Edward Burrough had met with a paper circulated for signatures,
which purported to be a free call to William Brunsward to exercise his ministry at Kendal.
On this, Edward had addressed some queries to the said Brunsward,
relative to his call to the ministry and a few other subjects,
concluding with a proposition to hold a public discussion with him at Kendal.
No notice was taken of this challenge,
but Brunsward soon afterward attempted to revenge himself on Edward,
for the doubt insinuated in the Queries as to his true call to the ministry,
by writing a book, entitled The Quaker-Jesuit, or Popery in Quakerism.
This book was answered by John Story, in a tract called Babylon`'s Defence Broken Down,
and One of Antichrist`'s Warriors Defeated.
Edward Burrough added some remarks to this,
publishing the Queries he had formerly sent to Brunsward,
and renewing the challenge to meet him at Kendal.
He says, "`These things I am willing to travel through in discourse with you,
the said William Brunsward, or any other that shall accept of the propositions,
with the consent of the mayor and aldermen of the town,
who may preserve the place and people in peace and soberness; also provided,
that each of us on both parts may have full deliberation
to speak forth our minds pertinently to the matter,
and that each may have silence from the other, while he is speaking;
that all fair and sober dealing be among us, and the fear of God.`"

Addressing Brunsward and his party in Kendal, he says, "`I am a lover of your souls,
and a friend to righteousness;
and daily travail in the work of the Gospel to the
intent that sinners may be converted to God,
and the saints be strengthened in the faith which gives them victory over the world;
and I wait for Zion`'s redemption, and for the overthrow of great Babylon,
that has ruled over the kings of the earth.`"

About this time an Address, signed by sixty-one ministers of the city of London,
was published under the title of A Seasonable Exhortation;
in which they treat on the present distracted state of the nation,
in respect both to civil and religious affairs.
Among the evidences of the deplorable condition of the nation,
they adduce "`The many horrid and hideous errors which for some years past have abounded,
against the authority of Scriptures, the deity of Christ, the Holy Spirit,
Trinity of persons, immortality of souls, doctrines of repentance, humiliation,
sanctification, resurrection of the dead,
and the eternal recompense of heaven and hell,`" "`and the
various sects increasing every day in number and power,
and under the names of Quakers, Ranters, Seekers, etc.,
oppugning the received doctrine and unquestionable interest of Christ Jesus.`"

To these heavy accusations against the society of Friends,
Edward Burrough published a reply, entitled, A Return to the Ministers of London,
in which he successfully refutes the accusations,
and gives much pertinent advice to the authors of them.
From this Essay the following is extracted:

That many horrid errors have abounded among you, is very true,
as in many particulars might be instanced.
But why do you maliciously charge the Quakers with opposing the interest of Christ Jesus?
The Lord shall judge you in his day, when he makes it appear to all the world,
that those whom you charge with the contrary, are the very friends of Christ`'s interest,
and have been patient sufferers for his name sake,
under the wickedness of your generation.
As for the Ranters, Seekers, and others, whom you have reckoned up with the Quakers,
it is well known that we are in opposition in spirit unto all these,
and have given large testimony in the fear of God against them.

What the Seekers, Ranters, Familists, and the rest mentioned by you, do hold,
as in these things you have charged them with, I will leave that,
for I am not now pleading their cause, but the cause of God and his people,
whom you in scorn called Quakers.
And though you have joined them in accusation with others,
yet I must separate them from others in my answer,
and must tell you in the fear of the Lord, that you have belied them,
and falsely accused them.
For they do not deny the authority of the Scriptures, but give that authority to them,
which the spirit of God that gave them forth has formerly given.
Neither do they deny the Deity of Christ, but do say,
In him dwells the fullness of the Godhead; neither do they deny the Holy Spirit,
nor the Father, Son, and Spirit, but say there are three, and these three are one;
but as for your Trinity of Persons, that is language beside the Scriptures.
We do affirm the soul is immortal: and as for the doctrines of repentance, humiliation,
sanctification, resurrection from the dead, the eternal recompense of heaven and hell;
these doctrines are publicly held forth by them in words, and also in practice,
more than by yourselves.
Therefore with what face you could charge them with the denial of these things,
is almost wonderful.
There are thousands of your congregations that are
and have been sometimes hearing them in your city,
that shall bear witness against your accusations,
and give evidence that they have heard them whom you call Quakers,
give faithful witness of and for all these things
which you charge them with the denial of.
Do you think that your congregations are all so blind
as to receive for truth what you have herein spoken;
no, I must tell you, some of them are offended with you because hereof.

On the first day of the third month, 1660, Edward Burrough being in Oxfordshire,
felt a concern that his brethren should be preserved
in the true place of spiritual safety,
amid the tumults, agitations, and fears which were shaking the nation,
at the bringing in of King Charles II.,
and addressed them in an Epistle which contained the following:

Dearly Beloved,

Whom the Father has called and chosen into the election of eternal salvation,
and who have handled, and tasted, and felt of the judgments and mercies of the Lord;
and among whom the God of heaven and earth has appeared in his Spirit, and in his power,
which has begotten you into the heirship of the heavenly kingdom.

Oh Friends! our kingdom and victory are not of this world, nor earthly, but from above,
and spiritual; wherein we have peace and comfort, endless and everlasting,
which the world knows not of.
I say unto you all that know these things, Live in the peace, and victory,
and kingdom which is invisible, and mind the things, as your greatest treasure,
that pertain to that kingdom, even the weighty matters of it,
which are eternal and infinite;
and that every one of you may feel and enjoy a portion in that kingdom.
It is precious for a people to be subjects of the heavenly kingdom,
and for a man to have an assurance of life and peace in God;
to be an heir of that kingdom that fades not away,
and to have his name written in the record of Life.
Blessed is everyone whose hope and confidence,
and peace and assurance are in the living God,
and whose soul rests under the government of the Almighty, and who knows him to be Judge,
King, and Lawgiver in all things.
This is the kingdom that is heavenly, and is altogether blessed; for peace, and truth,
and righteousness, and all virtue are enjoyed in it forevermore.

Now Friends, you must all be subjected in all things under the power of the Lord God,
and unto his will, and he must work in you to will and to do;
for in this is true rest and peace unto the soul,
where the will of the Father is done and suffered in all things, and not the will of man,
which works sorrow to the creature, and not peace, in the obedience to it,
and where it rules.
That must be subjected in you, even in every word, work, and motion,
unto the eternal Power, that you may die, and Christ may live.
In this you will have union and fellowship in spirit with the Lord God,
and he alone will be your trust and confidence, and your glory.
If he live in you, and walk in you, then you are his people, and he is your God.

Friends are to mind this, even peace, and union, and fellowship with the Lord,
and the comfort of his presence, which is the only happiness of the creature,
even the enjoyment of him that is invisible, who is God infinite over all,
to whom mortal eye cannot approach, neither can the mortal mind apprehend,
but in his own life manifested in mortal flesh,
and by the measure of his own Spirit that dwells in us is he seen, felt, perceived,
and enjoyed of us.
So mind the immortal life begotten of the Father in you, that that may live in you,
even the Heir of God, which is his image and likeness,
for in that alone is covenant with God made and kept,
and in it is the Father`'s presence enjoyed, and he worshipped without respect of time,
place, or visible thing.
If that live in you, then you in that will live unto God,
in all that is answerable unto him.
Your words and works will be accepted of him, and well-pleasing to him,
even because it is he that works in you to will and to do all good things.
He alone is exalted in you, and you subjected, and the Maker is become the Husband,
and you married unto him.
He lives in power, and rule, and command, and you live in subjection unto him,
and in fulfilling his will in what he guides in, by his Holy Spirit.
And this life is very precious.

Oh, Friends! live in it, and dwell in it always,
and then your joy and peace will be over all this world,
and you will be comforted when fear and terror comes upon all men.
For the Lord God whom we serve and worship in the spirit,
will cause his enemies to know his power; and that he does and can do whatever he will,
and will smite his enemies, and wound them in their consciences; for all power, dominion,
and authority are with him, he is mighty to save, and mighty to destroy,
and his reward is to everyone according to their deeds.

This is the God whom we fear and worship, and all flesh must bow before him,
when he shows his presence; though men be high and lifted up,
and go on in rebellion against him without fear,
yet the hand of the Lord will be upon them,
and he shall smite them with the rod of his mouth.
Therefore all Friends,
have respect unto the Lord in your hearts in all things that you do,
and in all things that come to pass, for that is blessed in a people;
and they shall prosper, their souls shall be nourished,
and their lives refreshed with the mercies of the Lord,
even all they that wait upon the Lord, and have respect unto him and his eternal power,
which does and permits all things that be.
In this power you must dwell and walk, and feel it in your hearts,
and it will be your armour and defence in all things,
and it will carry you through all that which works contrary.

It is very precious to be armed with the armour of God,
in the day of temptations and trials, that you may not be overcome of the wicked,
nor spoiled of the heavenly inheritance.
Oh Friends! put on strength, that you may stand,
and never be moved from the hope of eternal life,
and feel the renewing of your inward man,
even the increase and growth of the immortal life in you,
that you may live in that unto the Lord God,
and that your covenant with him may be preserved,
whereby you may be a praise and a glory to him in
your generation in the sight of the whole world.

You who have tasted of the presence and power of the Lord,
and who have known his mercies and judgments, and been acquainted with him,
may you be kept faithful unto the end, and not be subverted by the wicked one,
nor drawn from obedience to the truth, nor lose your crown of immortality,
neither by the flattery nor terror of the ungodly,
but that you live in the dominion of immortal life,
which keeps above all temptations and terror, and gives authority over all.
This life is blessed, where the glory and peace of this world,
and the troubles and sorrows of it also, are seen over, and felt beyond,
and nothing of it can move the heart, nor disquiet the spirit,
nor work any separation from the Father`'s love.
In the Seed of God, where it lives above mortal,
is this enjoyed by us and all the faithful.

But if the man`'s part live above the Seed of God,
that will be drawn aside by the love or by the terror of this world,
for that is changeable, and the evil one has a part in it.
So that part is to be kept in subjection in you, under the Seed of God,
and it must bear the cross of Christ always, else you will be overcome of the wicked.
For in that part (the man`'s part) which is of this world, the devil has something,
a place to receive him, and part to obey him; but in the Seed of God he has nothing,
neither place nor part.
And so Friends live in the Seed of God,
for in that is your victory and heavenly dominion,
and also your election and assurance forever, even in the second birth,
begotten of the Father; for that is the Heir of God,
and therein does man inherit eternal life, and rest and peace to his soul.
Therein are blessings and peace, and life inwardly and outwardly,
and all fulness is enjoyed.
Here the Lord is the Teacher, the Father, the Shepherd, the Master, the King and Judge.
He is become to us the all in all, and the kingdom is delivered to him,
and all subjected under him, even God with us, the Substance of all, the End of all.
All the contrary is put under, even the lion and the lamb laid down together,
and man lives in peace according to the promise;
and the mountain of the Lord`'s house is established on the top of all,
in which nothing can destroy or hurt the pure life; but life is in dominion over all,
and death is swallowed up of it.

Oh Friends! this is the mark that is before you.
Press on towards it, that you may obtain the final end of all your travail and waiting,
of your obedience and suffering, the end of your hope and patience,
and the very end of the message sent of God, and delivered to you by us.
The end of all is this, That you may dwell in God, and he in you,
and be gathered up to him, to be ever with him; and that he may be your all in all,
and you may be to him an honour and praise throughout the world, in your generation;
even he your only God, and you his people.

Friends, certain it is, that the way of life, and peace,
and of salvation is made manifest unto you,
and you know wherein everlasting peace and reconciliation with God stand.
You also know, what the cause is of all trouble, and sorrow, and condemnation.
The Lord has opened many hearts, and given unto many a good understanding.
And seeing you know this, live in the way of peace, and escape the other,
that you may not come into condemnation;
for it is a fearful thing to fall into the condemnation and wrath of the Almighty.

For this cause, that men should be saved from wrath, and have peace with God,
the Lord has sent abroad plentifully in this nation the message of life and salvation,
and you have received it, and believed the report,
though many have rejected it to their destruction, whose judgment will be upon them.
But you have tasted, handled, and felt of the Word of eternal life,
by which the Lord has wounded you, and healed you again; and many has he slain,
and made them alive, even through his word and power, which has entered into many hearts,
which kills the enmity, and quickens the seed,
and which breaks off from all the world`'s fellowship,
both in transgressions and righteousness, and makes all void,
all covenants with death and hell, and marries unto the Lamb.

Oh Friends! wait upon the Lord, that you may possess these things; for to know them,
and be in them, is everlasting treasure and riches;
the possession of them is riches to the poor, bread to the hungry, clothing to the naked,
and life to the dead.
And if you know these things, lay them up in your hearts, as your most precious treasure,
and let none spoil you of it.
And if you are married unto the Lamb, then are you the true and only Church,
even his body and living members of it; for such only are the true Church,
that are married to Christ, and united to him in his own nature.
And in that you have received the truth, and do know the truth, live in it,
and walk in it in all faithfulness.
Be not fearful and unbelieving, as though the Lord were not with you,
though you suffer much for his namesake;
for he is not lacking unto that man that does fear his name, and that walks in his way;
but for the deliverance of all such will he appear.
He will free the oppressed, and the afflicted people he will save,
even by his outstretched arm.
Therefore let our eye be unto the Lord in all states and conditions,
whether of sufferings or otherwise, for from him salvation comes,
and not from the mountains of the earth.
Keep your meetings in your several places and be faithful in all things,
that your consciences may be kept void of offence, both towards God and men,
that no disobedience or load of iniquity may be upon you, but that in the sight of God,
you may feel clearness and freedom of soul and spirit,
from the burden of all transgression, that you may know the remission of all sin,
and all iniquity may be blotted out, and no guilt of transgression may lie upon you,
but you may enjoy peace in your consciences,
in the sanctification and justification of the new man; and this is the heavenly life,
even upon earth.

And when you are met together in the name and power of the Lord,
mind his presence among you, for that is life,
and will make your meetings profitable and full of virtue to your souls,
and the Lord will instruct you in all that is good,
and Christ will be your minister of peace and comfort,
and his Spirit will lead you into all truth, and by his Word,
even the speech of God in your hearts, you will be quickened in spirit;
and your strength and peace in God will be renewed day by day.
Walk in all wisdom, and in the fear of the Lord one towards another,
and towards all people, that your righteous and innocent life,
and your holy ways and works of truth, may have evidence in the hearts of your enemies,
that you are of God, by the shining forth of your light before them, and that the devil,
nor all your enemies may have ought against you, saving concerning your God,
and the worship of Him, and the matters pertaining to good conscience.

If any suffer afflictions and tribulation by wicked men, if it be for righteousness sake,
and concerning the law of your God, and the matters of his kingdom;
in such suffering the Lord will be with you, and not forsake you,
but he will give you dominion, and carry you through it all in patience and faith,
which gives you victory over all enemies.
And nothing shall come upon you, nor happen to you in the anger of God,
but all afflictions shall be turned to your comfort,
and by persecutions and tribulations the Lord will but try you, and not destroy you,
you being delivered from his wrath, and from that which is the cause of it.

Therefore let us have patience towards all men in
all conditions and faith towards God at all times,
for therein is our armour of defence, and our weapons to resist all our enemies.
Let us give up unto the eternal will of the Father, whether in life or death,
in tribulations or in rejoicing, and give our power wholly to the Lord,
and not unto any other, knowing that not one hair of our head can fall without him,
whose power is over all, and through all.
So that if we live it may be unto him alone; and if we suffer and die, it may be for him.
Herein peace shall be with us, in whatever comes to pass upon us,
if we can receive all things as from the hand of the Lord,
and live in the feeling of that power, which does all things,
or permits all things to be done.

And blessed is he that is not offended in Christ, who cannot be offended in him,
nor separated from him by principalities, nor powers of darkness, nor death, nor life,
nor anything.
In this growth was the Apostle, and the same is to be waited for;
blessed is he that obtains it.
That which takes offence against Christ, is of the same with that which gives it.
For all offences against him arise from the corrupted nature which knows him not,
and that which receives any offence against him, is the same which knows him not.
Yes, though an offence may be justly given, yet that in which the offence takes place,
knows not the Father nor the Son.
And Christ said offences should come, but woe unto him by whom they come,
and woe unto that which stumbles and falls through offences.
Therefore everyone is to mind the certain evidence of the Spirit of God,
and of the truth and way of salvation in his own heart,
and being persuaded concerning the way of salvation by the Spirit of God,
that spirit will judge every offence that is given, and not embrace it.

By that Spirit which judges and casts out that which gave offence against God,
may a man be preserved above all offences,
so as nothing can separate him from the love of God; but though this offence,
or the other, may arise, yet such a one feels and possesses the mercy,
love and peace from God in his own spirit, and such a one lives in the heavenly life,
and cannot make the evil example of another an occasion of iniquity to himself,
but he rather hears and fears,
and keeps in more diligence and respect to the fear and presence of God in his own heart.
Yet he covers not the offence that is given in itself,
but with a spirit of judgment treads it down, and walks over it;
and this is the right way for a man of God to walk in.
That spirit is not right before the Lord, nor that heart,
which takes unto itself an occasion to stumble at,
or deny the power and mercy of the Lord, because another may abuse them.

But if one be gone from the Spirit of God in their own hearts,
their mind unsettled upon that, and unseasoned with that, then the offences enter,
and work darkness and prejudice in the mind, and the wrong part being up,
it receives all things to a wrong end, and it abuses God`'s mercies,
and also lacks the authority to pass judgment upon offences,
and because hereof is a man undone.
For prejudice will eat out the good, and destroy simplicity, and wound the soul,
and bring men into death and bitterness of spirit.
Therefore this is to all Friends, that you may be kept in the spirit of judgment,
which will not receive an offence into the wrong part,
but will judge all offences in themselves, and hereby all will be preserved.
Truth must travel through all his enemies,
and blessed is he that is kept faithful to the end, in the power of the Lord God,
that reigns over, and judges the power of darkness in every appearance of it,
inwardly and outwardly.

And as concerning the times and seasons,
and the present confusions and distractions that are among men, much might be spoken;
but certainly the end of all these things shall be turned for good unto
us and unto all that do abide in faith and patience unto the end.
Though the present times be of a heavy countenance towards us,
like as if we should be swallowed up through the roaring of the sea,
and because wickedness does abound by the spirit that now is exalted;
yet in this let us respect the Lord, for certain it is,
that times and seasons are in his hand, to change them at his pleasure,
and to take them from one, and give them to another when he will.
The day is his, and the victory is in his hand.
Oh! let not mortal men glory against him; man`'s time is but for a moment,
and it is our blessedness and peace to be still;
and to have a respect to the Lord through all these overturnings.
And though the spirit that now is, be wicked and abounding in iniquity,
yet the Lord will limit its way.

And as for all the confusions, and distractions, and rumors of wars, what are they to us?
What have we to do with them?
Wherein are we concerned in these things?
Is not our kingdom of another world, even that of peace and righteousness?
Has not the Lord called us, and chosen us into the possession of that inheritance,
wherein strife and enmity dwell not?
Yes, he has broken down that part in us that is related thereunto,
and being dead in that nature of strife, bloodshed, and wars,
how can we live in strife and contention in the world,
or have fellowship with any therein?

Can we have pleasure in the confusion and distraction among men,
or join in anything with them, if so be we are quickened in the new life to God,
which is a life of love and peace, and free from such things?
If we are crucified in the life to this world,
out of which all strife and confusion arise, how can we live therein?
Therefore these things are nothing to us, neither are we of one party,
or against another, to oppose any by rebellion, or plottings against them, in enmity,
and striving with them by carnal weapons,
nor to destroy any men`'s lives though our enemies: for we war not for any,
nor against any, for the matters of this world`'s kingdom.

But our kingdom is inward, and our weapons are spiritual,
and our victory and peace are not of this world.
Our war is against souls`' enemies, and against the powers of darkness,
even by the sword of the Spirit, which God has given us, and called us to war therewith,
to convert people from sin and death,
and from the very occasion of wars and contentions about the things that are earthly.
This is our calling and work at this day;
and these things all the children of the Lord are to mind,
and to keep over the spirit of this world in all people, which all this enmity,
strife and confusion that is up among men, lodges in, and arises out of it.

These things are the fruits of the spirit of this evil and sinful world,
and the fruits of the Spirit of God are of another nature,
even peace and meekness towards all, and not enmity towards any.
In this spirit let us live and walk, admonishing all hereunto,
and praying for our enemies, and not hating them, but doing good for evil,
and not rendering evil for evil; but being meek and humble,
merciful and patient towards all.
This is the true Christian life, learned of Christ,
and this life is blessed in this world, and in the world to come.
They that live here are redeemed out of the world, wherein is trouble and confusion,
wars and strifes.

But let us not heed any of these things, for they rise and fall in their season,
and are brought forth and effected in the changeable and erring spirt,
which works not the honour of God, but is in the dishonour to him.
Friends, let us be a people separate from all that live therein,
waiting for the deliverance of the holy seed in all, and believing,
that through all these things the Lord will set up his kingdom.
Thus it must come to pass, Babylon must fall with a great noise;
for in strife and confusion was she built, and therein has she long stood,
and thereby must she fall.
Tribulations must come upon the earth,
that people may learn to fear the Lord through his judgments.
And he will speedily do great things in the world, which cannot be believed by many,
if it were told them, for hell and death must be destroyed,
and the beast must be taken alive, and cast into the lake of the anger of God.
But blessed are they that do wait upon the Lord, and rest under his shadow,
and wait in his counsel, and receive his instructions;
they shall see the marvellous works of his hand;
but the wicked and unbelieving shall be turned into darkness,
and shall not see the countenance of the Lord to refresh them,
but their sorrow shall be increased.

And as for me, if I were no more,
this is the testimony of my love unto the seed of God through these nations,
who am a companion to all that travail after truth and righteousness,
and that seek the Lord in their hearts that he may rule; and these things were upon me,
to send among the flock of God, to be read in all your meetings.

Edward Burrough.

Oxfordshire, the 1st day of the Third month, 1660.

Charles II. was now established as King over Great Britain,
and as many public predictions had been given out by Friends,
plainly foretelling that he would be brought in,
some of his friends wished to know whether the Quakers
could tell if his power was likely to be permanent.
Someone, Sewel supposes it to have been Lord Clarendon,
drew up several Queries addressed to Friends on this subject.
It had this heading; "`To the Quakers, some Queries are sent to be answered,
that all people may know your spirit, and the temper of it,
and your judgment concerning the times and seasons.`"
This was added; "`Let your answer be directed, Tradite hanc Amico Regis.`"
"`Deliver this to the king`'s friend.`"

About the middle of the third month, Edward Burrough replied to this in a work,
entitled A Visitation and Presentation of Love unto the King and Those Called Royalists.

In this Essay he replies to a number of queries propounded to the Society,
relative to the state of affairs in the government.

In the course of his answers he deals with his catechist
in a strain of honest and fearless exposition,
not sparing to reprove their evil practices;
and warning them faithfully what must be the consequences
if they persist in allowing wickedness to go unpunished,
while the righteous are persecuted for their conscientious
adherence to the law of their God.

Although busy with his pen,
Edward Burrough still found time to travel in the
work of the ministry as his Master led him.
Soon after writing the foregoing he went into the west of England.
Being in Somersetshire on the 25th of the fourth month,
he felt his heart drawn in love to salute his fellow-believers in London with an epistle.

He remained some time labouring among Friends in the west.
On the 4th of the sixth month he was at Bristol, where he had been for several weeks.
While at this place he wrote A Presentation of Wholesome
Information to the King of England.
This was a defence of the Society of Friends from
an attack made upon them by a George Wellington,
of Bristol, in a work then just published,
entitled The Thrice Happy Welcome of King Charles the Second.

Of his labour at Bristol he says,
"`I continued about Bristol two months in much precious service for the Lord,
and truth had good authority over all, and great acceptation in the hearts of many.
Some were convinced, and some edified and confirmed, as many can witness.
Until after the time of the fair I was not clear of that city,
but immediately after I was free.`"

A concern had been long on his mind to pay a second visit to Ireland,
and the time now seemed come to fulfill it.
Almost immediately after writing the above answer to Wellington,
he took shipping with Joseph Coale and others for Cork.
In that city he remained for a considerable time, labouring in the work of the ministry,
with his usual faithfulness and success.
On the 21st of the sixth month he once more addressed
an epistle to his beloved Friends in London.

At the close of this epistle he says:

I am now according to the will of the Father in Ireland.
It is some weeks since I arrived in Cork city in much peace and safety,
with my dear companions,
it having been long upon my spirit to visit the seed of God in this nation.
Of love have I felt it in me; not of constraint,
but of a willing mind--a free spirit and not of force.
After a time of patience and waiting for many days to see my way clear for it,
the Lord has I ordered it and brought it to pass, acceptable to me and many here.
This is the time when this visitation must be effected, for till now my way was not clear.
But that this journey has laid upon me I should have
rejoiced to have been present among you,
either in testimony, by suffering, or otherwise.
But this is the will of God, and it is in my heart to pass through this nation,
and to visit the seed of God, by the love and word of the Father,
as he gives of his life and strength, and opens the way before me.
I perceive in this land Friends are generally well,
and truth grows in victory and dominion,
and the Lord is adding to the numberless number of them that must stand on Mount Zion;
and through the rage of men, and above it all,
the little flock is preserved in its beauty,
and the seed sown in weakness and affliction, is received and quickened in much power,
which is my joy.

I hope in the continuance of the power and presence of the Lord with me through this work.
In his power I am compelled, even to do and suffer all things for his name-sake,
and that by virtue of his own life that dwells in me.
The Lord preserve all the brethren likeminded,
that the work of the Lord may be fulfilled and finished by us.
Amen.

He travelled throughout Ireland,
and for six months laboured abundantly in the defence
and promulgation of the truth in that nation.
Of the particulars of his service but little information has been preserved.

Towards the close of his visit, he was once more in Cork.
At this time persecution was beginning to rage in London,
and many Friends there were cast into prison.
The account of this stirred up the warm feelings of Christian love in Edward,
and it would seem, from the following eloquent and fervent letter,
he had a foresight that he would speedily suffer, even to death, among them.

My very dear and beloved Friends:

My very heart is filled with love to you,
and never was the affection of a brother to his brother, more lively, fervent and full.
I am wholly affected with your integrity and faithfulness.
Shall I say, like as a father loves his children,
so do I you,--wishing and desiring with my whole heart,
the increase of blessing and peace upon you, when I am no more,
by any outward testimony in this world.
How it shall be with me,
and whether my testimony must pass the outward world with my blood, I cannot tell;
but if so, I doubt not but to receive great gain.
My witness is with the Lord, that I have served him from a child.

I am brimful of deep, serious and weighty contemplation concerning what has been,
what now is, and what must be,--not lawful to be declared.
Well, as for Friends in London, my kind and dearest love salutes them all.
Tell them that I am well, and that as they are faithful in God`'s truth,
it adds to my joy.
To my dearly and truly beloved G. F., F. H., R. H., and all the rest who know me,
let this be mentioned.

The truth of our testimony and its glorious effects through the world,
for these some years you know.
God has been with us in a very large measure, and he will not forsake us unto the end.
When we are no more, our memorial shall be precious, and our testimony shall not die.
Let me be mentioned to all our friends who are in prison in the city, and elsewhere.
My heart longs after you,--even that you may be faithful to the end.
Our God shall conquer for us;--if he were not our strength,
we should be swallowed up quick.
There is great wickedness hatching against us.
Our enemies are thirsting for our blood.
This is so.
God has not deceived me; but his hand can deliver us, if he will.
But if he will not, as you have often heard me say, let us not bow to the devil.
My heart is full,--but I must cease from writing, though never from love,
nor from being your very dearly and tenderly beloved

Edward Burrough.

How shall I mention any by name in the remembrance of my love?
I heartily love all the saints, and bid all the faithful in my soul farewell.
I cannot give any particular account of my peril and sore
travail;--but all is well as to truth in this land,
and God has been, is, and let him ever be, with me.

Cork, the 18th of Eleventh month, 1660.

From Cork, Edward Burrough appears to have taken passage to Bristol,
from which place on the 11th of twelfth month,
he addressed an Epistle "`To his companions in the travail and
labour of the Gospel of Christ,`" in which he exhorts them to stand
faithful amid the sufferings and trials which attend them,
and not to be dismayed or discouraged,
but lift up their heads in humble hope and confidence in the Lord,
and commit themselves wholly into his hand.
He thus concludes:

It is now eight days since I left Ireland,
where my service has been precious for the Lord, for full six months;
all which time the Lord carried me in much faithfulness and diligence in his service,
to the confirming of many in the truth of God, and to the converting of others;
and through and because of the presence of the Lord, which was with me,
I had a very precious time,
and was wonderfully preserved through many dangers and trials.
I travelled nearly two thousand miles to and fro in that land,
and had very free passage in the principal cities and towns,
till my work for the present was fully ended there,
having more time than could be expected to clear my conscience to all people.
It would be too large to mention every particular transaction,
wherein I perceived the eminent hand of God with me;
and also many things I observed concerning the present state of things,
which I shall not now mention;
for what have we to do with the affairs of worldly kingdoms?
But as for Friends, it was well with them,
they grow and increase in the blessings and fulness of the Father.
When I came there all was quiet, and very few in prison,
though I suppose the tidings of things as they are here,
will produce the same sufferings upon them.
But I hope they will be bold and valiant for the truth,
in giving their testimony by faithful sufferings, till these things be finished.

Thus I remain in life and death, and when I am no more, in everlasting remembrance,
your dear brother and companion,
by doing and suffering for the name of the Lord and his truth.
I am well, and at liberty as yet.

Edward Burrough.

11th of the Twelfth month, 1660.

The insurrection of the fifth monarchy men,
had occasioned a proclamation from King Charles against
the meetings of the people called Quakers.
At Bristol there were many ready and willing to do
all they could to suppress the meetings in that city.
On the 15th of the eleventh month,
before the king`'s proclamation had been published there,
a company of soldiers with their officers,
took sixty-five persons from the meeting at Dennis Hollister`'s,
and carried them to the Guild-hall.
Dennis Hollister and George Bishop being selected from the rest,
were taken before the mayor.
He examined them apart, and endeavoured to persuade them,
and to frighten them with threats from holding religious meetings.
Unconvinced by his arguments, and undaunted by his threats,
they answered with Christian courage and boldness,
"`that they thought it their duty so to meet, in obedience to the requirings of the Lord,
whom they ought to obey rather than man.
In so doing they had broken no law,
not even the proclamation which had not yet been published.`"
The mayor then demanded of them sureties for their good behaviour.
This they refused to give,
because they knew that the mayor held their attending
their religious meetings to be a breach of good behaviour.
While speaking on this subject they told the magistrates,
"`That they might as well think to hinder the sun from shining, or the tide from flowing,
as to think to hinder the Lord`'s people from meeting to wait on him,
while two of them were left together.`"

The mayor, who had respect to persons, sent to prison all the men arrested,
except Dennis Hollister and George Bishop,
who had been great men in that community before they turned Quakers,
and indeed men of influence through the nation.
When the magistrates told these two that they might go to their own houses,
they felt indignant at the perversion of justice, and nobly said,
"`We seek not liberty at the hand of those who have ordered our brethren to prison,
nor can it be just to commit poor men, and let us go free.`"

They were, however, left at liberty, but Dennis Hollister was the next day committed,
and George Bishop two days after,
the last being taken from a meeting at his own hired house.
The first arrest of sixty-five was made on third day, Dennis Hollister on fourth-day,
George Bishop on sixth-day, and the next first-day sixty-five more were committed.
Some were arrested at private houses, and at this time, the 20th,
there were one hundred and ninety in the prison.

On the 24th they were all released in consequence of a second proclamation of the king,
obtained by the efforts of Margaret Fell,
who represented to him the grievous sufferings his first proclamation had occasioned.
When Edward Burrough arrived in Bristol in the twelfth month,
Friends were generally at liberty,
except a few imprisoned for refusing to contribute towards the charge of the militia,
and others for not taking the oath of allegiance.

On the 11th day of the twelfth month,
a petition or address from the court of Boston in New England, was presented to the king.
It was an endeavour on behalf of the rulers in New
England to justify their persecution of Friends,
and the taking of their lives.
To expose the fallacies of this address, Edward Burrough was soon ready with a work,
entitled Some Considerations, in which he says:

I do testify to the king, and before the whole world,
that we do profess and believe concerning the Father, Son and Spirit,
and the Lord Jesus Christ, and the blessed Gospel, and the Holy Scriptures.
I say,
we do believe and make profession in truth and righteousness concerning all these things,
and by our doctrines and instructions do persuade all people to believe,
and not to seduce any from these truths of the Gospel.

As for the Scriptures being the rule of life, we say,
the Spirit of God that gave forth the Scriptures
is the rule of life and faith unto the saints,
and leads not contrary, but according unto, the Scriptures,
in the belief and practice of whatever the Scripture says.
If these petitioners did make the Scriptures the rule of their lives and practices,
for the denial of which they accuse us, they would not have cut off ears,
banished and put to death for the cause of conscience,
which is contrary to the Scriptures,
and proceeds from another spirit than that which gave forth the Scriptures.

Concerning government.
We are not enemies unto government itself, as these our accusers do charge us;
but it is our principle, and has ever been,
and it is our practice to be subject to whatever government is set up over us,
either by doing or suffering.
And neither to vilify nor rebel against any government or governors,
by any malicious plots and contrivances;
but to walk in meekness and humility towards all, being subject for conscience sake.

As for our doctrines tending to subvert both church and state,
this is also a false accusation and slander; for our doctrines are to convert,
and not to subvert.
Even to convert to God, and truth, and righteousness,
that men should live in these things, and forsake all that which is contrary.

As many things were stated falsely concerning the doctrines and practices of Friends,
Edward Burrough deemed it right to draw up something
more full on some points than he had yet done.
He accordingly prepared A Just and Righteous Plea,
Presented unto the King of England and Council.
In this he treats on "`swearing,`" "`meetings for worship,`" "`tithes,`"
"`giving security to live peaceably,`" "`concerning government,`" and "`persecution.`"
It is preceded by an epistle to the king and his council,
written on the 10th of the second month, 1661.

About this time a book came forth anonymously, bearing the title, Semper Idem,
or A Parallel of Fanatics.
This was the production of a Roman Catholic,
and appeared as a justification of the burning of
those Protestants commonly called martyrs,
who are designated ancient fanatics.
To this work Edward replied in a publication entitled, Persecution Impeached,
as a Traitor Against God, His Laws and Government;
and the Cause of the Ancient Martyrs Vindicated,
Against the Cruelty Inflicted Upon Them by the Papists of Former Days,
"`Wherein is contained a relation of the martyrdom of many
such as dissented and opposed the Church of Rome;
who are in the said book vilified and reproached by the name and term of ancient fanatics.
This is sent forth as an answer thereunto, to pursue it, apprehend it, and condemn it,
as a pamphlet of calumnies and slanders against the Protestants,
both of former and present days; who are all of them scorned in the said book,
the one as ancient, the other as modern fanatics.`"

On the 26th of third month, 1661,
Edward again appeared as a champion of the violated rights of man, in an Address,
entitled The Case of Free Liberty of Conscience in the Exercise of Faith and Religion,
Presented to the King and Both Houses of Parliament.
